>P1;KIR:KIR00049
KIR:KIR00049 KIR2DS5*001 304 bases
 MLLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LPAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADSPLDPA THGGAYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00050
KIR:KIR00050 KIR2DS5*0020101 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00299
KIR:KIR00299 KIR2DS5*0020102 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00297
KIR:KIR00297 KIR2DS5*0020103 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00433
KIR:KIR00433 KIR2DS5*0020104 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01467
KIR:KIR01467 KIR2DS5*0020105 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01468
KIR:KIR01468 KIR2DS5*0020106 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01470
KIR:KIR01470 KIR2DS5*0020107 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01472
KIR:KIR01472 KIR2DS5*0020108 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01473
KIR:KIR01473 KIR2DS5*0020109 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01475
KIR:KIR01475 KIR2DS5*0020110 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01476
KIR:KIR01476 KIR2DS5*0020111 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01479
KIR:KIR01479 KIR2DS5*0020112 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01482
KIR:KIR01482 KIR2DS5*0020113 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01484
KIR:KIR01484 KIR2DS5*0020114 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01488
KIR:KIR01488 KIR2DS5*0020115 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01490
KIR:KIR01490 KIR2DS5*0020116 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01491
KIR:KIR01491 KIR2DS5*0020117 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01493
KIR:KIR01493 KIR2DS5*0020118 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01498
KIR:KIR01498 KIR2DS5*0020119 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01500
KIR:KIR01500 KIR2DS5*0020120 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01502
KIR:KIR01502 KIR2DS5*0020121 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01505
KIR:KIR01505 KIR2DS5*0020122 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01507
KIR:KIR01507 KIR2DS5*0020123 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01508
KIR:KIR01508 KIR2DS5*0020124 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01509
KIR:KIR01509 KIR2DS5*0020125 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01511
KIR:KIR01511 KIR2DS5*0020126 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01512
KIR:KIR01512 KIR2DS5*0020127 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01514
KIR:KIR01514 KIR2DS5*0020128 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01515
KIR:KIR01515 KIR2DS5*0020129 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01523
KIR:KIR01523 KIR2DS5*0020130 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01524
KIR:KIR01524 KIR2DS5*0020131 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01525
KIR:KIR01525 KIR2DS5*0020132 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01529
KIR:KIR01529 KIR2DS5*0020133 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00532
KIR:KIR00532 KIR2DS5*00202 283 bases
 FFLLQGAWPH EGFRRKPSLL AHPGPLVKSE ETVILQCWSD VMFEHFLLHR EGTFNHTLRL
 IGEHIDGVSK GNFSIGRMTQ DLAGTYRCYG SVTHSPYQLS APSDPLDIVI TGLYEKPSLS
 AQPGPTVLAG ESVTLSCSSR SSYDMYHLSR EGEAHERRLP AGPKVNRTFQ ADFPLDPATH
 GGTYRCFGSF RDSPYEWSKS SDPLLVSVTG NSSNSWPSPT EPSSETGNPR HLHVLIGTSV
 VKLPFTILLF FLLHRWCSNK KNASVMDQGP AGNRTVNRED SDE* 
>P1;KIR:KIR01477
KIR:KIR01477 KIR2DS5*00203 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01481
KIR:KIR01481 KIR2DS5*00204 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01495
KIR:KIR01495 KIR2DS5*0020501 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01520
KIR:KIR01520 KIR2DS5*0020502 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01492
KIR:KIR01492 KIR2DS5*0020503 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01499
KIR:KIR01499 KIR2DS5*00206 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01504
KIR:KIR01504 KIR2DS5*0020701 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01517
KIR:KIR01517 KIR2DS5*0020702 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00051
KIR:KIR00051 KIR2DS5*003 298 bases
 SMACVAFFLL QGAWPHEGFR RKPSLLAHPG PLVKSEETVI LQCWSDVMFE HFLLHREGTF
 NHTLRLIGEH IDGVSKGNFS IGRMTQDLAG TYRCYGSVTH SPYQLSAPSD PLDIVITGLY
 EKPSLSAQPG PTVLAGENVT LSCSSRSSYD MYHLSREGEA HERRLPAGPK VNGTFQADFP
 LDPATHGGTY RCFGSFRDSP YEWSKSSDPL LVSVTGNSSN SWPSPTEPSS ETGNPRHLHV
 LIGTSVVKLP FTILLFFLLH RWCSNKKNAS VMDQGPAGNR TVNREDSDEQ DHQEVSYA*
>P1;KIR:KIR00100
KIR:KIR00100 KIR2DS5*004 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLDPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00101
KIR:KIR00101 KIR2DS5*00501 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00706
KIR:KIR00706 KIR2DS5*00502 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00276
KIR:KIR00276 KIR2DS5*0060101 304 bases
 MSLMVISKAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01503
KIR:KIR01503 KIR2DS5*0060102 304 bases
 MSLMVISKAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00277
KIR:KIR00277 KIR2DS5*0070101 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01478
KIR:KIR01478 KIR2DS5*0070102 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00278
KIR:KIR00278 KIR2DS5*00801 283 bases
 FFLLQGAWPR EGFRRKPSLL AHPGPLVKSE ETVILQCWSD VMFEHFLLHR EGTFNHTLRL
 IGEHIDGVSK GNFSIGRMTQ DLAGTYRCYG SVTHSPYQLS APSDPLDIVI TGLYEKPSLS
 AQPGPTVLAG ESVTLSCSSR SSYDMYHLSR EGEAHERRLP AGPKVNGTFQ ADFPLDPATH
 GGTYRCFGSF RDSPYEWSKS SDPLLVSVTG NSSNSWPSPT EPSSETGNPR HLHVLIGTSV
 VKLPFTILLF FLLHRWCSNK KNASVMDQGP AGNRTVNRED SDE* 
>P1;KIR:KIR00339
KIR:KIR00339 KIR2DS5*00802 283 bases
 FFLLQGAWPR EGFRRKPSLL AHPGPLVKSE ETVILQCWSD VMFEHFLLHR EGTFNHTLRL
 IGEHIDGVSK GNFSIGRMTQ DLAGTYRCYG SVTHSPYQLS APSDPLDIVI TGLYEKPSLS
 AQPGPTVLAG ESVTLSCSSR SSYDMYHLSR EGEAHERRLP AGPKVNGTFQ ADFPLDPATH
 GGTYRCFGSF RDSPYEWSKS SDPLLVSVTG NSSNSWPSPT EPSSETGNPR HLHVLIGTSV
 VKLPFTILLF FLLHRWCSNK KNASVMDQGP AGNRTVNRED SDE* 
>P1;KIR:KIR00319
KIR:KIR00319 KIR2DS5*009 292 bases
 FFLLQGAWPH EGFRRKPSLL AHPGPLVKSE ETVILQCWSD VMFEHFLLHR EGTFNHTLRL
 IGEHIDGVSK GNFSIGRMTQ DLAGTYRCYG SVTHSPYQLS APSDPLDIVI TGLYEKPSLS
 AQPGPTVLAG ESVTLSCSSR SSYDMYHLSR EGEAHERRLP AGPKVNRTFQ ADFPLDPATH
 GGTYTCFGSF RDSPYEWSKS SDPLLVSVTG NSSNSWPSPT EPSSETGNPR HLHVLIGTSV
 VKLPFTILLF FLLHRWCSNK KNASVMDQGP AGNRTVNRED SDEQDHQEVS YA*
>P1;KIR:KIR00432
KIR:KIR00432 KIR2DS5*010 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLFCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLDPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00665
KIR:KIR00665 KIR2DS5*011 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNRT
 FQADFPLDPA THGGTYTCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00680
KIR:KIR00680 KIR2DS5*01201 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00970
KIR:KIR00970 KIR2DS5*01202 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00822
KIR:KIR00822 KIR2DS5*013 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00824
KIR:KIR00824 KIR2DS5*014 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGHM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00878
KIR:KIR00878 KIR2DS5*015 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00893
KIR:KIR00893 KIR2DS5*016 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00948
KIR:KIR00948 KIR2DS5*017 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNTSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01469
KIR:KIR01469 KIR2DS5*018 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQANFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01471
KIR:KIR01471 KIR2DS5*019 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLARTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01474
KIR:KIR01474 KIR2DS5*020 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYVMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01480
KIR:KIR01480 KIR2DS5*0210101 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01494
KIR:KIR01494 KIR2DS5*0210102 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01483
KIR:KIR01483 KIR2DS5*022 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYKWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01486
KIR:KIR01486 KIR2DS5*0230101 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILKCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01519
KIR:KIR01519 KIR2DS5*0230102 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILKCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01487
KIR:KIR01487 KIR2DS5*024 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS IKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01526
KIR:KIR01526 KIR2DS5*0250101 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDIYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01489
KIR:KIR01489 KIR2DS5*0250102 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDIYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01497
KIR:KIR01497 KIR2DS5*026 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ FSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01496
KIR:KIR01496 KIR2DS5*0270101 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHSGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01528
KIR:KIR01528 KIR2DS5*0270102 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHSGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01501
KIR:KIR01501 KIR2DS5*028 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHEHR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01506
KIR:KIR01506 KIR2DS5*029 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRRFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01510
KIR:KIR01510 KIR2DS5*030 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGNYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01513
KIR:KIR01513 KIR2DS5*031 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFCRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01516
KIR:KIR01516 KIR2DS5*032 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNAAVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01518
KIR:KIR01518 KIR2DS5*033 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSEPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01521
KIR:KIR01521 KIR2DS5*034 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLRRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01522
KIR:KIR01522 KIR2DS5*035 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTMNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01527
KIR:KIR01527 KIR2DS5*036 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS KKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01530
KIR:KIR01530 KIR2DS5*037 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01584
KIR:KIR01584 KIR2DS5*038 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHLWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
