>P1;KIR:KIR00132
KIR:KIR00132 KIR2DS4*007 234 bases
 IMACVGFFLL QGAWPQEGVH RKPSFLALPG HLVKSEETVI LQCWSDVMFE HFLLHREGKF
 NNTLHLIGEH HDGVSKANFS IGPMMPVLAG TYRCYGSVTH SPYQLSAPSD PLDMVIIGLY
 EKPSLSAQPG PTVQAGENVT LSCSSIYPGK GRPMNVGSLQ CAASTEHSRP TFLWALPPTE
 GPTDASALSV TLPTSGQTRV IHCLFPSQET LQIVGLHPLN QAPKPVTPDT YMFX
>P1;KIR:KIR00258
KIR:KIR00258 KIR2DS4*008 233 bases
 MACVGFFLLQ GAWPQEGVHR KPSFLALPGH LVKSEETVIL QCWSDVMFEH FLLHREGKFD
 NTLHLIGEHH DGVSKANFSI GPMMPVLAGT YRCYGSVPHS PYQLSAPSDP LDMVIIGLYE
 KPSLSAQPGP TVQAGENVTL SCSSIYPGKG RPMNVGSLQC AASTEHSRPT FLWALPPTEG
 PTDASALSVT LPTSGQTRVI HCLFPSQETL QIVGLHPLNQ APKPVTPDTY MFX
>P1;KIR:KIR00275
KIR:KIR00275 KIR2DS4*009 233 bases
 MACVGFFLLQ GAWPQEGVHR KPSFLALPGH LVKSEETVIL QCWSDVMFEH FLLHREGKFN
 NTLHLIGEHH DGVSKANFSI GPMMPVLAGT YRCYGSVPHS PYQLSAPSDP LDMVIIGLYE
 KPSLSAQPGP TVQAGENVTL SCSSIYPGKG RPMNVGSLQC AASTEHSRPT FFWALPPTEG
 PTDALALSVT LPTSGQTRVI HCLFPSQETL QIVGLHPLNQ APKPVTPDTY MFX
>P1;KIR:KIR00315
KIR:KIR00315 KIR2DS4*010 240 bases
 MSLMVIIMAC VGFFLLQGAW PQEEVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVTHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SIYPGKGRPM NVGSLQCAAS TEHSRPTFLW
 ALPPTEGPTD ASALSVTLPT SGQTRVIHCL FPSQETLQIV GLHPLNQAPK PVTPDTYMFX
>P1;KIR:KIR00323
KIR:KIR00323 KIR2DS4*012 233 bases
 MACVGFFLLQ GAWPQEGVHR KPSFLALPGH LVKSEETVIL QCWSDVMFEH FLLHREGKFN
 NTLHLIGEHH DGVSKANFSI GPMMPVLEGT YRCYGSVPHS PYQLSAPSDP LDMVIIGLYE
 KPSLSAQPGP TVQAGENVTL SCSSIYPGRG RPMNVGSLQC AASTEHSRPT FLWALPPTEG
 PTDASALSVT LPTSGQTRVI HCLFPSQETL QIVGLHPLNQ APKPVTPDTY MFX
>P1;KIR:KIR00338
KIR:KIR00338 KIR2DS4*013 233 bases
 MACVGFFLLQ GAWPQEGAHR KPSFLALPGH LVKSEETVIL QCWSDVMFEH FLLHREGKFN
 NTLHLIGEHH DGVSKANFSI GPMMPVLAGT YRCYGSVPHS PYQLSAPSDP LDMVIIGLYE
 KPSLSAQPGP TVQAGENVTL SCSSIYPGRG RPMNVGSLQC AASTEHSRPT FLWALPPTEG
 PTDASALSVT LPTSGQTRVI HCLFPSQETL QIVGLHPLNQ APKPVTPDTY MFX
>P1;KIR:KIR00340
KIR:KIR00340 KIR2DS4*014 292 bases
 FFLLQGAWPQ EGVHRKPSFL ALPGHLVKSE ETVILQCWSD VMFEHFLLHR EGKFNNTLHL
 IGEHHDGVSK ANFSIGPMMP VLAGTYRCYG SVTHSPYQLS APSDPLDMVI IGLYEKPSLS
 AQPGPTVQAG ENVTLSCSSR SSYDMYHLSR EGEAHERRLP AVRSINGTFQ ADFPLGPATH
 GGTYRCFGSF RDAPYEWSNS SDPLLVSVTG NPSNSWPSPT EPSSKTGNPR HLHVLIGTSV
 VKIPFTILLF FLLHRWCSDK KNAAVMDQEP AGNRTVNSED SDEQDHQEVS YA
>P1;KIR:KIR00342
KIR:KIR00342 KIR2DS4*015 297 bases
 MACVGFFLLQ GAWPQEGVHR KPSFLALPGH LVKSEETVIL QCWSDVMFEH FLLHREGKFN
 NTLHLIGEHH DGVSKANFSI GPMMPVLSGT YRCYGSVPHS PYQLSAPSDP LDMVIIGLYE
 KPSLSAQPGP TVQAGENVTL SCSSRSSYDM YHLSREGEAH ERRLPAVRSI NGTFQADFPL
 GPATHGGTYR CFGSFRDAPY EWSNSSDPLL VSVTGNPSNS WPSPTEPSSK TGNPRHLHVL
 IGTSVVKIPF TILLFFLLHR WCSDKKNAAV MDQEPAGNRT VNSEDSDEQD HQEVSYA
>P1;KIR:KIR00731
KIR:KIR00731 KIR2DS4*016 304 bases
 MSLMVIIMAC VGFFLLQGAW PQEEVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVTHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAVRSINGT
 FQADFPLGPA THGGTYRCFG SFRDAPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00819
KIR:KIR00819 KIR2DS4*017 304 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAVRSINGT
 FQADFPLGPA THGGTYRCFG SFRDAPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSCKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00821
KIR:KIR00821 KIR2DS4*018 240 bases
 MSLMVIIMAC VGFFLLQGAW PQEEVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVTDSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SIYPGKGRPM NVGSLQCAAS TEHSRPTFLW
 ALPPTEGPTD ASALSVTLPT SGQTRVIHCL FPSQETLQIV GLHPLNQAPK PVTPDTYMFX
>P1;KIR:KIR00995
KIR:KIR00995 KIR2DS4*019 304 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLTGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCR SRSSYDMYHL SREGEAHERR LPAVRSINGT
 FQADFPLGPA THGGTYRCFG SFRDAPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00996
KIR:KIR00996 KIR2DS4*020 304 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAVRSINGT
 FQADFPLGPA THGGTYRCFG SFRDAPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNN EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01583
KIR:KIR01583 KIR2DS4*021 304 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLTGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAVRSINGT
 FQADFPLGPA THGGTYRCFG SFRDAPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01581
KIR:KIR01581 KIR2DS4*022 304 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGPLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAVRSINGT
 FQADFPLGPA THGGTYRCFG SFRDAPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01686
KIR:KIR01686 KIR2DS4*023 304 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVIFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAVRSINGT
 FQADFPLGPA THGGTYRCFG SFRDAPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01688
KIR:KIR01688 KIR2DS4*024 304 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAVRSINGT
 FQADFPLGPA THGGTNRCFG SFRDAPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00046
KIR:KIR00046 KIR2DS4*00102 304 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAVRSINGT
 FQADFPLGPA THGGTYRCFG SFRDAPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00274
KIR:KIR00274 KIR2DS4*00103 290 bases
 MACVGFFLLQ GAWPQEGVHR KPSFLALPGH LVKSEETVIL QCWSDVMFEH FLLHREGKFN
 NTLHLIGEHH DGVSKANFSI GPMMPVLAGT YRCYGSVPHS PYQLSAPSDP LDMVIIGLYE
 KPSLSAQPGP TVQAGENVTL SCSSRSSYDM YHLSREGEAH ERRLPAVRSI NGTFQADFPL
 GPATHGGTYR CFGSFRDAPY EWSNSSDPLL VSVTGNPSNS WPSPTEPSSK TGNPRHLHVL
 IGTSVVKIPF TILLFFLLHR WCSDKKNAAV MDQEPAGNRT VNSEDSDEQD 
>P1;KIR:KIR00327
KIR:KIR00327 KIR2DS4*00104 292 bases
 FFLLQGAWPQ EGVHRKPSFL ALPGHLVKSE ETVILQCWSD VMFEHFLLHR EGKFNNTLHL
 IGEHHDGVSK ANFSIGPMMP VLAGTYRCYG SVPHSPYQLS APSDPLDMVI IGLYEKPSLS
 AQPGPTVQAG ENVTLSCSSR SSYDMYHLSR EGEAHERRLP AVRSINGTFQ ADFPLGPATH
 GGTYRCFGSF RDAPYEWSNS SDPLLVSVTG NPSNSWPSPT EPSSKTGNPR HLHVLIGTSV
 VKIPFTILLF FLLHRWCSDK KNAAVMDQEP AGNRTVNSED SDEQDHQEVS YA
>P1;KIR:KIR00820
KIR:KIR00820 KIR2DS4*00105 304 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAVRSINGT
 FQADFPLGPA THGGTYRCFG SFRDAPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00947
KIR:KIR00947 KIR2DS4*00106 304 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAVRSINGT
 FQADFPLGPA THGGTYRCFG SFRDAPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00320
KIR:KIR00320 KIR2DS4*01101 290 bases
 MACVGFFLLQ GAWPQEGVHR KPSFLALPGH LVKSEETVIL QCWSDVMFEH FLLHREGKFN
 NTLHLIGEHH DGVSKANFSI GPMMPVLAGT YRCYGSVPHS PYQLSAPSDP LDMVIIGLYE
 KPSLSAQPGP TVQAGENVTL SCSSRSSYDM YHLSREGEAH ERRLPAVRSI NGTFQADFPL
 GPATHGGTYR CFGSFRDAPY EWSNSSDPLL VSVTGNPSNS WPSPTEPSSK TGNPRHLHVL
 IGTSVVKIPF TILLFFLLHR WCSNKKNAAV MDQEPAGNRT VNSEDSDEQD 
>P1;KIR:KIR00341
KIR:KIR00341 KIR2DS4*01102 304 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAVRSINGT
 FQADFPLGPA THGGTYRCFG SFRDAPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00045
KIR:KIR00045 KIR2DS4*0010101 304 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAVRSINGT
 FQADFPLGPA THGGTYRCFG SFRDAPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00092
KIR:KIR00092 KIR2DS4*0010102 304 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAVRSINGT
 FQADFPLGPA THGGTYRCFG SFRDAPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00099
KIR:KIR00099 KIR2DS4*0010103 304 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAVRSINGT
 FQADFPLGPA THGGTYRCFG SFRDAPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00452
KIR:KIR00452 KIR2DS4*0010104 304 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAVRSINGT
 FQADFPLGPA THGGTYRCFG SFRDAPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00453
KIR:KIR00453 KIR2DS4*0010105 304 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAVRSINGT
 FQADFPLGPA THGGTYRCFG SFRDAPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00496
KIR:KIR00496 KIR2DS4*0010106 304 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAVRSINGT
 FQADFPLGPA THGGTYRCFG SFRDAPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00499
KIR:KIR00499 KIR2DS4*0010107 304 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAVRSINGT
 FQADFPLGPA THGGTYRCFG SFRDAPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00498
KIR:KIR00498 KIR2DS4*0010108 304 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAVRSINGT
 FQADFPLGPA THGGTYRCFG SFRDAPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00497
KIR:KIR00497 KIR2DS4*0010109 304 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAVRSINGT
 FQADFPLGPA THGGTYRCFG SFRDAPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00048
KIR:KIR00048 KIR2DS4*0030101 240 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SIYPGKGRPM NVGSLQCAAS TEHSRPTFLW
 ALPPTEGPTD ASALSVTLPT SGQTRVIHCL FPSQETLQIV GLHPLNQAPK PVTPDTYMFX
>P1;KIR:KIR00318
KIR:KIR00318 KIR2DS4*0030102 240 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SIYPGKGRPM NVGSLQCAAS TEHSRPTFLW
 ALPPTEGPTD ASALSVTLPT SGQTRVIHCL FPSQETLQIV GLHPLNQAPK PVTPDTYMFX
>P1;KIR:KIR00430
KIR:KIR00430 KIR2DS4*0030103 240 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SIYPGKGRPM NVGSLQCAAS TEHSRPTFLW
 ALPPTEGPTD ASALSVTLPT SGQTRVIHCL FPSQETLQIV GLHPLNQAPK PVTPDTYMFX
>P1;KIR:KIR00431
KIR:KIR00431 KIR2DS4*0030104 240 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SIYPGKGRPM NVGSLQCAAS TEHSRPTFLW
 ALPPTEGPTD ASALSVTLPT SGQTRVIHCL FPSQETLQIV GLHPLNQAPK PVTPDTYMFX
>P1;KIR:KIR00089
KIR:KIR00089 KIR2DS4*0040101 240 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YSSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVSLSCS SIYPGRGRPM NVGSLQCAAS TEHSRPTFLW
 ALPPTEGPTD ASALSVTLPT SGQTRVIHCL FPSQETLQIV GLHPLNQAPK PVTPDTYMFX
>P1;KIR:KIR00637
KIR:KIR00637 KIR2DS4*0040102 240 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YSSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVSLSCS SIYPGRGRPM NVGSLQCAAS TEHSRPTFLW
 ALPPTEGPTD ASALSVTLPT SGQTRVIHCL FPSQETLQIV GLHPLNQAPK PVTPDTYMFX
>P1;KIR:KIR00090
KIR:KIR00090 KIR2DS4*0060101 240 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SIYPGRGRPM NVGSLQCAAS TEHSRPTFLW
 ALPPTEGPTD ASALSVTLPT SGQTRVIHCL FPSQETLQIV GLHPLNQAPK PVTPDTYMFX
>P1;KIR:KIR00651
KIR:KIR00651 KIR2DS4*0060102 240 bases
 MSLMVIIMAC VGFFLLQGAW PQEGVHRKPS FLALPGHLVK SEETVILQCW SDVMFEHFLL
 HREGKFNNTL HLIGEHHDGV SKANFSIGPM MPVLAGTYRC YGSVPHSPYQ LSAPSDPLDM
 VIIGLYEKPS LSAQPGPTVQ AGENVTLSCS SIYPGRGRPM NVGSLQCAAS TEHSRPTFLW
 ALPPTEGPTD ASALSVTLPT SGQTRVIHCL FPSQETLQIV GLHPLNQAPK PVTPDTYMFX
