>DL;IPD:KIR00001
KIR:KIR00001 KIR2DL1*001 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00002
KIR:KIR00002 KIR2DL1*0020101 1047 bases
 ATGTCGCTCT TGTTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00398
KIR:KIR00398 KIR2DL1*0020102 1047 bases
 ATGTCGCTCT TGTTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00644
KIR:KIR00644 KIR2DL1*0020103 1047 bases
 ATGTCGCTCT TGTTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00003
KIR:KIR00003 KIR2DL1*00301 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACGGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00004
KIR:KIR00004 KIR2DL1*0030201 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00294
KIR:KIR00294 KIR2DL1*0030202 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00397
KIR:KIR00397 KIR2DL1*0030203 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00399
KIR:KIR00399 KIR2DL1*0030204 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00404
KIR:KIR00404 KIR2DL1*0030205 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00400
KIR:KIR00400 KIR2DL1*0030206 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00401
KIR:KIR00401 KIR2DL1*0030207 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00402
KIR:KIR00402 KIR2DL1*0030208 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00403
KIR:KIR00403 KIR2DL1*0030209 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00616
KIR:KIR00616 KIR2DL1*0030210 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00005
KIR:KIR00005 KIR2DL1*00303 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAGAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00897
KIR:KIR00897 KIR2DL1*00304 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00898
KIR:KIR00898 KIR2DL1*00305 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCGTGA*   
>DL;IPD:KIR00006
KIR:KIR00006 KIR2DL1*0040101 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATTGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00007
KIR:KIR00007 KIR2DL1*0040102 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATTGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00203
KIR:KIR00203 KIR2DL1*00402 1037 bases
 TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG CCACATGAGG
 GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA TCAGAAGAGA
 CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG CACAGAGAGG
 GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC TCCAAGGCCA
 ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC TACGGTTCTG
 TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC GTGATCATAG
 GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG GCAGGAGAGA
 ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA TCCAGGGAAG
 GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA TTCCAGGCCA
 ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC TCTTTCCGTG
 ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC ACAGGAAACC
 CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC CCCCGACACC
 TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC TTCTTTCTCC
 TTCATTGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG TCTGCAGGAA
 ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG ACGTACACAC
 AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG AGGCCCAAGA
 CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC AGATCCAAAG
 TTGTCTCCTG CCCATGA*    
>DL;IPD:KIR00330
KIR:KIR00330 KIR2DL1*00403 1037 bases
 TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG CCACATGAGG
 GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA TCAGAAGAGA
 CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG CACAGAGAGG
 GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC TCCAAGGCCA
 ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC TACGGTTCTG
 TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC GTGATCATAG
 GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG GCAGGAGAGA
 ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA TCCAGGGAAG
 GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA TTCCAGGCCA
 ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC TCTTTCCGTG
 ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC ACAGGAAACC
 CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC CCCCGACACC
 TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC TTCTTTCTCC
 TTCATTGCTG GTGCTCCAAC AAAAAAAATG CTGCTGTAAT GGACCAAGAG TCTGCAGGAA
 ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG ACATACACAC
 AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG AGGCCCAAGA
 CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC AGATCCAAAG
 TTGTCTCCTG CCCATGA*    
>DL;IPD:KIR00008
KIR:KIR00008 KIR2DL1*005 1007 bases
 TCTTGCTGCA GGGGGCCTGG CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC
 ACCCAGGTCG CCTGGTGAAA TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA
 TGTTTGAACA CTTCCTTCTG CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG
 GAGAACACCA TGATGGGGTC TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC
 TGGCAGGGAC CTACAGATGC TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC
 CCAGTGACCC TCTGGACATC GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC
 AGCTGGGCCC CACGGTTCTG GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT
 CCTATGACAT GTACCATCTA TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG
 GGCCCAAGGT CAACGGAACA TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG
 GGACCTACAG ATGCTTCGGC TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG
 ACCCACTGCT TGTTTCTGTC ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC
 CAAGCTCCAA AACCGGTAAC CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA
 TCATCCTCTT CATCCTCCTC TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG
 CTGCGGTAAT GGACCAAGAG TCTGCAGGGA ACAGAACAGC GAATAGCGAG GACTCTGATG
 AACAAGACCC TCAGGAGGTG ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA
 AAATCACTCG CCCTTCTCAG AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACGCGG
 AACTTCCAAA TGCTGAGTCC AGATCCAAAG TTGTCTCCTG CCCATGA* 
>DL;IPD:KIR00009
KIR:KIR00009 KIR2DL1*00601 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATTGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00764
KIR:KIR00764 KIR2DL1*00602 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATTGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00200
KIR:KIR00200 KIR2DL1*007 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACGTC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATTGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00201
KIR:KIR00201 KIR2DL1*008 1037 bases
 TGTTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG CCACATGAGG
 GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGATCC CCTGGTGAAA TCAGAAGAGA
 CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG CACAGAGAGG
 GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC TCCAAGGCCA
 ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC TACGGTTCTG
 TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC GTGATCATAG
 GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG GCAGGAGAGA
 ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA TCCAGGGAAG
 GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA TTCCAGGCTG
 ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC TCTTTCCATG
 ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC ACAGGAAACC
 CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC CCCCGACACC
 TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC TTCTTTCTCC
 TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG TCTGCAGGAA
 ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG ACATACACAC
 AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG AGGCCCAAGA
 CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC AGATCCAAAG
 TTGTCTCCTG CCCATGA*    
>DL;IPD:KIR00202
KIR:KIR00202 KIR2DL1*009 1037 bases
 TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG CCACATGAGG
 GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA TCAGAAGAGA
 CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG CACAGAGAGG
 GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC TCCAAGGCCA
 ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC TACGGTTCTG
 TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC GTGATCATAG
 GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG GCAGGAGAGA
 ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA TCCAGGGAAG
 GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA TTCCAGGCTG
 ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC TCTTTCCATG
 ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC ACAGGAAACC
 CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC CCCCGACACC
 TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC TTCTTTCTCC
 TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG TCTGCAGGAA
 ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG ACATACGTAC
 AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG AGGCCCAAGA
 CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC AGATCCAAAG
 TTGTCTCCTG CCCATGA*    
>DL;IPD:KIR00214
KIR:KIR00214 KIR2DL1*010 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00329
KIR:KIR00329 KIR2DL1*01101 1037 bases
 TGTTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG CCACATGAGG
 GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA TCAGAAGAGA
 CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG CACAGAGAGG
 GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC TCCAAGGCCA
 ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC TACGGTTCTG
 TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC GTGATCATAG
 GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG GCAGGAGAGA
 ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA TCCAGGGAAG
 GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA TTCCAGGCCA
 ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC TCTTTCCGTG
 ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC ACAGGAAACC
 CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC CCCAGACACC
 TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC TTCTTTCTCC
 TTCATTGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG TCTGCAGGAA
 ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG ACATACACAC
 AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG AGGCCCAAGA
 CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC AGATCCAAAG
 TTGTCTCCTG CCCATGA*    
>DL;IPD:KIR00396
KIR:KIR00396 KIR2DL1*01102 1047 bases
 ATGTCGCTCT TGTTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA TGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATTGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00331
KIR:KIR00331 KIR2DL1*01201 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00574
KIR:KIR00574 KIR2DL1*01202 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAGAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00332
KIR:KIR00332 KIR2DL1*013N 1037 bases
 TGTTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG CCACATGAGG
 GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA TCAGAAGAGA
 CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTTAACA CTTCCTTCTG CACAGAGAGG
 GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC TCCAAGGCCA
 ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC TACGGTTCTG
 TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC GTGATCATAG
 GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG GCAGGAGAGA
 ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA TCCAGGGAAG
 GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA TTCCAGGCCA
 ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC TCTTTCCGTG
 ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC ACAGGAAACC
 CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC CCCCGACACC
 TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC TTCTTTCTCC
 TTCATTGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG TCTGCAGGAA
 ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG ACATACACAC
 AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG AGGCCCAAGA
 CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC AGATCCAAAG
 TTGTCTCCTG CCCATGA*    
>DL;IPD:KIR00333
KIR:KIR00333 KIR2DL1*014 1037 bases
 TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG CCACATGAGG
 GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA TCAGAAGAGA
 CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG CACAGAGAGG
 GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC TCCAAGGCCA
 ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC TACGGTTCTG
 TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC GTGATCATAG
 GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG GCAGGAGAGA
 ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA TCCAGGGAAG
 GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA TTCCAGGCTG
 ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCAGC TCTTTCCATG
 ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC ACAGGAAACC
 CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC CCCCGACACC
 TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC TTCTTTCTCC
 TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG TCTGCAGGAA
 ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG ACATACACAC
 AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG AGGCCCAAGA
 CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC AGATCCAAAG
 TTGTCTCCTG CCCATGA*    
>DL;IPD:KIR00334
KIR:KIR00334 KIR2DL1*015 1037 bases
 TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG CCACATGAGG
 GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA TCAGAAGAGA
 CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG CACAGAGAGG
 GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC TCCAAGGCCA
 ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC TACGGTTCTG
 TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC GTGATCATAG
 GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG GCAGGAGAGA
 ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA TCCAGGGAAG
 GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA TTCCAGGCTG
 ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC TCTTTCCATG
 ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC ACAGGAAACC
 CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC CCCCGACACC
 TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC TTCTTTCTCC
 TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG TCTGCAGGAA
 ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGAACC TCAGGAGGTG ACATACACAC
 AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG AGGCCCAAGA
 CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC AGATCCAAAG
 TTGTCTCCTG CCCATGA*    
>DL;IPD:KIR00349
KIR:KIR00349 KIR2DL1*016 1037 bases
 TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG CCACATGAGG
 GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA TCAGAAGAGA
 CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG CACAGAGAGG
 GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC TCCAAGGCCA
 ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC TACGGTTCTG
 TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC GTGATCATAG
 GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG GCAGGAGAGA
 ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA TCCAGGGAAG
 GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA TTCCAGGCTG
 ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC TCTTTCCATG
 ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC ACAGGAAACC
 CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC CCCCGACACC
 TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC TTCTTTCTCC
 TTCATCGCTG GTGCTCCAAC AAGAAAAATG CTGCGGTAAT GGACCAAGAG TCTGCAGGAA
 ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG ACATACACAC
 AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTTG CCCTTCTCAG AGGCCCAAGA
 CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC AGATCCAAAG
 TTGTCTCCTG CCCATGA*    
>DL;IPD:KIR00350
KIR:KIR00350 KIR2DL1*017 1037 bases
 TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG CCACATGAGG
 GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA TCAGAAGAGA
 CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG CACAGAGAGG
 GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC TCCAAGGCCA
 ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC TACGGTTCTG
 TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC GTGATCATAG
 GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG GCAGGAGAGA
 ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA TCCAGGGAAG
 GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA TTCCAGGCTG
 ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC TCTTTCCATG
 ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC ACAGGAAACC
 CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC CCCCAACACC
 TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC TTCTTTCTCC
 TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG TCTGCAGGAA
 ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG ACATACACAC
 AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG AGGCCCAAGA
 CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC AGATCCAAAG
 TTGTCTCCTG CCCATGA*    
>DL;IPD:KIR00351
KIR:KIR00351 KIR2DL1*018 1037 bases
 TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG CCACATGAGG
 GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA TCAGAAGAGA
 CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG CACAGAGAGG
 GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC TCCAAGGCCA
 ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC TACGGTTCTG
 TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC GTGATCATAG
 GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG GCAGGAGAGA
 ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA TCCAGGGAAG
 GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA TTCCAGGCTG
 ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC TCTTTCCATG
 ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC ACAGGAAACC
 CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC CCCCGACACC
 TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC TTCTTTCTCC
 TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG TCTGCAGGAA
 ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG ACATACCCAC
 AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG AGGCCCAAGA
 CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC AGATCCAAAG
 TTGTCTCCTG CCCATGA*    
>DL;IPD:KIR00352
KIR:KIR00352 KIR2DL1*019 1037 bases
 TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG CCACATGAGG
 GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA TCAGAAGAGA
 CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG CACAGAGAGG
 GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC TCCAAGGCCA
 ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC TACGGTTCTG
 TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC GTGATCATAG
 GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG GCAGGAGAGA
 ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA TCCAGGGAAG
 GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA TTCCAGGCTG
 ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC TCTTTCCATG
 ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC ACAGGAAACC
 CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC CCCCGACACC
 TGCACATTGT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC TTCTTTCTCC
 TTCATCGCTG GTGCTCCAAC AAGAAAAATG CTGCGGTAAT GGACCAAGAG TCTGCAGGAA
 ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG ACATACACAC
 AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG AGGCCCAAGA
 CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC AGATCCAAAG
 TTGTCTCCTG CCCATGA*    
>DL;IPD:KIR00518
KIR:KIR00518 KIR2DL1*020 1038 bases
 TTGGTCGTCA GCATGGCGTG TGTTGGGTTC TTCTTGCTGC AGGGGGCCTG GCCACATGAG
 GGAGTCCACA GAAAACCTTC CCTCCTGGCC CACCCAGGTC GCCTGGTGAA ATCAGAAGAG
 ACAGTCATCC TGCAGTGTTG GTCAGATGTC ATGTTTGAAC ACTTCCTTCT GCACAGAGAG
 GGGATGTTTA ACGACACTTT GCGCCTCATT GGAGAACACC ATGATGGGGT CTCCAAGGCC
 AACTTCTCCA TCGGTCGCAT GACGCAAGAC CTGGCAGGGA CCTACAGATG CTACGGTTCT
 GTTACTCACT CCCCCTATCA GGTGTCAGCT CCCAGTGACC CTCTGGACAT CGTGATCATA
 GGTCTATATG AGAAACCTTC TCTCTCAGCC CAGCTGGGCC CCACGGTTCT GGCAGGAGAG
 AATGTGACCT TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAA
 GGGGAGGCCC ATGAACGTAG GCTCCCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT
 GACTTTCCTC TGGGCCCTGC CACCCACGGA GGGACCTACA GATGCTTCGG CTCTTTCCAT
 GACTCTCCAT ACGAGTGGTC AAAGTCAAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC
 CCTTCAAATA GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAA CCCCCGACAC
 CTGCACATTC TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CTTCTTTCTC
 CTTCATCGCT GGTGCTCCAA CAAAAAAAAT GCTGCGGTAA TGGACCAAGA GTCTGCAGGA
 AACAGAACAG CGAATAGCGA GGACTCTGAT GAACAAGACC CTCAGGAGGT GACATACACA
 CAGTTGAATC ACTGCGTTTT CACACAGAGA AAAATCACTC GCCCTTCTCA GAGGCCCAAG
 ACACCCCCAA CAGATATCAT CGTGTACACG GAACTTCCAA ATGCTGAGTC CAGATCCAAA
 GTTGTCTCCT GCCCATGA*    
>DL;IPD:KIR00519
KIR:KIR00519 KIR2DL1*021 1038 bases
 TTGTTCGTCA GCATGGCGTG TGTTGGGTTC TTCTTGCTGC AGGGGGCCTG GCCACATGAG
 GGAGTCCACA GAAAACCTTC CCTCCTGGCC CACCCAGGTC CCCTGGTGAA ATCAGAAGAG
 ACAGTCATCC TGCAATGTTG GTCAGATGTC ATGTTTGAAC ACTTCCTTCT GCACAGAGAG
 GGGATGTTTA ACGACACTTT GCGCCTCATT GGAGAACACC ATGATGGGGT CTCCAAGGCC
 AACTTCTCCA TCAGTCGCAT GACGCAAGAC CTGGCAGGGA CCTACAGATG CTACGGTTCT
 GTTACTCACT CCCCCTATCA GGTGTCAGCT CCCAGTGACC CTCTGGACAT CGTGATCATA
 GGTCTATATC AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG
 AATGTGACCT TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAA
 GGGGAGGCCC ATGAACGTAG GCTCCCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT
 GACTTTCCTC TGGGCCCTGC CACCCACGGA GGGACCTACA GATGCTTCGG CTCTTTCCAT
 GACTCTCCAT ACGAGTGGTC AAAGTCAAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC
 CCTTCAAATA GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAA CCCCCGACAC
 CTGCACATTC TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CTTCTTTCTC
 CTTCATCGCT GGTGCTCCAA CAAAAAAAAT GCTGCGGTAA TGGACCAAGA GTCTGCAGGA
 AACAGAACAG CGAATAGCGA GGACTCTGAT GAACAAGACC CTCAGGAGGT GACATACACA
 CAGTTGAATC ACTGCGTTTT CACACAGAGA AAAATCACTC GCCCTTCTCA GAGGCCCAAG
 ACACCCCCAA CAGATATCAT CGTGTACACG GAACTTCCAA ATGCTGAGTC CAGATCCAAA
 GTTGTCTCCT GCCCATGA*    
>DL;IPD:KIR00577
KIR:KIR00577 KIR2DL1*02201 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00575
KIR:KIR00575 KIR2DL1*023 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAGAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00576
KIR:KIR00576 KIR2DL1*024 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCG TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATTGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00617
KIR:KIR00617 KIR2DL1*025 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00677
KIR:KIR00677 KIR2DL1*026 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG ATGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00798
KIR:KIR00798 KIR2DL1*027 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGAACTACAG ATGCTTCAGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00799
KIR:KIR00799 KIR2DL1*028 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCGT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00800
KIR:KIR00800 KIR2DL1*029 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATTGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00817
KIR:KIR00817 KIR2DL1*030 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCGGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00818
KIR:KIR00818 KIR2DL1*031 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGGGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00865
KIR:KIR00865 KIR2DL1*032N 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA GGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00899
KIR:KIR00899 KIR2DL1*033 1047 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGGGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00900
KIR:KIR00900 KIR2DL1*034 1047 bases
 ATGTCGCTCT TGTTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAGTGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
