>DL;IPD:KIR00020
KIR:KIR00020 KIR2DL4*00101 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CACAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAA
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAATGGTC AGACGCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TTACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00021
KIR:KIR00021 KIR2DL4*0010201 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CACAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACGCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTATCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00424
KIR:KIR00424 KIR2DL4*0010202 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CACAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACGCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTATCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00112
KIR:KIR00112 KIR2DL4*0010301 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CACAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACGCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00115
KIR:KIR00115 KIR2DL4*0010302 1106 bases
 TGGCATGTCT TGGGTTCTTC TTGGACCAGA GTGTGTGGGC ACACGTGGGT GGTCAGGACA
 AGCCCTTCTG CTCTGCCTGG CCCAGCGCTG TGGTGCCTCA AGGAGGACAC GTGACTCTTC
 GGTGTCACTA TCGTCGTGGG TTTAACATCT TCACGCTGTA CAAGAAAGAT GGGGTCCCTG
 TCCCTGAGCT CTACAACAGA ATATTCTGGA ACAGTTTCCT CATTAGCCCT GTGACCCCAG
 CACACGCAGG GACCTACAGA TGTCGAGGTT TTCACCCGCA CTCCCCCACT GAGTGGTCGG
 CACCCAGCAA CCCCCTGGTG ATCATGGTCA CAGGTCTATA TGAGAAACCT TCGCTTACAG
 CCCGGCCGGG CCCCACGGTT CGCACAGGAG AGAACGTGAC CTTGTCCTGC AGCTCCCAGA
 GCTCCTTTGA CATCTACCAT CTATCCAGGG AGGGGGAAGC CCATGAACTT AGGCTCCCTG
 CAGTGCCCAG CATCAATGGA ACATTCCAGG CCGACTTCCC TCTGGGTCCT GCCACCCACG
 GAGAGACCTA CAGATGCTTC GGCTCTTTCC ATGGATCTCC CTACGAGTGG TCAGACGCGA
 GTGACCCACT GCCTGTTTCT GTCACAGGAA ACCCTTCTAG TAGTTGGCCT TCACCCACTG
 AACCAAGCTT CAAAACTGGT ATCGCCAGAC ACCTGCATGC TGTGATTAGG TACTCAGTGG
 CCATCATCCT CTTCACCATC CTTCCCTTCT TTCTCCTTCA TCGCTGGTGC TCCAAAAAAA
 AAAATGCTGC TGTAATGAAC CAAGAGCCTG CGGGACACAG AACAGTGAAC AGGGAGGACT
 CTGATGAACA AGACCCTCAG GAGGTGACAT ACGCACAGTT GGATCACTGC ATTTTCACAC
 AGAGAAAAAT CACTGGCCCT TCTCAGAGGA GCAAGAGACC CTCAACAGAT ACCAGCGTGT
 GTATAGAACT TCCAAATGCT GAGCCCAGAG CGTTGTCTCC TGCCCATGAG CACCACAGTC
 AGGCCTTGAT GGGATCTTCT AGGGAGACAA CAGCCCTGTC TCAAACCCAG CTTGCCAGCT
 CTAATGTACC AGCAGCTGGA ATCTGA*   
>DL;IPD:KIR00420
KIR:KIR00420 KIR2DL4*0010303 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CACAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACGCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00421
KIR:KIR00421 KIR2DL4*0010304 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CACAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACGCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00422
KIR:KIR00422 KIR2DL4*0010305 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CACAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACGCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00423
KIR:KIR00423 KIR2DL4*0010306 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CACAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACGCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00425
KIR:KIR00425 KIR2DL4*0010307 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CACAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACGCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00620
KIR:KIR00620 KIR2DL4*0010308 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CACAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACGCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00119
KIR:KIR00119 KIR2DL4*00104 1106 bases
 TGGCATGTCT TGGGTTCTTC TTGGACCAGA GTGTGTGGGC ACACGTGGGT GGTCAGGACA
 AGCCCTTCTG CTCTGCCTGG CCCAGCGCTG TGGTGCCTCA AGGAGGACAC GTGACTCTTC
 GGTGTCACTA TCGTCGTGGG TTTAACATCT TCACGCTGTA CAAGAAAGAT GGGGTCCCTG
 TCCCTGAGCT CTACAACAGA ATATTCTGGA ACAGTTTCCT CATTAGCCCT GTGACCCCAG
 CACACGCAGG GACCTACAGA TGTCGAGGTT TTCACCCGCA CTCCCCCACT GAGTGGTCGG
 CACCCAGCAA CCCCCTGGTG ATCATGGTCA CAGGTCTATA TGAGAAACCT TCGCTTACAG
 CCCGGCCGGG CCCCACGGTT CGCACAGGAG AGAACGTGAC CTTGTCCTGC AGCTCCCAGA
 GCTCCTTTGA CATCTACCAT CTATCCAGGG AAGGGGAAGC CCATGAACTT AGGCTCCCTG
 CAGTGCCCAG CATCAATGGA ACATTCCAGG CCGACTTCCC TCTGGGTCCT GCCACCCACG
 GAGAGACCTA CAGATGCTTC GGCTCTTTCC ATGGATCTCC CTACGAGTGG TCAGACGCGA
 GTGACCCACT GCCTGTTTCT GTCACAGGAA ACCCTTCTAG TAGTTGGCCT TCACCCACTG
 AACCAAGCTT CAAAACTGGT ATCGCCAGAC ACCTGCATGC TGTGATTAGG TACTCAGTGG
 CCATCATCCT CTTCACCATC CTTCCCTTCT TTCTCCTTCA TCGCTGGTGC TCCAAAAAAA
 AAAATGCTGC TGTAATGAAC CAAGAGCCTG CGGGACACAG AACAGTGAAC AGGGAGGACT
 CTGATGAACA AGACCCTCAG GAGGTGACAT ACGCACAGTT GGATCACTGC ATTTTCACAC
 AGAGAAAAAT CACTGGCCCT TCTCAGAGGA GCAAGAGACC CTCAACAGAT ACCAGCGTGT
 GTATAGAACT TCCAAATGCT GAGCCCAGAG CGTTGTCTCC TGCCCATGAG CACCACAGTC
 AGGCCTTGAT GGGATCTTCT AGGGAGACAA CAGCCCTGTC TCAAACCCAG CTTGCCAGCT
 CTAATGTACC AGCAGCTGGA ATCTGA*   
>DL;IPD:KIR00129
KIR:KIR00129 KIR2DL4*00105 1128 bases
 ATGTCACCCA CGGTCATCAT CCTGGCATGT CTTGGGTTCT TCTTGGACCA GAGTGTGTGG
 GCACACGTGG GTGGTCAGGA CAAGCCCTTC TGCTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CAAGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCGTG GGTTTAACAT CTTCACGCTG
 TACAAGAAAG ATGGGGTCCC TGTCCCTGAG CTCTACAACA GAATATTCTG GAACAGTTTC
 CTCATTAGCC CTGTGACCCC AGCACACGCA GGGACCTACA GATGTCGAGG TTTTCACCCG
 CACTCCCCCA CTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCATGGT CACAGGTCTA
 TATGAGAAAC CTTCGCTTAC AGCCCGGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCCA GAGCTCCTTT GACATCTACC ATCTATCCAG GGAGGGGGAA
 GCCCATGAAC TTAGGCTCCC TGCAGTGCCC AGCATCAATG GAACATTCCA GGCCGACTTC
 CCTCTGGGTC CTGCCACCCA CGGAGAGACC TACAGATGCT TCGGCTCTTT CCATGGATCT
 CCCTACGAGT GGTCAGACGC GAGTGACCCA CTGCCTGTTT CTGTCACAGG AAACCCTTCT
 AGTAGTTGGC CTTCACCCAC TGAACCAAGC TTCAAAACTG GTATCGCCAG ACACCTGCAT
 GCTGTGATTA GGTACTCAGT GGCCATCATC CTCTTCACCA TCCTTCCCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAAAAA AAAAAATGCT GCTGTAATGA ACCAAGAGCC TGCAGGACAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAA CAAGACCCTC AGGAGGTGAC ATACGCACAG
 TTGGATCACT GCATTTTCAC ACAGAGAAAA ATCACTGGCC CTTCTCAGAG GAGCAAGAGA
 CCCTCAACAG ATACCAGCGT GTGTATAGAA CTTCCAAATG CTGAGCCCAG AGCGTTATCT
 CCTGCCCATG AGCACCACAG TCAGGCCTTG ATGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAACCC AGCTTGCCAG CTCTAATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00022
KIR:KIR00022 KIR2DL4*00201 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAA
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TTACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00023
KIR:KIR00023 KIR2DL4*00202 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TTACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00024
KIR:KIR00024 KIR2DL4*003 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTCT GACCCCTGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CACAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACGCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACAGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT CCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA GATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTATCTCCTG CGCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCC CATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00025
KIR:KIR00025 KIR2DL4*004 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTCT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACAGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CGCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCC CATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00026
KIR:KIR00026 KIR2DL4*00501 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTGTC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00901
KIR:KIR00901 KIR2DL4*00503 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTGTC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAAGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00902
KIR:KIR00902 KIR2DL4*00504 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTGTC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTTTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00027
KIR:KIR00027 KIR2DL4*00601 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCTGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACAGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00130
KIR:KIR00130 KIR2DL4*00602 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCTGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00913
KIR:KIR00913 KIR2DL4*00603 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCTGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTATCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00028
KIR:KIR00028 KIR2DL4*007 1106 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCAACAGATG TCGAGGTTTT
 CGCCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TTACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA ATGCTGCTGT AATGAACCAA GAGCCTGCGG
 GACACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG GTGACATACG
 CACAGTTGGA TCACTGCATT TTCACACAGA GAAAAATCAC TGGCCCTTCT CAGAGGAGCA
 AGAGACCCTC AACAGATACC AGCGTGTGTA TAGAACTTCC AAATGCTGAG CCCAGTGCGT
 TGTCTCCTGC CCATGAGCAC CACAGTCAGG CCTTGATGGG ATCTTCTAGG GAGACAACAG
 CCCTGTCTCA AACCCAGCTT GCCAGC*   
>DL;IPD:KIR00109
KIR:KIR00109 KIR2DL4*0080101 1133 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TTACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA ATGCTGCTGT AATGAACCAA GAGCCTGCGG
 GACACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG GTGACATACG
 CACAGTTGGA TCACTGCATT TTCACACAGA GAAAAATCAC TGGCCCTTCT CAGAGGAGCA
 AGAGACCCTC AACAGATACC AGCGTGTGTA TAGAACTTCC AAATGCTGAG CCCAGAGCGT
 TGTCTCCTGC CCATGAGCAC CACAGTCAGG CCTTGATGGG ATCTTCTAGG GAGACAACAG
 CCCTGTCTCA AACCCAGCTT GCCAGCTCTA ATGTACCAGC AGCTGGAATC TGA*
>DL;IPD:KIR00110
KIR:KIR00110 KIR2DL4*0080102 1064 bases
 CACGTGGGTG GTCAGGACAA GCCCTTCTGC TCTGCCTGGC CCAGCGCTGT GGTGCCTCAA
 GGAGGACACG TGACTCTTCG GTGTCACTAT CGTCGTGGGT TTAACATCTT CACGCTGTAC
 AAGAAAGATG GGGTCCCTGT CCCTGAGCTC TACAACAGAA TATTCTGGAA CAGTTTCCTC
 ATTAGCCCTG TGACCCCAGC ACACGCAGGG ACCTACAGAT GTCGAGGTTT TCACCCGCAC
 TCCCCCACTG AGTGGTCGGC ACCCAGCAAC CCCCTGGTGA TCATGGTCAC AGGTCTATAT
 GAGAAACCTT CGCTTACAGC CCGGCCGGGC CCCACGGTTC GCGCAGGAGA GAACGTGACC
 TTGTCCTGCA GCTCCCAGAG CTCCTTTGAC ATCTACCATC TATCCAGGGA GGGGGAAGCC
 CATGAACTTA GGCTCCCTGC AGTGCCCAGC ATCAATGGAA CATTCCAGGC CGACTTCCCT
 CTGGGTCCTG CCACCCACGG AGAGACCTAC AGATGCTTCG GCTCTTTCCA TGGATCTCCC
 TACGAGTGGT CAGACCCGAG TGACCCACTG CCTGTTTCTG TCACAGGAAA CCCTTCTAGT
 AGTTGGCCTT CACCCACTGA ACCAAGCTTC AAAACTGGTA TCGCCAGACA CCTGCATGCT
 GTGATTAGGT ACTCAGTGGC CATCATCCTC TTTACCATCC TTCCCTTCTT TCTCCTTCAT
 CGCTGGTGCT CCAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG GGACACAGAA
 CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GCACAGTTGG
 ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC AAGAGACCCT
 CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGACCG TTGTCTCCTG
 CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA GCCCTGTCTC
 AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA* 
>DL;IPD:KIR00117
KIR:KIR00117 KIR2DL4*0080103 1105 bases
 TGGCATGTCT TGGGTTCTTC TTGGACCAGA GTGTGTGGGC ACACGTGGGT GGTCAGGACA
 AGCCCTTCTG CTCTGCCTGG CCCAGCGCTG TGGTGCCTCA AGGAGGACAC GTGACTCTTC
 GGTGTCACTA TCGTCGTGGG TTTAACATCT TCACGCTGTA CAAGAAAGAT GGGGTCCCTG
 TCCCTGAGCT CTACAACAGA ATATTCTGGA ACAGTTTCCT CATTAGCCCT GTGACCCCAG
 CACACGCAGG GACCTACAGA TGTCGAGGTT TTCACCCGCA CTCCCCCACT GAGTGGTCGG
 CACCCAGCAA CCCCCTGGTG ATCATGGTCA CAGGTCTATA TGAGAAACCT TCGCTTACAG
 CCCGGCCGGG CCCCACGGTT CGCGCAGGAG AGAACGTGAC CTTGTCCTGC AGCTCCCAGA
 GCTCCTTTGA CATCTACCAT CTATCCAGGG AGGGGGAAGC CCATGAACTT AGGCTCCCTG
 CAGTGCCCAG CATCAATGGA ACATTCCAGG CCGACTTCCC TCTGGGTCCT GCCACCCACG
 GAGAGACCTA CAGATGCTTC GGCTCTTTCC ATGGATCTCC CTACGAGTGG TCAGACCCGA
 GTGACCCACT GCCTGTTTCT GTCACAGGAA ACCCTTCTAG TAGTTGGCCT TCACCCACTG
 AACCAAGCTT CAAAACTGGT ATCGCCAGAC ACCTGCATGC TGTGATTAGG TACTCAGTGG
 CCATCATCCT CTTTACCATC CTTCCCTTCT TTCTCCTTCA TCGCTGGTGC TCCAAAAAAA
 AAATGCTGCT GTAATGAACC AAGAGCCTGC GGGACACAGA ACAGTGAACA GGGAGGACTC
 TGATGAACAA GACCCTCAGG AGGTGACATA CGCACAGTTG GATCACTGCA TTTTCACACA
 GAGAAAAATC ACTGGCCCTT CTCAGAGGAG CAAGAGACCC TCAACAGATA CCAGCGTGTG
 TATAGAACTT CCAAATGCTG AGCCCAGAGC GTTGTCTCCT GCCCATGAGC ACCACAGTCA
 GGCCTTGATG GGATCTTCTA GGGAGACAAC AGCCCTGTCT CAAACCCAGC TTGCCAGCTC
 TAATGTACCA GCAGCTGGAA TCTGA*   
>DL;IPD:KIR00213
KIR:KIR00213 KIR2DL4*0080104 1105 bases
 TGGCATGTCT TGGGTTCTTC TTGGACCAGA GTGTGTGGGC ACACGTGGGT GGTCAGGACA
 AGCCCTTCTG CTCTGCCTGG CCCAGCGCTG TGGTGCCTCA AGGAGGACAC GTGACTCTTC
 GGTGTCACTA TCGTCGTGGG TTTAACATCT TCACGCTGTA CAAGAAAGAT GGGGTCCCTG
 TCCCTGAGCT CTACAACAGA ATATTCTGGA ACAGTTTCCT CATTAGCCCT GTGACCCCAG
 CACACGCAGG GACCTACAGA TGTCGAGGTT TTCACCCGCA CTCCCCCACT GAGTGGTCGG
 CACCCAGCAA CCCCCTGGTG ATCATGGTCA CAGGTCTATA TGAGAAACCT TCGCTTACAG
 CCCGGCCGGG CCCCACGGTT CGCGCAGGAG AGAACGTGAC CTTGTCCTGC AGCTCCCAGA
 GCTCCTTTGA CATCTACCAT CTATCCAGGG AGGGGGAAGC CCATGAACTT AGGCTCCCTG
 CAGTGCCCAG CATCAATGGA ACATTCCAGG CCGACTTCCC TCTGGGTCCT GCCACCCACG
 GAGAGACCTA CAGATGCTTC GGCTCTTTCC ATGGATCTCC CTACGAGTGG TCAGACCCGA
 GTGACCCACT GCCTGTTTCT GTCACAGGAA ACCCTTCTAG TAGTTGGCCT TCACCCACTG
 AACCAAGCTT CAAAACTGGT ATCGCCAGAC ACCTGCATGC TGTGATTAGG TACTCAGTGG
 CCATCATCCT CTTTACCATC CTTCCCTTCT TTCTCCTTCA TCGCTGGTGC TCCAAAAAAA
 AAATGCTGCT GTAATGAACC AAGAGCCTGC GGGACACAGA ACAGTGAACA GGGAGGACTC
 TGATGAACAA GACCCTCAGG AGGTGACATA CGCACAGTTG GATCACTGCA TTTTCACACA
 GAGAAAAATC ACTGGCCCTT CTCAGAGGAG CAAGAGACCC TCAACAGATA CCAGCGTGTG
 TATAGAACTT CCAAATGCTG AGCCCAGAGC GTTGTCTCCT GCCCATGAGC ACCACAGTCA
 GGCCTTGATG GGATCTTCTA GGGAGACAAC AGCCCTGTCT CAAACCCAGT TTGCCAGCTC
 TAATGTACCA GCAGCTGGAA TCTGA*   
>DL;IPD:KIR00436
KIR:KIR00436 KIR2DL4*0080105 1133 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TTACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA ATGCTGCTGT AATGAACCAA GAGCCTGCGG
 GACACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG GTGACATACG
 CACAGTTGGA TCACTGCATT TTCACACAGA GAAAAATCAC TGGCCCTTCT CAGAGGAGCA
 AGAGACCCTC AACAGATACC AGCGTGTGTA TAGAACTTCC AAATGCTGAG CCCAGAGCGT
 TGTCTCCTGC CCATGAGCAC CACAGTCAGG CCTTGATGGG ATCTTCTAGG GAGACAACAG
 CCCTGTCTCA AACCCAGCTT GCCAGCTCTA ATGTACCAGC AGCTGGAATC TGA*
>DL;IPD:KIR00111
KIR:KIR00111 KIR2DL4*0080201 1133 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAA
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TTACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA ATGCTGCTGT AATGAACCAA GAGCCTGCGG
 GACACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG GTGACATACG
 CACAGTTGGA TCACTGCATT TTCACACAGA GAAAAATCAC TGGCCCTTCT CAGAGGAGCA
 AGAGACCCTC AACAGATACC AGCGTGTGTA TAGAACTTCC AAATGCTGAG CCCAGAGCGT
 TGTCTCCTGC CCATGAGCAC CACAGTCAGG CCTTGATGGG ATCTTCTAGG GAGACAACAG
 CCCTGTCTCA AACCCAGCTT GCCAGCTCTA ATGTACCAGC AGCTGGAATC TGA*
>DL;IPD:KIR00116
KIR:KIR00116 KIR2DL4*0080202 1105 bases
 TGGCATGTCT TGGGTTCTTC TTGGACCAGA GTGTGTGGGC ACACGTGGGT GGTCAGGACA
 AGCCCTTCTG CTCTGCCTGG CCCAGCGCTG TGGTGCCTCA AGGAGGACAC GTGACTCTTC
 GGTGTCACTA TCGTCGTGGG TTTAACATCT TCACGCTGTA CAAGAAAGAT GGGGTCCCTG
 TCCCTGAGCT CTACAACAGA ATATTCTGGA ACAGTTTCCT CATTAGCCCT GTGACCCCAG
 CACACGCAGG GACCTACAGA TGTCGAGGTT TTCACCCGCA CTCCCCCACT GAGTGGTCGG
 CACCCAGCAA CCCCCTGGTG ATCATGGTCA CAGGTCTATA TGAGAAACCT TCGCTTACAG
 CCCGGCCGGG CCCCACGGTT CGCGCAGGAG AGAACGTGAC CTTGTCCTGC AGCTCCCAGA
 GCTCCTTTGA CATCTACCAT CTATCCAGGG AAGGGGAAGC CCATGAACTT AGGCTCCCTG
 CAGTGCCCAG CATCAATGGA ACATTCCAGG CCGACTTCCC TCTGGGTCCT GCCACCCACG
 GAGAGACCTA CAGATGCTTC GGCTCTTTCC ATGGATCTCC CTACGAGTGG TCAGACCCGA
 GTGACCCACT GCCTGTTTCT GTCACAGGAA ACCCTTCTAG TAGTTGGCCT TCACCCACTG
 AACCAAGCTT CAAAACTGGT ATCGCCAGAC ACCTGCATGC TGTGATTAGG TACTCAGTGG
 CCATCATCCT CTTTACCATC CTTCCCTTCT TTCTCCTTCA TCGCTGGTGC TCCAAAAAAA
 AAATGCTGCT GTAATGAACC AAGAGCCTGC GGGACACAGA ACAGTGAACA GGGAGGACTC
 TGATGAACAA GACCCTCAGG AGGTGACATA CGCACAGTTG GATCACTGCA TTTTCACACA
 GAGAAAAATC ACTGGCCCTT CTCAGAGGAG CAAGAGACCC TCAACAGATA CCAGCGTGTG
 TATAGAACTT CCAAATGCTG AGCCCAGAGC GTTGTCTCCT GCCCATGAGC ACCACAGTCA
 GGCCTTGATG GGATCTTCTA GGGAGACAAC AGCCCTGTCT CAAACCCAGC TTGCCAGCTC
 TAATGTACCA GCAGCTGGAA TCTGA*   
>DL;IPD:KIR00437
KIR:KIR00437 KIR2DL4*0080203 1133 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAA
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TTACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA ATGCTGCTGT AATGAACCAA GAGCCTGCGG
 GACACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG GTGACATACG
 CACAGTTGGA TCACTGCATT TTCACACAGA GAAAAATCAC TGGCCCTTCT CAGAGGAGCA
 AGAGACCCTC AACAGATACC AGCGTGTGTA TAGAACTTCC AAATGCTGAG CCCAGAGCGT
 TGTCTCCTGC CCATGAGCAC CACAGTCAGG CCTTGATGGG ATCTTCTAGG GAGACAACAG
 CCCTGTCTCA AACCCAGCTT GCCAGCTCTA ATGTACCAGC AGCTGGAATC TGA*
>DL;IPD:KIR00647
KIR:KIR00647 KIR2DL4*0080204 1133 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAA
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TTACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA ATGCTGCTGT AATGAACCAA GAGCCTGCGG
 GACACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG GTGACATACG
 CACAGTTGGA TCACTGCATT TTCACACAGA GAAAAATCAC TGGCCCTTCT CAGAGGAGCA
 AGAGACCCTC AACAGATACC AGCGTGTGTA TAGAACTTCC AAATGCTGAG CCCAGAGCGT
 TGTCTCCTGC CCATGAGCAC CACAGTCAGG CCTTGATGGG ATCTTCTAGG GAGACAACAG
 CCCTGTCTCA AACCCAGCTT GCCAGCTCTA ATGTACCAGC AGCTGGAATC TGA*
>DL;IPD:KIR00118
KIR:KIR00118 KIR2DL4*00901 1105 bases
 TGGCATGTCT TGGGTTCTTC TTGGACCAGA GTGTGTGGGC ACACGTGGGT GGTCAGGACA
 AGCCCTTCTG CTCTGCCTGG CCCAGCGCTG TGGTGCCTCA AGGAGGACAC GTGACTCTTC
 GGTGTCACTA TCGTCGTGGG TTTAACATCT TCACGCTGTA CAAGAAAGAT GGGGTCCCTG
 TCCCTGAGCT CTACAACAGA ATATTCTGGA ACAGTTTCCT CATTAGCCCT GTGACCCCAG
 CACACGCAGG GACCTACAGA TGTCGAGGTT TTCACCCGCA CTCCCCCACT GAGTGGTCGG
 CACCCAGCAA CCCCCTGGTG ATCATGGTCA CAGGTCTATA TGAGAAACCT TCGCTTACAG
 CCCGGCCGGG CCCCACGGTT CGCGCAGGAG AGAACGTGAC CTTGTCCTGC AGCTCCCAGA
 GCTCCTTTGA CATCTACCAT CTATCCAGGG AGGGGGAAGC CCATGAACTT AGGCTCCCTG
 CAGTGCCCAG CATCAATGGA ACATTCCAGG CCGACTTCCC TGTGGGTCCT GCCACCCACG
 GAGAGACCTA CAGATGCTTC GGCTCTTTCC ATGGATCTCC CTACGAGTGG TCAGACCCGA
 GTGACCCACT GCCTGTTTCT GTCACAGGAA ACCCTTCTAG TAGTTGGCCT TCACCCACTG
 AACCAAGCTT CAAAACTGGT ATCGCCAGAC ACCTGCATGC TGTGATTAGG TACTCAGTGG
 CCATCATCCT CTTTACCATC CTTCCCTTCT TTCTCCTTCA TCGCTGGTGC TCCAAAAAAA
 AAATGCTGCT GTAATGAACC AAGAGCCTGC GGGACACAGA ACAGTGAACA GGGAGGACTC
 TGATGAACAA GACCCTCAGG AGGTGACATA CGCACAGTTG GATCACTGCA TTTTCACACA
 GAGAAAAATC ACTGGCCCTT CTCAGAGGAG CAAGAGACCC TCAACAGATA CCAGCGTGTG
 TATAGAACTT CCAAATGCTG AGCCCAGAGC GTTGTCTCCT GCCCATGAGC ACCACAGTCA
 GGCCTTGATG GGATCTTCTA GGGAGACAAC AGCCCTGTCT CAAACCCAGC TTGCCAGCTC
 TAATGTACCA GCAGCTGGAA TCTGA*   
>DL;IPD:KIR00520
KIR:KIR00520 KIR2DL4*00902 1105 bases
 TGGCATGTCT TGGGTTCTTC TTGGACCAGA GTGTGTGGGC ACACGTGGGT GGTCAGGACA
 AGCCCTTCTG CTCTGCCTGG CCCAGCGCTG TGGTGCCTCA AGGAGGACAC GTGACTCTTC
 GGTGTCACTA TCGTCGTGGG TTTAACATCT TCACGCTGTA CAAGAAAGAT GGGGTCCCTG
 TCCCTGAGCT CTACAACAGA ATATTCTGGA ACAGTTTCCT CATTAGCCCT GTGACCCCAG
 CACACGCAGG GACCTACAGA TGTCGAGGTT TTCACCCGCA CTCCCCCACT GAGTGGTCGG
 CACCCAGCAA CCCCCTGGTG ATCATGGTCA CAGGTCTATA TGAGAAACCT TCGCTTACAG
 CCCGGCCGGG CCCCACGGTT CGCGCAGGAG AGAACGTGAC CTTGTCCTGC AGCTCCCAGA
 GCTCCTTTGA CATCTACCAT CTATCCAGGG AAGGGGAAGC CCATGAACTT AGGCTCCCTG
 CAGTGCCCAG CATCAATGGA ACATTCCAGG CCGACTTCCC TGTGGGTCCT GCCACCCACG
 GAGAGACCTA CAGATGCTTC GGCTCTTTCC ATGGATCTCC CTACGAGTGG TCAGACCCGA
 GTGACCCACT GCCTGTTTCT GTCACAGGAA ACCCTTCTAG TAGTTGGCCT TCACCCACTG
 AACCAAGCTT CAAAACTGGT ATCGCCAGAC ACCTGCATGC TGTGATTAGG TACTCAGTGG
 CCATCATCCT CTTTACCATC CTTCCCTTCT TTCTCCTTCA TCGCTGGTGC TCCAAAAAAA
 AAATGCTGCT GTAATGAACC AAGAGCCTGC GGGACACAGA ACAGTGAACA GGGAGGACTC
 TGATGAACAA GACCCTCAGG AGGTGACATA CGCACAGTTG GATCACTGCA TTTTCACACA
 GAGAAAAATC ACTGGCCCTT CTCAGAGGAG CAAGAGACCC TCAACAGATA CCAGCGTGTG
 TATAGAACTT CCAAATGCTG AGCCCAGAGC GTTGTCTCCT GCCCATGAGC ACCACAGTCA
 GGCCTTGATG GGATCTTCTA GGGAGACAAC AGCCCTGTCT CAAACCCAGC TTGCCAGCTC
 TAATGTACCA GCAGCTGGAA TCTGA*   
>DL;IPD:KIR00114
KIR:KIR00114 KIR2DL4*010 1106 bases
 TGGCATGTCT TGGGTTCTTC TTGGACCAGA GTGTGTGGGC ACACGTGGGT GGTCAGGACA
 AGCCCTTCTG CTCTGCCTGG CCCAGCGCTG TGGTGCCTCA AGGAGGACAC GTGACTCTTC
 GGTGTCACTA TCGTCGTGGG TTTAACATCT TCACGCTGTA CAAGAAAGAT GGGGTCCCTG
 TCCCTGAGCT CTACAACAGA ATATTCTGGA ACAGTTTCCT CATTAGCCCT GTGACCCCAG
 CACACGCAGG GACCTACAGA TGTCGAGGTT TTCACCCGCA CTCCCCCACT GAGTGGTCGG
 CACCCAGCAA CCCCCTGGTG ATCATGGTCA CAGGTCTATA TGAGAAACCT TCGCTTACAG
 CCCGGCTGGG CCCCACGGTT CGCGCAGGAG AGAACGTGAC CTTGTCCTGC AGCTCCCAGA
 GCTCCTTTGA CATCTACCAT CTATCCAGGG AGGGGGAAGC CCATGAACTT AGGCTCCATG
 CAGTGCCCAG CATCAATGGA ACATTCCAGG CCGACTTCCC TCTGGGTCCT GCCACCCACG
 GAGAGACCTA CAGATGCTTC GGCTCTTTCC ATGGATCTCC CTACGAGTGG TCAGACCCGA
 GTGACCCACT GCCTGTTTCT GTCACAGGAA ACCCTTCTAG TAGTTGGCCT TCACCCACTG
 AACCAAGCTT CAAAACTGGT ATCGCCAGAC ACCTGCATGC TGTGATTAGG TACTCAGTGG
 CCATCATCCT CTTCACCATC CTTCCCTTCT TTCTCCTTCA TCGCTGGTGC TCCAAAAAAA
 AAAATGCTGC TGTAATGAAC CAAGAGCCTG CGGGACACAG AACAGTGAAC AGGGAGGACT
 CTGATGAACA AGACCCTCAG GAGGTGACAT ACGCACAGTT GGATCACTGC ATTTTCACAC
 AGAGAAAAAT CACTGGCCCT TCTCAGAGGA GCAAGAGACC CTCAACAGAT ACCAGCGTGT
 GTATAGAACT TCCAAATGCT GAGCCCAGAG CGTTGTCTCC TGCCCATGAG CACCACAGTC
 AGGCCTTGAT GGGATCTTCT AGGGAGACAA CAGCCCTGTC TCAAACCCAG CTTGCCAGCT
 CTAATGTACC AGCAGCTGGA ATCTGA*   
>DL;IPD:KIR00113
KIR:KIR00113 KIR2DL4*011 1133 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTGTC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TTACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA ATGCTGCTGT AATGAACCAA GAGCCTGCGG
 GACACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG GTGACATACG
 CACAGTTGGA TCACTGCATT TTCACACAGA GAAAAATCAC TGGCCCTTCT CAGAGGAGCA
 AGAGACCCTC AACAGATACC AGCGTGTGTA TAGAACTTCC AAATGCTGAG CCCAGAGCGT
 TGTCTCCTGC CCATGAGCAC CACAGTCAGG CCTTGATGGG ATCTTCTAGG GAGACAACAG
 CCCTGTCTCA AACCCAGCTT GCCAGCTCTA ATGTACCAGC AGCTGGAATC TGA*
>DL;IPD:KIR00212
KIR:KIR00212 KIR2DL4*01201 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTGTC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTGAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00593
KIR:KIR00593 KIR2DL4*01202 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTGTC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTGAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCA
 TTGTCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00512
KIR:KIR00512 KIR2DL4*013 1133 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CACAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACGCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TTACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA ATGCTGCTGT AATGAACCAA GAGCCTGCGG
 GACACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG GTGACATACG
 CACAGTTGGA TCACTGCATT TTCACACAGA GAAAAATCAC TGGCCCTTCT CAGAGGAGCA
 AGAGACCCTC AACAGATACC AGCGTGTGTA TAGAACTTCC AAATGCTGAG CCCAGAGCGT
 TGTCTCCTGC CCATGAGCAC CACAGTCAGG CCTTGATGGG ATCTTCTAGG GAGACAACAG
 CCCTGTCTCA AACCCAGCTT GCCAGCTCTA ATGTACCAGC AGCTGGAATC TGA*
>DL;IPD:KIR00521
KIR:KIR00521 KIR2DL4*014 1106 bases
 TGGCATGTCT TGGGTTCTTC TTGGACCAGA GTGTGTGGGC ACACGTGGGT GGTCAGGACA
 AGCCCTTCTG CTCTGCCTGG CCCAGCACTG TGGTGCCTCA AGGAGGACAC GTGACTCTTC
 GGTGTCACTG TCGTCGTGGG TTTAACATCT TCACGCTGTA CAAGAAAGAT GGGGTCCCTG
 TCCCTGAGCT CTACAACAGA ATATTCTGGA ACAGTTTCCT CATTAGCCCT GTGACCCCAG
 CACACGCAGG GACCTACAGA TGTCGAGGTT TTCACCCGCA CTCCCCCACT GAGTGGTCGG
 CACCCAGCAA CCCCCTGGTG ATCATGGTCA CAGGTCTATA TGAGAAACCT TCGCTTACAG
 CCCGGCCGGG CCCCACGGTT CGCGCAGGAG AGAACGTGAC CTTGTCCTGC AGCTCCCAGA
 GCTCCTTTGA CATCTACCAT CTATCCAGGG AGGGGGAAGC CCATGAACTT AGGCTCCCTG
 CAGTGCCCAG CATCAATGGA ACATTCCAGG CCGACTTCCC TCTGGGTCCT GCCACCCACG
 GAGAGACCTA CAGATGCTTC GGCTCTTTCC ATGGATCTCC CTACGAGTGG TCAGACCCGA
 GTGACCCACT GCCTGTTTCT GTCACAGGAA ACCCTTCTAG TAGTTGGCCT TCACCCACTG
 AACCAAGCTT CAAAACTGGT ATCGCCAGAC ACCTGCATGC TGTGATTAGG TACTCAGTGG
 CCATCATCCT CTTCACCATC CTTCCCTTCT TTCTCCTTCA TCGCTGGTGC TCCAAAAAAA
 AAAATGCTGC TGTAATGAAC CAAGAGCCTG CGGGACACAG AACAGTGAAC AGGGAGGACT
 CTGATGAACA AGACCCTCAG GAGGTGACAT ACGCACAGTT GGATCACTGC ATTTTCACAC
 AGAGAAAAAT CACTGGCCCT TCTCAGAGGA GCAAGAGACC CTCAACAGAT ACCAGCGTGT
 GTATAGAACT TCCAAATGCT GAGCCCAGAG CGTTGTCTCC TGCCCATGAG CACCACAGTC
 AGGCCTTGAT GGGATCTTCT AGGGAGACAA CAGCCCTGTC TCAAACCCAG CTTGCCAGCT
 CTAATGTACC AGCAGCTGGA ATCTGA*   
>DL;IPD:KIR00522
KIR:KIR00522 KIR2DL4*015 1106 bases
 TGGCATGTCT TGGGTTCTTC TTGGACCAGA GTGTGTGGGC ACACGTGGGT GGTCAGGACA
 AGCCCTTCTG CTCTGCCTGG CCCAGCGCTG TGGTGCCTCA AGGAGGACAC GTGACTCTTT
 GGTGTCACTA TCGTCGTGGG TTTAACATCT TCACGCTGTA CAAGAAAGAT GGGGTCCCTG
 TCCCTGAGCT CTACAACAGA ATATTCTGGA ACAGTTTCCT CATTAGCCCT GTGACCCCAG
 CACACGCAGG GACCTACAGA TGTCGAGGTT TTCACCCGCA CTCCCCCACT GAGTGGTCGG
 CACCCAGCAA CCCCCTGGTG ATCATGGTCA CAGGTCTATA TGAGAAACCT TCGCTTACAG
 CCCGGCCGGG CCCCACGGTT CGCACAGGAG AGAACGTGAC CTTGTCCTGC AGCTCCCAGA
 GCTCCTTTGA CATCTACCAT CTATCCAGGG AGGGGGAAGC CCATGAACTT AGGCTCCCTG
 CAGTGCCCAG CATCAATGGA ACATTCCAGG CCGACTTCCC TCTGGGTCCT GCCACCCACG
 GAGAGACCTA CAGATGCTTC GGCTCTTTCC ATGGATCTCC CTACGAGTGG TCAGACGCGA
 GTGACCCACT GCCTGTTTCT GTCACAGGAA ACCCTTCTAG TAGTTGGCCT TCACCCACTG
 AACCAAGCTT CAAAACTGGT ATCGCCAGAC ACCTGCATGC TGTGATTAGG TACTCAGTGG
 CCATCATCCT CTTCACCATC CTTCCCTTCT TTCTCCTTCA TCGCTGGTGC TCCAAAAAAA
 AAAATGCTGC TGTAATGAAC CAAGAGCCTG CGGGACACAG AACAGTGAAC AGGGAGGACT
 CTGATGAACA AGACCCTCAG GAGGTGACAT ACGCACAGTT GGATCACTGC ATTTTCACAC
 AGAGAAAAAT CACTGGCCCT TCTCAGAGGA GCAAGAGACC CTCAACAGAT ACCAGCGTGT
 GTATAGAACT TCCAAATGCT GAGCCCAGAG CGTTATCTCC TGCCCATGAG CACCACAGTC
 AGGCCTTGAT GGGATCTTCT AGGGAGACAA CAGCCCTGTC TCAAACCCAG CTTGCCAGCT
 CTAATGTACC AGCAGCTGGA ATCTGA*   
>DL;IPD:KIR00523
KIR:KIR00523 KIR2DL4*016 1106 bases
 TGGCATGTCT TGGGTTCTTC TTGGACCAGA GTGTGTGGGC ACACGTGGGT GGTCAGGACA
 AGCCCTTCTG CTCTGCCTGG CCCAGCGCTG TGGTGCCTCA AGGAGGACAC GTGACTCTTC
 GGTGTCACTA TCGTCGTGGG TTTAACATCT TCACGCTGTA CAAGAAAGAT GGGTTCCCTG
 TCCCTGAGCT CTACAACAGA ATATTCTGGA ACAGTTTCCT CATTAGCCCT GTGACCCCAG
 CACACGCAGG GACCTACAGA TGTCGAGGTT TTCACCCGCA CTCCCCCACT GAGTGGTCGG
 CACCCAGCAA CCCCCTGGTG ATCATGGTCA CAGGTCTATA TGAGAAACCT TCGCTTACAG
 CCCGGCCGGG CCCCACGGTT CGCACAGGAG AGAACGTGAC CTTGTCCTGC AGCTCCCAGA
 GCTCCTTTGA CATCTACCAT CTATCCAGGG AGGGGGAAGC CCATGAACTT AGGCTCCCTG
 CAGTGCCCAG CATCAATGGA ACATTCCAGG CCGACTTCCC TCTGGGTCCT GCCACCCACG
 GAGAGACCTA CAGATGCTTC GGCTCTTTCC ATGGATCTCC CTACGAGTGG TCAGACGCGA
 GTGACCCACT GCCTGTTTCT GTCACAGGAA ACCCTTCTAG TAGTTGGCCT TCACCCACTG
 AACCAAGCTT CAAAACTGGT ATCGCCAGAC ACCTGCATGC TGTGATTAGG TACTCAGTGG
 CCATCATCCT CTTCACCATC CTTCCCTTCT TTCTCCTTCA TCGCTGGTGC TCCAAAAAAA
 AAAATGCTGC TGTAATGAAC CAAGAGCCTG CGGGACACAG AACAGTGAAC AGGGAGGACT
 CTGATGAACA AGACCCTCAG GAGGTGACAT ACGCACAGTT GGATCACTGC ATTTTCACAC
 AGAGAAAAAT CACTGGCCCT TCTCAGAGGA GCAAGAGACC CTCAACAGAT ACCAGCGTGT
 GTATAGAACT TCCAAATGCT GAGCCCAGAG CGTTATCTCC TGCCCATGAG CACCACAGTC
 AGGCCTTGAT GGGATCTTCT AGGGAGACAA CAGCCCTGTC TCAAACCCAG CTTGCCAGCT
 CTAATGTACC AGCAGCTGGA ATCTGA*   
>DL;IPD:KIR00591
KIR:KIR00591 KIR2DL4*017 1133 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAAGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAA
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TTACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA ATGCTGCTGT AATGAACCAA GAGCCTGCGG
 GACACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG GTGACATACG
 CACAGTTGGA TCACTGCATT TTCACACAGA GAAAAATCAC TGGCCCTTCT CAGAGGAGCA
 AGAGACCCTC AACAGATACC AGCGTGTGTA TAGAACTTCC AAATGCTGAG CCCAGAGCGT
 TGTCTCCTGC CCATGAGCAC CACAGTCAGG CCTTGATGGG ATCTTCTAGG GAGACAACAG
 CCCTGTCTCA AACCCAGCTT GCCAGCTCTA ATGTACCAGC AGCTGGAATC TGA*
>DL;IPD:KIR00592
KIR:KIR00592 KIR2DL4*018 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTGGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CACAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCAG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACGCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00594
KIR:KIR00594 KIR2DL4*019 1133 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTGGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CACAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCAG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACGCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TTACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA ATGCTGCTGT AATGAACCAA GAGCCTGCGG
 GACACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG GTGACATACG
 CACAGTTGGA TCACTGCATT TTCACACAGA GAAAAATCAC TGGCCCTTCT CAGAGGAGCA
 AGAGACCCTC AACAGATACC AGCGTGTGTA TAGAACTTCC AAATGCTGAG CCCAGAGCGT
 TGTCTCCTGC CCATGAGCAC CACAGTCAGG CCTTGATGGG ATCTTCTAGG GAGACAACAG
 CCCTGTCTCA AACCCAGCTT GCCAGCTCTA ATGTACCAGC AGCTGGAATC TGA*
>DL;IPD:KIR00595
KIR:KIR00595 KIR2DL4*020 1133 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGTA
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TTACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA ATGCTGCTGT AATGAACCAA GAGCCTGCGG
 GACACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG GTGACATACG
 CACAGTTGGA TCACTGCATT TTCACACAGA GAAAAATCAC TGGCCCTTCT CAGAGGAGCA
 AGAGACCCTC AACAGATACC AGCGTGTGTA TAGAACTTCC AAATGCTGAG CCCAGAGCGT
 TGTCTCCTGC CCATGAGCAC CACAGTCAGG CCTTGATGGG ATCTTCTAGG GAGACAACAG
 CCCTGTCTCA AACCCAGCTT GCCAGCTCTA ATGTACCAGC AGCTGGAATC TGA*
>DL;IPD:KIR00596
KIR:KIR00596 KIR2DL4*021 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CACAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 AACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACGCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00590
KIR:KIR00590 KIR2DL4*022 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CACAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACGCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGTG
 TTGTCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00668
KIR:KIR00668 KIR2DL4*023 1059 bases
 GGTGGTCAGG ACAAGCCCTT CTGCTCTGCC TGGCCCAGCG CTGTGGTGCC TCAAGGAGGA
 CACGTGACTC TTCGGTGTCA CTATCGTCGT GGGTTTAACA TCTTCACGCT GTACAAGAAA
 GATGGGGTCC CTGTCCCTGA GCTCTACAAC AGAATATTCT GGAACAGTTT CCTCATTAGC
 CCTGTGACCC CAGCACACGC AGGGACCTAC AGATGTCGAG GTTTTCACCC GCACTCCCCC
 ACTGAGTGGT CGGCACCCAG CAACCCCCTG GTGATCATGG TCACAGGTCT ATATGAGAAA
 CCTTCGCTTA CAGCCCGGCC GGGCCCCACG GTTCGCACAG GAGAGAACGT GACCTTGTCC
 TGCAGCTCCC AGAGCTCCTT TGACATCTAC CATCTATCCA GGGAGGGGGA AGCCCATGAA
 CTTAGGCTCC CTGCAGTGCC CAGCATCAAT GGAACATTCC AGGCCGACTT CCCTCTGGGT
 CCTGCCACCC ACGGAGAGAC CTACAGATGC TTCAGCTCTT TCCATGGATC TCCCTACGAG
 TGGTCAGACG CGAGTGACCC ACTGCCTGTT TCTGTCACAG GAAACCCTTC TAGTAGTTGG
 CCTTCACCCA CTGAACCAAG CTTCAAAACT GGTATCGCCA GACACCTGCA TGCTGTGATT
 AGGTACTCAG TGGCCATCAT CCTCTTCACC ATCCTTCCCT TCTTTCTCCT TCATCGCTGG
 TGCTCCAAAA AAAAAAATGC TGCTGTAATG AACCAAGAGC CTGCGGGACA CAGAACAGTG
 AACAGGGAGG ACTCTGATGA ACAAGACCCT CAGGAGGTGA CATACGCACA GTTGGATCAC
 TGCATTTTCA CACAGAGAAA AATCACTGGC CCTTCTCAGA GGAGCAAGAG ACCCTCAACA
 GATACCAGCG TGTGTATAGA ACTTCCAAAT GCTGAGCCCA GAGCGTTGTC TCCTGCCCAT
 GAGCACCACA GTCAGGCCTT GATGGGATCT TCTAGGGAGA CAACAGCCCT GTCTCAAACC
 CAGCTTGCCA GCTCTAATGT ACCAGCAGCT GGAATCTGA*  
>DL;IPD:KIR00670
KIR:KIR00670 KIR2DL4*024 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTGTC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTGAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATGAGCA CCACACTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00672
KIR:KIR00672 KIR2DL4*025 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTGTC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATGAGCA CCACACTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00674
KIR:KIR00674 KIR2DL4*026 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CACAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACGCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTGAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATGAGCA CCACACTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00675
KIR:KIR00675 KIR2DL4*027 1133 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CACAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACGCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TTACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA ATGCTGCTGT CATGAACCAA GAGCCTGCGG
 GACACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG GTGACATACG
 CACAGTTGGA TCACTGCATT TTCACACAGA GAAAAATCAC TGGCCCTTCT CAGAGGAGCA
 AGAGACCCTC AACAGATACC AGCGTGTGTA TAGAACTTCC AAATGCTGAG CCCAGAGCGT
 TGTCTCCTGC CCATGAGCAC CACAGTCAGG CCTTGATGGG ATCTTCTAGG GAGACAACAG
 CCCTGTCTCA AACCCAGCTT GCCAGCTCTA ATGTACCAGC AGCTGGAATC TGA*
>DL;IPD:KIR00748
KIR:KIR00748 KIR2DL4*028 1132 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCAGGGCC CCATGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AAAAATCACT GGCCCTTCTC AGAGGAGCAA
 GAGACCCTCA ACAGATACCA GCGTGTGTAT AGAACTTCCA AATGCTGAGC CCAGAGCGTT
 GTCTCCTGCC CATGAGCACC ACAGTCAGGC CTTGATGGGA TCTTCTAGGG AGACAACAGC
 CCTGTCTCAA ACCCAGCTTG CCAGCTCTAA TGTACCAGCA GCTGGAATCT GA*
>DL;IPD:KIR00826
KIR:KIR00826 KIR2DL4*029 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CACAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCAG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACGCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATACTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00830
KIR:KIR00830 KIR2DL4*030 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGTTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CACAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACGCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00828
KIR:KIR00828 KIR2DL4*031 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTGTC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTGAGGA GGTGACATAC
 GCATAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00904
KIR:KIR00904 KIR2DL4*032 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACGACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CACAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACGCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTATCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00905
KIR:KIR00905 KIR2DL4*033 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CACAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACGCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GTCCAGAGCG
 TTATCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00903
KIR:KIR00903 KIR2DL4*034 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTGTC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGT GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00909
KIR:KIR00909 KIR2DL4*035 1133 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGAAG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAA
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TTACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA ATGCTGCTGT AATGAACCAA GAGCCTGCGG
 GACACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG GTGACATACG
 CACAGTTGGA TCACTGCATT TTCACACAGA GAAAAATCAC TGGCCCTTCT CAGAGGAGCA
 AGAGACCCTC AACAGATACC AGCGTGTGTA TAGAACTTCC AAATGCTGAG CCCAGAGCGT
 TGTCTCCTGC CCATGAGCAC CACAGTCAGG CCTTGATGGG ATCTTCTAGG GAGACAACAG
 CCCTGTCTCA AACCCAGCTT GCCAGCTCTA ATGTACCAGC AGCTGGAATC TGA*
>DL;IPD:KIR00912
KIR:KIR00912 KIR2DL4*036 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CACAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACAAGTGGTC AGACGCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTATCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00914
KIR:KIR00914 KIR2DL4*037 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTGTC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCGAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CGCAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACCCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTGTCTCCTG CCCATAAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
>DL;IPD:KIR00928
KIR:KIR00928 KIR2DL4*038 1134 bases
 ATGTCCATGT CACCCACGGT CATCATCCTG GCATGTCTTG GGTTCTTCTT GGACCAGAGT
 GTGTGGGCAC ACGTGGGTGG TCAGGACAAG CCCTTCTGCT CTGCCTGGCC CAGCGCTGTG
 GTGCCTCAAG GAGGACACGT GACTCTTCGG TGTCACTATC GTCGTGGGTT TAACATCTTC
 ACGCTGTACA AGAAAGATGG GGTCCCTGTC CCTGAGCTCT ACAACAGAAT ATTCTGGAAC
 AGTTTCCTCA TTAGCCCTGT GACCCCAGCA CACGCAGGGA CCTACAGATG TCAAGGTTTT
 CACCCGCACT CCCCCACTGA GTGGTCGGCA CCCAGCAACC CCCTGGTGAT CATGGTCACA
 GGTCTATATG AGAAACCTTC GCTTACAGCC CGGCCGGGCC CCACGGTTCG CACAGGAGAG
 AACGTGACCT TGTCCTGCAG CTCCCAGAGC TCCTTTGACA TCTACCATCT ATCCAGGGAG
 GGGGAAGCCC ATGAACTTAG GCTCCCTGCA GTGCCCAGCA TCAATGGAAC ATTCCAGGCC
 GACTTCCCTC TGGGTCCTGC CACCCACGGA GAGACCTACA GATGCTTCGG CTCTTTCCAT
 GGATCTCCCT ACGAGTGGTC AGACGCGAGT GACCCACTGC CTGTTTCTGT CACAGGAAAC
 CCTTCTAGTA GTTGGCCTTC ACCCACTGAA CCAAGCTTCA AAACTGGTAT CGCCAGACAC
 CTGCATGCTG TGATTAGGTA CTCAGTGGCC ATCATCCTCT TCACCATCCT TCCCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAAAAAAAAA AATGCTGCTG TAATGAACCA AGAGCCTGCG
 GGACACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC
 GCACAGTTGG ATCACTGCAT TTTCACACAG AGAAAAATCA CTGGCCCTTC TCAGAGGAGC
 AAGAGACCCT CAACAGATAC CAGCGTGTGT ATAGAACTTC CAAATGCTGA GCCCAGAGCG
 TTATCTCCTG CCCATGAGCA CCACAGTCAG GCCTTGATGG GATCTTCTAG GGAGACAACA
 GCCCTGTCTC AAACCCAGCT TGCCAGCTCT AATGTACCAG CAGCTGGAAT CTGA*
