>P1;KIR:KIR00042
KIR:KIR00042 KIR2DS3*00101 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00043
KIR:KIR00043 KIR2DS3*00102 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00044
KIR:KIR00044 KIR2DS3*0010301 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00636
KIR:KIR00636 KIR2DS3*0010302 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00272
KIR:KIR00272 KIR2DS3*00104 295 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDE*
>P1;KIR:KIR00321
KIR:KIR00321 KIR2DS3*00105 295 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDE*
>P1;KIR:KIR00322
KIR:KIR00322 KIR2DS3*00106 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00131
KIR:KIR00131 KIR2DS3*0020101 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00429
KIR:KIR00429 KIR2DS3*0020102 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00652
KIR:KIR00652 KIR2DS3*0020103 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00232
KIR:KIR00232 KIR2DS3*003N 149 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSX*   
>P1;KIR:KIR00273
KIR:KIR00273 KIR2DS3*004 295 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDE*
>P1;KIR:KIR00529
KIR:KIR00529 KIR2DS3*005 295 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDE*
>P1;KIR:KIR00663
KIR:KIR00663 KIR2DS3*006 281 bases
 GFRRKPSLLA HPGRLVKSEE RVILQCWSDV MFEHFLLHRE GTFNDTLRLI GEHIDGVSKA
 NFSIGRMRQD LAGTYRCYGS VPHSPYQFSA PSDPLDIVIT GLYEKPSLSA QPGPTVLAGE
 SVTLSCSSWS SYDMYHLSTE GEAHERRFSA GPKVNGTFQA DFPLGPATQG GTYRCFGSFH
 DSPYEWSKSS DPLLVSVTGN PSNSWPSPTE PSSKTGNPRH LHVLIGTSVV KLPFTILLFF
 LLHRWCSDKK NASVMDQGPA GNRTVNREDS DEQDHQEVSY A* 
>P1;KIR:KIR00699
KIR:KIR00699 KIR2DS3*007 304 bases
 MSLMVISMAC VAFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00885
KIR:KIR00885 KIR2DS3*008 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDAMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
