>P1;KIR:KIR00049
KIR:KIR00049 KIR2DS5*001 304 bases
 MLLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LPAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADSPLDPA THGGAYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00050
KIR:KIR00050 KIR2DS5*0020101 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00299
KIR:KIR00299 KIR2DS5*0020102 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00297
KIR:KIR00297 KIR2DS5*0020103 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00433
KIR:KIR00433 KIR2DS5*0020104 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNRT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00532
KIR:KIR00532 KIR2DS5*00202 283 bases
 FFLLQGAWPH EGFRRKPSLL AHPGPLVKSE ETVILQCWSD VMFEHFLLHR EGTFNHTLRL
 IGEHIDGVSK GNFSIGRMTQ DLAGTYRCYG SVTHSPYQLS APSDPLDIVI TGLYEKPSLS
 AQPGPTVLAG ESVTLSCSSR SSYDMYHLSR EGEAHERRLP AGPKVNRTFQ ADFPLDPATH
 GGTYRCFGSF RDSPYEWSKS SDPLLVSVTG NSSNSWPSPT EPSSETGNPR HLHVLIGTSV
 VKLPFTILLF FLLHRWCSNK KNASVMDQGP AGNRTVNRED SDE* 
>P1;KIR:KIR00051
KIR:KIR00051 KIR2DS5*003 298 bases
 SMACVAFFLL QGAWPHEGFR RKPSLLAHPG PLVKSEETVI LQCWSDVMFE HFLLHREGTF
 NHTLRLIGEH IDGVSKGNFS IGRMTQDLAG TYRCYGSVTH SPYQLSAPSD PLDIVITGLY
 EKPSLSAQPG PTVLAGENVT LSCSSRSSYD MYHLSREGEA HERRLPAGPK VNGTFQADFP
 LDPATHGGTY RCFGSFRDSP YEWSKSSDPL LVSVTGNSSN SWPSPTEPSS ETGNPRHLHV
 LIGTSVVKLP FTILLFFLLH RWCSNKKNAS VMDQGPAGNR TVNREDSDEQ DHQEVSYA*
>P1;KIR:KIR00100
KIR:KIR00100 KIR2DS5*004 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLDPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00101
KIR:KIR00101 KIR2DS5*00501 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00706
KIR:KIR00706 KIR2DS5*00502 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00276
KIR:KIR00276 KIR2DS5*006 304 bases
 MSLMVISKAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00277
KIR:KIR00277 KIR2DS5*007 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00278
KIR:KIR00278 KIR2DS5*00801 283 bases
 FFLLQGAWPR EGFRRKPSLL AHPGPLVKSE ETVILQCWSD VMFEHFLLHR EGTFNHTLRL
 IGEHIDGVSK GNFSIGRMTQ DLAGTYRCYG SVTHSPYQLS APSDPLDIVI TGLYEKPSLS
 AQPGPTVLAG ESVTLSCSSR SSYDMYHLSR EGEAHERRLP AGPKVNGTFQ ADFPLDPATH
 GGTYRCFGSF RDSPYEWSKS SDPLLVSVTG NSSNSWPSPT EPSSETGNPR HLHVLIGTSV
 VKLPFTILLF FLLHRWCSNK KNASVMDQGP AGNRTVNRED SDE* 
>P1;KIR:KIR00339
KIR:KIR00339 KIR2DS5*00802 283 bases
 FFLLQGAWPR EGFRRKPSLL AHPGPLVKSE ETVILQCWSD VMFEHFLLHR EGTFNHTLRL
 IGEHIDGVSK GNFSIGRMTQ DLAGTYRCYG SVTHSPYQLS APSDPLDIVI TGLYEKPSLS
 AQPGPTVLAG ESVTLSCSSR SSYDMYHLSR EGEAHERRLP AGPKVNGTFQ ADFPLDPATH
 GGTYRCFGSF RDSPYEWSKS SDPLLVSVTG NSSNSWPSPT EPSSETGNPR HLHVLIGTSV
 VKLPFTILLF FLLHRWCSNK KNASVMDQGP AGNRTVNRED SDE* 
>P1;KIR:KIR00319
KIR:KIR00319 KIR2DS5*009 292 bases
 FFLLQGAWPH EGFRRKPSLL AHPGPLVKSE ETVILQCWSD VMFEHFLLHR EGTFNHTLRL
 IGEHIDGVSK GNFSIGRMTQ DLAGTYRCYG SVTHSPYQLS APSDPLDIVI TGLYEKPSLS
 AQPGPTVLAG ESVTLSCSSR SSYDMYHLSR EGEAHERRLP AGPKVNRTFQ ADFPLDPATH
 GGTYTCFGSF RDSPYEWSKS SDPLLVSVTG NSSNSWPSPT EPSSETGNPR HLHVLIGTSV
 VKLPFTILLF FLLHRWCSNK KNASVMDQGP AGNRTVNRED SDEQDHQEVS YA*
>P1;KIR:KIR00432
KIR:KIR00432 KIR2DS5*010 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLFCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLDPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00665
KIR:KIR00665 KIR2DS5*011 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNRT
 FQADFPLDPA THGGTYTCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00680
KIR:KIR00680 KIR2DS5*012 304 bases
 MSLMVISMAC VAFFLLQGAW PHEGFRRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKGNFSIGRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNSSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
