>DL;KIR:KIR00536
KIR:KIR00536 KIR2DL5A*014 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CCGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00537
KIR:KIR00537 KIR2DL5A*015 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTTGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA TGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00907
KIR:KIR00907 KIR2DL5A*022 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGAG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00993
KIR:KIR00993 KIR2DL5A*024 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAG GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01191
KIR:KIR01191 KIR2DL5A*025 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCATCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01194
KIR:KIR01194 KIR2DL5A*026 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCTCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01195
KIR:KIR01195 KIR2DL5A*027 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGAAA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01202
KIR:KIR01202 KIR2DL5A*028 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGAGTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01210
KIR:KIR01210 KIR2DL5A*029 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCATCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01213
KIR:KIR01213 KIR2DL5A*030 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA GTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01220
KIR:KIR01220 KIR2DL5A*031 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACTCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01223
KIR:KIR01223 KIR2DL5A*032N 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTTAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01588
KIR:KIR01588 KIR2DL5A*040 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGAG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01687
KIR:KIR01687 KIR2DL5A*042 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCGC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00259
KIR:KIR00259 KIR2DL5A*00102 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00260
KIR:KIR00260 KIR2DL5A*00103 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00262
KIR:KIR00262 KIR2DL5A*00104 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00263
KIR:KIR00263 KIR2DL5A*00105 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TTGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01201
KIR:KIR01201 KIR2DL5A*00106 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC CGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01214
KIR:KIR01214 KIR2DL5A*00107 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA TTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01218
KIR:KIR01218 KIR2DL5A*00108 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC TAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00391
KIR:KIR00391 KIR2DL5A*01201 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00389
KIR:KIR00389 KIR2DL5A*01202 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCGAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCCAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00029
KIR:KIR00029 KIR2DL5A*0010101 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00300
KIR:KIR00300 KIR2DL5A*0010102 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00439
KIR:KIR00439 KIR2DL5A*0010103 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01039
KIR:KIR01039 KIR2DL5A*0010104 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01041
KIR:KIR01041 KIR2DL5A*0010105 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01217
KIR:KIR01217 KIR2DL5A*0010106 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01196
KIR:KIR01196 KIR2DL5A*0010901 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA TGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01219
KIR:KIR01219 KIR2DL5A*0010902 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA TGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00095
KIR:KIR00095 KIR2DL5A*0050101 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00249
KIR:KIR00249 KIR2DL5A*0050102 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00438
KIR:KIR00438 KIR2DL5A*0050103 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00440
KIR:KIR00440 KIR2DL5A*0050104 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01209
KIR:KIR01209 KIR2DL5A*0050105 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00882
KIR:KIR00882 KIR2DL5A*0210101 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCAGA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01221
KIR:KIR01221 KIR2DL5A*0210102 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCAGA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01222
KIR:KIR01222 KIR2DL5A*0210103 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCAGA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00992
KIR:KIR00992 KIR2DL5A*0230101 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCACACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01199
KIR:KIR01199 KIR2DL5A*0230102 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCACACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01200
KIR:KIR01200 KIR2DL5A*0330101 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACACA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01212
KIR:KIR01212 KIR2DL5A*0330102 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACACA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01215
KIR:KIR01215 KIR2DL5A*0340101 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAT ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01216
KIR:KIR01216 KIR2DL5A*0340102 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAT ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
