>P1;KIR:KIR00029
KIR:KIR00029 KIR2DL5A*0010101 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00300
KIR:KIR00300 KIR2DL5A*0010102 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00439
KIR:KIR00439 KIR2DL5A*0010103 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01039
KIR:KIR01039 KIR2DL5A*0010104 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01041
KIR:KIR01041 KIR2DL5A*0010105 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01217
KIR:KIR01217 KIR2DL5A*0010106 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00259
KIR:KIR00259 KIR2DL5A*00102 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00260
KIR:KIR00260 KIR2DL5A*00103 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00262
KIR:KIR00262 KIR2DL5A*00104 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00263
KIR:KIR00263 KIR2DL5A*00105 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01201
KIR:KIR01201 KIR2DL5A*00106 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01214
KIR:KIR01214 KIR2DL5A*00107 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01218
KIR:KIR01218 KIR2DL5A*00108 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01196
KIR:KIR01196 KIR2DL5A*0010901 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01219
KIR:KIR01219 KIR2DL5A*0010902 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00095
KIR:KIR00095 KIR2DL5A*0050101 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00249
KIR:KIR00249 KIR2DL5A*0050102 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00438
KIR:KIR00438 KIR2DL5A*0050103 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00440
KIR:KIR00440 KIR2DL5A*0050104 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01209
KIR:KIR01209 KIR2DL5A*0050105 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00391
KIR:KIR00391 KIR2DL5A*01201 375 bases
 MSLMVISMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00389
KIR:KIR00389 KIR2DL5A*01202 375 bases
 MSLMVISMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00536
KIR:KIR00536 KIR2DL5A*014 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHRGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00537
KIR:KIR00537 KIR2DL5A*015 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVCTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00882
KIR:KIR00882 KIR2DL5A*0210101 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAQKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01221
KIR:KIR01221 KIR2DL5A*0210102 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAQKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01222
KIR:KIR01222 KIR2DL5A*0210103 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAQKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00907
KIR:KIR00907 KIR2DL5A*022 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRSSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00992
KIR:KIR00992 KIR2DL5A*0230101 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVHTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01199
KIR:KIR01199 KIR2DL5A*0230102 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVHTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00993
KIR:KIR00993 KIR2DL5A*024 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTRYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01191
KIR:KIR01191 KIR2DL5A*025 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SINGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01194
KIR:KIR01194 KIR2DL5A*026 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GSTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01195
KIR:KIR01195 KIR2DL5A*027 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKK PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01202
KIR:KIR01202 KIR2DL5A*028 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVSLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01210
KIR:KIR01210 KIR2DL5A*029 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SHLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01213
KIR:KIR01213 KIR2DL5A*030 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREESDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01220
KIR:KIR01220 KIR2DL5A*031 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NSLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01223
KIR:KIR01223 KIR2DL5A*032N 316 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSX    
>P1;KIR:KIR01200
KIR:KIR01200 KIR2DL5A*0330101 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDT LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01212
KIR:KIR01212 KIR2DL5A*0330102 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDT LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01215
KIR:KIR01215 KIR2DL5A*0340101 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTYTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01216
KIR:KIR01216 KIR2DL5A*0340102 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTYTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01588
KIR:KIR01588 KIR2DL5A*040 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRSSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00030
KIR:KIR00030 KIR2DL5B*0020101 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00248
KIR:KIR00248 KIR2DL5B*0020102 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00301
KIR:KIR00301 KIR2DL5B*0020103 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00394
KIR:KIR00394 KIR2DL5B*0020104 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00524
KIR:KIR00524 KIR2DL5B*0020106 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00632
KIR:KIR00632 KIR2DL5B*0020107 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01095
KIR:KIR01095 KIR2DL5B*0020108 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01197
KIR:KIR01197 KIR2DL5B*0020109 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01198
KIR:KIR01198 KIR2DL5B*0020110 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01204
KIR:KIR01204 KIR2DL5B*0020111 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00535
KIR:KIR00535 KIR2DL5B*0020201 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00972
KIR:KIR00972 KIR2DL5B*0020202 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00802
KIR:KIR00802 KIR2DL5B*00203 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00994
KIR:KIR00994 KIR2DL5B*00204 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01193
KIR:KIR01193 KIR2DL5B*00205 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00031
KIR:KIR00031 KIR2DL5B*003 375 bases
 MSLMVVSMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIMVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00032
KIR:KIR00032 KIR2DL5B*004 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSTVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00125
KIR:KIR00125 KIR2DL5B*00601 375 bases
 MSLMVVSMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00267
KIR:KIR00267 KIR2DL5B*00602 375 bases
 MSLMVVSMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00393
KIR:KIR00393 KIR2DL5B*00603 375 bases
 MSLMVVSMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00126
KIR:KIR00126 KIR2DL5B*0070101 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIMVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00525
KIR:KIR00525 KIR2DL5B*0070102 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIMVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00244
KIR:KIR00244 KIR2DL5B*0080101 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00395
KIR:KIR00395 KIR2DL5B*0080102 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00266
KIR:KIR00266 KIR2DL5B*00802 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00682
KIR:KIR00682 KIR2DL5B*00803 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00805
KIR:KIR00805 KIR2DL5B*00804 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00946
KIR:KIR00946 KIR2DL5B*00805 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00245
KIR:KIR00245 KIR2DL5B*009 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGILRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00264
KIR:KIR00264 KIR2DL5B*010 375 bases
 MSLMVVSMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00265
KIR:KIR00265 KIR2DL5B*011 375 bases
 MSLMVVSMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCIFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00390
KIR:KIR00390 KIR2DL5B*01301 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVCTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00392
KIR:KIR00392 KIR2DL5B*01302 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVCTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00534
KIR:KIR00534 KIR2DL5B*01303 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVCTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00801
KIR:KIR00801 KIR2DL5B*01304 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVCTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00538
KIR:KIR00538 KIR2DL5B*016 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSYP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00664
KIR:KIR00664 KIR2DL5B*017 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKNNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00684
KIR:KIR00684 KIR2DL5B*018 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVH RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCWGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00803
KIR:KIR00803 KIR2DL5B*019 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVCTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKNNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00804
KIR:KIR00804 KIR2DL5B*020 304 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHX     
>P1;KIR:KIR01205
KIR:KIR01205 KIR2DL5B*035 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVIYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01206
KIR:KIR01206 KIR2DL5B*036 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRDLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01208
KIR:KIR01208 KIR2DL5B*037 375 bases
 MSLMVVSMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP CSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01190
KIR:KIR01190 KIR2DL5B*038 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHRGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01207
KIR:KIR01207 KIR2DL5B*0390101 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP CSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01203
KIR:KIR01203 KIR2DL5B*0390102 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP CSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01596
KIR:KIR01596 KIR2DL5B*041 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRYRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
