>DL;IPD:KIR00052
KIR:KIR00052 KIR2DP1*00101 572 bases
 GGTTCTTCTT GCTGCAGGGG GCCTGGCCAC ATGAGGGAGT CCACAGAAAA CCTTCCCTCC
 TGGCCCACCC AGGTCCCCTG GTGAAATCAG AAGAGACAGT CATCCTGCAA TGTTGGTCAG
 ATGTCAGGTT TGAGCACTTC CTTCTGCACA GAGAGGGGAC ATTTAACGAC ACTTTGCACC
 TCACTGGAGA GCACCATGAT GGGGTCTCCA AGGCCAACTT CTCCATCGGT CCCATGATGG
 AAGACCTGGC AGGGACCTAC AGATGCTACG GTTCTGTTAC TCACTCCCCC ATCAGTTGTC
 AGCTCCCAGT GACCCTCTGG ACATCGTCAT CACAGGTCTA TATGAGAAAC CTTCTCTCTC
 AGCCCAGCCG GGCCCCACGG TTCTGGCAGG AGAGAGCGTG ACCTTGTCCT GCAGCTCCCG
 GAGCTCCTAT GACATGTACC ATCTATCCAC GGAGGGGGAG GCCCATGAAC GTAGGTTCTC
 TGCAGGGACC AAGGTCAACG GAACATTCCA GGCTGACTTT CCTCTGGGCC CTGCCACCCA
 CGGAGGAACC TACAGATGCT TCGGCTCTTT CC*  
>DL;IPD:KIR00127
KIR:KIR00127 KIR2DP1*0010201 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACATTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCACGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCGAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCT AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA CGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00649
KIR:KIR00649 KIR2DP1*0010202 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACATTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCACGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCGAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCT AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA CGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00634
KIR:KIR00634 KIR2DP1*0010203 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACATTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCACGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCGAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCT AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA CGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00694
KIR:KIR00694 KIR2DP1*00103 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACATTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT TGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA CGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00053
KIR:KIR00053 KIR2DP1*0020101 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA AGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00293
KIR:KIR00293 KIR2DP1*0020102 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA AGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00442
KIR:KIR00442 KIR2DP1*0020103 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA AGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00443
KIR:KIR00443 KIR2DP1*0020104 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA AGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00444
KIR:KIR00444 KIR2DP1*0020105 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA AGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00445
KIR:KIR00445 KIR2DP1*0020106 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA AGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00621
KIR:KIR00621 KIR2DP1*0020107 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA AGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00633
KIR:KIR00633 KIR2DP1*0020108 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA AGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00625
KIR:KIR00625 KIR2DP1*0020109 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA AGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00690
KIR:KIR00690 KIR2DP1*00202 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGATCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA AGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00880
KIR:KIR00880 KIR2DP1*00203 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCA AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA AGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00892
KIR:KIR00892 KIR2DP1*00204 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA CGACACTTTG CACCTCACGG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA AGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00242
KIR:KIR00242 KIR2DP1*0030101 1049 bases
 ATGTCGCTCA CGGTCGTCAG CGTGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA AGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00648
KIR:KIR00648 KIR2DP1*0030102 1049 bases
 ATGTCGCTCA CGGTCGTCAG CGTGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA AGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00473
KIR:KIR00473 KIR2DP1*004 1049 bases
 ATGTCGCTCA CGGTCGTCAG CGTGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAA TGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA AGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00474
KIR:KIR00474 KIR2DP1*005 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA AGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00475
KIR:KIR00475 KIR2DP1*006 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACATTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCGAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA CGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00476
KIR:KIR00476 KIR2DP1*007 1049 bases
 ATGTCGCTCA CGGTCGTCAG CGTGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACAGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAGCC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA AGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00477
KIR:KIR00477 KIR2DP1*008 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TTTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA AGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00478
KIR:KIR00478 KIR2DP1*009 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAT GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCG
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA AGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00622
KIR:KIR00622 KIR2DP1*010 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACATTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGGG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA CGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00692
KIR:KIR00692 KIR2DP1*011 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACATTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCACGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCAAGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCGAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCT AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA CGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00686
KIR:KIR00686 KIR2DP1*012 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACATTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCACGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GACCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCGAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCT AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA CGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00688
KIR:KIR00688 KIR2DP1*013 1049 bases
 ATGTCGCTCA CGGTCGTCAG CGTGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA CGACACTTCG CACCTCACTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACGGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA AGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00685
KIR:KIR00685 KIR2DP1*014 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACATTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGGG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA CGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00861
KIR:KIR00861 KIR2DP1*015 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACATTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCACGGAGGG GGAGGCCCAA GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCGAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCT AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA CGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00881
KIR:KIR00881 KIR2DP1*016 1049 bases
 ATGTCGCTCA CGGTCGTCAG CGTGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCT
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATGCCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA CGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00884
KIR:KIR00884 KIR2DP1*017 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA TCTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA AGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00886
KIR:KIR00886 KIR2DP1*018 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACATTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACAGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCACGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCGAA ACCGGTAACC
 CAAGACACCT GCACATTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCT AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA CGTTGTCTCC TGCCCATGA*   
>DL;IPD:KIR00894
KIR:KIR00894 KIR2DP1*019 1049 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA CGACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGGAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCTGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTTGGCT
 CTTTCCGTGA CTCTCCCTAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CAAGACACCT GCACGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAGAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GCGAATAGCG AGGACTCTGA TGAACAAGAC CCTCAGGAGG
 TGACATACGT ACAGTTGGAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC
 AGAGGCCCAA GACACCCCCA ACAGATACCA GAGTGTACAC GGAACTTCCA AATGCTGAGT
 CCAGATCCAA AGTTGTCTCC TGCCCATGA*   
