>P1;KIR:KIR00037
KIR:KIR00037 KIR2DS2*0010101 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00302
KIR:KIR00302 KIR2DS2*0010102 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00270
KIR:KIR00270 KIR2DS2*0010103 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00336
KIR:KIR00336 KIR2DS2*0010104 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00446
KIR:KIR00446 KIR2DS2*0010105 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00447
KIR:KIR00447 KIR2DS2*0010106 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00448
KIR:KIR00448 KIR2DS2*0010107 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00449
KIR:KIR00449 KIR2DS2*0010108 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00450
KIR:KIR00450 KIR2DS2*0010109 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00451
KIR:KIR00451 KIR2DS2*0010110 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00623
KIR:KIR00623 KIR2DS2*0010111 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00635
KIR:KIR00635 KIR2DS2*0010112 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01266
KIR:KIR01266 KIR2DS2*0010113 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01270
KIR:KIR01270 KIR2DS2*0010114 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01272
KIR:KIR01272 KIR2DS2*0010115 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01273
KIR:KIR01273 KIR2DS2*0010116 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01274
KIR:KIR01274 KIR2DS2*0010117 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01275
KIR:KIR01275 KIR2DS2*0010118 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01276
KIR:KIR01276 KIR2DS2*0010119 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01277
KIR:KIR01277 KIR2DS2*0010120 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01278
KIR:KIR01278 KIR2DS2*0010121 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01280
KIR:KIR01280 KIR2DS2*0010122 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01282
KIR:KIR01282 KIR2DS2*0010123 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01285
KIR:KIR01285 KIR2DS2*0010124 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01286
KIR:KIR01286 KIR2DS2*0010125 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01288
KIR:KIR01288 KIR2DS2*0010126 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01292
KIR:KIR01292 KIR2DS2*0010127 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01293
KIR:KIR01293 KIR2DS2*0010128 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01294
KIR:KIR01294 KIR2DS2*0010129 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01303
KIR:KIR01303 KIR2DS2*0010130 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00097
KIR:KIR00097 KIR2DS2*00102 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00098
KIR:KIR00098 KIR2DS2*00103 296 bases
 SLMVVSMACV GFFLLQGAWP HEGVHRKPSL LAHPGPLVKS EETVILQCWS DVRFEHFLLH
 REGKYKDTLH LIGEHHDGVS KANFSIGPMM QDLAGTYRCY GSVTHSPYQL SAPSDPLDIV
 ITGLYEKPSL SAQPGPTVLA GESVTLSCSS RSSYDMYHLS REGEAHERRF SAGPKVNGTF
 QADFPLGPAT HGGTYRCFGS FRDSPYEWSN SSDPLLVSVT GNPSNSWPSP TEPSSKTGNP
 RHLHVLIGTS VVKIPFTILL FFLLHRWCSN KKNAAVMDQE PAGNRTVNSE DSDEQD
>P1;KIR:KIR00211
KIR:KIR00211 KIR2DS2*00104 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00973
KIR:KIR00973 KIR2DS2*00105 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01263
KIR:KIR01263 KIR2DS2*00106 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01291
KIR:KIR01291 KIR2DS2*0010701 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01287
KIR:KIR01287 KIR2DS2*0010702 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00038
KIR:KIR00038 KIR2DS2*002 304 bases
 MSLMVVSMAC VGFFLLQGAG PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00039
KIR:KIR00039 KIR2DS2*003 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 SRYLHALIGT SVVIIPFAIL LFFLLHRWCA NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00040
KIR:KIR00040 KIR2DS2*004 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00041
KIR:KIR00041 KIR2DS2*005 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00337
KIR:KIR00337 KIR2DS2*00601 297 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQD
>P1;KIR:KIR01283
KIR:KIR01283 KIR2DS2*00602 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00530
KIR:KIR00530 KIR2DS2*007 297 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS FLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQD
>P1;KIR:KIR00531
KIR:KIR00531 KIR2DS2*008 297 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQD
>P1;KIR:KIR00906
KIR:KIR00906 KIR2DS2*0090101 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGSLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01297
KIR:KIR01297 KIR2DS2*0090102 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGSLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01264
KIR:KIR01264 KIR2DS2*010 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRGSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01265
KIR:KIR01265 KIR2DS2*011 304 bases
 MSLMVVSMAC VGFFLLQGAG PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGETVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01268
KIR:KIR01268 KIR2DS2*012 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSASSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01271
KIR:KIR01271 KIR2DS2*013 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01279
KIR:KIR01279 KIR2DS2*014 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGK
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01281
KIR:KIR01281 KIR2DS2*015 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 FITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01284
KIR:KIR01284 KIR2DS2*016 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01289
KIR:KIR01289 KIR2DS2*017 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRIVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01298
KIR:KIR01298 KIR2DS2*018 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01301
KIR:KIR01301 KIR2DS2*019 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNR EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01267
KIR:KIR01267 KIR2DS2*0200101 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PIHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01299
KIR:KIR01299 KIR2DS2*0200102 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PIHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01300
KIR:KIR01300 KIR2DS2*0200103 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PIHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01302
KIR:KIR01302 KIR2DS2*0200104 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PIHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01269
KIR:KIR01269 KIR2DS2*0210101 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHCWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01290
KIR:KIR01290 KIR2DS2*0210102 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHCWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01295
KIR:KIR01295 KIR2DS2*0210103 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHCWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01609
KIR:KIR01609 KIR2DS2*022 304 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
