>P1;KIR:KIR00010
KIR:KIR00010 KIR2DL2*0010101 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV IGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYAELPNAES RSKVVSCP 
>P1;KIR:KIR00405
KIR:KIR00405 KIR2DL2*0010102 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV IGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYAELPNAES RSKVVSCP 
>P1;KIR:KIR00407
KIR:KIR00407 KIR2DL2*0010103 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV IGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYAELPNAES RSKVVSCP 
>P1;KIR:KIR00410
KIR:KIR00410 KIR2DL2*0010104 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV IGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYAELPNAES RSKVVSCP 
>P1;KIR:KIR00618
KIR:KIR00618 KIR2DL2*0010105 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV IGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYAELPNAES RSKVVSCP 
>P1;KIR:KIR00645
KIR:KIR00645 KIR2DL2*0010106 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV IGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYAELPNAES RSKVVSCP 
>P1;KIR:KIR00630
KIR:KIR00630 KIR2DL2*0010107 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV IGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYAELPNAES RSKVVSCP 
>P1;KIR:KIR00324
KIR:KIR00324 KIR2DL2*00102 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV IGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYAELPNAES RSKVVSCP 
>P1;KIR:KIR00850
KIR:KIR00850 KIR2DL2*00103 344 bases
 LMVVSMACVG FFLLQGAWPH EGVHRKPSLL AHPGRLVKSE ETVILQCWSD VRFEHFLLHR
 EGKFKDTLHL IGEHHDGVSK ANFSIGPMMQ DLAGTYRCYG SVTHSPYQLS APSDPLDIVI
 TGLYEKPSLS AQPGPTVLAG ESVTLSCSSR SSYDMYHLSR EGEAHECRFS AGPKVNGTFQ
 ADFPLGPATH GGTYRCFGSF RDSPYEWSNS SDPLLVSVIG NPSNSWPSPT EPSSKTGNPR
 HLHILIGTSV VIILFILLFF LLHRWCSNKK NAAVMDQESA GNRTANSEDS DEQDPQEVTY
 TQLNHCVFTQ RKITRPSQRP KTPPTDIIVY AELPNAESRS KVVS 
>P1;KIR:KIR00011
KIR:KIR00011 KIR2DL2*002 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV IGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANRQ DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYAELPNAES RSKVVSCP 
>P1;KIR:KIR00012
KIR:KIR00012 KIR2DL2*0030101 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP 
>P1;KIR:KIR00316
KIR:KIR00316 KIR2DL2*0030102 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP 
>P1;KIR:KIR00335
KIR:KIR00335 KIR2DL2*0030103 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP 
>P1;KIR:KIR00406
KIR:KIR00406 KIR2DL2*0030104 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP 
>P1;KIR:KIR00408
KIR:KIR00408 KIR2DL2*0030105 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP 
>P1;KIR:KIR00409
KIR:KIR00409 KIR2DL2*0030106 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP 
>P1;KIR:KIR00411
KIR:KIR00411 KIR2DL2*0030107 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP 
>P1;KIR:KIR01089
KIR:KIR01089 KIR2DL2*0030108 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP 
>P1;KIR:KIR00587
KIR:KIR00587 KIR2DL2*00302 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP 
>P1;KIR:KIR00653
KIR:KIR00653 KIR2DL2*00303 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP 
>P1;KIR:KIR00654
KIR:KIR00654 KIR2DL2*00304 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP 
>P1;KIR:KIR00013
KIR:KIR00013 KIR2DL2*004 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HTEGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLDPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANIE DSDEQDPQEV
 TYTQLNHCVF TQRKITHPSQ RPKTPPTDII VYTELPSAES RSKVVSCP 
>P1;KIR:KIR00096
KIR:KIR00096 KIR2DL2*005 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV IGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP 
>P1;KIR:KIR00325
KIR:KIR00325 KIR2DL2*00601 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP 
>P1;KIR:KIR00326
KIR:KIR00326 KIR2DL2*00602 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP 
>P1;KIR:KIR00328
KIR:KIR00328 KIR2DL2*007 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV IGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVAIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYAELPNAES RSKVVSCP 
>P1;KIR:KIR00584
KIR:KIR00584 KIR2DL2*008 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV IGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP 
>P1;KIR:KIR00585
KIR:KIR00585 KIR2DL2*009 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP 
>P1;KIR:KIR00586
KIR:KIR00586 KIR2DL2*010 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV IGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSYEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP 
>P1;KIR:KIR00661
KIR:KIR00661 KIR2DL2*011 325 bases
 GVHRKPSLLA HPGPLVKSEE TVILQCWSDV RFEHFLLHRE GKFKDTLHLI GEHHDGVSKA
 NFSIGPMMQD LAGTYRCYGS VTHSPYQLSA PSDPLDIVIT GLYEKPSLSA QPGPTVLAGE
 SVTLSCSSRS SYDMYHLSRE GEAHECRFSA GPKVNGTFQA DFPLDPATHG GTYRCFGSFR
 DSPYEWSNSS DPLLVSVTGN PSNSWPSPTE PSSETGNPRH LHILIGTSVV IILFILLFFL
 LHRWCSNKKN AAVMDQESAG NRTANIEDSD EQDPQEVTYT QLNHCVFTQR KITHPSQRPK
 TPPTDIIVYT ELPSAESRSK VVSCP   
>P1;KIR:KIR00678
KIR:KIR00678 KIR2DL2*012 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEEVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP 
>P1;KIR:KIR00765
KIR:KIR00765 KIR2DL2*013 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCCN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAEP RSKVVSCP 
>P1;KIR:KIR00984
KIR:KIR00984 KIR2DL2*014 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVQ SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDRYHL SREGEAHECR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP 
>P1;KIR:KIR00985
KIR:KIR00985 KIR2DL2*015 348 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV IGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYAELPNAES RSKVVSCP 
