>DL;IPD:KIR00042
KIR:KIR00042 KIR2DS3*00101 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ACGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00043
KIR:KIR00043 KIR2DS3*00102 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC GGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00044
KIR:KIR00044 KIR2DS3*0010301 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00636
KIR:KIR00636 KIR2DS3*0010302 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00272
KIR:KIR00272 KIR2DS3*00104 887 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAATGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACA* 
>DL;IPD:KIR00321
KIR:KIR00321 KIR2DS3*00105 887 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTTGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACA* 
>DL;IPD:KIR00322
KIR:KIR00322 KIR2DS3*00106 887 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACA* 
>DL;IPD:KIR00131
KIR:KIR00131 KIR2DS3*0020101 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00429
KIR:KIR00429 KIR2DS3*0020102 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00652
KIR:KIR00652 KIR2DS3*0020103 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00232
KIR:KIR00232 KIR2DS3*003N 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGAAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00273
KIR:KIR00273 KIR2DS3*004 887 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACA* 
>DL;IPD:KIR00529
KIR:KIR00529 KIR2DS3*005 887 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACA* 
>DL;IPD:KIR00663
KIR:KIR00663 KIR2DS3*006 846 bases
 GGATTCCGCA GAAAACCTTC CCTCCTGGCC CACCCAGGTC GCCTGGTGAA ATCAGAAGAG
 AGAGTCATCC TGCAATGTTG GTCAGATGTC ATGTTTGAGC ACTTCCTTCT GCACAGAGAG
 GGGACGTTTA ACGACACTTT GCGCCTCATT GGAGAGCACA TTGATGGGGT CTCCAAGGCC
 AACTTCTCCA TCGGTCGCAT GAGGCAAGAC CTGGCAGGGA CCTACAGATG CTACGGTTCT
 GTTCCTCACT CCCCCTATCA GTTTTCAGCT CCCAGTGACC CTCTGGACAT CGTGATCACA
 GGTCTATATG AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG
 AGCGTGACCT TGTCCTGCAG CTCCTGGAGC TCCTATGACA TGTACCATCT ATCCACGGAG
 GGGGAGGCCC ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCC
 GACTTTCCTC TGGGCCCTGC CACCCAAGGA GGAACCTACA GATGCTTCGG CTCTTTCCAT
 GACTCTCCCT ACGAGTGGTC AAAGTCAAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC
 CCTTCAAATA GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAA CCCCAGACAC
 CTACACGTTC TGATTGGGAC CTCAGTGGTC AAACTCCCTT TCACCATCCT CCTCTTCTTT
 CTCCTTCATC GCTGGTGCTC CGACAAAAAA AATGCATCTG TAATGGACCA AGGGCCTGCG
 GGGAACAGAA CAGTGAACAG GGAGGATTCT GATGAACAGG ACCATCAGGA GGTGTCATAC
 GCATAA*     
>DL;IPD:KIR00699
KIR:KIR00699 KIR2DS3*007 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGCGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
