>DL;IPD:KIR00049
KIR:KIR00049 KIR2DS5*001 915 bases
 ATGTTGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCCCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTCTCCTCT GGACCCTGCC ACCCACGGAG GGGCCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00050
KIR:KIR00050 KIR2DS5*0020101 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00299
KIR:KIR00299 KIR2DS5*0020102 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00297
KIR:KIR00297 KIR2DS5*0020103 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00433
KIR:KIR00433 KIR2DS5*0020104 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00532
KIR:KIR00532 KIR2DS5*00202 853 bases
 CGTTCTTCTT GCTGCAGGGG GCCTGGCCAC ATGAGGGATT CCGCAGAAAA CCTTCCCTCC
 TGGCCCACCC AGGTCCCCTG GTGAAATCAG AAGAGACAGT CATCCTGCAA TGTTGGTCAG
 ATGTCATGTT TGAGCACTTC CTTCTGCACA GAGAGGGGAC GTTTAACCAC ACTTTGCGCC
 TCATTGGAGA GCACATTGAT GGGGTCTCCA AGGGCAACTT CTCCATCGGT CGCATGACAC
 AAGACCTGGC AGGGACCTAC AGATGCTACG GTTCTGTTAC TCACTCCCCC TATCAGTTGT
 CAGCGCCCAG TGACCCTCTG GACATCGTGA TCACAGGTCT ATATGAGAAA CCTTCTCTCT
 CAGCCCAGCC GGGCCCCACG GTTCTGGCAG GAGAGAGCGT GACCTTGTCC TGCAGCTCCC
 GGAGCTCCTA TGACATGTAC CATCTATCCA GGGAAGGGGA GGCCCATGAA CGTAGGCTCC
 CTGCAGGGCC CAAGGTCAAC CGAACATTCC AGGCCGACTT TCCTCTGGAC CCTGCCACCC
 ACGGAGGGAC CTACAGATGC TTCGGCTCTT TCCGTGACTC TCCATACGAG TGGTCAAAGT
 CAAGTGACCC ACTGCTTGTT TCTGTCACAG GAAACTCTTC AAATAGTTGG CCTTCACCCA
 CTGAACCAAG CTCCGAAACC GGTAACCCCA GACACCTACA CGTTCTGATT GGGACCTCAG
 TGGTCAAACT CCCTTTCACC ATCCTCCTCT TCTTTCTCCT TCATCGCTGG TGCTCCAACA
 AAAAAAATGC ATCTGTAATG GACCAAGGGC CTGCGGGGAA CAGAACAGTG AACAGGGAGG
 ATTCTGATGA ACA*    
>DL;IPD:KIR00051
KIR:KIR00051 KIR2DS5*003 899 bases
 TCAGCATGGC GTGTGTTGCG TTCTTCTTGC TGCAGGGGGC CTGGCCACAT GAGGGATTCC
 GCAGAAAACC TTCCCTCCTG GCCCACCCAG GTCCCCTGGT GAAATCAGAA GAGACAGTCA
 TCCTGCAATG TTGGTCAGAT GTCATGTTTG AGCACTTCCT TCTGCACAGA GAGGGGACGT
 TTAACCACAC TTTGCGCCTC ATTGGAGAGC ACATTGATGG GGTCTCCAAG GGCAACTTCT
 CCATCGGTCG CATGACACAA GACCTGGCAG GGACCTACAG ATGCTACGGT TCTGTTACTC
 ACTCCCCCTA TCAGTTGTCA GCTCCCAGTG ACCCTCTGGA CATCGTGATC ACAGGTCTAT
 ATGAGAAACC TTCTCTCTCA GCCCAGCCGG GCCCCACGGT TCTGGCAGGA GAGAATGTGA
 CCTTGTCCTG CAGCTCCCGG AGCTCCTATG ACATGTACCA TCTATCCAGG GAAGGGGAGG
 CCCATGAACG TAGGCTCCCT GCAGGGCCCA AGGTCAACGG AACATTCCAG GCCGACTTTC
 CTCTGGACCC TGCCACCCAC GGAGGGACCT ACAGATGCTT CGGCTCTTTC CGTGACTCTC
 CATACGAGTG GTCAAAGTCA AGTGACCCAC TGCTTGTTTC TGTCACAGGA AACTCTTCAA
 ATAGTTGGCC TTCACCCACT GAACCAAGCT CCGAAACCGG TAACCCCAGA CACCTACACG
 TTCTGATTGG GACCTCAGTG GTCAAACTCC CTTTCACCAT CCTCCTCTTC TTTCTCCTTC
 ATCGCTGGTG CTCCAACAAA AAAAATGCAT CTGTAATGGA CCAAGGGCCT GCGGGGAACA
 GAACAGTGAA CAGGGAGGAT TCTGATGAAC AGGACCATCA GGAGGTGTCA TACGCATAA*
>DL;IPD:KIR00100
KIR:KIR00100 KIR2DS5*004 915 bases
 ATGTCACTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00101
KIR:KIR00101 KIR2DS5*00501 915 bases
 ATGTCACTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00706
KIR:KIR00706 KIR2DS5*00502 915 bases
 ATGTCACTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCAC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00276
KIR:KIR00276 KIR2DS5*006 915 bases
 ATGTCGCTCA TGGTCATCAG CAAGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00277
KIR:KIR00277 KIR2DS5*007 915 bases
 ATGTCACTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00278
KIR:KIR00278 KIR2DS5*00801 853 bases
 CGTTCTTCTT GCTGCAGGGG GCCTGGCCAC GTGAGGGATT CCGCAGAAAA CCTTCCCTCC
 TGGCCCACCC AGGTCCCCTG GTGAAATCAG AAGAGACAGT CATCCTGCAA TGTTGGTCAG
 ATGTCATGTT TGAGCACTTC CTTCTGCACA GAGAGGGGAC GTTTAACCAC ACTTTGCGCC
 TCATTGGAGA GCACATTGAT GGGGTCTCCA AGGGCAACTT CTCCATCGGT CGCATGACAC
 AAGACCTGGC AGGGACCTAC AGATGCTACG GTTCTGTTAC TCACTCCCCC TATCAGTTGT
 CAGCGCCCAG TGACCCTCTG GACATCGTGA TCACAGGTCT ATATGAGAAA CCTTCTCTCT
 CAGCCCAGCC GGGCCCCACG GTTCTGGCAG GAGAGAGCGT GACCTTGTCC TGCAGCTCCC
 GGAGCTCCTA TGACATGTAC CATCTATCCA GGGAAGGGGA GGCCCATGAA CGTAGGCTCC
 CTGCAGGGCC CAAGGTCAAC GGAACATTCC AGGCCGACTT TCCTCTGGAC CCTGCCACCC
 ACGGAGGGAC CTACAGATGC TTCGGCTCTT TCCGTGACTC TCCATACGAG TGGTCAAAGT
 CAAGTGACCC ACTGCTTGTT TCTGTCACAG GAAACTCTTC AAATAGTTGG CCTTCACCCA
 CTGAACCAAG CTCCGAAACC GGTAACCCCA GACACCTACA TGTTCTGATT GGGACCTCAG
 TGGTCAAACT CCCTTTCACC ATCCTCCTCT TCTTTCTCCT TCATCGCTGG TGCTCCAACA
 AAAAAAATGC ATCTGTAATG GACCAAGGGC CTGCGGGGAA CAGAACAGTG AACAGGGAGG
 ATTCTGATGA ACA*    
>DL;IPD:KIR00339
KIR:KIR00339 KIR2DS5*00802 853 bases
 CGTTCTTCTT GCTGCAGGGG GCCTGGCCAC GTGAGGGATT CCGCAGAAAA CCTTCCCTCC
 TGGCCCACCC AGGTCCCCTG GTGAAATCAG AAGAGACAGT CATCCTGCAA TGTTGGTCAG
 ATGTCATGTT TGAGCACTTC CTTCTGCACA GAGAGGGGAC GTTTAACCAC ACTTTGCGCC
 TCATTGGAGA GCACATTGAT GGGGTCTCCA AGGGCAACTT CTCCATCGGT CGCATGACAC
 AAGACCTGGC AGGGACCTAC AGATGCTACG GTTCTGTTAC TCACTCCCCC TATCAGTTGT
 CAGCGCCCAG TGACCCTCTG GACATCGTGA TCACAGGTCT ATATGAGAAA CCTTCTCTCT
 CAGCCCAGCC GGGCCCCACG GTTCTGGCAG GAGAGAGCGT GACCTTGTCC TGCAGCTCCC
 GGAGCTCCTA TGACATGTAC CATCTATCCA GGGAAGGGGA GGCCCATGAA CGTAGGCTCC
 CTGCAGGGCC CAAGGTCAAC GGAACATTCC AGGCCGACTT TCCTCTGGAC CCTGCCACCC
 ACGGAGGGAC CTACAGATGC TTCGGCTCTT TCCGTGACTC TCCATACGAG TGGTCAAAGT
 CAAGTGACCC ACTGCTTGTT TCTGTCACAG GAAACTCTTC AAATAGTTGG CCTTCACCCA
 CTGAACCAAG CTCCGAAACC GGTAACCCCA GACACCTACA CGTTCTGATT GGGACCTCAG
 TGGTCAAACT CCCTTTCACC ATCCTCCTCT TCTTTCTCCT TCATCGCTGG TGCTCCAACA
 AAAAAAATGC ATCTGTAATG GACCAAGGGC CTGCGGGGAA CAGAACAGTG AACAGGGAGG
 ATTCTGATGA ACA*    
>DL;IPD:KIR00319
KIR:KIR00319 KIR2DS5*009 881 bases
 CGTTCTTCTT GCTGCAGGGG GCCTGGCCAC ATGAGGGATT CCGCAGAAAA CCTTCCCTCC
 TGGCCCACCC AGGTCCCCTG GTGAAATCAG AAGAGACAGT CATCCTGCAA TGTTGGTCAG
 ATGTCATGTT TGAGCACTTC CTTCTGCACA GAGAGGGGAC GTTTAACCAC ACTTTGCGCC
 TCATTGGAGA GCACATTGAT GGGGTCTCCA AGGGCAACTT CTCCATCGGT CGCATGACAC
 AAGACCTGGC AGGGACCTAC AGATGCTACG GTTCTGTTAC TCACTCCCCC TATCAGTTGT
 CAGCGCCCAG TGACCCTCTG GACATCGTGA TCACAGGTCT ATATGAGAAA CCTTCTCTCT
 CAGCCCAGCC GGGCCCCACG GTTCTGGCAG GAGAGAGCGT GACCTTGTCC TGCAGCTCCC
 GGAGCTCCTA TGACATGTAC CATCTATCCA GGGAAGGGGA GGCCCATGAA CGTAGGCTCC
 CTGCAGGGCC CAAGGTCAAC AGAACATTCC AGGCCGACTT TCCTCTGGAC CCTGCCACCC
 ACGGAGGGAC CTACACATGC TTCGGCTCTT TCCGTGACTC TCCATACGAG TGGTCAAAGT
 CAAGTGACCC ACTGCTTGTT TCTGTCACAG GAAACTCTTC AAATAGTTGG CCTTCACCCA
 CTGAACCAAG CTCCGAAACC GGTAACCCCA GACACCTACA CGTTCTGATT GGGACCTCAG
 TGGTCAAACT CCCTTTCACC ATCCTCCTCT TCTTTCTCCT TCATCGCTGG TGCTCCAACA
 AAAAAAATGC ATCTGTAATG GACCAAGGGC CTGCGGGGAA CAGAACAGTG AACAGGGAGG
 ATTCTGATGA ACAGGACCAT CAGGAGGTGT CATACGCATA A* 
>DL;IPD:KIR00432
KIR:KIR00432 KIR2DS5*010 915 bases
 ATGTCACTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTTCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00665
KIR:KIR00665 KIR2DS5*011 915 bases
 ATGTCACTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAC ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00680
KIR:KIR00680 KIR2DS5*01201 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGTCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00970
KIR:KIR00970 KIR2DS5*01202 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00822
KIR:KIR00822 KIR2DS5*013 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00824
KIR:KIR00824 KIR2DS5*014 915 bases
 ATGTCACTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCACATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00878
KIR:KIR00878 KIR2DS5*015 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00893
KIR:KIR00893 KIR2DS5*016 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00948
KIR:KIR00948 KIR2DS5*017 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACA CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGTCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
