>DL;KIR:KIR00049
KIR:KIR00049 KIR2DS5*001 915 bases
 ATGTTGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCCCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTCTCCTCT GGACCCTGCC ACCCACGGAG GGGCCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00050
KIR:KIR00050 KIR2DS5*0020101 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00299
KIR:KIR00299 KIR2DS5*0020102 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00297
KIR:KIR00297 KIR2DS5*0020103 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00433
KIR:KIR00433 KIR2DS5*0020104 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01467
KIR:KIR01467 KIR2DS5*0020105 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01468
KIR:KIR01468 KIR2DS5*0020106 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01470
KIR:KIR01470 KIR2DS5*0020107 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01472
KIR:KIR01472 KIR2DS5*0020108 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01473
KIR:KIR01473 KIR2DS5*0020109 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01475
KIR:KIR01475 KIR2DS5*0020110 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01476
KIR:KIR01476 KIR2DS5*0020111 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01479
KIR:KIR01479 KIR2DS5*0020112 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01482
KIR:KIR01482 KIR2DS5*0020113 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01484
KIR:KIR01484 KIR2DS5*0020114 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01488
KIR:KIR01488 KIR2DS5*0020115 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01490
KIR:KIR01490 KIR2DS5*0020116 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01491
KIR:KIR01491 KIR2DS5*0020117 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01493
KIR:KIR01493 KIR2DS5*0020118 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01498
KIR:KIR01498 KIR2DS5*0020119 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01500
KIR:KIR01500 KIR2DS5*0020120 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01502
KIR:KIR01502 KIR2DS5*0020121 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01505
KIR:KIR01505 KIR2DS5*0020122 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01507
KIR:KIR01507 KIR2DS5*0020123 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01508
KIR:KIR01508 KIR2DS5*0020124 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01509
KIR:KIR01509 KIR2DS5*0020125 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01511
KIR:KIR01511 KIR2DS5*0020126 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01512
KIR:KIR01512 KIR2DS5*0020127 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01514
KIR:KIR01514 KIR2DS5*0020128 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01515
KIR:KIR01515 KIR2DS5*0020129 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01523
KIR:KIR01523 KIR2DS5*0020130 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01524
KIR:KIR01524 KIR2DS5*0020131 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01525
KIR:KIR01525 KIR2DS5*0020132 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01529
KIR:KIR01529 KIR2DS5*0020133 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00532
KIR:KIR00532 KIR2DS5*00202 853 bases
 CGTTCTTCTT GCTGCAGGGG GCCTGGCCAC ATGAGGGATT CCGCAGAAAA CCTTCCCTCC
 TGGCCCACCC AGGTCCCCTG GTGAAATCAG AAGAGACAGT CATCCTGCAA TGTTGGTCAG
 ATGTCATGTT TGAGCACTTC CTTCTGCACA GAGAGGGGAC GTTTAACCAC ACTTTGCGCC
 TCATTGGAGA GCACATTGAT GGGGTCTCCA AGGGCAACTT CTCCATCGGT CGCATGACAC
 AAGACCTGGC AGGGACCTAC AGATGCTACG GTTCTGTTAC TCACTCCCCC TATCAGTTGT
 CAGCGCCCAG TGACCCTCTG GACATCGTGA TCACAGGTCT ATATGAGAAA CCTTCTCTCT
 CAGCCCAGCC GGGCCCCACG GTTCTGGCAG GAGAGAGCGT GACCTTGTCC TGCAGCTCCC
 GGAGCTCCTA TGACATGTAC CATCTATCCA GGGAAGGGGA GGCCCATGAA CGTAGGCTCC
 CTGCAGGGCC CAAGGTCAAC CGAACATTCC AGGCCGACTT TCCTCTGGAC CCTGCCACCC
 ACGGAGGGAC CTACAGATGC TTCGGCTCTT TCCGTGACTC TCCATACGAG TGGTCAAAGT
 CAAGTGACCC ACTGCTTGTT TCTGTCACAG GAAACTCTTC AAATAGTTGG CCTTCACCCA
 CTGAACCAAG CTCCGAAACC GGTAACCCCA GACACCTACA CGTTCTGATT GGGACCTCAG
 TGGTCAAACT CCCTTTCACC ATCCTCCTCT TCTTTCTCCT TCATCGCTGG TGCTCCAACA
 AAAAAAATGC ATCTGTAATG GACCAAGGGC CTGCGGGGAA CAGAACAGTG AACAGGGAGG
 ATTCTGATGA ACA*    
>DL;KIR:KIR01477
KIR:KIR01477 KIR2DS5*00203 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01481
KIR:KIR01481 KIR2DS5*00204 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGT TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01495
KIR:KIR01495 KIR2DS5*0020501 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA TGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01520
KIR:KIR01520 KIR2DS5*0020502 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA TGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01492
KIR:KIR01492 KIR2DS5*0020503 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA TGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01499
KIR:KIR01499 KIR2DS5*00206 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01504
KIR:KIR01504 KIR2DS5*0020701 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ATTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01517
KIR:KIR01517 KIR2DS5*0020702 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ATTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00051
KIR:KIR00051 KIR2DS5*003 899 bases
 TCAGCATGGC GTGTGTTGCG TTCTTCTTGC TGCAGGGGGC CTGGCCACAT GAGGGATTCC
 GCAGAAAACC TTCCCTCCTG GCCCACCCAG GTCCCCTGGT GAAATCAGAA GAGACAGTCA
 TCCTGCAATG TTGGTCAGAT GTCATGTTTG AGCACTTCCT TCTGCACAGA GAGGGGACGT
 TTAACCACAC TTTGCGCCTC ATTGGAGAGC ACATTGATGG GGTCTCCAAG GGCAACTTCT
 CCATCGGTCG CATGACACAA GACCTGGCAG GGACCTACAG ATGCTACGGT TCTGTTACTC
 ACTCCCCCTA TCAGTTGTCA GCTCCCAGTG ACCCTCTGGA CATCGTGATC ACAGGTCTAT
 ATGAGAAACC TTCTCTCTCA GCCCAGCCGG GCCCCACGGT TCTGGCAGGA GAGAATGTGA
 CCTTGTCCTG CAGCTCCCGG AGCTCCTATG ACATGTACCA TCTATCCAGG GAAGGGGAGG
 CCCATGAACG TAGGCTCCCT GCAGGGCCCA AGGTCAACGG AACATTCCAG GCCGACTTTC
 CTCTGGACCC TGCCACCCAC GGAGGGACCT ACAGATGCTT CGGCTCTTTC CGTGACTCTC
 CATACGAGTG GTCAAAGTCA AGTGACCCAC TGCTTGTTTC TGTCACAGGA AACTCTTCAA
 ATAGTTGGCC TTCACCCACT GAACCAAGCT CCGAAACCGG TAACCCCAGA CACCTACACG
 TTCTGATTGG GACCTCAGTG GTCAAACTCC CTTTCACCAT CCTCCTCTTC TTTCTCCTTC
 ATCGCTGGTG CTCCAACAAA AAAAATGCAT CTGTAATGGA CCAAGGGCCT GCGGGGAACA
 GAACAGTGAA CAGGGAGGAT TCTGATGAAC AGGACCATCA GGAGGTGTCA TACGCATAA*
>DL;KIR:KIR00100
KIR:KIR00100 KIR2DS5*004 915 bases
 ATGTCACTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00101
KIR:KIR00101 KIR2DS5*00501 915 bases
 ATGTCACTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00706
KIR:KIR00706 KIR2DS5*00502 915 bases
 ATGTCACTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCAC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00276
KIR:KIR00276 KIR2DS5*0060101 915 bases
 ATGTCGCTCA TGGTCATCAG CAAGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01503
KIR:KIR01503 KIR2DS5*0060102 915 bases
 ATGTCGCTCA TGGTCATCAG CAAGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00277
KIR:KIR00277 KIR2DS5*0070101 915 bases
 ATGTCACTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01478
KIR:KIR01478 KIR2DS5*0070102 915 bases
 ATGTCACTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00278
KIR:KIR00278 KIR2DS5*00801 853 bases
 CGTTCTTCTT GCTGCAGGGG GCCTGGCCAC GTGAGGGATT CCGCAGAAAA CCTTCCCTCC
 TGGCCCACCC AGGTCCCCTG GTGAAATCAG AAGAGACAGT CATCCTGCAA TGTTGGTCAG
 ATGTCATGTT TGAGCACTTC CTTCTGCACA GAGAGGGGAC GTTTAACCAC ACTTTGCGCC
 TCATTGGAGA GCACATTGAT GGGGTCTCCA AGGGCAACTT CTCCATCGGT CGCATGACAC
 AAGACCTGGC AGGGACCTAC AGATGCTACG GTTCTGTTAC TCACTCCCCC TATCAGTTGT
 CAGCGCCCAG TGACCCTCTG GACATCGTGA TCACAGGTCT ATATGAGAAA CCTTCTCTCT
 CAGCCCAGCC GGGCCCCACG GTTCTGGCAG GAGAGAGCGT GACCTTGTCC TGCAGCTCCC
 GGAGCTCCTA TGACATGTAC CATCTATCCA GGGAAGGGGA GGCCCATGAA CGTAGGCTCC
 CTGCAGGGCC CAAGGTCAAC GGAACATTCC AGGCCGACTT TCCTCTGGAC CCTGCCACCC
 ACGGAGGGAC CTACAGATGC TTCGGCTCTT TCCGTGACTC TCCATACGAG TGGTCAAAGT
 CAAGTGACCC ACTGCTTGTT TCTGTCACAG GAAACTCTTC AAATAGTTGG CCTTCACCCA
 CTGAACCAAG CTCCGAAACC GGTAACCCCA GACACCTACA TGTTCTGATT GGGACCTCAG
 TGGTCAAACT CCCTTTCACC ATCCTCCTCT TCTTTCTCCT TCATCGCTGG TGCTCCAACA
 AAAAAAATGC ATCTGTAATG GACCAAGGGC CTGCGGGGAA CAGAACAGTG AACAGGGAGG
 ATTCTGATGA ACA*    
>DL;KIR:KIR00339
KIR:KIR00339 KIR2DS5*00802 853 bases
 CGTTCTTCTT GCTGCAGGGG GCCTGGCCAC GTGAGGGATT CCGCAGAAAA CCTTCCCTCC
 TGGCCCACCC AGGTCCCCTG GTGAAATCAG AAGAGACAGT CATCCTGCAA TGTTGGTCAG
 ATGTCATGTT TGAGCACTTC CTTCTGCACA GAGAGGGGAC GTTTAACCAC ACTTTGCGCC
 TCATTGGAGA GCACATTGAT GGGGTCTCCA AGGGCAACTT CTCCATCGGT CGCATGACAC
 AAGACCTGGC AGGGACCTAC AGATGCTACG GTTCTGTTAC TCACTCCCCC TATCAGTTGT
 CAGCGCCCAG TGACCCTCTG GACATCGTGA TCACAGGTCT ATATGAGAAA CCTTCTCTCT
 CAGCCCAGCC GGGCCCCACG GTTCTGGCAG GAGAGAGCGT GACCTTGTCC TGCAGCTCCC
 GGAGCTCCTA TGACATGTAC CATCTATCCA GGGAAGGGGA GGCCCATGAA CGTAGGCTCC
 CTGCAGGGCC CAAGGTCAAC GGAACATTCC AGGCCGACTT TCCTCTGGAC CCTGCCACCC
 ACGGAGGGAC CTACAGATGC TTCGGCTCTT TCCGTGACTC TCCATACGAG TGGTCAAAGT
 CAAGTGACCC ACTGCTTGTT TCTGTCACAG GAAACTCTTC AAATAGTTGG CCTTCACCCA
 CTGAACCAAG CTCCGAAACC GGTAACCCCA GACACCTACA CGTTCTGATT GGGACCTCAG
 TGGTCAAACT CCCTTTCACC ATCCTCCTCT TCTTTCTCCT TCATCGCTGG TGCTCCAACA
 AAAAAAATGC ATCTGTAATG GACCAAGGGC CTGCGGGGAA CAGAACAGTG AACAGGGAGG
 ATTCTGATGA ACA*    
>DL;KIR:KIR00319
KIR:KIR00319 KIR2DS5*009 881 bases
 CGTTCTTCTT GCTGCAGGGG GCCTGGCCAC ATGAGGGATT CCGCAGAAAA CCTTCCCTCC
 TGGCCCACCC AGGTCCCCTG GTGAAATCAG AAGAGACAGT CATCCTGCAA TGTTGGTCAG
 ATGTCATGTT TGAGCACTTC CTTCTGCACA GAGAGGGGAC GTTTAACCAC ACTTTGCGCC
 TCATTGGAGA GCACATTGAT GGGGTCTCCA AGGGCAACTT CTCCATCGGT CGCATGACAC
 AAGACCTGGC AGGGACCTAC AGATGCTACG GTTCTGTTAC TCACTCCCCC TATCAGTTGT
 CAGCGCCCAG TGACCCTCTG GACATCGTGA TCACAGGTCT ATATGAGAAA CCTTCTCTCT
 CAGCCCAGCC GGGCCCCACG GTTCTGGCAG GAGAGAGCGT GACCTTGTCC TGCAGCTCCC
 GGAGCTCCTA TGACATGTAC CATCTATCCA GGGAAGGGGA GGCCCATGAA CGTAGGCTCC
 CTGCAGGGCC CAAGGTCAAC AGAACATTCC AGGCCGACTT TCCTCTGGAC CCTGCCACCC
 ACGGAGGGAC CTACACATGC TTCGGCTCTT TCCGTGACTC TCCATACGAG TGGTCAAAGT
 CAAGTGACCC ACTGCTTGTT TCTGTCACAG GAAACTCTTC AAATAGTTGG CCTTCACCCA
 CTGAACCAAG CTCCGAAACC GGTAACCCCA GACACCTACA CGTTCTGATT GGGACCTCAG
 TGGTCAAACT CCCTTTCACC ATCCTCCTCT TCTTTCTCCT TCATCGCTGG TGCTCCAACA
 AAAAAAATGC ATCTGTAATG GACCAAGGGC CTGCGGGGAA CAGAACAGTG AACAGGGAGG
 ATTCTGATGA ACAGGACCAT CAGGAGGTGT CATACGCATA A* 
>DL;KIR:KIR00432
KIR:KIR00432 KIR2DS5*010 915 bases
 ATGTCACTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTTCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00665
KIR:KIR00665 KIR2DS5*011 915 bases
 ATGTCACTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAC ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00680
KIR:KIR00680 KIR2DS5*01201 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGTCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00970
KIR:KIR00970 KIR2DS5*01202 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00822
KIR:KIR00822 KIR2DS5*013 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00824
KIR:KIR00824 KIR2DS5*014 915 bases
 ATGTCACTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCACATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00878
KIR:KIR00878 KIR2DS5*015 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00893
KIR:KIR00893 KIR2DS5*016 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00948
KIR:KIR00948 KIR2DS5*017 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACA CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGTCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01469
KIR:KIR01469 KIR2DS5*018 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCA ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01471
KIR:KIR01471 KIR2DS5*019 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCACGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01474
KIR:KIR01474 KIR2DS5*020 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGTCAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01480
KIR:KIR01480 KIR2DS5*0210101 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01494
KIR:KIR01494 KIR2DS5*0210102 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01483
KIR:KIR01483 KIR2DS5*022 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CAAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01486
KIR:KIR01486 KIR2DS5*0230101 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GAAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01519
KIR:KIR01519 KIR2DS5*0230102 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GAAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01487
KIR:KIR01487 KIR2DS5*024 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC ATCAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01526
KIR:KIR01526 KIR2DS5*0250101 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT ATACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01489
KIR:KIR01489 KIR2DS5*0250102 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT ATACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01497
KIR:KIR01497 KIR2DS5*026 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01496
KIR:KIR01496 KIR2DS5*0270101 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACTCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01528
KIR:KIR01528 KIR2DS5*0270102 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACTCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01501
KIR:KIR01501 KIR2DS5*028 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACATAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01506
KIR:KIR01506 KIR2DS5*029 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ACGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01510
KIR:KIR01510 KIR2DS5*030 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAA CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01513
KIR:KIR01513 KIR2DS5*031 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCTGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01516
KIR:KIR01516 KIR2DS5*032 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01518
KIR:KIR01518 KIR2DS5*033 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGAACC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01521
KIR:KIR01521 KIR2DS5*034 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCGTCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01522
KIR:KIR01522 KIR2DS5*035 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AATGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01527
KIR:KIR01527 KIR2DS5*036 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AAGAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01530
KIR:KIR01530 KIR2DS5*037 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01584
KIR:KIR01584 KIR2DS5*038 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGCGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGGCA ACTTCTCCAT CGGTCGCATG ACACAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGCCCAAGGT CAACAGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACT CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCT CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
