>P1;KIR:KIR00033
KIR:KIR00033 KIR2DS1*001 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM RQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00034
KIR:KIR00034 KIR2DS1*0020101 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00298
KIR:KIR00298 KIR2DS1*0020102 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00296
KIR:KIR00296 KIR2DS1*0020103 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00426
KIR:KIR00426 KIR2DS1*0020104 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00427
KIR:KIR00427 KIR2DS1*0020105 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00428
KIR:KIR00428 KIR2DS1*0020106 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01251
KIR:KIR01251 KIR2DS1*0020107 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01252
KIR:KIR01252 KIR2DS1*0020108 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01253
KIR:KIR01253 KIR2DS1*0020109 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01254
KIR:KIR01254 KIR2DS1*0020110 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01255
KIR:KIR01255 KIR2DS1*0020111 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01256
KIR:KIR01256 KIR2DS1*0020112 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01257
KIR:KIR01257 KIR2DS1*0020113 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01258
KIR:KIR01258 KIR2DS1*0020114 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01259
KIR:KIR01259 KIR2DS1*0020115 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01260
KIR:KIR01260 KIR2DS1*0020116 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01261
KIR:KIR01261 KIR2DS1*0020117 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01262
KIR:KIR01262 KIR2DS1*0020118 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00255
KIR:KIR00255 KIR2DS1*00202 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00035
KIR:KIR00035 KIR2DS1*00301 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00254
KIR:KIR00254 KIR2DS1*00302 303 bases
 SLMVVSMACV GFFLLQGAWP HEGVHRKPSL LAHPGRLVKS EETVILQCWS DVMFEHFLLH
 REGMFNDTLR LIGEHHDGVS KANFSISRMK QDLAGTYRCY GSVTHSPYQL SAPSDPLDIV
 IIGLYEKPSL SAQPGPTVLA GENVTLSCSS RSSYDMYHLS REGEAHERRL PAGTKVNGTF
 QANFPLGPAT HGGTYRCFGS FRDSPYEWSK SSDPLLVSVT GNPSNSWPSP TEPSSETGNP
 RHLHVLIGTS VVKIPFTILL FFLLHRWCSD KKNAAVMDQE PAGNRTVNSE DSDEQDHQEV
 SYA*     
>P1;KIR:KIR00036
KIR:KIR00036 KIR2DS1*004 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00252
KIR:KIR00252 KIR2DS1*00501 304 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00256
KIR:KIR00256 KIR2DS1*00502 304 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00253
KIR:KIR00253 KIR2DS1*006 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00271
KIR:KIR00271 KIR2DS1*008 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00797
KIR:KIR00797 KIR2DS1*009 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01572
KIR:KIR01572 KIR2DS1*010 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRV KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01573
KIR:KIR01573 KIR2DS1*011 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01574
KIR:KIR01574 KIR2DS1*0120101 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01575
KIR:KIR01575 KIR2DS1*0120102 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01576
KIR:KIR01576 KIR2DS1*013 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
