>P1;KIR:KIR00020
KIR:KIR00020 KIR2DL4*00101 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00021
KIR:KIR00021 KIR2DL4*0010201 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00424
KIR:KIR00424 KIR2DL4*0010202 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR01133
KIR:KIR01133 KIR2DL4*0010203 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00112
KIR:KIR00112 KIR2DL4*0010301 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00115
KIR:KIR00115 KIR2DL4*0010302 367 bases
 ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF TLYKKDGVPV
 PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT GLYEKPSLTA
 RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA DFPLGPATHG
 ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH LHAVIRYSVA
 IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY AQLDHCIFTQ
 RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT ALSQTQLASS
 NVPAAGI*     
>P1;KIR:KIR00420
KIR:KIR00420 KIR2DL4*0010303 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00421
KIR:KIR00421 KIR2DL4*0010304 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00422
KIR:KIR00422 KIR2DL4*0010305 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00423
KIR:KIR00423 KIR2DL4*0010306 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00425
KIR:KIR00425 KIR2DL4*0010307 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00620
KIR:KIR00620 KIR2DL4*0010308 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR01134
KIR:KIR01134 KIR2DL4*0010309 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00119
KIR:KIR00119 KIR2DL4*00104 367 bases
 ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF TLYKKDGVPV
 PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT GLYEKPSLTA
 RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA DFPLGPATHG
 ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH LHAVIRYSVA
 IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY AQLDHCIFTQ
 RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT ALSQTQLASS
 NVPAAGI*     
>P1;KIR:KIR00129
KIR:KIR00129 KIR2DL4*00105 375 bases
 MSPTVIILAC LGFFLDQSVW AHVGGQDKPF CSAWPSAVVP QGGHVTLRCH YRRGFNIFTL
 YKKDGVPVPE LYNRIFWNSF LISPVTPAHA GTYRCRGFHP HSPTEWSAPS NPLVIMVTGL
 YEKPSLTARP GPTVRTGENV TLSCSSQSSF DIYHLSREGE AHELRLPAVP SINGTFQADF
 PLGPATHGET YRCFGSFHGS PYEWSDASDP LPVSVTGNPS SSWPSPTEPS FKTGIARHLH
 AVIRYSVAII LFTILPFFLL HRWCSKKKNA AVMNQEPAGH RTVNREDSDE QDPQEVTYAQ
 LDHCIFTQRK ITGPSQRSKR PSTDTSVCIE LPNAEPRALS PAHEHHSQAL MGSSRETTAL
 SQTQLASSNV PAAGI*    
>P1;KIR:KIR00969
KIR:KIR00969 KIR2DL4*00106 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR01135
KIR:KIR01135 KIR2DL4*00107 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00022
KIR:KIR00022 KIR2DL4*00201 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00023
KIR:KIR00023 KIR2DL4*00202 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00024
KIR:KIR00024 KIR2DL4*003 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPLTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK DAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS HVPAAGI*    
>P1;KIR:KIR00025
KIR:KIR00025 KIR2DL4*004 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPLTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS HVPAAGI*    
>P1;KIR:KIR00026
KIR:KIR00026 KIR2DL4*0050101 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR01136
KIR:KIR01136 KIR2DL4*0050102 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR01137
KIR:KIR01137 KIR2DL4*0050103 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR01138
KIR:KIR01138 KIR2DL4*0050104 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR01139
KIR:KIR01139 KIR2DL4*0050105 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR01140
KIR:KIR01140 KIR2DL4*0050106 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR01141
KIR:KIR01141 KIR2DL4*0050107 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00901
KIR:KIR00901 KIR2DL4*00503 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00902
KIR:KIR00902 KIR2DL4*00504 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00027
KIR:KIR00027 KIR2DL4*00601 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RLGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00130
KIR:KIR00130 KIR2DL4*0060201 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RLGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR01142
KIR:KIR01142 KIR2DL4*0060202 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RLGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00913
KIR:KIR00913 KIR2DL4*00603 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RLGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR01143
KIR:KIR01143 KIR2DL4*00604 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RLGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00028
KIR:KIR00028 KIR2DL4*007 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTNRCRGF RPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR00109
KIR:KIR00109 KIR2DL4*0080101 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR00110
KIR:KIR00110 KIR2DL4*0080102 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR00117
KIR:KIR00117 KIR2DL4*0080103 264 bases
 ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF TLYKKDGVPV
 PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT GLYEKPSLTA
 RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA DFPLGPATHG
 ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH LHAVIRYSVA
 IILFTILPFF LLHRWCSKKK MLLX*   
>P1;KIR:KIR00213
KIR:KIR00213 KIR2DL4*0080104 264 bases
 ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF TLYKKDGVPV
 PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT GLYEKPSLTA
 RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA DFPLGPATHG
 ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH LHAVIRYSVA
 IILFTILPFF LLHRWCSKKK MLLX*   
>P1;KIR:KIR00436
KIR:KIR00436 KIR2DL4*0080105 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR01144
KIR:KIR01144 KIR2DL4*0080106 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR01145
KIR:KIR01145 KIR2DL4*0080107 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR01146
KIR:KIR01146 KIR2DL4*0080108 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR00111
KIR:KIR00111 KIR2DL4*0080201 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR00116
KIR:KIR00116 KIR2DL4*0080202 264 bases
 ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF TLYKKDGVPV
 PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT GLYEKPSLTA
 RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA DFPLGPATHG
 ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH LHAVIRYSVA
 IILFTILPFF LLHRWCSKKK MLLX*   
>P1;KIR:KIR00437
KIR:KIR00437 KIR2DL4*0080203 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR00647
KIR:KIR00647 KIR2DL4*0080204 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR01147
KIR:KIR01147 KIR2DL4*0080205 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR01148
KIR:KIR01148 KIR2DL4*0080206 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR01149
KIR:KIR01149 KIR2DL4*0080207 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR01150
KIR:KIR01150 KIR2DL4*0080208 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR01151
KIR:KIR01151 KIR2DL4*00803 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR01152
KIR:KIR01152 KIR2DL4*0080401 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR01153
KIR:KIR01153 KIR2DL4*0080402 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR01154
KIR:KIR01154 KIR2DL4*00805 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR00118
KIR:KIR00118 KIR2DL4*00901 264 bases
 ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF TLYKKDGVPV
 PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT GLYEKPSLTA
 RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA DFPVGPATHG
 ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH LHAVIRYSVA
 IILFTILPFF LLHRWCSKKK MLLX*   
>P1;KIR:KIR00520
KIR:KIR00520 KIR2DL4*00902 264 bases
 ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF TLYKKDGVPV
 PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT GLYEKPSLTA
 RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA DFPVGPATHG
 ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH LHAVIRYSVA
 IILFTILPFF LLHRWCSKKK MLLX*   
>P1;KIR:KIR00114
KIR:KIR00114 KIR2DL4*010 367 bases
 ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF TLYKKDGVPV
 PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT GLYEKPSLTA
 RLGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLHA VPSINGTFQA DFPLGPATHG
 ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH LHAVIRYSVA
 IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY AQLDHCIFTQ
 RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT ALSQTQLASS
 NVPAAGI*     
>P1;KIR:KIR00113
KIR:KIR00113 KIR2DL4*0110101 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR01155
KIR:KIR01155 KIR2DL4*0110102 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR01156
KIR:KIR01156 KIR2DL4*0110103 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR01595
KIR:KIR01595 KIR2DL4*0110104 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR00991
KIR:KIR00991 KIR2DL4*01102 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR00212
KIR:KIR00212 KIR2DL4*01201 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPEEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00593
KIR:KIR00593 KIR2DL4*01202 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPEEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00512
KIR:KIR00512 KIR2DL4*013 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR00521
KIR:KIR00521 KIR2DL4*014 367 bases
 ACLGFFLDQS VWAHVGGQDK PFCSAWPSTV VPQGGHVTLR CHCRRGFNIF TLYKKDGVPV
 PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT GLYEKPSLTA
 RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA DFPLGPATHG
 ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH LHAVIRYSVA
 IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY AQLDHCIFTQ
 RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT ALSQTQLASS
 NVPAAGI*     
>P1;KIR:KIR00522
KIR:KIR00522 KIR2DL4*015 367 bases
 ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLW CHYRRGFNIF TLYKKDGVPV
 PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT GLYEKPSLTA
 RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA DFPLGPATHG
 ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH LHAVIRYSVA
 IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY AQLDHCIFTQ
 RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT ALSQTQLASS
 NVPAAGI*     
>P1;KIR:KIR00523
KIR:KIR00523 KIR2DL4*016 367 bases
 ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF TLYKKDGFPV
 PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT GLYEKPSLTA
 RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA DFPLGPATHG
 ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH LHAVIRYSVA
 IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY AQLDHCIFTQ
 RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT ALSQTQLASS
 NVPAAGI*     
>P1;KIR:KIR00591
KIR:KIR00591 KIR2DL4*017 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGRHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR00592
KIR:KIR00592 KIR2DL4*018 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRGGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFSSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00594
KIR:KIR00594 KIR2DL4*019 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRGGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFSSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR00595
KIR:KIR00595 KIR2DL4*020 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRV GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR00596
KIR:KIR00596 KIR2DL4*021 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 NFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00590
KIR:KIR00590 KIR2DL4*022 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRV LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00668
KIR:KIR00668 KIR2DL4*023 352 bases
 GGQDKPFCSA WPSAVVPQGG HVTLRCHYRR GFNIFTLYKK DGVPVPELYN RIFWNSFLIS
 PVTPAHAGTY RCRGFHPHSP TEWSAPSNPL VIMVTGLYEK PSLTARPGPT VRTGENVTLS
 CSSQSSFDIY HLSREGEAHE LRLPAVPSIN GTFQADFPLG PATHGETYRC FSSFHGSPYE
 WSDASDPLPV SVTGNPSSSW PSPTEPSFKT GIARHLHAVI RYSVAIILFT ILPFFLLHRW
 CSKKKNAAVM NQEPAGHRTV NREDSDEQDP QEVTYAQLDH CIFTQRKITG PSQRSKRPST
 DTSVCIELPN AEPRALSPAH EHHSQALMGS SRETTALSQT QLASSNVPAA GI*
>P1;KIR:KIR00670
KIR:KIR00670 KIR2DL4*024 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPEEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHTQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00672
KIR:KIR00672 KIR2DL4*025 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHTQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00674
KIR:KIR00674 KIR2DL4*026 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPEEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHTQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00675
KIR:KIR00675 KIR2DL4*027 275 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLSX*  
>P1;KIR:KIR00748
KIR:KIR00748 KIR2DL4*028 336 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RQGPMVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ KNHWPFSEEQ ETLNRYQRVY RTSKCX*  
>P1;KIR:KIR00826
KIR:KIR00826 KIR2DL4*029 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFSSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NTAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00830
KIR:KIR00830 KIR2DL4*030 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSVV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00828
KIR:KIR00828 KIR2DL4*031 302 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPEEVTY
 AX*     
>P1;KIR:KIR00904
KIR:KIR00904 KIR2DL4*032 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYDRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00905
KIR:KIR00905 KIR2DL4*033 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAESRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00903
KIR:KIR00903 KIR2DL4*034 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDVVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00909
KIR:KIR00909 KIR2DL4*035 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRSRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR00912
KIR:KIR00912 KIR2DL4*036 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYKWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00914
KIR:KIR00914 KIR2DL4*037 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHKHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00928
KIR:KIR00928 KIR2DL4*038 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCQGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00967
KIR:KIR00967 KIR2DL4*039 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RLGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00968
KIR:KIR00968 KIR2DL4*040 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSISGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00990
KIR:KIR00990 KIR2DL4*041 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLSPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR01157
KIR:KIR01157 KIR2DL4*042 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK KAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR01158
KIR:KIR01158 KIR2DL4*043 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYKKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR01159
KIR:KIR01159 KIR2DL4*044 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HTGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR01160
KIR:KIR01160 KIR2DL4*045 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSPRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR01161
KIR:KIR01161 KIR2DL4*046 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVALR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR01162
KIR:KIR01162 KIR2DL4*047 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDLS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR01163
KIR:KIR01163 KIR2DL4*048 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRCSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR01164
KIR:KIR01164 KIR2DL4*049 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYENPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR01165
KIR:KIR01165 KIR2DL4*050 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPDAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR01166
KIR:KIR01166 KIR2DL4*051 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFSSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR01167
KIR:KIR01167 KIR2DL4*052 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQG SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR01168
KIR:KIR01168 KIR2DL4*053 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYHRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR01169
KIR:KIR01169 KIR2DL4*054 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHLWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR01586
KIR:KIR01586 KIR2DL4*055 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTFRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR01582
KIR:KIR01582 KIR2DL4*056 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPMVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR01601
KIR:KIR01601 KIR2DL4*057 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCHRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR01602
KIR:KIR01602 KIR2DL4*058 367 bases
 ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRHGFNIF TLYKKDGVPV
 PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT GLYEKPSLTA
 RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA DFPLGPATHG
 ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH LHAVIRYSVA
 IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY AQLDHCIFTQ
 RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT ALSQTQLASS
 NVPAAGI*     
