>DL;KIR:KIR00033
KIR:KIR00033 KIR2DS1*001 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00036
KIR:KIR00036 KIR2DS1*004 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00253
KIR:KIR00253 KIR2DS1*006 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATATTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00271
KIR:KIR00271 KIR2DS1*008 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00797
KIR:KIR00797 KIR2DS1*009 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01572
KIR:KIR01572 KIR2DS1*010 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCGTG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01573
KIR:KIR01573 KIR2DS1*011 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01576
KIR:KIR01576 KIR2DS1*013 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG ACGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00255
KIR:KIR00255 KIR2DS1*00202 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00035
KIR:KIR00035 KIR2DS1*00301 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA CGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00254
KIR:KIR00254 KIR2DS1*00302 914 bases
 TGTCGCTCAT GGTCGTCAGC ATGGCGTGTG TTGGGTTCTT CTTGCTGCAG GGGGCCTGGC
 CACATGAGGG AGTCCACAGA AAACCTTCCC TCCTGGCCCA CCCAGGTCGC CTGGTGAAAT
 CAGAAGAGAC AGTCATCCTG CAATGTTGGT CAGATGTCAT GTTTGAACAC TTCCTTCTGC
 ACAGAGAGGG GATGTTTAAC GACACTTTGC GCCTCATTGG AGAACACCAT GATGGGGTCT
 CCAAGGCCAA CTTCTCCATC AGTCGCATGA AGCAAGACCT GGCAGGGACC TACAGATGCT
 ACGGTTCTGT TACTCACTCC CCCTATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TGATCATAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAA TGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAAGG GGAGGCCCAT GAACGTAGGC TCCCTGCAGG GACCAAGGTC AACGGAACAT
 TCCAGGCCAA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG GACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCATAC GAGTGGTCAA AGTCAAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCGAA ACCGGTAACC
 CCAGACACCT ACATGTTCTG ATTGGGACCT CAGTGGTCAA AATCCCTTTC ACCATCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCG ACAAAAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GTGAACAGCG AGGATTCTGA TGAACAAGAC CATCAGGAGG
 TGTCATACGC ATAA    
>DL;KIR:KIR00252
KIR:KIR00252 KIR2DS1*00501 915 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCA CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00256
KIR:KIR00256 KIR2DS1*00502 915 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00034
KIR:KIR00034 KIR2DS1*0020101 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00298
KIR:KIR00298 KIR2DS1*0020102 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00296
KIR:KIR00296 KIR2DS1*0020103 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00426
KIR:KIR00426 KIR2DS1*0020104 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00427
KIR:KIR00427 KIR2DS1*0020105 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00428
KIR:KIR00428 KIR2DS1*0020106 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01251
KIR:KIR01251 KIR2DS1*0020107 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01252
KIR:KIR01252 KIR2DS1*0020108 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01253
KIR:KIR01253 KIR2DS1*0020109 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01254
KIR:KIR01254 KIR2DS1*0020110 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01255
KIR:KIR01255 KIR2DS1*0020111 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01256
KIR:KIR01256 KIR2DS1*0020112 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01257
KIR:KIR01257 KIR2DS1*0020113 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01258
KIR:KIR01258 KIR2DS1*0020114 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01259
KIR:KIR01259 KIR2DS1*0020115 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01260
KIR:KIR01260 KIR2DS1*0020116 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01261
KIR:KIR01261 KIR2DS1*0020117 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01262
KIR:KIR01262 KIR2DS1*0020118 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01574
KIR:KIR01574 KIR2DS1*0120101 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01575
KIR:KIR01575 KIR2DS1*0120102 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
