>DL;IPD:KIR00010
KIR:KIR00010 KIR2DL2*0010101 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ATAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGGA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACGCGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00405
KIR:KIR00405 KIR2DL2*0010102 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ATAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGGA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACGCGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00407
KIR:KIR00407 KIR2DL2*0010103 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ATAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGGA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACGCGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00410
KIR:KIR00410 KIR2DL2*0010104 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ATAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGGA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACGCGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00618
KIR:KIR00618 KIR2DL2*0010105 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ATAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGGA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACGCGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00645
KIR:KIR00645 KIR2DL2*0010106 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ATAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGGA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACGCGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00630
KIR:KIR00630 KIR2DL2*0010107 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ATAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGGA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACGCGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00324
KIR:KIR00324 KIR2DL2*00102 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TATGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ATAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGGA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACGCGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00011
KIR:KIR00011 KIR2DL2*002 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ATAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGGA ACAGAACAGC GAACAGGCAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACGCGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00012
KIR:KIR00012 KIR2DL2*0030101 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGGA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00316
KIR:KIR00316 KIR2DL2*0030102 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGGA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00335
KIR:KIR00335 KIR2DL2*0030103 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGGA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00406
KIR:KIR00406 KIR2DL2*0030104 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGGA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00408
KIR:KIR00408 KIR2DL2*0030105 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGGA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00409
KIR:KIR00409 KIR2DL2*0030106 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGGA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00411
KIR:KIR00411 KIR2DL2*0030107 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGGA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00587
KIR:KIR00587 KIR2DL2*00302 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00653
KIR:KIR00653 KIR2DL2*00303 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGGA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00654
KIR:KIR00654 KIR2DL2*00304 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGGA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00013
KIR:KIR00013 KIR2DL2*004 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACACAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGACCCTGCC ACCCACGGAG GAACGTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCTGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATATCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCA CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAG TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00096
KIR:KIR00096 KIR2DL2*005 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ATAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGGA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00325
KIR:KIR00325 KIR2DL2*00601 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGGA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00326
KIR:KIR00326 KIR2DL2*00602 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGACGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGGA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00328
KIR:KIR00328 KIR2DL2*007 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ATAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGCCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGGA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACGCGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00584
KIR:KIR00584 KIR2DL2*008 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ATAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATTGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00585
KIR:KIR00585 KIR2DL2*009 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGGA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00586
KIR:KIR00586 KIR2DL2*010 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ATAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATTGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTTATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00661
KIR:KIR00661 KIR2DL2*011 978 bases
 GGAGTCCACA GAAAACCTTC CCTCCTGGCC CACCCAGGTC CCCTGGTGAA ATCAGAAGAG
 ACAGTCATCC TGCAATGTTG GTCAGATGTC AGGTTTGAGC ACTTCCTTCT GCACAGAGAA
 GGGAAGTTTA AGGACACTTT GCACCTCATT GGAGAGCACC ATGATGGGGT CTCCAAAGCC
 AACTTCTCCA TCGGTCCCAT GATGCAAGAC CTTGCAGGGA CCTACAGATG CTACGGTTCT
 GTTACTCACT CCCCCTATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA
 GGTCTATATG AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG
 AGCGTGACCT TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAG
 GGGGAGGCCC ATGAATGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCC
 GACTTTCCTC TGGACCCTGC CACCCACGGA GGAACGTACA GATGCTTCGG CTCTTTCCGT
 GACTCTCCAT ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC
 CCTTCAAATA GTTGGCCTTC ACCCACTGAA CCAAGCTCCG AAACCGGTAA CCCCCGACAC
 CTGCACATTC TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CTTCTTTCTC
 CTTCATCGCT GGTGCTCCAA CAAAAAAAAT GCTGCTGTAA TGGACCAAGA GTCTGCAGGA
 AACAGAACAG CGAATATCGA GGACTCTGAT GAACAAGACC CTCAGGAGGT GACATACACA
 CAGTTGAATC ACTGCGTTTT CACACAGAGA AAAATCACTC ACCCTTCTCA GAGGCCCAAG
 ACACCCCCAA CAGATATCAT CGTGTACACG GAACTTCCAA GTGCTGAGTC CAGATCCAAA
 GTTGTCTCCT GCCCATGA*    
>DL;IPD:KIR00678
KIR:KIR00678 KIR2DL2*012 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG AAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTCCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGGA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGTCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
>DL;IPD:KIR00765
KIR:KIR00765 KIR2DL2*013 1047 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCTAA AACCGGTAAC
 CCCCGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 TTCTTTCTCC TTCATCGCTG GTGCTGCAAC AAAAAAAATG CTGCGGTAAT GGACCAAGAG
 TCTGCAGGAA ACAGAACAGC GAATAGCGAG GACTCTGATG AACAAGACCC TCAGGAGGTG
 ACATACACAC AGTTGAATCA CTGCGTTTTC ACACAGAGAA AAATCACTCG CCCTTCTCAG
 AGGCCCAAGA CACCCCCAAC AGATATCATC GTGTACACGG AACTTCCAAA TGCTGAGCCC
 AGATCCAAAG TTGTCTCCTG CCCATGA*   
