>DL;KIR:KIR00030
KIR:KIR00030 KIR2DL5B*0020101 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00248
KIR:KIR00248 KIR2DL5B*0020102 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00301
KIR:KIR00301 KIR2DL5B*0020103 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00394
KIR:KIR00394 KIR2DL5B*0020104 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00524
KIR:KIR00524 KIR2DL5B*0020106 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00632
KIR:KIR00632 KIR2DL5B*0020107 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01095
KIR:KIR01095 KIR2DL5B*0020108 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01197
KIR:KIR01197 KIR2DL5B*0020109 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01198
KIR:KIR01198 KIR2DL5B*0020110 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01204
KIR:KIR01204 KIR2DL5B*0020111 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00535
KIR:KIR00535 KIR2DL5B*0020201 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCCAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00972
KIR:KIR00972 KIR2DL5B*0020202 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCCAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00802
KIR:KIR00802 KIR2DL5B*00203 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00994
KIR:KIR00994 KIR2DL5B*00204 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTTGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01193
KIR:KIR01193 KIR2DL5B*00205 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC GCAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00031
KIR:KIR00031 KIR2DL5B*003 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCATGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00032
KIR:KIR00032 KIR2DL5B*004 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCAC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCCAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00125
KIR:KIR00125 KIR2DL5B*00601 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00267
KIR:KIR00267 KIR2DL5B*00602 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCGAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00393
KIR:KIR00393 KIR2DL5B*00603 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCGAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCCAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00126
KIR:KIR00126 KIR2DL5B*0070101 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCATGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00525
KIR:KIR00525 KIR2DL5B*0070102 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCATGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00244
KIR:KIR00244 KIR2DL5B*0080101 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00395
KIR:KIR00395 KIR2DL5B*0080102 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00266
KIR:KIR00266 KIR2DL5B*00802 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TTGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00682
KIR:KIR00682 KIR2DL5B*00803 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCCAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00805
KIR:KIR00805 KIR2DL5B*00804 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00946
KIR:KIR00946 KIR2DL5B*00805 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCGAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCCAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00245
KIR:KIR00245 KIR2DL5B*009 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00264
KIR:KIR00264 KIR2DL5B*010 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00265
KIR:KIR00265 KIR2DL5B*011 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCATTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00390
KIR:KIR00390 KIR2DL5B*01301 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTTGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA TGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00392
KIR:KIR00392 KIR2DL5B*01302 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTTGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA TGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00534
KIR:KIR00534 KIR2DL5B*01303 1128 bases
 ATGTCGCTCA TGGTGGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTTGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA TGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00801
KIR:KIR00801 KIR2DL5B*01304 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTTGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00538
KIR:KIR00538 KIR2DL5B*016 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCATACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00664
KIR:KIR00664 KIR2DL5B*017 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAACAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00684
KIR:KIR00684 KIR2DL5B*018 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCAT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTTGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00803
KIR:KIR00803 KIR2DL5B*019 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTTGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA TGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAACAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR00804
KIR:KIR00804 KIR2DL5B*020 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GAGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01205
KIR:KIR01205 KIR2DL5B*035 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAT ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01206
KIR:KIR01206 KIR2DL5B*036 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG AGACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01208
KIR:KIR01208 KIR2DL5B*037 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 TGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01190
KIR:KIR01190 KIR2DL5B*038 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CAGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01207
KIR:KIR01207 KIR2DL5B*0390101 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 TGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01203
KIR:KIR01203 KIR2DL5B*0390102 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 TGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
>DL;KIR:KIR01596
KIR:KIR01596 KIR2DL5B*041 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATATCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA 
