>P1;KIR:KIR00037
KIR:KIR00037 KIR2DS2*0010101 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00302
KIR:KIR00302 KIR2DS2*0010102 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00270
KIR:KIR00270 KIR2DS2*0010103 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00336
KIR:KIR00336 KIR2DS2*0010104 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00446
KIR:KIR00446 KIR2DS2*0010105 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00447
KIR:KIR00447 KIR2DS2*0010106 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00448
KIR:KIR00448 KIR2DS2*0010107 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00449
KIR:KIR00449 KIR2DS2*0010108 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00450
KIR:KIR00450 KIR2DS2*0010109 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00451
KIR:KIR00451 KIR2DS2*0010110 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00623
KIR:KIR00623 KIR2DS2*0010111 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00635
KIR:KIR00635 KIR2DS2*0010112 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00097
KIR:KIR00097 KIR2DS2*00102 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00098
KIR:KIR00098 KIR2DS2*00103 296 bases
 SLMVVSMACV GFFLLQGAWP HEGVHRKPSL LAHPGPLVKS EETVILQCWS DVRFEHFLLH
 REGKYKDTLH LIGEHHDGVS KANFSIGPMM QDLAGTYRCY GSVTHSPYQL SAPSDPLDIV
 ITGLYEKPSL SAQPGPTVLA GESVTLSCSS RSSYDMYHLS REGEAHERRF SAGPKVNGTF
 QADFPLGPAT HGGTYRCFGS FRDSPYEWSN SSDPLLVSVT GNPSNSWPSP TEPSSKTGNP
 RHLHVLIGTS VVKIPFTILL FFLLHRWCSN KKNAAVMDQE PAGNRTVNSE DSDEQD*
>P1;KIR:KIR00211
KIR:KIR00211 KIR2DS2*00104 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00038
KIR:KIR00038 KIR2DS2*002 304 bases
 MSLMVVSMAC VGFFLLQGAG PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00039
KIR:KIR00039 KIR2DS2*003 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 SRYLHALIGT SVVIIPFAIL LFFLLHRWCA NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00040
KIR:KIR00040 KIR2DS2*004 290 bases
 LLQGAWPHEG VHRKPSLLAH PGPLVKSEET VILQCWSDVR FEHFLLHREG KYKDTLHLIG
 EHHDGVSKAN FSIGPMMQDL AGTYRCYGSV THSPYQLSAP SDPLDIVITG LYEKPSLSAQ
 PGPTVLAGES VTLSCSSRSS YDMYHLSREG EAHERRFSAG PKVNGTFQAD FPLGPATHGG
 TYRCFGSFRD SPYEWSNSSD PLLVSVTGNP SNSWPSPTEP SSETGNPRHL HVLIGTSVVK
 IPFTILLFFL LHRWCSNKKN AAVMDQEPAG NRTVNSEDSD EQDHQEVSYA *
>P1;KIR:KIR00041
KIR:KIR00041 KIR2DS2*005 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00337
KIR:KIR00337 KIR2DS2*006 297 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQD*
>P1;KIR:KIR00530
KIR:KIR00530 KIR2DS2*007 297 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS FLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQD*
>P1;KIR:KIR00531
KIR:KIR00531 KIR2DS2*008 297 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQD*
>P1;KIR:KIR00906
KIR:KIR00906 KIR2DS2*009 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGSLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS NKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
