>P1;KIR:KIR00001
KIR:KIR00001 KIR2DL1*0010101 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00978
KIR:KIR00978 KIR2DL1*0010102 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00979
KIR:KIR00979 KIR2DL1*0010103 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00002
KIR:KIR00002 KIR2DL1*0020101 348 bases
 MSLLFVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00398
KIR:KIR00398 KIR2DL1*0020102 348 bases
 MSLLFVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00644
KIR:KIR00644 KIR2DL1*0020103 348 bases
 MSLLFVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01038
KIR:KIR01038 KIR2DL1*0020104 348 bases
 MSLLFVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01055
KIR:KIR01055 KIR2DL1*0020105 348 bases
 MSLLFVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01056
KIR:KIR01056 KIR2DL1*0020106 348 bases
 MSLLFVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01059
KIR:KIR01059 KIR2DL1*0020107 348 bases
 MSLLFVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01063
KIR:KIR01063 KIR2DL1*0020108 348 bases
 MSLLFVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01065
KIR:KIR01065 KIR2DL1*0020109 348 bases
 MSLLFVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01068
KIR:KIR01068 KIR2DL1*0020110 348 bases
 MSLLFVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01076
KIR:KIR01076 KIR2DL1*0020111 348 bases
 MSLLFVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01091
KIR:KIR01091 KIR2DL1*0020112 348 bases
 MSLLFVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01106
KIR:KIR01106 KIR2DL1*0020113 348 bases
 MSLLFVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01111
KIR:KIR01111 KIR2DL1*0020114 348 bases
 MSLLFVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01118
KIR:KIR01118 KIR2DL1*0020115 348 bases
 MSLLFVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01122
KIR:KIR01122 KIR2DL1*0020116 348 bases
 MSLLFVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00003
KIR:KIR00003 KIR2DL1*00301 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00004
KIR:KIR00004 KIR2DL1*0030201 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00294
KIR:KIR00294 KIR2DL1*0030202 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00397
KIR:KIR00397 KIR2DL1*0030203 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00399
KIR:KIR00399 KIR2DL1*0030204 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00404
KIR:KIR00404 KIR2DL1*0030205 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00400
KIR:KIR00400 KIR2DL1*0030206 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00401
KIR:KIR00401 KIR2DL1*0030207 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00402
KIR:KIR00402 KIR2DL1*0030208 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00403
KIR:KIR00403 KIR2DL1*0030209 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00616
KIR:KIR00616 KIR2DL1*0030210 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01047
KIR:KIR01047 KIR2DL1*0030211 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01048
KIR:KIR01048 KIR2DL1*0030212 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01061
KIR:KIR01061 KIR2DL1*0030213 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01070
KIR:KIR01070 KIR2DL1*0030214 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01077
KIR:KIR01077 KIR2DL1*0030215 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01081
KIR:KIR01081 KIR2DL1*0030216 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01082
KIR:KIR01082 KIR2DL1*0030217 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01083
KIR:KIR01083 KIR2DL1*0030218 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01087
KIR:KIR01087 KIR2DL1*0030219 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01088
KIR:KIR01088 KIR2DL1*0030220 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01098
KIR:KIR01098 KIR2DL1*0030221 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01099
KIR:KIR01099 KIR2DL1*0030222 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01107
KIR:KIR01107 KIR2DL1*0030223 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01113
KIR:KIR01113 KIR2DL1*0030224 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01115
KIR:KIR01115 KIR2DL1*0030225 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01125
KIR:KIR01125 KIR2DL1*0030226 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01126
KIR:KIR01126 KIR2DL1*0030227 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01129
KIR:KIR01129 KIR2DL1*0030228 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01130
KIR:KIR01130 KIR2DL1*0030229 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01131
KIR:KIR01131 KIR2DL1*0030230 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01132
KIR:KIR01132 KIR2DL1*0030231 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00005
KIR:KIR00005 KIR2DL1*00303 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00897
KIR:KIR00897 KIR2DL1*00304 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00898
KIR:KIR00898 KIR2DL1*00305 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00957
KIR:KIR00957 KIR2DL1*00306 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00006
KIR:KIR00006 KIR2DL1*0040101 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00007
KIR:KIR00007 KIR2DL1*0040102 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01052
KIR:KIR01052 KIR2DL1*0040103 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01053
KIR:KIR01053 KIR2DL1*0040104 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01062
KIR:KIR01062 KIR2DL1*0040105 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01069
KIR:KIR01069 KIR2DL1*0040106 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01074
KIR:KIR01074 KIR2DL1*0040107 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01079
KIR:KIR01079 KIR2DL1*0040108 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01084
KIR:KIR01084 KIR2DL1*0040109 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01085
KIR:KIR01085 KIR2DL1*0040110 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01090
KIR:KIR01090 KIR2DL1*0040111 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01094
KIR:KIR01094 KIR2DL1*0040112 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01104
KIR:KIR01104 KIR2DL1*0040113 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01108
KIR:KIR01108 KIR2DL1*0040114 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR01123
KIR:KIR01123 KIR2DL1*0040115 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00203
KIR:KIR00203 KIR2DL1*00402 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00330
KIR:KIR00330 KIR2DL1*00403 344 bases
 VVSMACVGFF LLQGAWPHEG VHRKPSLLAH PGRLVKSEET VILQCWSDVM FEHFLLHREG
 MFNDTLRLIG EHHDGVSKAN FSISRMTQDL AGTYRCYGSV THSPYQVSAP SDPLDIVIIG
 LYEKPSLSAQ PGPTVLAGEN VTLSCSSRSS YDMYHLSREG EAHERRLPAG TKVNGTFQAN
 FPLGPATHGG TYRCFGSFRD SPYEWSKSSD PLLVSVTGNP SNSWPSPTEP SSETGNPRHL
 HILIGTSVVI ILFILLFFLL HCWCSNKKNA AVMDQESAGN RTANSEDSDE QDPQEVTYTQ
 LNHCVFTQRK ITRPSQRPKT PPTDIIVYTE LPNAESRSKV VSCP* 
>P1;KIR:KIR00982
KIR:KIR00982 KIR2DL1*00404 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00008
KIR:KIR00008 KIR2DL1*005 334 bases
 LLQGAWPHEG VHRKPSLLAH PGRLVKSEET VILQCWSDVM FEHFLLHREG MFNDTLRLIG
 EHHDGVSKAN FSISRMTQDL AGTYRCYGSV THSPYQVSAP SDPLDIVIIG LYEKPSLSAQ
 LGPTVLAGEN VTLSCSSRSS YDMYHLSREG EAHERRLPAG PKVNGTFQAD FPLGPATHGG
 TYRCFGSFHD SPYEWSKSSD PLLVSVTGNP SNSWPSPTEP SSKTGNPRHL HILIGTSVVI
 ILFILLFFLL HRWCSNKKNA AVMDQESAGN RTANSEDSDE QDPQEVTYTQ LNHCVFTQRK
 ITRPSQRPKT PPTDIIVYAE LPNAESRSKV VSCP*  
>P1;KIR:KIR00009
KIR:KIR00009 KIR2DL1*00601 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00764
KIR:KIR00764 KIR2DL1*00602 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00200
KIR:KIR00200 KIR2DL1*007 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDV
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00201
KIR:KIR00201 KIR2DL1*008 348 bases
 MSLLFVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPDPLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00202
KIR:KIR00202 KIR2DL1*009 344 bases
 VVSMACVGFF LLQGAWPHEG VHRKPSLLAH PGRLVKSEET VILQCWSDVM FEHFLLHREG
 MFNDTLRLIG EHHDGVSKAN FSISRMTQDL AGTYRCYGSV THSPYQVSAP SDPLDIVIIG
 LYEKPSLSAQ LGPTVLAGEN VTLSCSSRSS YDMYHLSREG EAHERRLPAG PKVNGTFQAD
 FPLGPATHGG TYRCFGSFHD SPYEWSKSSD PLLVSVTGNP SNSWPSPTEP SSKTGNPRHL
 HILIGTSVVI ILFILLFFLL HRWCSNKKNA AVMDQESAGN RTANSEDSDE QDPQEVTYVQ
 LNHCVFTQRK ITRPSQRPKT PPTDIIVYTE LPNAESRSKV VSCP* 
>P1;KIR:KIR00214
KIR:KIR00214 KIR2DL1*010 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00329
KIR:KIR00329 KIR2DL1*01101 344 bases
 FVSMACVGFF LLQGAWPHEG VHRKPSLLAH PGRLVKSEET VILQCWSDVM FEHFLLHREG
 MFNDTLRLIG EHHDGVSKAN FSISRMTQDL AGTYRCYGSV THSPYQVSAP SDPLDIVIIG
 LYEKPSLSAQ PGPTVLAGEN VTLSCSSRSS YDMYHLSREG EAHERRLPAG TKVNGTFQAN
 FPLGPATHGG TYRCFGSFRD SPYEWSKSSD PLLVSVTGNP SNSWPSPTEP SSETGNPRHL
 HILIGTSVVI ILFILLFFLL HCWCSNKKNA AVMDQESAGN RTANSEDSDE QDPQEVTYTQ
 LNHCVFTQRK ITRPSQRPKT PPTDIIVYTE LPNAESRSKV VSCP* 
>P1;KIR:KIR00396
KIR:KIR00396 KIR2DL1*01102 348 bases
 MSLLFVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00331
KIR:KIR00331 KIR2DL1*01201 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00574
KIR:KIR00574 KIR2DL1*01202 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00332
KIR:KIR00332 KIR2DL1*013N 52 bases
 FVSMACVGFF LLQGAWPHEG VHRKPSLLAH PGRLVKSEET VILQCWSDVM FX*
>P1;KIR:KIR00333
KIR:KIR00333 KIR2DL1*014 344 bases
 VVSMACVGFF LLQGAWPHEG VHRKPSLLAH PGRLVKSEET VILQCWSDVM FEHFLLHREG
 MFNDTLRLIG EHHDGVSKAN FSISRMTQDL AGTYRCYGSV THSPYQVSAP SDPLDIVIIG
 LYEKPSLSAQ LGPTVLAGEN VTLSCSSRSS YDMYHLSREG EAHERRLPAG PKVNGTFQAD
 FPLGPATHGG TYRCFSSFHD SPYEWSKSSD PLLVSVTGNP SNSWPSPTEP SSKTGNPRHL
 HILIGTSVVI ILFILLFFLL HRWCSNKKNA AVMDQESAGN RTANSEDSDE QDPQEVTYTQ
 LNHCVFTQRK ITRPSQRPKT PPTDIIVYTE LPNAESRSKV VSCP* 
>P1;KIR:KIR00334
KIR:KIR00334 KIR2DL1*015 344 bases
 VVSMACVGFF LLQGAWPHEG VHRKPSLLAH PGRLVKSEET VILQCWSDVM FEHFLLHREG
 MFNDTLRLIG EHHDGVSKAN FSISRMTQDL AGTYRCYGSV THSPYQVSAP SDPLDIVIIG
 LYEKPSLSAQ LGPTVLAGEN VTLSCSSRSS YDMYHLSREG EAHERRLPAG PKVNGTFQAD
 FPLGPATHGG TYRCFGSFHD SPYEWSKSSD PLLVSVTGNP SNSWPSPTEP SSKTGNPRHL
 HILIGTSVVI ILFILLFFLL HRWCSNKKNA AVMDQESAGN RTANSEDSDE QEPQEVTYTQ
 LNHCVFTQRK ITRPSQRPKT PPTDIIVYTE LPNAESRSKV VSCP* 
>P1;KIR:KIR00349
KIR:KIR00349 KIR2DL1*016 344 bases
 VVSMACVGFF LLQGAWPHEG VHRKPSLLAH PGRLVKSEET VILQCWSDVM FEHFLLHREG
 MFNDTLRLIG EHHDGVSKAN FSISRMTQDL AGTYRCYGSV THSPYQVSAP SDPLDIVIIG
 LYEKPSLSAQ LGPTVLAGEN VTLSCSSRSS YDMYHLSREG EAHERRLPAG PKVNGTFQAD
 FPLGPATHGG TYRCFGSFHD SPYEWSKSSD PLLVSVTGNP SNSWPSPTEP SSKTGNPRHL
 HILIGTSVVI ILFILLFFLL HRWCSNKKNA AVMDQESAGN RTANSEDSDE QDPQEVTYTQ
 LNHCVFTQRK ITCPSQRPKT PPTDIIVYTE LPNAESRSKV VSCP* 
>P1;KIR:KIR00350
KIR:KIR00350 KIR2DL1*017 344 bases
 VVSMACVGFF LLQGAWPHEG VHRKPSLLAH PGRLVKSEET VILQCWSDVM FEHFLLHREG
 MFNDTLRLIG EHHDGVSKAN FSISRMTQDL AGTYRCYGSV THSPYQVSAP SDPLDIVIIG
 LYEKPSLSAQ LGPTVLAGEN VTLSCSSRSS YDMYHLSREG EAHERRLPAG PKVNGTFQAD
 FPLGPATHGG TYRCFGSFHD SPYEWSKSSD PLLVSVTGNP SNSWPSPTEP SSKTGNPQHL
 HILIGTSVVI ILFILLFFLL HRWCSNKKNA AVMDQESAGN RTANSEDSDE QDPQEVTYTQ
 LNHCVFTQRK ITRPSQRPKT PPTDIIVYTE LPNAESRSKV VSCP* 
>P1;KIR:KIR00351
KIR:KIR00351 KIR2DL1*018 344 bases
 VVSMACVGFF LLQGAWPHEG VHRKPSLLAH PGRLVKSEET VILQCWSDVM FEHFLLHREG
 MFNDTLRLIG EHHDGVSKAN FSISRMTQDL AGTYRCYGSV THSPYQVSAP SDPLDIVIIG
 LYEKPSLSAQ LGPTVLAGEN VTLSCSSRSS YDMYHLSREG EAHERRLPAG PKVNGTFQAD
 FPLGPATHGG TYRCFGSFHD SPYEWSKSSD PLLVSVTGNP SNSWPSPTEP SSKTGNPRHL
 HILIGTSVVI ILFILLFFLL HRWCSNKKNA AVMDQESAGN RTANSEDSDE QDPQEVTYPQ
 LNHCVFTQRK ITRPSQRPKT PPTDIIVYTE LPNAESRSKV VSCP* 
>P1;KIR:KIR00352
KIR:KIR00352 KIR2DL1*019 344 bases
 VVSMACVGFF LLQGAWPHEG VHRKPSLLAH PGRLVKSEET VILQCWSDVM FEHFLLHREG
 MFNDTLRLIG EHHDGVSKAN FSISRMTQDL AGTYRCYGSV THSPYQVSAP SDPLDIVIIG
 LYEKPSLSAQ PGPTVLAGEN VTLSCSSRSS YDMYHLSREG EAHERRLPAG PKVNGTFQAD
 FPLGPATHGG TYRCFGSFHD SPYEWSKSSD PLLVSVTGNP SNSWPSPTEP SSKTGNPRHL
 HIVIGTSVVI ILFILLFFLL HRWCSNKKNA AVMDQESAGN RTANSEDSDE QDPQEVTYTQ
 LNHCVFTQRK ITRPSQRPKT PPTDIIVYTE LPNAESRSKV VSCP* 
>P1;KIR:KIR00518
KIR:KIR00518 KIR2DL1*020 345 bases
 LVVSMACVGF FLLQGAWPHE GVHRKPSLLA HPGRLVKSEE TVILQCWSDV MFEHFLLHRE
 GMFNDTLRLI GEHHDGVSKA NFSIGRMTQD LAGTYRCYGS VTHSPYQVSA PSDPLDIVII
 GLYEKPSLSA QLGPTVLAGE NVTLSCSSRS SYDMYHLSRE GEAHERRLPA GPKVNGTFQA
 DFPLGPATHG GTYRCFGSFH DSPYEWSKSS DPLLVSVTGN PSNSWPSPTE PSSKTGNPRH
 LHILIGTSVV IILFILLFFL LHRWCSNKKN AAVMDQESAG NRTANSEDSD EQDPQEVTYT
 QLNHCVFTQR KITRPSQRPK TPPTDIIVYT ELPNAESRSK VVSCP* 
>P1;KIR:KIR00519
KIR:KIR00519 KIR2DL1*021 345 bases
 LFVSMACVGF FLLQGAWPHE GVHRKPSLLA HPGPLVKSEE TVILQCWSDV MFEHFLLHRE
 GMFNDTLRLI GEHHDGVSKA NFSISRMTQD LAGTYRCYGS VTHSPYQVSA PSDPLDIVII
 GLYQKPSLSA QPGPTVLAGE NVTLSCSSRS SYDMYHLSRE GEAHERRLPA GPKVNGTFQA
 DFPLGPATHG GTYRCFGSFH DSPYEWSKSS DPLLVSVTGN PSNSWPSPTE PSSKTGNPRH
 LHILIGTSVV IILFILLFFL LHRWCSNKKN AAVMDQESAG NRTANSEDSD EQDPQEVTYT
 QLNHCVFTQR KITRPSQRPK TPPTDIIVYT ELPNAESRSK VVSCP* 
>P1;KIR:KIR00577
KIR:KIR00577 KIR2DL1*02201 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGKFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00956
KIR:KIR00956 KIR2DL1*02202 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGKFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00575
KIR:KIR00575 KIR2DL1*023 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVPHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00576
KIR:KIR00576 KIR2DL1*024 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHRDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00617
KIR:KIR00617 KIR2DL1*025 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SWSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00677
KIR:KIR00677 KIR2DL1*026 267 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRX*   
>P1;KIR:KIR00798
KIR:KIR00798 KIR2DL1*027 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGNYRCFS SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00799
KIR:KIR00799 KIR2DL1*028 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSVSRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00800
KIR:KIR00800 KIR2DL1*029 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ FSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00817
KIR:KIR00817 KIR2DL1*030 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPGDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00818
KIR:KIR00818 KIR2DL1*031 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HRGGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00865
KIR:KIR00865 KIR2DL1*032N 207 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPX*   
>P1;KIR:KIR00899
KIR:KIR00899 KIR2DL1*033 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANRE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00900
KIR:KIR00900 KIR2DL1*034 348 bases
 MSLLFVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00954
KIR:KIR00954 KIR2DL1*035 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHCWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00955
KIR:KIR00955 KIR2DL1*036 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQANFPLGPA THGGTYRCCG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00980
KIR:KIR00980 KIR2DL1*037 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHHWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
>P1;KIR:KIR00981
KIR:KIR00981 KIR2DL1*038 348 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQLGPMVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHILIGT SVVIILFILL FFLLHRWCSN KKNAAVMDQE SAGNRTANSE DSDEQDPQEV
 TYTQLNHCVF TQRKITRPSQ RPKTPPTDII VYTELPNAES RSKVVSCP* 
