>P1;KIR:KIR00020
KIR:KIR00020 KIR2DL4*00101 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00021
KIR:KIR00021 KIR2DL4*0010201 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00424
KIR:KIR00424 KIR2DL4*0010202 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00112
KIR:KIR00112 KIR2DL4*0010301 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00115
KIR:KIR00115 KIR2DL4*0010302 367 bases
 ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF TLYKKDGVPV
 PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT GLYEKPSLTA
 RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA DFPLGPATHG
 ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH LHAVIRYSVA
 IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY AQLDHCIFTQ
 RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT ALSQTQLASS
 NVPAAGI*     
>P1;KIR:KIR00420
KIR:KIR00420 KIR2DL4*0010303 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00421
KIR:KIR00421 KIR2DL4*0010304 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00422
KIR:KIR00422 KIR2DL4*0010305 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00423
KIR:KIR00423 KIR2DL4*0010306 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00425
KIR:KIR00425 KIR2DL4*0010307 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00620
KIR:KIR00620 KIR2DL4*0010308 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00119
KIR:KIR00119 KIR2DL4*00104 367 bases
 ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF TLYKKDGVPV
 PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT GLYEKPSLTA
 RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA DFPLGPATHG
 ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH LHAVIRYSVA
 IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY AQLDHCIFTQ
 RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT ALSQTQLASS
 NVPAAGI*     
>P1;KIR:KIR00129
KIR:KIR00129 KIR2DL4*00105 375 bases
 MSPTVIILAC LGFFLDQSVW AHVGGQDKPF CSAWPSAVVP QGGHVTLRCH YRRGFNIFTL
 YKKDGVPVPE LYNRIFWNSF LISPVTPAHA GTYRCRGFHP HSPTEWSAPS NPLVIMVTGL
 YEKPSLTARP GPTVRTGENV TLSCSSQSSF DIYHLSREGE AHELRLPAVP SINGTFQADF
 PLGPATHGET YRCFGSFHGS PYEWSDASDP LPVSVTGNPS SSWPSPTEPS FKTGIARHLH
 AVIRYSVAII LFTILPFFLL HRWCSKKKNA AVMNQEPAGH RTVNREDSDE QDPQEVTYAQ
 LDHCIFTQRK ITGPSQRSKR PSTDTSVCIE LPNAEPRALS PAHEHHSQAL MGSSRETTAL
 SQTQLASSNV PAAGI*    
>P1;KIR:KIR00022
KIR:KIR00022 KIR2DL4*00201 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00023
KIR:KIR00023 KIR2DL4*00202 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00024
KIR:KIR00024 KIR2DL4*003 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPLTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK DAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS HVPAAGI*    
>P1;KIR:KIR00025
KIR:KIR00025 KIR2DL4*004 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPLTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS HVPAAGI*    
>P1;KIR:KIR00026
KIR:KIR00026 KIR2DL4*00501 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00209
KIR:KIR00209 KIR2DL4*00502 367 bases
 ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF TLYKKDGVPV
 PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT GLYEKPSLTA
 RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA DFPLGPATHG
 ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH LHAVIRYSVA
 IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY AQLDHCIFTQ
 RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT ALSQTQLASS
 NVPAAGI*     
>P1;KIR:KIR00027
KIR:KIR00027 KIR2DL4*00601 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RLGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00130
KIR:KIR00130 KIR2DL4*00602 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RLGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00028
KIR:KIR00028 KIR2DL4*007 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTNRCRGF RPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR00109
KIR:KIR00109 KIR2DL4*0080101 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR00110
KIR:KIR00110 KIR2DL4*0080102 251 bases
 HVGGQDKPFC SAWPSAVVPQ GGHVTLRCHY RRGFNIFTLY KKDGVPVPEL YNRIFWNSFL
 ISPVTPAHAG TYRCRGFHPH SPTEWSAPSN PLVIMVTGLY EKPSLTARPG PTVRAGENVT
 LSCSSQSSFD IYHLSREGEA HELRLPAVPS INGTFQADFP LGPATHGETY RCFGSFHGSP
 YEWSDPSDPL PVSVTGNPSS SWPSPTEPSF KTGIARHLHA VIRYSVAIIL FTILPFFLLH
 RWCSKKKMLL X*    
>P1;KIR:KIR00117
KIR:KIR00117 KIR2DL4*0080103 264 bases
 ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF TLYKKDGVPV
 PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT GLYEKPSLTA
 RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA DFPLGPATHG
 ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH LHAVIRYSVA
 IILFTILPFF LLHRWCSKKK MLLX*   
>P1;KIR:KIR00213
KIR:KIR00213 KIR2DL4*0080104 264 bases
 ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF TLYKKDGVPV
 PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT GLYEKPSLTA
 RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA DFPLGPATHG
 ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH LHAVIRYSVA
 IILFTILPFF LLHRWCSKKK MLLX*   
>P1;KIR:KIR00436
KIR:KIR00436 KIR2DL4*0080105 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR00111
KIR:KIR00111 KIR2DL4*0080201 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR00116
KIR:KIR00116 KIR2DL4*0080202 264 bases
 ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF TLYKKDGVPV
 PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT GLYEKPSLTA
 RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA DFPLGPATHG
 ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH LHAVIRYSVA
 IILFTILPFF LLHRWCSKKK MLLX*   
>P1;KIR:KIR00437
KIR:KIR00437 KIR2DL4*0080203 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR00647
KIR:KIR00647 KIR2DL4*0080204 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR00118
KIR:KIR00118 KIR2DL4*00901 264 bases
 ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF TLYKKDGVPV
 PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT GLYEKPSLTA
 RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA DFPVGPATHG
 ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH LHAVIRYSVA
 IILFTILPFF LLHRWCSKKK MLLX*   
>P1;KIR:KIR00520
KIR:KIR00520 KIR2DL4*00902 264 bases
 ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF TLYKKDGVPV
 PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT GLYEKPSLTA
 RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA DFPVGPATHG
 ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH LHAVIRYSVA
 IILFTILPFF LLHRWCSKKK MLLX*   
>P1;KIR:KIR00114
KIR:KIR00114 KIR2DL4*010 367 bases
 ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF TLYKKDGVPV
 PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT GLYEKPSLTA
 RLGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLHA VPSINGTFQA DFPLGPATHG
 ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH LHAVIRYSVA
 IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY AQLDHCIFTQ
 RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT ALSQTQLASS
 NVPAAGI*     
>P1;KIR:KIR00113
KIR:KIR00113 KIR2DL4*011 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR00212
KIR:KIR00212 KIR2DL4*01201 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPEEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00593
KIR:KIR00593 KIR2DL4*01202 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPEEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00512
KIR:KIR00512 KIR2DL4*013 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR00521
KIR:KIR00521 KIR2DL4*014 367 bases
 ACLGFFLDQS VWAHVGGQDK PFCSAWPSTV VPQGGHVTLR CHCRRGFNIF TLYKKDGVPV
 PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT GLYEKPSLTA
 RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA DFPLGPATHG
 ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH LHAVIRYSVA
 IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY AQLDHCIFTQ
 RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT ALSQTQLASS
 NVPAAGI*     
>P1;KIR:KIR00522
KIR:KIR00522 KIR2DL4*015 367 bases
 ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLW CHYRRGFNIF TLYKKDGVPV
 PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT GLYEKPSLTA
 RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA DFPLGPATHG
 ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH LHAVIRYSVA
 IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY AQLDHCIFTQ
 RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT ALSQTQLASS
 NVPAAGI*     
>P1;KIR:KIR00523
KIR:KIR00523 KIR2DL4*016 367 bases
 ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF TLYKKDGFPV
 PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT GLYEKPSLTA
 RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA DFPLGPATHG
 ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH LHAVIRYSVA
 IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY AQLDHCIFTQ
 RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT ALSQTQLASS
 NVPAAGI*     
>P1;KIR:KIR00591
KIR:KIR00591 KIR2DL4*017 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGRHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR00592
KIR:KIR00592 KIR2DL4*018 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRGGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFSSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00594
KIR:KIR00594 KIR2DL4*019 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRGGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFSSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR00595
KIR:KIR00595 KIR2DL4*020 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRV GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
>P1;KIR:KIR00596
KIR:KIR00596 KIR2DL4*021 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 NFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00590
KIR:KIR00590 KIR2DL4*022 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRV LSPAHEHHSQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00668
KIR:KIR00668 KIR2DL4*023 352 bases
 GGQDKPFCSA WPSAVVPQGG HVTLRCHYRR GFNIFTLYKK DGVPVPELYN RIFWNSFLIS
 PVTPAHAGTY RCRGFHPHSP TEWSAPSNPL VIMVTGLYEK PSLTARPGPT VRTGENVTLS
 CSSQSSFDIY HLSREGEAHE LRLPAVPSIN GTFQADFPLG PATHGETYRC FSSFHGSPYE
 WSDASDPLPV SVTGNPSSSW PSPTEPSFKT GIARHLHAVI RYSVAIILFT ILPFFLLHRW
 CSKKKNAAVM NQEPAGHRTV NREDSDEQDP QEVTYAQLDH CIFTQRKITG PSQRSKRPST
 DTSVCIELPN AEPRALSPAH EHHSQALMGS SRETTALSQT QLASSNVPAA GI*
>P1;KIR:KIR00670
KIR:KIR00670 KIR2DL4*024 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPEEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHTQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00672
KIR:KIR00672 KIR2DL4*025 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHCRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRAGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDPS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPQEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHTQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00674
KIR:KIR00674 KIR2DL4*026 377 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK NAAVMNQEPA GHRTVNREDS DEQDPEEVTY
 AQLDHCIFTQ RKITGPSQRS KRPSTDTSVC IELPNAEPRA LSPAHEHHTQ ALMGSSRETT
 ALSQTQLASS NVPAAGI*    
>P1;KIR:KIR00675
KIR:KIR00675 KIR2DL4*027 274 bases
 MSMSPTVIIL ACLGFFLDQS VWAHVGGQDK PFCSAWPSAV VPQGGHVTLR CHYRRGFNIF
 TLYKKDGVPV PELYNRIFWN SFLISPVTPA HAGTYRCRGF HPHSPTEWSA PSNPLVIMVT
 GLYEKPSLTA RPGPTVRTGE NVTLSCSSQS SFDIYHLSRE GEAHELRLPA VPSINGTFQA
 DFPLGPATHG ETYRCFGSFH GSPYEWSDAS DPLPVSVTGN PSSSWPSPTE PSFKTGIARH
 LHAVIRYSVA IILFTILPFF LLHRWCSKKK MLLX*  
