>DL;IPD:KIR00029
KIR:KIR00029 KIR2DL5A*0010101 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00300
KIR:KIR00300 KIR2DL5A*0010102 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00439
KIR:KIR00439 KIR2DL5A*0010103 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00259
KIR:KIR00259 KIR2DL5A*00102 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00260
KIR:KIR00260 KIR2DL5A*00103 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00262
KIR:KIR00262 KIR2DL5A*00104 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00263
KIR:KIR00263 KIR2DL5A*00105 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TTGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00095
KIR:KIR00095 KIR2DL5A*0050101 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00249
KIR:KIR00249 KIR2DL5A*0050102 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00438
KIR:KIR00438 KIR2DL5A*0050103 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00440
KIR:KIR00440 KIR2DL5A*0050104 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00391
KIR:KIR00391 KIR2DL5A*01201 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00389
KIR:KIR00389 KIR2DL5A*01202 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCGAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCCAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00536
KIR:KIR00536 KIR2DL5A*014 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CCGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00537
KIR:KIR00537 KIR2DL5A*015 1128 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTTGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA TGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00030
KIR:KIR00030 KIR2DL5B*0020101 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00248
KIR:KIR00248 KIR2DL5B*0020102 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00301
KIR:KIR00301 KIR2DL5B*0020103 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00394
KIR:KIR00394 KIR2DL5B*0020104 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00441
KIR:KIR00441 KIR2DL5B*0020105 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00524
KIR:KIR00524 KIR2DL5B*0020106 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00632
KIR:KIR00632 KIR2DL5B*0020107 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00535
KIR:KIR00535 KIR2DL5B*00202 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCCAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00031
KIR:KIR00031 KIR2DL5B*003 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCATGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00032
KIR:KIR00032 KIR2DL5B*004 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCAC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCCAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00125
KIR:KIR00125 KIR2DL5B*00601 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00267
KIR:KIR00267 KIR2DL5B*00602 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCGAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00393
KIR:KIR00393 KIR2DL5B*00603 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCGAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCCAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00126
KIR:KIR00126 KIR2DL5B*0070101 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCATGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00525
KIR:KIR00525 KIR2DL5B*0070102 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCATGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00244
KIR:KIR00244 KIR2DL5B*0080101 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00395
KIR:KIR00395 KIR2DL5B*0080102 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00266
KIR:KIR00266 KIR2DL5B*00802 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TTGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00682
KIR:KIR00682 KIR2DL5B*00803 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCCAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00245
KIR:KIR00245 KIR2DL5B*009 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00264
KIR:KIR00264 KIR2DL5B*010 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00265
KIR:KIR00265 KIR2DL5B*011 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCATTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00390
KIR:KIR00390 KIR2DL5B*01301 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTTGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA TGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00392
KIR:KIR00392 KIR2DL5B*01302 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTTGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA TGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00534
KIR:KIR00534 KIR2DL5B*01303 1128 bases
 ATGTCGCTCA TGGTGGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTTGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA TGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00538
KIR:KIR00538 KIR2DL5B*016 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCATACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00664
KIR:KIR00664 KIR2DL5B*017 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGACAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTCGGGG TTCACACCCG
 CGCTCCCCCA TTGAGTGGTC GGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCGATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCAGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAACAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
>DL;IPD:KIR00684
KIR:KIR00684 KIR2DL5B*018 1128 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCGC TGTGGTGCAT
 CGAGGAGGAC ATGTGACTCT TCTGTGTCGC TCTCGTCTTG GGTTTACCAT CTTCAGTCTG
 TACAAAGAAG ATGGGGTGCC TGTCCCTGAG CTCTACAACA AAATATTCTG GAAGAGCATC
 CTCATGGGCC CTGTGACCCC TGCACACGCA GGGACCTACA GATGTTGGGG TTCACACCCA
 CGCTCCCCCA TTGAGTGGTC AGCACCCAGC AACCCCCTGG TGATCGTGGT CACAGGTCTA
 TTTGGGAAAC CTTCACTCTC AGCCCAGCCG GGCCCCACGG TTCGCACAGG AGAGAACGTG
 ACCTTGTCCT GCAGCTCCAG GAGCTCATTT GACATGTACC ATCTATCCAG GGAGGGGAGG
 GCCCATGAAC CTAGGCTCCC TGCAGTGCCC AGCGTCAATG GAACATTCCA GGCTGACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACACATGCT TCGGCTCTCT CCATGACTCA
 CCCTATGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACTCTTCA
 AGTAGTTCAT CTTCACCCAC TGAACCAAGC TCCAAAACTG GTATCCGCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGCTATCATC CTCTTCATCA TCCTCTTCTT CTTTCTCCTT
 CATTGCTGCT GCTCCAACAA AAAGAATGCT GCTGTAATGG ACCAAGAGCC TGCCGGGGAC
 AGAACAGTGA ACAGGGAGGA CTCTGATGAT CAAGACCCTC AGGAGGTGAC ATATGCACAG
 TTGGATCACT GCGTTTTCAC ACAGACAAAA ATCACTTCCC CTTCTCAGAG GCCCAAGACA
 CCTCCAACAG ATACCACCAT GTACATGGAA CTTCCAAATG CTAAGCCAAG ATCATTGTCT
 CCTGCCCATA AGCACCACAG TCAGGCCTTG AGGGGATCTT CTAGGGAGAC AACAGCCCTG
 TCTCAAAACC GGGTTGCTAG CTCCCATGTA CCAGCAGCTG GAATCTGA* 
