>DL;IPD:KIR00052
KIR:KIR00052 KIR2DP1*00101 854 bases
 GGTTCTTCTT GCTGCAGGGG GCCTGGCCAC ATGAGGGTGG TCAGGACAAG CCCTTGCTGT
 CTGCCTGGCC CAGCTCTGTG GTGCCTCCAG GACATGTGAT TCTTCGGTGT CATTCTTATC
 TTGGGTTTAA CAACTTCAGT CTGTAAAAGG AAGATGGGGT GCCTGGCACT GAGCTCTACA
 ACAGAATATT CTGGAAGAGC CTTTTCATGG GCCCTGTGAC CCCAGCACAC ACAGGGACGT
 ACAGATGTCG GGGTTCACAC CCACACTCCC CCAGTGGGTG GTCGGCACCC AGCAACCCCC
 TGGTGATCAT GGCCACAGGA GTCCACAGAA AACCTTCCCT CCTGGCCCAC CCAGGTCCCC
 TGGTGAAATC AGAAGAGACA GTCATCCTGC AATGTTGGTC AGATGTCAGG TTTGAGCACT
 TCCTTCTGCA CAGAGAGGGG ACATTTAACG ACACTTTGCA CCTCACTGGA GAGCACCATG
 ATGGGGTCTC CAAGGCCAAC TTCTCCATCG GTCCCATGAT GGAAGACCTG GCAGGGACCT
 ACAGATGCTA CGGTTCTGTT ACTCACTCCC CCATCAGTTG TCAGCTCCCA GTGACCCTCT
 GGACATCGTC ATCACAGGTC TATATGAGAA ACCTTCTCTC TCAGCCCAGC CGGGCCCCAC
 GGTTCTGGCA GGAGAGAGCG TGACCTTGTC CTGCAGCTCC CGGAGCTCCT ATGACATGTA
 CCATCTATCC ACGGAGGGGG AGGCCCATGA ACGTAGGTTC TCTGCAGGGA CCAAGGTCAA
 CGGAACATTC CAGGCTGACT TTCCTCTGGG CCCTGCCACC CACGGAGGAA CCTACAGATG
 CTTCGGCTCT TTCC*    
>DL;IPD:KIR00127
KIR:KIR00127 KIR2DP1*0010201 1331 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA GAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TCCCCCAGTG GGTGGTCGGC ACCCAGCAAC CCCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTGAG CACTTCCTTC TGCACAGAGA GGGGACATTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TCTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCACGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCG AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CTAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AACGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00649
KIR:KIR00649 KIR2DP1*0010202 1331 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA GAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TCCCCCAGTG GGTGGTCGGC ACCCAGCAAC CCCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTGAG CACTTCCTTC TGCACAGAGA GGGGACATTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TCTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCACGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCG AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CTAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AACGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00634
KIR:KIR00634 KIR2DP1*0010203 1331 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA GAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TCCCCCAGTG GGTGGTCGGC ACCCAGCAAC CCCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTGAG CACTTCCTTC TGCACAGAGA GGGGACATTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TCTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCACGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCG AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CTAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AACGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00694
KIR:KIR00694 KIR2DP1*00103 1331 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA GAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TCCCCCAGTG GGTGGTCGGC ACCCAGCAAC CCCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTGAG CACTTCCTTC TGCACAGAGA GGGGACATTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TCTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTTGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AACGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00053
KIR:KIR00053 KIR2DP1*0020101 1331 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA GAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TACCCCAGTG GGTGGTCGGC ACCCAGCAAC ACCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTCAG CACTTCCTTC TGCACAGAGA AGGGAAGTTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TTTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AAAGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00293
KIR:KIR00293 KIR2DP1*0020102 1331 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA GAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TACCCCAGTG GGTGGTCGGC ACCCAGCAAC ACCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTCAG CACTTCCTTC TGCACAGAGA AGGGAAGTTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TTTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AAAGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00442
KIR:KIR00442 KIR2DP1*0020103 1331 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA GAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TACCCCAGTG GGTGGTCGGC ACCCAGCAAC ACCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTCAG CACTTCCTTC TGCACAGAGA AGGGAAGTTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TTTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AAAGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00443
KIR:KIR00443 KIR2DP1*0020104 1331 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA GAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TACCCCAGTG GGTGGTCGGC ACCCAGCAAC ACCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTCAG CACTTCCTTC TGCACAGAGA AGGGAAGTTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TTTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AAAGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00444
KIR:KIR00444 KIR2DP1*0020105 1331 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA GAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TACCCCAGTG GGTGGTCGGC ACCCAGCAAC ACCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTCAG CACTTCCTTC TGCACAGAGA AGGGAAGTTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TTTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AAAGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00445
KIR:KIR00445 KIR2DP1*0020106 1331 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA GAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TACCCCAGTG GGTGGTCGGC ACCCAGCAAC ACCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTCAG CACTTCCTTC TGCACAGAGA AGGGAAGTTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TTTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AAAGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00621
KIR:KIR00621 KIR2DP1*0020107 1331 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA GAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TACCCCAGTG GGTGGTCGGC ACCCAGCAAC ACCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTCAG CACTTCCTTC TGCACAGAGA AGGGAAGTTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TTTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AAAGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00633
KIR:KIR00633 KIR2DP1*0020108 1331 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA GAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TACCCCAGTG GGTGGTCGGC ACCCAGCAAC ACCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTCAG CACTTCCTTC TGCACAGAGA AGGGAAGTTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TTTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AAAGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00625
KIR:KIR00625 KIR2DP1*0020109 1331 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA GAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TACCCCAGTG GGTGGTCGGC ACCCAGCAAC ACCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTCAG CACTTCCTTC TGCACAGAGA AGGGAAGTTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TTTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AAAGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00690
KIR:KIR00690 KIR2DP1*00202 1331 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA GAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TACCCCAGTG GGTGGTCGGC ACCCAGCAAC ACCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTCAG CACTTCCTTC TGCACAGAGA AGGGAAGTTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TTTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGATC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AAAGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00242
KIR:KIR00242 KIR2DP1*0030101 1331 bases
 ATGTCGCTCA CGGTCGTCAG CGTGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA GAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TACCCCAGTG GGTGGTCGGC ACCCAGCAAC ACCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTGAG CACTTCCTTC TGCACAGAGA AGGGAAGTTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TTTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AAAGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00648
KIR:KIR00648 KIR2DP1*0030102 1331 bases
 ATGTCGCTCA CGGTCGTCAG CGTGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA GAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TACCCCAGTG GGTGGTCGGC ACCCAGCAAC ACCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTGAG CACTTCCTTC TGCACAGAGA AGGGAAGTTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TTTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AAAGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00473
KIR:KIR00473 KIR2DP1*004 1331 bases
 ATGTCGCTCA CGGTCGTCAG CGTGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA GAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TACCCCAGTG GGTGGTCGGC ACCCAGCAAC ACCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTGAG CACTTCCTTC TGCACAGAGA AGGGAAGTTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TTTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AATGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AAAGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00474
KIR:KIR00474 KIR2DP1*005 1331 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA CAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TACCCCAGTG GGTGGTCGGC ACCCAGCAAC ACCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTCAG CACTTCCTTC TGCACAGAGA AGGGAAGTTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TTTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AAAGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00475
KIR:KIR00475 KIR2DP1*006 1331 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA GAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TCCCCCAGTG GGTGGTCGGC ACCCAGCAAC CCCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTGAG CACTTCCTTC TGCACAGAGA GGGGACATTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TCTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCG AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AACGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00476
KIR:KIR00476 KIR2DP1*007 1331 bases
 ATGTCGCTCA CGGTCGTCAG CGTGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA GAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TACCCCAGTG GGTGGTCGGC ACCCAGCAAC ACCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTGAG CACTTCCTTC TGCACAGAGA AGGGAAGTTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TTTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACAGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAG CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AAAGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00477
KIR:KIR00477 KIR2DP1*008 1331 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA CAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TACCCCAGTG GGTGGTCGGC ACCCAGCAAC ACCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTCAG CACTTCCTTC TGCACAGAGA AGGGAAGTTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TTTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAG GGGGAGGCCC
 ATGAACGTAG GTTTTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AAAGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00478
KIR:KIR00478 KIR2DP1*009 1331 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA GAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TACCCCAGTG GGTGGTCGGC ACCCAGCAAC ACCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTGAG CACTTCCTTC TGCACAGAGA AGGGAAGTTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TTTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ATGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CGTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AAAGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00622
KIR:KIR00622 KIR2DP1*010 1331 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA GAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TCCCCCAGTG GGTGGTCGGC ACCCAGCAAC CCCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTGAG CACTTCCTTC TGCACAGAGA GGGGACATTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TCTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 GGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AACGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00692
KIR:KIR00692 KIR2DP1*011 1331 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA GAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TCCCCCAGTG GGTGGTCGGC ACCCAGCAAC CCCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTGAG CACTTCCTTC TGCACAGAGA GGGGACATTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TCTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCACGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCAAGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCG AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CTAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AACGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00686
KIR:KIR00686 KIR2DP1*012 1331 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA GAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TCCCCCAGTG GGTGGTCGGC ACCCAGCAAC CCCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CGCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTGAG CACTTCCTTC TGCACAGAGA GGGGACATTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TCTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCACGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGACCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCG AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CTAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AACGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00688
KIR:KIR00688 KIR2DP1*013 1331 bases
 ATGTCGCTCA CGGTCGTCAG CGTGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA GAGCCTTTTC
 ATGGGCCCTG TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TACCCCAGTG GGTGGTCGGC ACCCAGCAAC ACCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTGAG CACTTCCTTC TGCACAGAGA AGGGAAGTTT
 AACGACACTT CGCACCTCAC TGGAGAGCAC CATGATGGGG TTTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACGG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AAAGTTGTCT
 CCTGCCCATG A*    
>DL;IPD:KIR00685
KIR:KIR00685 KIR2DP1*014 1331 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTG CTGTCTGCCT GGCCCAGCTC TGTGGTGCCT
 CCAGGACATG TGATTCTTCG GTGTCATTCT TATCTTGGGT TTAACAACTT CAGTCTGTAA
 AAGGAAGATG GGGTGCCTGG CACTGAGCTC TACAACAGAA TATTCTGGAA GAGCCTTTTC
 ATGGGCCCTA TGACCCCAGC ACACACAGGG ACGTACAGAT GTCGGGGTTC ACACCCACAC
 TCCCCCAGTG GGTGGTCGGC ACCCAGCAAC CCCCTGGTGA TCATGGCCAC AGGAGTCCAC
 AGAAAACCTT CCCTCCTGGC CCACCCAGGT CCCCTGGTGA AATCAGAAGA GACAGTCATC
 CTGCAATGTT GGTCAGATGT CAGGTTTGAG CACTTCCTTC TGCACAGAGA GGGGACATTT
 AACGACACTT TGCACCTCAC TGGAGAGCAC CATGATGGGG TCTCCAAGGC CAACTTCTCC
 ATCGGTCCCA TGATGGAAGA CCTGGCAGGG ACCTACAGAT GCTACGGTTC TGTTACTCAC
 TCCCCCATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA GGTCTATATG
 GGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG AGCGTGACCT
 TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAG GGGGAGGCCC
 ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCT GACTTTCCTC
 TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT GACTCTCCCT
 ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC CCTTCAAATA
 GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAA CCCAAGACAC CTGCACGTTC
 TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCATCCTCCT CCTCTTCTTT CTCCTTCATC
 GCTGGTGCTC CAACAAGAAA AATGCTGCTG TAATGGACCA AGAGCCTGCA GGGAACAGAA
 CAGCGAATAG CGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAC GTACAGTTGG
 ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC AAGACACCCC
 CAACAGATAC CAGAGTGTAC ACGGAACTTC CAAATGCTGA GTCCAGATCC AACGTTGTCT
 CCTGCCCATG A*    
