>P1;KIR:KIR00014
KIR:KIR00014 KIR2DL3*0010101 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00412
KIR:KIR00412 KIR2DL3*0010102 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00413
KIR:KIR00413 KIR2DL3*0010103 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00415
KIR:KIR00415 KIR2DL3*0010104 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00416
KIR:KIR00416 KIR2DL3*0010105 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00417
KIR:KIR00417 KIR2DL3*0010106 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00418
KIR:KIR00418 KIR2DL3*0010107 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00419
KIR:KIR00419 KIR2DL3*0010108 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00619
KIR:KIR00619 KIR2DL3*0010109 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00631
KIR:KIR00631 KIR2DL3*0010110 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00657
KIR:KIR00657 KIR2DL3*0010111 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR01064
KIR:KIR01064 KIR2DL3*0010112 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR01072
KIR:KIR01072 KIR2DL3*0010113 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR01080
KIR:KIR01080 KIR2DL3*0010114 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR01101
KIR:KIR01101 KIR2DL3*0010115 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00566
KIR:KIR00566 KIR2DL3*00102 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00569
KIR:KIR00569 KIR2DL3*00103 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00656
KIR:KIR00656 KIR2DL3*00104 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00671
KIR:KIR00671 KIR2DL3*00105 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00689
KIR:KIR00689 KIR2DL3*00106 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00691
KIR:KIR00691 KIR2DL3*00107 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00695
KIR:KIR00695 KIR2DL3*00108 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00732
KIR:KIR00732 KIR2DL3*00109 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00734
KIR:KIR00734 KIR2DL3*00110 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00015
KIR:KIR00015 KIR2DL3*0020101 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWLS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITHPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00435
KIR:KIR00435 KIR2DL3*0020102 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWLS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITHPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00646
KIR:KIR00646 KIR2DL3*0020103 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWLS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITHPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00016
KIR:KIR00016 KIR2DL3*003 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYTQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00017
KIR:KIR00017 KIR2DL3*004 341 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LRAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL RLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PIHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITHPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00018
KIR:KIR00018 KIR2DL3*00501 341 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LRAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL RLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITHPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00806
KIR:KIR00806 KIR2DL3*00502 341 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LRAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL RLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITHPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00019
KIR:KIR00019 KIR2DL3*006 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITHPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00128
KIR:KIR00128 KIR2DL3*007 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWLS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAAVMDQ ESAGNRTANS EDSDEQDPQE
 VTYAQLNHCV FTQRKITHPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00313
KIR:KIR00313 KIR2DL3*008N 121 bases
 VHRKPSLLAH PGPLVKSEET VILQCWSDVR FQHFLLHREG KFKDTLHLIG EHHDGVSKAN
 FSIGPMMQDL AGTYRCYGSV THPPISCQLP VTLWTSSSQV YMRNLLSQPS RAPRFWQERA
 X*     
>P1;KIR:KIR00314
KIR:KIR00314 KIR2DL3*009 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHEPR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00414
KIR:KIR00414 KIR2DL3*010 349 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LRAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL RLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVIILFVLL LFFLLHRWCS NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE PRSKVVSCP* 
>P1;KIR:KIR00567
KIR:KIR00567 KIR2DL3*011 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQLGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00568
KIR:KIR00568 KIR2DL3*01201 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAAVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITHPF QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00660
KIR:KIR00660 KIR2DL3*01202 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAAVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITHPF QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00570
KIR:KIR00570 KIR2DL3*013 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SQSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00571
KIR:KIR00571 KIR2DL3*014 341 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL RLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00588
KIR:KIR00588 KIR2DL3*015 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWLS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITHPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00589
KIR:KIR00589 KIR2DL3*016 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00655
KIR:KIR00655 KIR2DL3*017 349 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL RLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE PRSKVVSCP* 
>P1;KIR:KIR00659
KIR:KIR00659 KIR2DL3*01801 326 bases
 GVHRKPSLLA HPGPLVKSEE TVILQCWSDV RFEHFLLHRE GKFKDTLRLI GEHHDGVSKA
 NFSIGPMMQD LAGTYRCYGS VTHSPYQLSA PSDPLDIVIT GLYEKPSLSA QPGPTVLAGE
 SVTLSCSSRS SYDMYHLSRE GEAHERRFSA GPKVNGTFQA DFPLGPATHG GTYRCFGSFR
 DSPYEWSNSS DPLLVSVTGN PSNSWPSPTE PSSKTGNPRH LHVLIGTSVV IILFVLLLFF
 LLHRWCSNKK NAVVMDQEPA GNRTVNREDS DEQDPQEVTY AQLNHCVFTQ RKITRPSQRP
 KTPPTDIIVY TELPNAEPRS KVVSCP*   
>P1;KIR:KIR00895
KIR:KIR00895 KIR2DL3*01802 349 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL RLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVIILFVLL LFFLLHRWCS NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE PRSKVVSCP* 
>P1;KIR:KIR00687
KIR:KIR00687 KIR2DL3*019 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYRL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00693
KIR:KIR00693 KIR2DL3*020 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFHDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00697
KIR:KIR00697 KIR2DL3*021 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAAVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00683
KIR:KIR00683 KIR2DL3*022 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWLS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITHPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00703
KIR:KIR00703 KIR2DL3*023 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGI SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00704
KIR:KIR00704 KIR2DL3*024 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKTTRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00733
KIR:KIR00733 KIR2DL3*025 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDIAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00735
KIR:KIR00735 KIR2DL3*026 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKNTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00736
KIR:KIR00736 KIR2DL3*027 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCS NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00737
KIR:KIR00737 KIR2DL3*028 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHHWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00738
KIR:KIR00738 KIR2DL3*029 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHESR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00739
KIR:KIR00739 KIR2DL3*030 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFNDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00740
KIR:KIR00740 KIR2DL3*031 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00741
KIR:KIR00741 KIR2DL3*032 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SLVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00849
KIR:KIR00849 KIR2DL3*033 341 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKYKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITHPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00879
KIR:KIR00879 KIR2DL3*034 341 bases
 MSLMVVSMVC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVRFQHFLL
 HREGKFKDTL HLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NTKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITRPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR00945
KIR:KIR00945 KIR2DL3*035 341 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LQAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL RLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITHPS QRPKTPPTDI IVYTELPNAE P* 
>P1;KIR:KIR01116
KIR:KIR01116 KIR2DL3*036 341 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LRAHPGPLVK SEETVILQCW SDVRFEHFLL
 HREGKFKDTL RLIGEHHDGV SKANFSIGPM MQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS NSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVIILFILL LFFLLHRWCC NKKNAVVMDQ EPAGNRTVNR EDSDEQDPQE
 VTYAQLNHCV FTQRKITHPS QRPKTPPTDI IVYTELPNAE P* 
