>P1;KIR:KIR00029
KIR:KIR00029 KIR2DL5A*0010101 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00300
KIR:KIR00300 KIR2DL5A*0010102 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00439
KIR:KIR00439 KIR2DL5A*0010103 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00259
KIR:KIR00259 KIR2DL5A*00102 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00260
KIR:KIR00260 KIR2DL5A*00103 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00262
KIR:KIR00262 KIR2DL5A*00104 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00263
KIR:KIR00263 KIR2DL5A*00105 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00095
KIR:KIR00095 KIR2DL5A*0050101 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00249
KIR:KIR00249 KIR2DL5A*0050102 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00438
KIR:KIR00438 KIR2DL5A*0050103 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00440
KIR:KIR00440 KIR2DL5A*0050104 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00391
KIR:KIR00391 KIR2DL5A*01201 375 bases
 MSLMVISMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00389
KIR:KIR00389 KIR2DL5A*01202 375 bases
 MSLMVISMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00536
KIR:KIR00536 KIR2DL5A*014 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHRGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00537
KIR:KIR00537 KIR2DL5A*015 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVCTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00882
KIR:KIR00882 KIR2DL5A*021 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAQKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00907
KIR:KIR00907 KIR2DL5A*022 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRSSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00030
KIR:KIR00030 KIR2DL5B*0020101 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00248
KIR:KIR00248 KIR2DL5B*0020102 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00301
KIR:KIR00301 KIR2DL5B*0020103 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00394
KIR:KIR00394 KIR2DL5B*0020104 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00441
KIR:KIR00441 KIR2DL5B*0020105 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00524
KIR:KIR00524 KIR2DL5B*0020106 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00632
KIR:KIR00632 KIR2DL5B*0020107 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00535
KIR:KIR00535 KIR2DL5B*00202 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00802
KIR:KIR00802 KIR2DL5B*00203 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00031
KIR:KIR00031 KIR2DL5B*003 375 bases
 MSLMVVSMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIMVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00032
KIR:KIR00032 KIR2DL5B*004 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSTVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00125
KIR:KIR00125 KIR2DL5B*00601 375 bases
 MSLMVVSMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00267
KIR:KIR00267 KIR2DL5B*00602 375 bases
 MSLMVVSMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00393
KIR:KIR00393 KIR2DL5B*00603 375 bases
 MSLMVVSMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00126
KIR:KIR00126 KIR2DL5B*0070101 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIMVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00525
KIR:KIR00525 KIR2DL5B*0070102 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIMVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00244
KIR:KIR00244 KIR2DL5B*0080101 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00395
KIR:KIR00395 KIR2DL5B*0080102 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00266
KIR:KIR00266 KIR2DL5B*00802 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00682
KIR:KIR00682 KIR2DL5B*00803 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00805
KIR:KIR00805 KIR2DL5B*00804 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00245
KIR:KIR00245 KIR2DL5B*009 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGILRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00264
KIR:KIR00264 KIR2DL5B*010 375 bases
 MSLMVVSMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00265
KIR:KIR00265 KIR2DL5B*011 375 bases
 MSLMVVSMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCIFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00390
KIR:KIR00390 KIR2DL5B*01301 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVCTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00392
KIR:KIR00392 KIR2DL5B*01302 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVCTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00534
KIR:KIR00534 KIR2DL5B*01303 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVCTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00801
KIR:KIR00801 KIR2DL5B*01304 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVCTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00538
KIR:KIR00538 KIR2DL5B*016 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSYP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00664
KIR:KIR00664 KIR2DL5B*017 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKNNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00684
KIR:KIR00684 KIR2DL5B*018 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVH RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCWGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00803
KIR:KIR00803 KIR2DL5B*019 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVCTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKNNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI*    
>P1;KIR:KIR00804
KIR:KIR00804 KIR2DL5B*020 303 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDH*     
