>DL;IPD:KIR00045
KIR:KIR00045 KIR2DS4*0010101 915 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG TGCGCAGCAT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACGCTCCCTA CGAGTGGTCA AACTCGAGTG ATCCACTGCT TGTTTCCGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00092
KIR:KIR00092 KIR2DS4*0010102 915 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG TGCGCAGCAT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACGCTCCCTA CGAGTGGTCA AACTCGAGTG ATCCACTGCT TGTTTCCGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00099
KIR:KIR00099 KIR2DS4*0010103 915 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG TGCGCAGCAT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACGCTCCCTA CGAGTGGTCA AACTCGAGTG ATCCACTGCT TGTTTCCGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00452
KIR:KIR00452 KIR2DS4*0010104 915 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG TGCGCAGCAT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACGCTCCCTA CGAGTGGTCA AACTCGAGTG ATCCACTGCT TGTTTCCGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00453
KIR:KIR00453 KIR2DS4*0010105 915 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG TGCGCAGCAT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACGCTCCCTA CGAGTGGTCA AACTCGAGTG ATCCACTGCT TGTTTCCGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00496
KIR:KIR00496 KIR2DS4*0010106 915 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG TGCGCAGCAT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACGCTCCCTA CGAGTGGTCA AACTCGAGTG ATCCACTGCT TGTTTCCGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00499
KIR:KIR00499 KIR2DS4*0010107 915 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG TGCGCAGCAT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACGCTCCCTA CGAGTGGTCA AACTCGAGTG ATCCACTGCT TGTTTCCGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00498
KIR:KIR00498 KIR2DS4*0010108 915 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG TGCGCAGCAT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACGCTCCCTA CGAGTGGTCA AACTCGAGTG ATCCACTGCT TGTTTCCGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00497
KIR:KIR00497 KIR2DS4*0010109 915 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG TGCGCAGCAT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACGCTCCCTA CGAGTGGTCA AACTCGAGTG ATCCACTGCT TGTTTCCGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00046
KIR:KIR00046 KIR2DS4*00102 915 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG TGCGCAGCAT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACGCTCCCTA CGAGTGGTCA AACTCGAGTG ATCCACTGCT TGTTTCCGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00274
KIR:KIR00274 KIR2DS4*00103 872 bases
 CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG CCACAGGAGG GAGTCCACAG
 AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA TCAGAAGAGA CAGTCATCCT
 GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG CACAGAGAGG GGAAGTTTAA
 CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT TCCAAGGCCA ACTTCTCCAT
 TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC TACGGTTCTG TTCCTCACTC
 CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG GTGATCATAG GTCTATATGA
 GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG GCAGGAGAGA ATGTGACCTT
 GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA TCCAGGGAAG GGGAGGCCCA
 TGAACGTAGG CTCCCTGCAG TGCGCAGCAT CAACGGAACA TTCCAGGCTG ACTTTCCTCT
 GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC TCTTTCCGTG ACGCTCCCTA
 CGAGTGGTCA AACTCGAGTG ATCCACTGCT TGTTTCCGTC ACAGGAAACC CTTCAAATAG
 TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC CCCAGACACC TACATGTTCT
 GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC CTCTTCTTTC TCCTTCATCG
 CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA GAGCCTGCAG GGAACAGAAC
 AGTGAACAGC GAGGATTCTG ATGAACAAGA CC*  
>DL;IPD:KIR00327
KIR:KIR00327 KIR2DS4*00104 881 bases
 GGTTCTTCTT GCTGCAGGGG GCCTGGCCAC AGGAGGGAGT CCACAGAAAA CCTTCCTTCC
 TGGCCCTCCC AGGTCACCTG GTGAAATCAG AAGAGACAGT CATCCTGCAA TGTTGGTCGG
 ATGTCATGTT TGAGCACTTC CTTCTGCACA GAGAGGGGAA GTTTAACAAC ACTTTGCACC
 TCATTGGAGA GCACCATGAT GGGGTTTCCA AGGCCAACTT CTCCATTGGT CCCATGATGC
 CTGTCCTTGC AGGAACCTAC AGATGCTACG GTTCTGTTCC TCACTCCCCC TATCAGTTGT
 CAGCTCCCAG TGACCCTCTG GACATGGTGA TCATAGGTCT ATATGAGAAA CCTTCTCTCT
 CAGCCCAGCC GGGCCCCACG GTTCAGGCAG GAGAGAATGT GACCTTGTCC TGCAGCTCCC
 GGAGCTCCTA TGACATGTAC CATCTATCCA GGGAAGGGGA GGCCCATGAA CGTAGGCTCC
 CTGCAGTGCG CAGCATCAAC GGAACATTCC AGGCCGACTT TCCTCTGGGC CCTGCCACCC
 ACGGAGGGAC CTACAGATGC TTCGGCTCTT TCCGTGACGC TCCCTACGAG TGGTCAAACT
 CGAGTGATCC ACTGCTTGTT TCCGTCACAG GAAACCCTTC AAATAGTTGG CCTTCACCCA
 CTGAACCAAG CTCCAAAACC GGTAACCCCA GACACCTACA TGTTCTGATT GGGACCTCAG
 TGGTCAAAAT CCCTTTCACC ATCCTCCTCT TCTTTCTCCT TCATCGCTGG TGCTCCGACA
 AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA CAGAACAGTG AACAGCGAGG
 ATTCTGATGA ACAAGACCAT CAGGAGGTAT CATACGCATA A* 
>DL;IPD:KIR00820
KIR:KIR00820 KIR2DS4*00105 915 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG TGCGCAGCAT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACGCTCCCTA CGAGTGGTCA AACTCGAGTG ATCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00947
KIR:KIR00947 KIR2DS4*00106 915 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTGTCAGCGC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG TGCGCAGCAT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACGCTCCCTA CGAGTGGTCA AACTCGAGTG ATCCACTGCT TGTTTCCGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00048
KIR:KIR00048 KIR2DS4*0030101 893 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCATCTATC CAGGGAAGGG GAGGCCCATG
 AACGTAGGCT CCCTGCAGTG CGCAGCATCA ACGGAACATT CCAGGCCGAC TTTCCTCTGG
 GCCCTGCCAC CCACGGAGGG ACCTACAGAT GCTTCGGCTC TTTCCGTGAC GCTCCCTACG
 AGTGGTCAAA CTCGAGTGAT CCACTGCTTG TTTCCGTCAC AGGAAACCCT TCAAATAGTT
 GGCCTTCACC CACTGAACCA AGCTCCAAAA CCGGTAACCC CAGACACCTA CATGTTCTGA
 TTGGGACCTC AGTGGTCAAA ATCCCTTTCA CCATCCTCCT CTTCTTTCTC CTTCATCGCT
 GGTGCTCCGA CAAAAAAAAT GCTGCTGTAA TGGACCAAGA GCCTGCAGGG AACAGAACAG
 TGAACAGCGA GGATTCTGAT GAACAAGACC ATCAGGAGGT GTCATACGCA TAA*
>DL;IPD:KIR00318
KIR:KIR00318 KIR2DS4*0030102 893 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCATCTATC CAGGGAAGGG GAGGCCCATG
 AACGTAGGCT CCCTGCAGTG CGCAGCATCA ACGGAACATT CCAGGCCGAC TTTCCTCTGG
 GCCCTGCCAC CCACGGAGGG ACCTACAGAT GCTTCGGCTC TTTCCGTGAC GCTCCCTACG
 AGTGGTCAAA CTCGAGTGAT CCACTGCTTG TTTCCGTCAC AGGAAACCCT TCAAATAGTT
 GGCCTTCACC CACTGAACCA AGCTCCAAAA CCGGTAACCC CAGACACCTA CATGTTCTGA
 TTGGGACCTC AGTGGTCAAA ATCCCTTTCA CCATCCTCCT CTTCTTTCTC CTTCATCGCT
 GGTGCTCCGA CAAAAAAAAT GCTGCTGTAA TGGACCAAGA GCCTGCAGGG AACAGAACAG
 TGAACAGCGA GGATTCTGAT GAACAAGACC ATCAGGAGGT GTCATACGCA TAA*
>DL;IPD:KIR00430
KIR:KIR00430 KIR2DS4*0030103 893 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCATCTATC CAGGGAAGGG GAGGCCCATG
 AACGTAGGCT CCCTGCAGTG CGCAGCATCA ACGGAACATT CCAGGCCGAC TTTCCTCTGG
 GCCCTGCCAC CCACGGAGGG ACCTACAGAT GCTTCGGCTC TTTCCGTGAC GCTCCCTACG
 AGTGGTCAAA CTCGAGTGAT CCACTGCTTG TTTCCGTCAC AGGAAACCCT TCAAATAGTT
 GGCCTTCACC CACTGAACCA AGCTCCAAAA CCGGTAACCC CAGACACCTA CATGTTCTGA
 TTGGGACCTC AGTGGTCAAA ATCCCTTTCA CCATCCTCCT CTTCTTTCTC CTTCATCGCT
 GGTGCTCCGA CAAAAAAAAT GCTGCTGTAA TGGACCAAGA GCCTGCAGGG AACAGAACAG
 TGAACAGCGA GGATTCTGAT GAACAAGACC ATCAGGAGGT GTCATACGCA TAA*
>DL;IPD:KIR00431
KIR:KIR00431 KIR2DS4*0030104 893 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCATCTATC CAGGGAAGGG GAGGCCCATG
 AACGTAGGCT CCCTGCAGTG CGCAGCATCA ACGGAACATT CCAGGCCGAC TTTCCTCTGG
 GCCCTGCCAC CCACGGAGGG ACCTACAGAT GCTTCGGCTC TTTCCGTGAC GCTCCCTACG
 AGTGGTCAAA CTCGAGTGAT CCACTGCTTG TTTCCGTCAC AGGAAACCCT TCAAATAGTT
 GGCCTTCACC CACTGAACCA AGCTCCAAAA CCGGTAACCC CAGACACCTA CATGTTCTGA
 TTGGGACCTC AGTGGTCAAA ATCCCTTTCA CCATCCTCCT CTTCTTTCTC CTTCATCGCT
 GGTGCTCCGA CAAAAAAAAT GCTGCTGTAA TGGACCAAGA GCCTGCAGGG AACAGAACAG
 TGAACAGCGA GGATTCTGAT GAACAAGACC ATCAGGAGGT GTCATACGCA TAA*
>DL;IPD:KIR00089
KIR:KIR00089 KIR2DS4*0040101 893 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACAGTTCTG TTCCTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGTCCTT GTCCTGCAGC TCCATCTATC CAGGGAGGGG GAGGCCCATG
 AACGTAGGCT CCCTGCAGTG CGCAGCATCC ACGGAACATT CCAGGCCGAC TTTCCTCTGG
 GCCCTGCCAC CCACGGAGGG ACCTACAGAT GCTTCGGCTC TTTCCGTGAC GCTCCCTACG
 AGTGGTCAAA CTCGAGTGAT CCACTGCTTG TTTCCGTCAC AGGAAACCCT TCAAATAGTT
 GGCCTTCACC CACTGAACCA AGCTCCAAAA CCGGTAACCC CAGACACCTA CATGTTCTGA
 TTGGGACCTC AGTGGTCAAA ATCCCTTTCA CCATCCTCCT CTTCTTTCTC CTTCATCGCT
 GGTGCTCCGA CAAAAAAAAT GCTGCTGTAA TGGACCAAGA GCCTGCAGGG AACAGAACAG
 TGAACAGCGA GGATTCTGAT GAACAAGACC ATCAGGAGGT GTCATACGCA TAA*
>DL;IPD:KIR00637
KIR:KIR00637 KIR2DS4*0040102 893 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACAGTTCTG TTCCTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGTCCTT GTCCTGCAGC TCCATCTATC CAGGGAGGGG GAGGCCCATG
 AACGTAGGCT CCCTGCAGTG CGCAGCATCC ACGGAACATT CCAGGCCGAC TTTCCTCTGG
 GCCCTGCCAC CCACGGAGGG ACCTACAGAT GCTTCGGCTC TTTCCGTGAC GCTCCCTACG
 AGTGGTCAAA CTCGAGTGAT CCACTGCTTG TTTCCGTCAC AGGAAACCCT TCAAATAGTT
 GGCCTTCACC CACTGAACCA AGCTCCAAAA CCGGTAACCC CAGACACCTA CATGTTCTGA
 TTGGGACCTC AGTGGTCAAA ATCCCTTTCA CCATCCTCCT CTTCTTTCTC CTTCATCGCT
 GGTGCTCCGA CAAAAAAAAT GCTGCTGTAA TGGACCAAGA GCCTGCAGGG AACAGAACAG
 TGAACAGCGA GGATTCTGAT GAACAAGACC ATCAGGAGGT GTCATACGCA TAA*
>DL;IPD:KIR00090
KIR:KIR00090 KIR2DS4*0060101 893 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCATCTATC CAGGGAGGGG GAGGCCCATG
 AACGTAGGCT CCCTGCAGTG CGCAGCATCA ACGGAACATT CCAGGCCGAC TTTCCTCTGG
 GCCCTGCCAC CCACGGAGGG ACCTACAGAT GCTTCGGCTC TTTCCGTGAC GCTCCCTACG
 AGTGGTCAAA CTCGAGTGAT CCACTGCTTG TTTCCGTCAC AGGAAACCCT TCAAATAGTT
 GGCCTTCACC CACTGAACCA AGCTCCAAAA CCGGTAACCC CAGACACCTA CATGTTCTGA
 TTGGGACCTC AGTGGTCAAA ATCCCTTTCA CCATCCTCCT CTTCTTTCTC CTTCATCGCT
 GGTGCTCCGA CAAAAAAAAT GCTGCTGTAA TGGACCAAGA GCCTGCAGGG AACAGAACAG
 TGAACAGCGA GGATTCTGAT GAACAAGACC ATCAGGAGGT GTCATACGCA TAA*
>DL;IPD:KIR00651
KIR:KIR00651 KIR2DS4*0060102 893 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCATCTATC CAGGGAGGGG GAGGCCCATG
 AACGTAGGCT CCCTGCAGTG CGCAGCATCA ACGGAACATT CCAGGCCGAC TTTCCTCTGG
 GCCCTGCCAC CCACGGAGGG ACCTACAGAT GCTTCGGCTC TTTCCGTGAC GCTCCCTACG
 AGTGGTCAAA CTCGAGTGAT CCACTGCTTG TTTCCGTCAC AGGAAACCCT TCAAATAGTT
 GGCCTTCACC CACTGAACCA AGCTCCAAAA CCGGTAACCC CAGACACCTA CATGTTCTGA
 TTGGGACCTC AGTGGTCAAA ATCCCTTTCA CCATCCTCCT CTTCTTTCTC CTTCATCGCT
 GGTGCTCCGA CAAAAAAAAT GCTGCTGTAA TGGACCAAGA GCCTGCAGGG AACAGAACAG
 TGAACAGCGA GGATTCTGAT GAACAAGACC ATCAGGAGGT GTCATACGCA TAA*
>DL;IPD:KIR00132
KIR:KIR00132 KIR2DS4*007 854 bases
 TCATCATGGC GTGTGTTGGG TTCTTCTTGC TGCAGGGGGC CTGGCCACAG GAGGGAGTCC
 ACAGAAAACC TTCCTTCCTG GCCCTCCCAG GTCACCTGGT GAAATCAGAA GAGACAGTCA
 TCCTGCAATG TTGGTCGGAT GTCATGTTTG AGCACTTCCT TCTGCACAGA GAGGGGAAGT
 TTAACAACAC TTTGCACCTC ATTGGAGAGC ACCATGATGG GGTTTCCAAG GCCAACTTCT
 CCATTGGTCC CATGATGCCT GTCCTTGCAG GAACCTACAG ATGCTACGGT TCTGTTACTC
 ACTCCCCCTA TCAGTTGTCA GCTCCCAGTG ACCCTCTGGA CATGGTGATC ATAGGTCTAT
 ATGAGAAACC TTCTCTCTCA GCCCAGCCGG GCCCCACGGT TCAGGCAGGA GAGAATGTGA
 CCTTGTCCTG CAGCTCCATC TATCCAGGGA AGGGGAGGCC CATGAACGTA GGCTCCCTGC
 AGTGCGCAGC ATCAACGGAA CATTCCAGGC CGACTTTCCT CTGGGCCCTG CCACCCACGG
 AGGGACCTAC AGATGCTTCG GCTCTTTCCG TGACGCTCCC TACGAGTGGT CAAACTCGAG
 TGATCCACTG CTTGTTTCCG TCACAGGAAA CCCTTCAAAT AGTTGGCCTT CACCCACTGA
 ACCAAGCTCC AAAACCGGTA ACCCCAGACA CCTACATGTT CTGATTGGGA CCTCAGTGGT
 CAAAATCCCT TTCACCATCC TCCTCTTCTT TCTCCTTCAT CGCTGGTGCT CCGACAAAAA
 AAATGCTGCT GTAATGGACC AAGAGCCTGC AGGGAACAGA ACAGTGAACA GCGAGGATTC
 TGATGAACAA GACC*    
>DL;IPD:KIR00258
KIR:KIR00258 KIR2DS4*008 850 bases
 CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG CCACAGGAGG GAGTCCACAG
 AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA TCAGAAGAGA CAGTCATCCT
 GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG CACAGAGAGG GGAAGTTTGA
 CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT TCCAAGGCCA ACTTCTCCAT
 TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC TACGGTTCTG TTCCTCACTC
 CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG GTGATCATAG GTCTATATGA
 GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG GCAGGAGAGA ATGTGACCTT
 GTCCTGCAGC TCCATCTATC CAGGGAAGGG GAGGCCCATG AACGTAGGCT CCCTGCAGTG
 CGCAGCATCA ACGGAACATT CCAGGCCGAC TTTCCTCTGG GCCCTGCCAC CCACGGAGGG
 ACCTACAGAT GCTTCGGCTC TTTCCGTGAC GCTCCCTACG AGTGGTCAAA CTCGAGTGAT
 CCACTGCTTG TTTCCGTCAC AGGAAACCCT TCAAATAGTT GGCCTTCACC CACTGAACCA
 AGCTCCAAAA CCGGTAACCC CAGACACCTA CATGTTCTGA TTGGGACCTC AGTGGTCAAA
 ATCCCTTTCA CCATCCTCCT CTTCTTTCTC CTTCATCGCT GGTGCTCCGA CAAAAAAAAT
 GCTGCTGTAA TGGACCAAGA GCCTGCAGGG AACAGAACAG TGAACAGCGA GGATTCTGAT
 GAACAAGACC *    
>DL;IPD:KIR00275
KIR:KIR00275 KIR2DS4*009 850 bases
 CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG CCACAGGAGG GAGTCCACAG
 AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA TCAGAAGAGA CAGTCATCCT
 GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG CACAGAGAGG GGAAGTTTAA
 CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT TCCAAGGCCA ACTTCTCCAT
 TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC TACGGTTCTG TTCCTCACTC
 CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG GTGATCATAG GTCTATATGA
 GAAACCTTCT CTCTCAGCAC AGCCGGGCCC CACGGTTCAG GCAGGAGAGA ATGTGACCTT
 GTCCTGCAGC TCCATCTATC CAGGGAAGGG GAGGCCCATG AACGTAGGCT CCCTGCAGTG
 CGCAGCATCA ACGGAACATT CCAGGCCGAC TTTCTTCTGG GCCCTGCCAC CCACGGAGGG
 ACCTACAGAT GCTTTGGCTC TTTCCGTGAC GCTCCCTACG AGTGGTCAAA CTCGAGTGAT
 CCACTGCTTG TTTCCGTCAC AGGAAACCCT TCAAATAGTT GGCCTTCACC CACTGAACCA
 AGCTCCAAAA CCGGTAACCC CAGACACCTA CATGTTCTGA TTGGGACCTC AGTGGTCAAA
 ATCCCTTTCA CCATCCTCCT CTTCTTTCTC CTTCATCGCT GGTGCTCCGA CAAAAAAAAT
 GCTGCTGTAA TGGACCAAGA GCCTGCAGGG AACAGAACAG TGAACAGCGA GGATTCTGAT
 GAACAAGACC *    
>DL;IPD:KIR00315
KIR:KIR00315 KIR2DS4*010 893 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG AAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCATCTATC CAGGGAAGGG GAGGCCCATG
 AACGTAGGCT CCCTGCAGTG CGCAGCATCA ACGGAACATT CCAGGCCGAC TTTCCTCTGG
 GCCCTGCCAC CCACGGAGGG ACCTACAGAT GCTTCGGCTC TTTCCGTGAC GCTCCCTACG
 AGTGGTCAAA CTCGAGTGAT CCACTGCTTG TTTCCGTCAC AGGAAACCCT TCAAATAGTT
 GGCCTTCACC CACTGAACCA AGCTCCAAAA CCGGTAACCC CAGACACCTA CATGTTCTGA
 TTGGGACCTC AGTGGTCAAA ATCCCTTTCA CCATCCTCCT CTTCTTTCTC CTTCATCGCT
 GGTGCTCCGA CAAAAAAAAT GCTGCTGTAA TGGACCAAGA GCCTGCAGGG AACAGAACAG
 TGAACAGCGA GGATTCTGAT GAACAAGACC ATCAGGAGGT GTCATACGCA TAA*
>DL;IPD:KIR00320
KIR:KIR00320 KIR2DS4*01101 872 bases
 CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG CCACAGGAGG GAGTCCACAG
 AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA TCAGAAGAGA CAGTCATCCT
 GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG CACAGAGAGG GGAAGTTTAA
 CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT TCCAAGGCCA ACTTCTCCAT
 TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC TACGGTTCTG TTCCTCACTC
 CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG GTGATCATAG GTCTATATGA
 GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG GCAGGAGAGA ATGTGACCTT
 GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA TCCAGGGAAG GGGAGGCCCA
 TGAACGTAGG CTCCCTGCAG TGCGCAGCAT CAACGGAACA TTCCAGGCCG ACTTTCCTCT
 GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC TCTTTCCGTG ACGCTCCCTA
 CGAGTGGTCA AACTCGAGTG ATCCACTGCT TGTTTCCGTC ACAGGAAACC CTTCAAATAG
 TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC CCCAGACACC TACATGTTCT
 GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC CTCTTCTTTC TCCTTCATCG
 CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA GAGCCTGCAG GGAACAGAAC
 AGTGAACAGC GAGGATTCTG ATGAACAAGA CC*  
>DL;IPD:KIR00341
KIR:KIR00341 KIR2DS4*01102 915 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG TGCGCAGCAT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACGCTCCCTA CGAGTGGTCA AACTCGAGTG ATCCACTGCT TGTTTCCGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00323
KIR:KIR00323 KIR2DS4*012 850 bases
 CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG CCACAGGAGG GAGTCCACAG
 AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA TCAGAAGAGA CAGTCATCCT
 GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG CACAGAGAGG GGAAGTTTAA
 CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT TCCAAGGCCA ACTTCTCCAT
 TGGTCCCATG ATGCCTGTCC TTGAAGGAAC CTACAGATGC TACGGTTCTG TTCCTCACTC
 CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG GTGATCATAG GTCTATATGA
 GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG GCAGGAGAGA ATGTGACCTT
 GTCCTGCAGC TCCATCTATC CAGGGAGGGG GAGGCCCATG AACGTAGGCT CCCTGCAGTG
 CGCAGCATCA ACGGAACATT CCAGGCCGAC TTTCCTCTGG GCCCTGCCAC CCACGGAGGG
 ACCTACAGAT GCTTCGGCTC TTTCCGTGAC GCTCCCTACG AGTGGTCAAA CTCGAGTGAT
 CCACTGCTTG TTTCCGTCAC AGGAAACCCT TCAAATAGTT GGCCTTCACC CACTGAACCA
 AGCTCCAAAA CCGGTAACCC CAGACACCTA CATGTTCTGA TTGGGACCTC AGTGGTCAAA
 ATCCCTTTCA CCATCCTCCT CTTCTTTCTC CTTCATCGCT GGTGCTCCGA CAAAAAAAAT
 GCTGCTGTAA TGGACCAAGA GCCTGCAGGG AACAGAACAG TGAACAGCGA GGATTCTGAT
 GAACAAGACC *    
>DL;IPD:KIR00338
KIR:KIR00338 KIR2DS4*013 850 bases
 CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG CCACAGGAGG GAGCCCACAG
 AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA TCAGAAGAGA CAGTCATCCT
 GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG CACAGAGAGG GGAAGTTTAA
 CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT TCCAAGGCCA ACTTCTCCAT
 TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC TACGGTTCTG TTCCTCACTC
 CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG GTGATCATAG GTCTATATGA
 GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG GCAGGAGAGA ATGTGACCTT
 GTCCTGCAGC TCCATCTATC CAGGGAGGGG GAGGCCCATG AACGTAGGCT CCCTGCAGTG
 CGCAGCATCC ACGGAACATT CCAGGCCGAC TTTCCTCTGG GCCCTGCCAC CCACGGAGGG
 ACCTACAGAT GCTTCGGCTC TTTCCGTGAC GCTCCCTACA AGTGGTCAAA CTCGAGTGAT
 CCACTGCTTG TTTCCGTCAC AGGAAACCCT TCAAATAGTT GGCCTTCACC CACTGAACCA
 AGCTCCAAAA CCGGTAACCC CAGACACCTA CATGTTCTGA TTGGGACCTC AGTGGTCAAA
 ATCCCTTTCA CCATCCTCCT CTTCTTTCTC CTTCATCGCT GGTGCTGCAA CAAAAAAAAT
 GCTGCTGTAA TGGACCAAGA GCCTGCAGGG AACAGAACAG TGAACAGCGA GGATTCTGAT
 GAACAAGACC *    
>DL;IPD:KIR00340
KIR:KIR00340 KIR2DS4*014 881 bases
 GGTTCTTCTT GCTGCAGGGG GCCTGGCCAC AGGAGGGAGT CCACAGAAAA CCTTCCTTCC
 TGGCCCTCCC AGGTCACCTG GTGAAATCAG AAGAGACAGT CATCCTGCAA TGTTGGTCGG
 ATGTCATGTT TGAGCACTTC CTTCTGCACA GAGAGGGGAA GTTTAACAAC ACTTTGCACC
 TCATTGGAGA GCACCATGAT GGGGTTTCCA AGGCCAACTT CTCCATTGGT CCCATGATGC
 CTGTCCTTGC AGGAACCTAC AGATGCTACG GTTCTGTTAC TCACTCCCCC TATCAGTTGT
 CAGCTCCCAG TGACCCTCTG GACATGGTGA TCATAGGTCT ATATGAGAAA CCTTCTCTCT
 CAGCCCAGCC GGGCCCCACG GTTCAGGCAG GAGAGAATGT GACCTTGTCC TGCAGCTCCC
 GGAGCTCCTA TGACATGTAC CATCTATCCA GGGAAGGGGA GGCCCATGAA CGTAGGCTCC
 CTGCAGTGCG CAGCATCAAC GGAACATTCC AGGCCGACTT TCCTCTGGGC CCTGCCACCC
 ACGGAGGGAC CTACAGATGC TTCGGCTCTT TCCGTGACGC TCCCTACGAG TGGTCAAACT
 CGAGTGATCC ACTGCTTGTT TCCGTCACAG GAAACCCTTC AAATAGTTGG CCTTCACCCA
 CTGAACCAAG CTCCAAAACC GGTAACCCCA GACACCTACA TGTTCTGATT GGGACCTCAG
 TGGTCAAAAT CCCTTTCACC ATCCTCCTCT TCTTTCTCCT TCATCGCTGG TGCTCCGACA
 AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA CAGAACAGTG AACAGCGAGG
 ATTCTGATGA ACAAGACCAT CAGGAGGTGT CATACGCATA A* 
>DL;IPD:KIR00342
KIR:KIR00342 KIR2DS4*015 895 bases
 CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG CCACAGGAGG GAGTCCACAG
 AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA TCAGAAGAGA CAGTCATCCT
 GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG CACAGAGAGG GGAAGTTTAA
 CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT TCCAAGGCCA ACTTCTCCAT
 TGGTCCCATG ATGCCTGTCC TTTCAGGAAC CTACAGATGC TACGGTTCTG TTCCTCACTC
 CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG GTGATCATAG GTCTATATGA
 GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG GCAGGAGAGA ATGTGACCTT
 GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA TCCAGGGAAG GGGAGGCCCA
 TGAACGTAGG CTCCCTGCAG TGCGCAGCAT CAACGGAACA TTCCAGGCCG ACTTTCCTCT
 GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC TCTTTCCGTG ACGCTCCCTA
 CGAGTGGTCA AACTCGAGTG ATCCACTGCT TGTTTCCGTC ACAGGAAACC CTTCAAATAG
 TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC CCCAGACACC TACATGTTCT
 GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC CTCTTCTTTC TCCTTCATCG
 CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA GAGCCTGCAG GGAACAGAAC
 AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG GTGTCATACG CATAA*
>DL;IPD:KIR00731
KIR:KIR00731 KIR2DS4*016 915 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG AAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG TGCGCAGCAT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACGCTCCCTA CGAGTGGTCA AACTCGAGTG ATCCACTGCT TGTTTCCGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00819
KIR:KIR00819 KIR2DS4*017 915 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG TGCGCAGCAT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACGCTCCCTA CGAGTGGTCA AACTCGAGTG ATCCACTGCT TGTTTCCGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTGCAA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00821
KIR:KIR00821 KIR2DS4*018 893 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG AAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTACTGACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCATCTATC CAGGGAAGGG GAGGCCCATG
 AACGTAGGCT CCCTGCAGTG CGCAGCATCA ACGGAACATT CCAGGCCGAC TTTCCTCTGG
 GCCCTGCCAC CCACGGAGGG ACCTACAGAT GCTTCGGCTC TTTCCGTGAC GCTCCCTACG
 AGTGGTCAAA CTCGAGTGAT CCACTGCTTG TTTCCGTCAC AGGAAACCCT TCAAATAGTT
 GGCCTTCACC CACTGAACCA AGCTCCAAAA CCGGTAACCC CAGACACCTA CATGTTCTGA
 TTGGGACCTC AGTGGTCAAA ATCCCTTTCA CCATCCTCCT CTTCTTTCTC CTTCATCGCT
 GGTGCTCCGA CAAAAAAAAT GCTGCTGTAA TGGACCAAGA GCCTGCAGGG AACAGAACAG
 TGAACAGCGA GGATTCTGAT GAACAAGACC ATCAGGAGGT GTCATACGCA TAA*
>DL;IPD:KIR00995
KIR:KIR00995 KIR2DS4*019 915 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCACTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGA TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG TGCGCAGCAT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACGCTCCCTA CGAGTGGTCA AACTCGAGTG ATCCACTGCT TGTTTCCGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00996
KIR:KIR00996 KIR2DS4*020 915 bases
 ATGTCGCTCA TGGTCATCAT CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACAGGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC TCCCAGGTCA CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCGGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTTTAA CAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCCTGTCC TTGCAGGAAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATG
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCAG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG TGCGCAGCAT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACGCTCCCTA CGAGTGGTCA AACTCGAGTG ATCCACTGCT TGTTTCCGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAAC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
