>P1;KIR:KIR00029
KIR:KIR00029 KIR2DL5A*0010101 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00300
KIR:KIR00300 KIR2DL5A*0010102 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00439
KIR:KIR00439 KIR2DL5A*0010103 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01039
KIR:KIR01039 KIR2DL5A*0010104 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01041
KIR:KIR01041 KIR2DL5A*0010105 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01217
KIR:KIR01217 KIR2DL5A*0010106 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00259
KIR:KIR00259 KIR2DL5A*00102 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00260
KIR:KIR00260 KIR2DL5A*00103 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00262
KIR:KIR00262 KIR2DL5A*00104 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00263
KIR:KIR00263 KIR2DL5A*00105 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01201
KIR:KIR01201 KIR2DL5A*00106 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01214
KIR:KIR01214 KIR2DL5A*00107 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01218
KIR:KIR01218 KIR2DL5A*00108 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01196
KIR:KIR01196 KIR2DL5A*0010901 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01219
KIR:KIR01219 KIR2DL5A*0010902 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00095
KIR:KIR00095 KIR2DL5A*0050101 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00249
KIR:KIR00249 KIR2DL5A*0050102 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00438
KIR:KIR00438 KIR2DL5A*0050103 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00440
KIR:KIR00440 KIR2DL5A*0050104 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01209
KIR:KIR01209 KIR2DL5A*0050105 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00391
KIR:KIR00391 KIR2DL5A*01201 375 bases
 MSLMVISMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00389
KIR:KIR00389 KIR2DL5A*01202 375 bases
 MSLMVISMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00536
KIR:KIR00536 KIR2DL5A*014 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHRGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00537
KIR:KIR00537 KIR2DL5A*015 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVCTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00882
KIR:KIR00882 KIR2DL5A*0210101 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAQKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01221
KIR:KIR01221 KIR2DL5A*0210102 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAQKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01222
KIR:KIR01222 KIR2DL5A*0210103 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAQKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00907
KIR:KIR00907 KIR2DL5A*022 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRSSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00992
KIR:KIR00992 KIR2DL5A*0230101 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVHTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01199
KIR:KIR01199 KIR2DL5A*0230102 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVHTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00993
KIR:KIR00993 KIR2DL5A*024 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTRYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01191
KIR:KIR01191 KIR2DL5A*025 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SINGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01194
KIR:KIR01194 KIR2DL5A*026 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GSTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01195
KIR:KIR01195 KIR2DL5A*027 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKK PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01202
KIR:KIR01202 KIR2DL5A*028 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVSLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01210
KIR:KIR01210 KIR2DL5A*029 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SHLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01213
KIR:KIR01213 KIR2DL5A*030 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREESDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01220
KIR:KIR01220 KIR2DL5A*031 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NSLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01223
KIR:KIR01223 KIR2DL5A*032N 316 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSX    
>P1;KIR:KIR01200
KIR:KIR01200 KIR2DL5A*0330101 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDT LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01212
KIR:KIR01212 KIR2DL5A*0330102 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDT LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01215
KIR:KIR01215 KIR2DL5A*0340101 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTYTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01216
KIR:KIR01216 KIR2DL5A*0340102 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTYTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01588
KIR:KIR01588 KIR2DL5A*040 375 bases
 MSLMVISMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRSSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
