>DL;IPD:KIR00033
KIR:KIR00033 KIR2DS1*001 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00034
KIR:KIR00034 KIR2DS1*0020101 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00298
KIR:KIR00298 KIR2DS1*0020102 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00296
KIR:KIR00296 KIR2DS1*0020103 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00426
KIR:KIR00426 KIR2DS1*0020104 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00427
KIR:KIR00427 KIR2DS1*0020105 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00428
KIR:KIR00428 KIR2DS1*0020106 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00255
KIR:KIR00255 KIR2DS1*00202 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00035
KIR:KIR00035 KIR2DS1*00301 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA CGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00254
KIR:KIR00254 KIR2DS1*00302 914 bases
 TGTCGCTCAT GGTCGTCAGC ATGGCGTGTG TTGGGTTCTT CTTGCTGCAG GGGGCCTGGC
 CACATGAGGG AGTCCACAGA AAACCTTCCC TCCTGGCCCA CCCAGGTCGC CTGGTGAAAT
 CAGAAGAGAC AGTCATCCTG CAATGTTGGT CAGATGTCAT GTTTGAACAC TTCCTTCTGC
 ACAGAGAGGG GATGTTTAAC GACACTTTGC GCCTCATTGG AGAACACCAT GATGGGGTCT
 CCAAGGCCAA CTTCTCCATC AGTCGCATGA AGCAAGACCT GGCAGGGACC TACAGATGCT
 ACGGTTCTGT TACTCACTCC CCCTATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TGATCATAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG
 CAGGAGAGAA TGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAAGG GGAGGCCCAT GAACGTAGGC TCCCTGCAGG GACCAAGGTC AACGGAACAT
 TCCAGGCCAA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG GACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCATAC GAGTGGTCAA AGTCAAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCGAA ACCGGTAACC
 CCAGACACCT ACATGTTCTG ATTGGGACCT CAGTGGTCAA AATCCCTTTC ACCATCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCG ACAAAAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GTGAACAGCG AGGATTCTGA TGAACAAGAC CATCAGGAGG
 TGTCATACGC ATAA*    
>DL;IPD:KIR00036
KIR:KIR00036 KIR2DS1*004 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00252
KIR:KIR00252 KIR2DS1*00501 915 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCA CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00256
KIR:KIR00256 KIR2DS1*00502 915 bases
 ATGTCGCTCT TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00253
KIR:KIR00253 KIR2DS1*006 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATATTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00271
KIR:KIR00271 KIR2DS1*008 915 bases
 ATGTCGCTCA CGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAACA CTTCCTTCTG
 CACAGAGAGG GGATGTTTAA CGACACTTTG CGCCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AAGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG GTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG CTCCCTGCAG GGACCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCATGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
