>DL;KIR:KIR00038
KIR:KIR00038 KIR2DS2*002 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCGGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00039
KIR:KIR00039 KIR2DS2*003 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 TCCAGATACC TGCACGCTCT GATTGGGACC TCAGTGGTCA TCATCCCCTT TGCTATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGTGCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00040
KIR:KIR00040 KIR2DS2*004 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGCTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCACGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00041
KIR:KIR00041 KIR2DS2*005 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00530
KIR:KIR00530 KIR2DS2*007 892 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CC
>DL;KIR:KIR00531
KIR:KIR00531 KIR2DS2*008 892 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CC
>DL;KIR:KIR01264
KIR:KIR01264 KIR2DS2*010 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG GCTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01265
KIR:KIR01265 KIR2DS2*011 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCGGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA CCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01268
KIR:KIR01268 KIR2DS2*012 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTT CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01271
KIR:KIR01271 KIR2DS2*013 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01279
KIR:KIR01279 KIR2DS2*014 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAG
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01281
KIR:KIR01281 KIR2DS2*015 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 TTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01284
KIR:KIR01284 KIR2DS2*016 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAATGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01289
KIR:KIR01289 KIR2DS2*017 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAT AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01298
KIR:KIR01298 KIR2DS2*018 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01301
KIR:KIR01301 KIR2DS2*019 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01609
KIR:KIR01609 KIR2DS2*022 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00097
KIR:KIR00097 KIR2DS2*00102 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00098
KIR:KIR00098 KIR2DS2*00103 891 bases
 TGTCGCTCAT GGTCGTCAGC ATGGCGTGTG TTGGGTTCTT CTTGCTGCAG GGGGCCTGGC
 CACATGAGGG AGTCCACAGA AAACCTTCCC TCCTGGCCCA CCCAGGTCCC CTGGTGAAAT
 CAGAAGAGAC AGTCATCCTG CAATGTTGGT CAGATGTCAG GTTTGAGCAC TTCCTTCTGC
 ACAGAGAGGG GAAGTATAAG GACACTTTGC ACCTCATTGG AGAGCACCAT GATGGGGTCT
 CCAAGGCCAA CTTCTCCATC GGTCCCATGA TGCAAGACCT TGCAGGGACC TACAGATGCT
 ACGGTTCTGT TACTCACTCC CCCTATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTTTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAC GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCCGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAT GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CCAGACACCT GCATGTTCTG ATTGGGACCT CAGTGGTCAA AATCCCTTTC ACCATCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAAAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GTGAACAGCG AGGATTCTGA TGAACAAGAC C
>DL;KIR:KIR00211
KIR:KIR00211 KIR2DS2*00104 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00973
KIR:KIR00973 KIR2DS2*00105 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCACGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01263
KIR:KIR01263 KIR2DS2*00106 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAAGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00337
KIR:KIR00337 KIR2DS2*00601 892 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CC
>DL;KIR:KIR01283
KIR:KIR01283 KIR2DS2*00602 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00037
KIR:KIR00037 KIR2DS2*0010101 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00302
KIR:KIR00302 KIR2DS2*0010102 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00270
KIR:KIR00270 KIR2DS2*0010103 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00336
KIR:KIR00336 KIR2DS2*0010104 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00446
KIR:KIR00446 KIR2DS2*0010105 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00447
KIR:KIR00447 KIR2DS2*0010106 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00448
KIR:KIR00448 KIR2DS2*0010107 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00449
KIR:KIR00449 KIR2DS2*0010108 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00450
KIR:KIR00450 KIR2DS2*0010109 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00451
KIR:KIR00451 KIR2DS2*0010110 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00623
KIR:KIR00623 KIR2DS2*0010111 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00635
KIR:KIR00635 KIR2DS2*0010112 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01266
KIR:KIR01266 KIR2DS2*0010113 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01270
KIR:KIR01270 KIR2DS2*0010114 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01272
KIR:KIR01272 KIR2DS2*0010115 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01273
KIR:KIR01273 KIR2DS2*0010116 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01274
KIR:KIR01274 KIR2DS2*0010117 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01275
KIR:KIR01275 KIR2DS2*0010118 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01276
KIR:KIR01276 KIR2DS2*0010119 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01277
KIR:KIR01277 KIR2DS2*0010120 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01278
KIR:KIR01278 KIR2DS2*0010121 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01280
KIR:KIR01280 KIR2DS2*0010122 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01282
KIR:KIR01282 KIR2DS2*0010123 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01285
KIR:KIR01285 KIR2DS2*0010124 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01286
KIR:KIR01286 KIR2DS2*0010125 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01288
KIR:KIR01288 KIR2DS2*0010126 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01292
KIR:KIR01292 KIR2DS2*0010127 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01293
KIR:KIR01293 KIR2DS2*0010128 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01294
KIR:KIR01294 KIR2DS2*0010129 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01303
KIR:KIR01303 KIR2DS2*0010130 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01291
KIR:KIR01291 KIR2DS2*0010701 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01287
KIR:KIR01287 KIR2DS2*0010702 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR00906
KIR:KIR00906 KIR2DS2*0090101 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTTC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01297
KIR:KIR01297 KIR2DS2*0090102 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTTC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01267
KIR:KIR01267 KIR2DS2*0200101 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCATACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01299
KIR:KIR01299 KIR2DS2*0200102 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCATACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01300
KIR:KIR01300 KIR2DS2*0200103 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCATACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01302
KIR:KIR01302 KIR2DS2*0200104 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCATACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01269
KIR:KIR01269 KIR2DS2*0210101 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATTG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01290
KIR:KIR01290 KIR2DS2*0210102 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATTG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
>DL;KIR:KIR01295
KIR:KIR01295 KIR2DS2*0210103 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATTG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA    
