>P1;KIR:KIR00033
KIR:KIR00033 KIR2DS1*001 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM RQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00034
KIR:KIR00034 KIR2DS1*0020101 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00298
KIR:KIR00298 KIR2DS1*0020102 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00296
KIR:KIR00296 KIR2DS1*0020103 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00426
KIR:KIR00426 KIR2DS1*0020104 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00427
KIR:KIR00427 KIR2DS1*0020105 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00428
KIR:KIR00428 KIR2DS1*0020106 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01251
KIR:KIR01251 KIR2DS1*0020107 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01252
KIR:KIR01252 KIR2DS1*0020108 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01253
KIR:KIR01253 KIR2DS1*0020109 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01254
KIR:KIR01254 KIR2DS1*0020110 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01255
KIR:KIR01255 KIR2DS1*0020111 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01256
KIR:KIR01256 KIR2DS1*0020112 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01257
KIR:KIR01257 KIR2DS1*0020113 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01258
KIR:KIR01258 KIR2DS1*0020114 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01259
KIR:KIR01259 KIR2DS1*0020115 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01260
KIR:KIR01260 KIR2DS1*0020116 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01261
KIR:KIR01261 KIR2DS1*0020117 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01262
KIR:KIR01262 KIR2DS1*0020118 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02341
KIR:KIR02341 KIR2DS1*0020119 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02354
KIR:KIR02354 KIR2DS1*0020120 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02356
KIR:KIR02356 KIR2DS1*0020121 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02350
KIR:KIR02350 KIR2DS1*0020122 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02343
KIR:KIR02343 KIR2DS1*0020123 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02364
KIR:KIR02364 KIR2DS1*0020124 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02358
KIR:KIR02358 KIR2DS1*0020125 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02365
KIR:KIR02365 KIR2DS1*0020126 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02348
KIR:KIR02348 KIR2DS1*0020127 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02362
KIR:KIR02362 KIR2DS1*0020128 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02363
KIR:KIR02363 KIR2DS1*0020129 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02355
KIR:KIR02355 KIR2DS1*0020130 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02359
KIR:KIR02359 KIR2DS1*0020131 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02352
KIR:KIR02352 KIR2DS1*0020132 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02349
KIR:KIR02349 KIR2DS1*0020133 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02340
KIR:KIR02340 KIR2DS1*0020134 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00255
KIR:KIR00255 KIR2DS1*00202 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02357
KIR:KIR02357 KIR2DS1*0020301 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02351
KIR:KIR02351 KIR2DS1*0020302 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00035
KIR:KIR00035 KIR2DS1*00301 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00254
KIR:KIR00254 KIR2DS1*00302 303 bases
 SLMVVSMACV GFFLLQGAWP HEGVHRKPSL LAHPGRLVKS EETVILQCWS DVMFEHFLLH
 REGMFNDTLR LIGEHHDGVS KANFSISRMK QDLAGTYRCY GSVTHSPYQL SAPSDPLDIV
 IIGLYEKPSL SAQPGPTVLA GENVTLSCSS RSSYDMYHLS REGEAHERRL PAGTKVNGTF
 QANFPLGPAT HGGTYRCFGS FRDSPYEWSK SSDPLLVSVT GNPSNSWPSP TEPSSETGNP
 RHLHVLIGTS VVKIPFTILL FFLLHRWCSD KKNAAVMDQE PAGNRTVNSE DSDEQDHQEV
 SYA     
>P1;KIR:KIR00036
KIR:KIR00036 KIR2DS1*004 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00252
KIR:KIR00252 KIR2DS1*00501 304 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00256
KIR:KIR00256 KIR2DS1*00502 304 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00253
KIR:KIR00253 KIR2DS1*006 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00271
KIR:KIR00271 KIR2DS1*008 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR00797
KIR:KIR00797 KIR2DS1*009 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQADFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01572
KIR:KIR01572 KIR2DS1*010 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRV KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01573
KIR:KIR01573 KIR2DS1*011 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01574
KIR:KIR01574 KIR2DS1*0120101 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01575
KIR:KIR01575 KIR2DS1*0120102 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGPLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR01576
KIR:KIR01576 KIR2DS1*013 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM TQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02312
KIR:KIR02312 KIR2DS1*014 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HRERMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02313
KIR:KIR02313 KIR2DS1*01501 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02344
KIR:KIR02344 KIR2DS1*01502 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02322
KIR:KIR02322 KIR2DS1*016 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02345
KIR:KIR02345 KIR2DS1*0170101 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YSSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02346
KIR:KIR02346 KIR2DS1*0170102 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YSSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02353
KIR:KIR02353 KIR2DS1*018 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC CGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02361
KIR:KIR02361 KIR2DS1*019 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEKTVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02360
KIR:KIR02360 KIR2DS1*020 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGHMVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA     
>P1;KIR:KIR02347
KIR:KIR02347 KIR2DS1*0210101 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS KDSDEQDHQE
 VSYA     
>P1;KIR:KIR02342
KIR:KIR02342 KIR2DS1*0210102 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS KDSDEQDHQE
 VSYA     
