>DL;IPD:KIR00037
KIR:KIR00037 KIR2DS2*0010101 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00302
KIR:KIR00302 KIR2DS2*0010102 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00270
KIR:KIR00270 KIR2DS2*0010103 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00336
KIR:KIR00336 KIR2DS2*0010104 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00446
KIR:KIR00446 KIR2DS2*0010105 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00447
KIR:KIR00447 KIR2DS2*0010106 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00448
KIR:KIR00448 KIR2DS2*0010107 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00449
KIR:KIR00449 KIR2DS2*0010108 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00450
KIR:KIR00450 KIR2DS2*0010109 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00451
KIR:KIR00451 KIR2DS2*0010110 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00623
KIR:KIR00623 KIR2DS2*0010111 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00635
KIR:KIR00635 KIR2DS2*0010112 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00097
KIR:KIR00097 KIR2DS2*00102 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00098
KIR:KIR00098 KIR2DS2*00103 891 bases
 TGTCGCTCAT GGTCGTCAGC ATGGCGTGTG TTGGGTTCTT CTTGCTGCAG GGGGCCTGGC
 CACATGAGGG AGTCCACAGA AAACCTTCCC TCCTGGCCCA CCCAGGTCCC CTGGTGAAAT
 CAGAAGAGAC AGTCATCCTG CAATGTTGGT CAGATGTCAG GTTTGAGCAC TTCCTTCTGC
 ACAGAGAGGG GAAGTATAAG GACACTTTGC ACCTCATTGG AGAGCACCAT GATGGGGTCT
 CCAAGGCCAA CTTCTCCATC GGTCCCATGA TGCAAGACCT TGCAGGGACC TACAGATGCT
 ACGGTTCTGT TACTCACTCC CCCTATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG
 TCATCACAGG TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTTTGG
 CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT
 CCAGGGAGGG GGAGGCCCAC GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT
 TCCAGGCCGA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT
 CTTTCCGTGA CTCTCCCTAT GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA
 CAGGAAACCC TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCAAA ACCGGTAACC
 CCAGACACCT GCATGTTCTG ATTGGGACCT CAGTGGTCAA AATCCCTTTC ACCATCCTCC
 TCTTCTTTCT CCTTCATCGC TGGTGCTCCA ACAAAAAAAA TGCTGCTGTA ATGGACCAAG
 AGCCTGCAGG GAACAGAACA GTGAACAGCG AGGATTCTGA TGAACAAGAC C*
>DL;IPD:KIR00211
KIR:KIR00211 KIR2DS2*00104 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00973
KIR:KIR00973 KIR2DS2*00105 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCACGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00038
KIR:KIR00038 KIR2DS2*002 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCGGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00039
KIR:KIR00039 KIR2DS2*003 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 TCCAGATACC TGCACGCTCT GATTGGGACC TCAGTGGTCA TCATCCCCTT TGCTATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGTGCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00040
KIR:KIR00040 KIR2DS2*004 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGCTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCACGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00041
KIR:KIR00041 KIR2DS2*005 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;IPD:KIR00337
KIR:KIR00337 KIR2DS2*006 892 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CC*
>DL;IPD:KIR00530
KIR:KIR00530 KIR2DS2*007 892 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC TTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CC*
>DL;IPD:KIR00531
KIR:KIR00531 KIR2DS2*008 892 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CC*
>DL;IPD:KIR00906
KIR:KIR00906 KIR2DS2*009 915 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTTC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA AAATCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGC GAGGATTCTG ATGAACAAGA CCATCAGGAG
 GTGTCATACG CATAA*    
