>P1;KIR:KIR00030
KIR:KIR00030 KIR2DL5B*0020101 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00248
KIR:KIR00248 KIR2DL5B*0020102 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00301
KIR:KIR00301 KIR2DL5B*0020103 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00394
KIR:KIR00394 KIR2DL5B*0020104 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00524
KIR:KIR00524 KIR2DL5B*0020106 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00632
KIR:KIR00632 KIR2DL5B*0020107 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01095
KIR:KIR01095 KIR2DL5B*0020108 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01197
KIR:KIR01197 KIR2DL5B*0020109 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01198
KIR:KIR01198 KIR2DL5B*0020110 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01204
KIR:KIR01204 KIR2DL5B*0020111 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00535
KIR:KIR00535 KIR2DL5B*0020201 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00972
KIR:KIR00972 KIR2DL5B*0020202 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00802
KIR:KIR00802 KIR2DL5B*00203 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00994
KIR:KIR00994 KIR2DL5B*00204 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01193
KIR:KIR01193 KIR2DL5B*00205 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00031
KIR:KIR00031 KIR2DL5B*003 375 bases
 MSLMVVSMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIMVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00032
KIR:KIR00032 KIR2DL5B*004 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSTVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00125
KIR:KIR00125 KIR2DL5B*00601 375 bases
 MSLMVVSMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00267
KIR:KIR00267 KIR2DL5B*00602 375 bases
 MSLMVVSMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00393
KIR:KIR00393 KIR2DL5B*00603 375 bases
 MSLMVVSMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00126
KIR:KIR00126 KIR2DL5B*0070101 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIMVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00525
KIR:KIR00525 KIR2DL5B*0070102 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIMVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00244
KIR:KIR00244 KIR2DL5B*0080101 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00395
KIR:KIR00395 KIR2DL5B*0080102 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00266
KIR:KIR00266 KIR2DL5B*00802 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00682
KIR:KIR00682 KIR2DL5B*00803 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00805
KIR:KIR00805 KIR2DL5B*00804 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00946
KIR:KIR00946 KIR2DL5B*00805 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00245
KIR:KIR00245 KIR2DL5B*009 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGILRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00264
KIR:KIR00264 KIR2DL5B*010 375 bases
 MSLMVVSMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00265
KIR:KIR00265 KIR2DL5B*011 375 bases
 MSLMVVSMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCIFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00390
KIR:KIR00390 KIR2DL5B*01301 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVCTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00392
KIR:KIR00392 KIR2DL5B*01302 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVCTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00534
KIR:KIR00534 KIR2DL5B*01303 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVCTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00801
KIR:KIR00801 KIR2DL5B*01304 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVCTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00538
KIR:KIR00538 KIR2DL5B*016 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSYP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00664
KIR:KIR00664 KIR2DL5B*017 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKNNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00684
KIR:KIR00684 KIR2DL5B*018 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVH RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCWGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00803
KIR:KIR00803 KIR2DL5B*019 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVCTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKNNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR00804
KIR:KIR00804 KIR2DL5B*020 304 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHGGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHX     
>P1;KIR:KIR01205
KIR:KIR01205 KIR2DL5B*035 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVIYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01206
KIR:KIR01206 KIR2DL5B*036 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRDLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01208
KIR:KIR01208 KIR2DL5B*037 375 bases
 MSLMVVSMAC VGFFLLQGAW PHEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP CSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01190
KIR:KIR01190 KIR2DL5B*038 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVNGTFQADF
 PLGPATHRGT YTCFGSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01207
KIR:KIR01207 KIR2DL5B*0390101 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP CSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01203
KIR:KIR01203 KIR2DL5B*0390102 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRCRGSHP CSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
>P1;KIR:KIR01596
KIR:KIR01596 KIR2DL5B*041 375 bases
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPL LSAWPSAVVP RGGHVTLLCR SRLGFTIFSL
 YKEDGVPVPE LYNKIFWKSI LMGPVTPAHA GTYRYRGSHP RSPIEWSAPS NPLVIVVTGL
 FGKPSLSAQP GPTVRTGENV TLSCSSRSSF DMYHLSREGR AHEPRLPAVP SVDGTFQADF
 PLGPATHGGT YTCFSSLHDS PYEWSDPSDP LLVSVTGNSS SSSSSPTEPS SKTGIRRHLH
 ILIGTSVAII LFIILFFFLL HCCCSNKKNA AVMDQEPAGD RTVNREDSDD QDPQEVTYAQ
 LDHCVFTQTK ITSPSQRPKT PPTDTTMYME LPNAKPRSLS PAHKHHSQAL RGSSRETTAL
 SQNRVASSHV PAAGI    
