>P1;KIR:KIR00033
KIR:KIR00033 KIR2DS1*001 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM RQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00034
KIR:KIR00034 KIR2DS1*0020101 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00298
KIR:KIR00298 KIR2DS1*0020102 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00296
KIR:KIR00296 KIR2DS1*0020103 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00426
KIR:KIR00426 KIR2DS1*0020104 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00427
KIR:KIR00427 KIR2DS1*0020105 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00428
KIR:KIR00428 KIR2DS1*0020106 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00255
KIR:KIR00255 KIR2DS1*00202 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00035
KIR:KIR00035 KIR2DS1*00301 304 bases
 MSLMVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00254
KIR:KIR00254 KIR2DS1*00302 303 bases
 SLMVVSMACV GFFLLQGAWP HEGVHRKPSL LAHPGRLVKS EETVILQCWS DVMFEHFLLH
 REGMFNDTLR LIGEHHDGVS KANFSISRMK QDLAGTYRCY GSVTHSPYQL SAPSDPLDIV
 IIGLYEKPSL SAQPGPTVLA GENVTLSCSS RSSYDMYHLS REGEAHERRL PAGTKVNGTF
 QANFPLGPAT HGGTYRCFGS FRDSPYEWSK SSDPLLVSVT GNPSNSWPSP TEPSSETGNP
 RHLHVLIGTS VVKIPFTILL FFLLHRWCSD KKNAAVMDQE PAGNRTVNSE DSDEQDHQEV
 SYA*     
>P1;KIR:KIR00036
KIR:KIR00036 KIR2DS1*004 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00252
KIR:KIR00252 KIR2DS1*00501 304 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00256
KIR:KIR00256 KIR2DS1*00502 304 bases
 MSLLVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00253
KIR:KIR00253 KIR2DS1*006 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ LSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGENVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHILIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00271
KIR:KIR00271 KIR2DS1*008 304 bases
 MSLTVVSMAC VGFFLLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGMFNDTL RLIGEHHDGV SKANFSISRM KQDLAGTYRC YGSVTHSPYQ VSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL SREGEAHERR LPAGTKVNGT
 FQANFPLGPA THGGTYRCFG SFRDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKIPFTIL LFFLLHRWCS DKKNAAVMDQ EPAGNRTVNS EDSDEQDHQE
 VSYA*     
