>DL;KIR:KIR00042
KIR:KIR00042 KIR2DS3*00101 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ACGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00043
KIR:KIR00043 KIR2DS3*00102 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC GGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00044
KIR:KIR00044 KIR2DS3*0010301 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00636
KIR:KIR00636 KIR2DS3*0010302 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01310
KIR:KIR01310 KIR2DS3*0010303 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01311
KIR:KIR01311 KIR2DS3*0010304 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01243
KIR:KIR01243 KIR2DS3*0010305 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01315
KIR:KIR01315 KIR2DS3*0010306 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01316
KIR:KIR01316 KIR2DS3*0010307 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01318
KIR:KIR01318 KIR2DS3*0010308 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01322
KIR:KIR01322 KIR2DS3*0010309 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01323
KIR:KIR01323 KIR2DS3*0010310 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01325
KIR:KIR01325 KIR2DS3*0010311 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01326
KIR:KIR01326 KIR2DS3*0010312 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01231
KIR:KIR01231 KIR2DS3*0010313 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01234
KIR:KIR01234 KIR2DS3*0010314 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01235
KIR:KIR01235 KIR2DS3*0010315 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01236
KIR:KIR01236 KIR2DS3*0010316 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01238
KIR:KIR01238 KIR2DS3*0010317 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01241
KIR:KIR01241 KIR2DS3*0010318 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01242
KIR:KIR01242 KIR2DS3*0010319 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01244
KIR:KIR01244 KIR2DS3*0010320 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01245
KIR:KIR01245 KIR2DS3*0010321 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00272
KIR:KIR00272 KIR2DS3*00104 887 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAATGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACA* 
>DL;KIR:KIR00321
KIR:KIR00321 KIR2DS3*00105 887 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTTGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACA* 
>DL;KIR:KIR00322
KIR:KIR00322 KIR2DS3*00106 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01320
KIR:KIR01320 KIR2DS3*00107 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCTG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01321
KIR:KIR01321 KIR2DS3*00108 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC TCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01226
KIR:KIR01226 KIR2DS3*00109 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01232
KIR:KIR01232 KIR2DS3*00110 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAGAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01239
KIR:KIR01239 KIR2DS3*00111 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC GTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01250
KIR:KIR01250 KIR2DS3*0011201 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACAGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01229
KIR:KIR01229 KIR2DS3*0011202 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACAGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01319
KIR:KIR01319 KIR2DS3*0011301 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATATG CATAA*    
>DL;KIR:KIR01237
KIR:KIR01237 KIR2DS3*0011302 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATATG CATAA*    
>DL;KIR:KIR00131
KIR:KIR00131 KIR2DS3*0020101 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00429
KIR:KIR00429 KIR2DS3*0020102 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00652
KIR:KIR00652 KIR2DS3*0020103 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01304
KIR:KIR01304 KIR2DS3*0020104 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01305
KIR:KIR01305 KIR2DS3*0020105 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01307
KIR:KIR01307 KIR2DS3*0020106 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01308
KIR:KIR01308 KIR2DS3*0020107 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01312
KIR:KIR01312 KIR2DS3*0020108 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01313
KIR:KIR01313 KIR2DS3*0020109 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01309
KIR:KIR01309 KIR2DS3*00202 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00232
KIR:KIR00232 KIR2DS3*0030101N 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGAAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01577
KIR:KIR01577 KIR2DS3*0030102N 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGAAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00273
KIR:KIR00273 KIR2DS3*004 887 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACA* 
>DL;KIR:KIR00529
KIR:KIR00529 KIR2DS3*005 887 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CCACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACA* 
>DL;KIR:KIR00663
KIR:KIR00663 KIR2DS3*006 846 bases
 GGATTCCGCA GAAAACCTTC CCTCCTGGCC CACCCAGGTC GCCTGGTGAA ATCAGAAGAG
 AGAGTCATCC TGCAATGTTG GTCAGATGTC ATGTTTGAGC ACTTCCTTCT GCACAGAGAG
 GGGACGTTTA ACGACACTTT GCGCCTCATT GGAGAGCACA TTGATGGGGT CTCCAAGGCC
 AACTTCTCCA TCGGTCGCAT GAGGCAAGAC CTGGCAGGGA CCTACAGATG CTACGGTTCT
 GTTCCTCACT CCCCCTATCA GTTTTCAGCT CCCAGTGACC CTCTGGACAT CGTGATCACA
 GGTCTATATG AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG
 AGCGTGACCT TGTCCTGCAG CTCCTGGAGC TCCTATGACA TGTACCATCT ATCCACGGAG
 GGGGAGGCCC ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCC
 GACTTTCCTC TGGGCCCTGC CACCCAAGGA GGAACCTACA GATGCTTCGG CTCTTTCCAT
 GACTCTCCCT ACGAGTGGTC AAAGTCAAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC
 CCTTCAAATA GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAA CCCCAGACAC
 CTACACGTTC TGATTGGGAC CTCAGTGGTC AAACTCCCTT TCACCATCCT CCTCTTCTTT
 CTCCTTCATC GCTGGTGCTC CGACAAAAAA AATGCATCTG TAATGGACCA AGGGCCTGCG
 GGGAACAGAA CAGTGAACAG GGAGGATTCT GATGAACAGG ACCATCAGGA GGTGTCATAC
 GCATAA*     
>DL;KIR:KIR00699
KIR:KIR00699 KIR2DS3*007 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGCGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR00885
KIR:KIR00885 KIR2DS3*008 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGCCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01227
KIR:KIR01227 KIR2DS3*009 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGATCAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01314
KIR:KIR01314 KIR2DS3*010 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCATAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01317
KIR:KIR01317 KIR2DS3*011 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCACATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01324
KIR:KIR01324 KIR2DS3*012 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATAG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01327
KIR:KIR01327 KIR2DS3*013 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGAAGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01328
KIR:KIR01328 KIR2DS3*014 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG AAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01224
KIR:KIR01224 KIR2DS3*015 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CAGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01225
KIR:KIR01225 KIR2DS3*016 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01228
KIR:KIR01228 KIR2DS3*017 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01230
KIR:KIR01230 KIR2DS3*018 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCATGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01233
KIR:KIR01233 KIR2DS3*019 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCA CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01246
KIR:KIR01246 KIR2DS3*020 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGCTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01240
KIR:KIR01240 KIR2DS3*0210101 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01306
KIR:KIR01306 KIR2DS3*0210102 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01248
KIR:KIR01248 KIR2DS3*0220101 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACAGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01247
KIR:KIR01247 KIR2DS3*0220102 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACAGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01249
KIR:KIR01249 KIR2DS3*0220103 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACAGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC GACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01579
KIR:KIR01579 KIR2DS3*023 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACCGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
>DL;KIR:KIR01580
KIR:KIR01580 KIR2DS3*024 915 bases
 ATGTCGCTCA TGGTCATCAG CATGGCATGT GTTGGGTTCT TCTGGCTGCA GGGGGCCTGG
 CCACATGAGG GATTCCGCAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCG CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA TGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGACGTTTAA CGACACTTTG CGCCTCATTG GAGAGCACAT TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCGCATG AGGCAAGACC TGGCAGGGAC CTACAGATGC
 TACGGTTCTG TTCCTCACTC CCCCTATCAG TTTTCAGCTC CCAGTGACCC TCTGGACATC
 GTGATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCTGGAGCT CCTATGACAT GTACCATCTA
 TCCACGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCAAGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCCTA CGAGTGGTCA AAGTCAGGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TACACGTTCT GATTGGGACC TCAGTGGTCA AACTCCCTTT CACCATCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCATCTGT AATGGACCAA
 GGGCCTGCGG GGAACAGAAC AGTGAACAGG GAGGATTCTG ATGAACAGGA CCATCAGGAG
 GTGTCATACG CATAA*    
