>P1;KIR:KIR00042
KIR:KIR00042 KIR2DS3*00101 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00043
KIR:KIR00043 KIR2DS3*00102 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00044
KIR:KIR00044 KIR2DS3*0010301 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00636
KIR:KIR00636 KIR2DS3*0010302 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01310
KIR:KIR01310 KIR2DS3*0010303 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01311
KIR:KIR01311 KIR2DS3*0010304 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01243
KIR:KIR01243 KIR2DS3*0010305 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01315
KIR:KIR01315 KIR2DS3*0010306 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01316
KIR:KIR01316 KIR2DS3*0010307 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01318
KIR:KIR01318 KIR2DS3*0010308 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01322
KIR:KIR01322 KIR2DS3*0010309 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01323
KIR:KIR01323 KIR2DS3*0010310 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01325
KIR:KIR01325 KIR2DS3*0010311 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01326
KIR:KIR01326 KIR2DS3*0010312 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01231
KIR:KIR01231 KIR2DS3*0010313 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01234
KIR:KIR01234 KIR2DS3*0010314 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01235
KIR:KIR01235 KIR2DS3*0010315 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01236
KIR:KIR01236 KIR2DS3*0010316 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01238
KIR:KIR01238 KIR2DS3*0010317 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01241
KIR:KIR01241 KIR2DS3*0010318 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01242
KIR:KIR01242 KIR2DS3*0010319 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01244
KIR:KIR01244 KIR2DS3*0010320 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01245
KIR:KIR01245 KIR2DS3*0010321 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00272
KIR:KIR00272 KIR2DS3*00104 295 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDE*
>P1;KIR:KIR00321
KIR:KIR00321 KIR2DS3*00105 295 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDE*
>P1;KIR:KIR00322
KIR:KIR00322 KIR2DS3*00106 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01320
KIR:KIR01320 KIR2DS3*00107 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01321
KIR:KIR01321 KIR2DS3*00108 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01226
KIR:KIR01226 KIR2DS3*00109 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01232
KIR:KIR01232 KIR2DS3*00110 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01239
KIR:KIR01239 KIR2DS3*00111 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01250
KIR:KIR01250 KIR2DS3*0011201 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01229
KIR:KIR01229 KIR2DS3*0011202 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01319
KIR:KIR01319 KIR2DS3*0011301 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01237
KIR:KIR01237 KIR2DS3*0011302 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00131
KIR:KIR00131 KIR2DS3*0020101 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00429
KIR:KIR00429 KIR2DS3*0020102 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00652
KIR:KIR00652 KIR2DS3*0020103 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01304
KIR:KIR01304 KIR2DS3*0020104 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01305
KIR:KIR01305 KIR2DS3*0020105 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01307
KIR:KIR01307 KIR2DS3*0020106 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01308
KIR:KIR01308 KIR2DS3*0020107 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01312
KIR:KIR01312 KIR2DS3*0020108 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01313
KIR:KIR01313 KIR2DS3*0020109 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01309
KIR:KIR01309 KIR2DS3*00202 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00232
KIR:KIR00232 KIR2DS3*0030101N 149 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSX*   
>P1;KIR:KIR01577
KIR:KIR01577 KIR2DS3*0030102N 149 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSX*   
>P1;KIR:KIR00273
KIR:KIR00273 KIR2DS3*004 295 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SRSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDE*
>P1;KIR:KIR00529
KIR:KIR00529 KIR2DS3*005 295 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNHTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDE*
>P1;KIR:KIR00663
KIR:KIR00663 KIR2DS3*006 281 bases
 GFRRKPSLLA HPGRLVKSEE RVILQCWSDV MFEHFLLHRE GTFNDTLRLI GEHIDGVSKA
 NFSIGRMRQD LAGTYRCYGS VPHSPYQFSA PSDPLDIVIT GLYEKPSLSA QPGPTVLAGE
 SVTLSCSSWS SYDMYHLSTE GEAHERRFSA GPKVNGTFQA DFPLGPATQG GTYRCFGSFH
 DSPYEWSKSS DPLLVSVTGN PSNSWPSPTE PSSKTGNPRH LHVLIGTSVV KLPFTILLFF
 LLHRWCSDKK NASVMDQGPA GNRTVNREDS DEQDHQEVSY A* 
>P1;KIR:KIR00699
KIR:KIR00699 KIR2DS3*007 304 bases
 MSLMVISMAC VAFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSETGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR00885
KIR:KIR00885 KIR2DS3*008 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDAMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01227
KIR:KIR01227 KIR2DS3*009 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGIRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01314
KIR:KIR01314 KIR2DS3*010 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VIIGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01317
KIR:KIR01317 KIR2DS3*011 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGHM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01324
KIR:KIR01324 KIR2DS3*012 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHSWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01327
KIR:KIR01327 KIR2DS3*013 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SEVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01328
KIR:KIR01328 KIR2DS3*014 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIEEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01224
KIR:KIR01224 KIR2DS3*015 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSISRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01225
KIR:KIR01225 KIR2DS3*016 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGPM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01228
KIR:KIR01228 KIR2DS3*017 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL SREGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01230
KIR:KIR01230 KIR2DS3*018 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESMTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01233
KIR:KIR01233 KIR2DS3*019 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHHWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01246
KIR:KIR01246 KIR2DS3*020 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYECS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01240
KIR:KIR01240 KIR2DS3*0210101 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01306
KIR:KIR01306 KIR2DS3*0210102 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGVHRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01248
KIR:KIR01248 KIR2DS3*0220101 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YSSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01247
KIR:KIR01247 KIR2DS3*0220102 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YSSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01249
KIR:KIR01249 KIR2DS3*0220103 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YSSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS DKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01579
KIR:KIR01579 KIR2DS3*023 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YRSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSSDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
>P1;KIR:KIR01580
KIR:KIR01580 KIR2DS3*024 304 bases
 MSLMVISMAC VGFFWLQGAW PHEGFRRKPS LLAHPGRLVK SEETVILQCW SDVMFEHFLL
 HREGTFNDTL RLIGEHIDGV SKANFSIGRM RQDLAGTYRC YGSVPHSPYQ FSAPSDPLDI
 VITGLYEKPS LSAQPGPTVL AGESVTLSCS SWSSYDMYHL STEGEAHERR FSAGPKVNGT
 FQADFPLGPA TQGGTYRCFG SFHDSPYEWS KSGDPLLVSV TGNPSNSWPS PTEPSSKTGN
 PRHLHVLIGT SVVKLPFTIL LFFLLHRWCS NKKNASVMDQ GPAGNRTVNR EDSDEQDHQE
 VSYA*     
