>DL;IPD:KIR00014
KIR:KIR00014 KIR2DL3*0010101 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00412
KIR:KIR00412 KIR2DL3*0010102 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00413
KIR:KIR00413 KIR2DL3*0010103 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00415
KIR:KIR00415 KIR2DL3*0010104 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00416
KIR:KIR00416 KIR2DL3*0010105 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00417
KIR:KIR00417 KIR2DL3*0010106 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00418
KIR:KIR00418 KIR2DL3*0010107 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00419
KIR:KIR00419 KIR2DL3*0010108 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00619
KIR:KIR00619 KIR2DL3*0010109 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00631
KIR:KIR00631 KIR2DL3*0010110 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00657
KIR:KIR00657 KIR2DL3*0010111 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00566
KIR:KIR00566 KIR2DL3*00102 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG GTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00569
KIR:KIR00569 KIR2DL3*00103 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00656
KIR:KIR00656 KIR2DL3*00104 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAACACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00671
KIR:KIR00671 KIR2DL3*00105 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTCC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00689
KIR:KIR00689 KIR2DL3*00106 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT TGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00691
KIR:KIR00691 KIR2DL3*00107 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00695
KIR:KIR00695 KIR2DL3*00108 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCAGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00732
KIR:KIR00732 KIR2DL3*00109 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATTTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00734
KIR:KIR00734 KIR2DL3*00110 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00015
KIR:KIR00015 KIR2DL3*0020101 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCTTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCACCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00435
KIR:KIR00435 KIR2DL3*0020102 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCTTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCACCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00646
KIR:KIR00646 KIR2DL3*0020103 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCTTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCACCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00016
KIR:KIR00016 KIR2DL3*003 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATACA CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00017
KIR:KIR00017 KIR2DL3*004 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCGGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CGCCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCATACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCACCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00018
KIR:KIR00018 KIR2DL3*00501 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCGGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CGCCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCACCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00806
KIR:KIR00806 KIR2DL3*00502 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCGGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CGCCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCTA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCACCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00019
KIR:KIR00019 KIR2DL3*006 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCACCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00128
KIR:KIR00128 KIR2DL3*007 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCTTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGCGGT AATGGACCAA
 GAGTCTGCAG GAAACAGAAC AGCGAATAGC GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCACCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00313
KIR:KIR00313 KIR2DL3*008N 955 bases
 GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA TCAGAAGAGA
 CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG CACAGAGAAG
 GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC TCCAAGGCCA
 ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC TACGGTTCTG
 TTACTCACCC CCCTATCAGT TGTCAGCTCC CAGTGACCCT CTGGACATCG TCATCACAGG
 TCTATATGAG AAACCTTCTC TCTCAGCCCA GCCGGGCCCC ACGGTTCTGG CAGGAGAGAG
 CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATG TACCATCTAT CCAGGGAGGG
 GGAGGCCCAT GAACGTAGGT TCTCTGCAGG GCCCAAGGTC AACGGAACAT TCCAGGCCGA
 CTTTCCTCTG GGCCCTGCCA CCCACGGAGG AACCTACAGA TGCTTCGGCT CTTTCCGTGA
 CTCTCCATAC GAGTGGTCAA ACTCGAGTGA CCCACTGCTT GTTTCTGTCA CAGGAAACCC
 TTCAAATAGT TGGCCTTCAC CCACTGAACC AAGCTCCGAA ACCGGTAACC CCAGACACCT
 GCATGTTCTG ATTGGGACCT CAGTGGTCAT CATCCTCTTC ATCCTCCTCC TCTTCTTTCT
 CCTTCATCGC TGGTGCTGCA ACAAAAAAAA TGCTGTTGTA ATGGACCAAG AGCCTGCAGG
 GAACAGAACA GTGAACAGGG AGGACTCTGA TGAACAAGAC CCTCAGGAGG TGACATATGC
 ACAGTTGAAT CACTGCGTTT TCACACAGAG AAAAATCACT CGCCCTTCTC AGAGGCCCAA
 GACACCCCCA ACAGATATCA TCGTGTACAC GGAACTTCCA AATGCTGAGC CCTGA*
>DL;IPD:KIR00314
KIR:KIR00314 KIR2DL3*009 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACCTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00414
KIR:KIR00414 KIR2DL3*010 1050 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCGGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CGCCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCACGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CGTCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCAGATCCA AAGTTGTCTC CTGCCCATGA *  
>DL;IPD:KIR00567
KIR:KIR00567 KIR2DL3*011 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCTGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00568
KIR:KIR00568 KIR2DL3*01201 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTT
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCACCCTTTT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00660
KIR:KIR00660 KIR2DL3*01202 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCACCCTTTT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00570
KIR:KIR00570 KIR2DL3*013 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCAGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00571
KIR:KIR00571 KIR2DL3*014 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CGCCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00588
KIR:KIR00588 KIR2DL3*015 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCTTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCACCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00589
KIR:KIR00589 KIR2DL3*016 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA ATGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATACG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00655
KIR:KIR00655 KIR2DL3*017 1050 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CGCCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCAGATCCA AAGTTGTCTC CTGCCCATGA *  
>DL;IPD:KIR00659
KIR:KIR00659 KIR2DL3*01801 981 bases
 GGAGTCCACA GAAAACCTTC CCTCCTGGCC CACCCAGGTC CCCTGGTGAA ATCAGAAGAG
 ACAGTCATCC TGCAATGTTG GTCAGATGTC AGGTTTGAGC ACTTCCTTCT GCACAGAGAA
 GGGAAGTTTA AGGACACTTT GCGCCTCATT GGAGAGCACC ATGATGGGGT CTCCAAGGCC
 AACTTCTCCA TCGGTCCCAT GATGCAAGAC CTTGCAGGGA CCTACAGATG CTACGGTTCT
 GTTACTCACT CCCCCTATCA GTTGTCAGCT CCCAGTGACC CTCTGGACAT CGTCATCACA
 GGTCTATATG AGAAACCTTC TCTCTCAGCC CAGCCGGGCC CCACGGTTCT GGCAGGAGAG
 AGCGTGACCT TGTCCTGCAG CTCCCGGAGC TCCTATGACA TGTACCATCT ATCCAGGGAG
 GGGGAGGCCC ATGAACGTAG GTTCTCTGCA GGGCCCAAGG TCAACGGAAC ATTCCAGGCC
 GACTTTCCTC TGGGCCCTGC CACCCACGGA GGAACCTACA GATGCTTCGG CTCTTTCCGT
 GACTCTCCAT ACGAGTGGTC AAACTCGAGT GACCCACTGC TTGTTTCTGT CACAGGAAAC
 CCTTCAAATA GTTGGCCTTC ACCCACTGAA CCAAGCTCCA AAACCGGTAA CCCCAGACAC
 CTGCACGTTC TGATTGGGAC CTCAGTGGTC ATCATCCTCT TCGTCCTCCT CCTCTTCTTT
 CTCCTTCATC GCTGGTGCTC CAACAAAAAA AATGCTGTTG TAATGGACCA AGAGCCTGCA
 GGGAACAGAA CAGTGAACAG GGAGGACTCT GATGAACAAG ACCCTCAGGA GGTGACATAT
 GCACAGTTGA ATCACTGCGT TTTCACACAG AGAAAAATCA CTCGCCCTTC TCAGAGGCCC
 AAGACACCCC CAACAGATAT CATCGTGTAC ACGGAACTTC CAAATGCTGA GCCCAGATCC
 AAAGTTGTCT CCTGCCCATG A*   
>DL;IPD:KIR00895
KIR:KIR00895 KIR2DL3*01802 1050 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CGCCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAAG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCACGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CGTCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCAGATCCA AAGTTGTCTC CTGCCCATGA *  
>DL;IPD:KIR00687
KIR:KIR00687 KIR2DL3*019 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCGTCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00693
KIR:KIR00693 KIR2DL3*020 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCATG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00697
KIR:KIR00697 KIR2DL3*021 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGCTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00683
KIR:KIR00683 KIR2DL3*022 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCA ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCTTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCACCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00703
KIR:KIR00703 KIR2DL3*023 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGATC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00704
KIR:KIR00704 KIR2DL3*024 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAACCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00733
KIR:KIR00733 KIR2DL3*025 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACA TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00735
KIR:KIR00735 KIR2DL3*026 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GAACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00736
KIR:KIR00736 KIR2DL3*027 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTCC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00737
KIR:KIR00737 KIR2DL3*028 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCA CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00738
KIR:KIR00738 KIR2DL3*029 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAAAGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00739
KIR:KIR00739 KIR2DL3*030 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA CGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00740
KIR:KIR00740 KIR2DL3*031 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCACATTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00741
KIR:KIR00741 KIR2DL3*032 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCACTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00849
KIR:KIR00849 KIR2DL3*033 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAGG GGAAGTATAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTTTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCCTA TGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCAA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCACCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00879
KIR:KIR00879 KIR2DL3*034 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGTGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCTGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTCAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CACCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GAACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACACAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCGCCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
>DL;IPD:KIR00945
KIR:KIR00945 KIR2DL3*035 1026 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GAGTCCACAG AAAACCTTCC CTCCAGGCCC ACCCAGGTCC CCTGGTGAAA
 TCAGAAGAGA CAGTCATCCT GCAATGTTGG TCAGATGTCA GGTTTGAGCA CTTCCTTCTG
 CACAGAGAAG GGAAGTTTAA GGACACTTTG CGCCTCATTG GAGAGCACCA TGATGGGGTC
 TCCAAGGCCA ACTTCTCCAT CGGTCCCATG ATGCAAGACC TTGCAGGGAC CTACAGATGC
 TACGGTTCTG TTACTCACTC CCCCTATCAG TTGTCAGCTC CCAGTGACCC TCTGGACATC
 GTCATCACAG GTCTATATGA GAAACCTTCT CTCTCAGCCC AGCCGGGCCC CACGGTTCTG
 GCAGGAGAGA GCGTGACCTT GTCCTGCAGC TCCCGGAGCT CCTATGACAT GTACCATCTA
 TCCAGGGAGG GGGAGGCCCA TGAACGTAGG TTCTCTGCAG GGCCCAAGGT CAACGGAACA
 TTCCAGGCCG ACTTTCCTCT GGGCCCTGCC ACCCACGGAG GGACCTACAG ATGCTTCGGC
 TCTTTCCGTG ACTCTCCATA CGAGTGGTCA AACTCGAGTG ACCCACTGCT TGTTTCTGTC
 ACAGGAAACC CTTCAAATAG TTGGCCTTCA CCCACTGAAC CAAGCTCCGA AACCGGTAAC
 CCCAGACACC TGCATGTTCT GATTGGGACC TCAGTGGTCA TCATCCTCTT CATCCTCCTC
 CTCTTCTTTC TCCTTCATCG CTGGTGCTGC AACAAAAAAA ATGCTGTTGT AATGGACCAA
 GAGCCTGCAG GGAACAGAAC AGTGAACAGG GAGGACTCTG ATGAACAAGA CCCTCAGGAG
 GTGACATATG CACAGTTGAA TCACTGCGTT TTCACACAGA GAAAAATCAC TCACCCTTCT
 CAGAGGCCCA AGACACCCCC AACAGATATC ATCGTGTACA CGGAACTTCC AAATGCTGAG
 CCCTGA*     
