>P1;KIR:KIR00077
KIR:KIR00077 KIR3DL3*00101 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00222
KIR:KIR00222 KIR3DL3*00102 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00224
KIR:KIR00224 KIR3DL3*00103 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00550
KIR:KIR00550 KIR3DL3*00104 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00078
KIR:KIR00078 KIR3DL3*00201 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00079
KIR:KIR00079 KIR3DL3*00202 393 bases
 GPWPHVGGQD KPFLSAWPGT VVSEGQHVTL QCRSRLGFNE FSLSKEDGMP VPELYNRIFR
 NSFLMGPVTP AHAGTYRCCS SHPHSPTGWS APSNPVVIMV TGVHRKPSLL AHPGPLVKSG
 ETVILQCWSD VRFERFLLHR EGITEDPLRL VGQLHDAGSQ VNYSMGPMTP ALAGTYRCFG
 SVTHLPYELS APSDPLDIVV VGLYGKPSLS AQPGPTVQAG ENVTLSCSSR SLFDIYHLSR
 EAEAGELRLT AVLRVNGTFQ ANFPLGPVTH GGNYRCFGSF RALPHAWSDP SDPLPVSVTG
 NSRHLHVLIG TSVVIIPFAI LLFFLLHRWC ANKKNAVVMD QEPAGNRTVN REDSDEQDPQ
 EVTYAQLNHC VFTQRKITRP SQRPKTPPTD TSV*  
>P1;KIR:KIR00180
KIR:KIR00180 KIR3DL3*00203 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00178
KIR:KIR00178 KIR3DL3*00204 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00198
KIR:KIR00198 KIR3DL3*00205 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00218
KIR:KIR00218 KIR3DL3*00206 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00230
KIR:KIR00230 KIR3DL3*00207 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00383
KIR:KIR00383 KIR3DL3*00208 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00554
KIR:KIR00554 KIR3DL3*00209 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00560
KIR:KIR00560 KIR3DL3*00210 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00790
KIR:KIR00790 KIR3DL3*00211 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00080
KIR:KIR00080 KIR3DL3*0030101 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00303
KIR:KIR00303 KIR3DL3*0030102 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00482
KIR:KIR00482 KIR3DL3*0030103 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00642
KIR:KIR00642 KIR3DL3*0030104 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00559
KIR:KIR00559 KIR3DL3*00302 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00081
KIR:KIR00081 KIR3DL3*00401 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SHLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00138
KIR:KIR00138 KIR3DL3*0040201 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SHLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00486
KIR:KIR00486 KIR3DL3*0040202 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SHLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00139
KIR:KIR00139 KIR3DL3*005 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP DPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00140
KIR:KIR00140 KIR3DL3*00601 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFKEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVSF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGT YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00191
KIR:KIR00191 KIR3DL3*00602 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFKEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVSF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGT YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00141
KIR:KIR00141 KIR3DL3*007 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF EHFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00142
KIR:KIR00142 KIR3DL3*00801 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SHLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00143
KIR:KIR00143 KIR3DL3*00802 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SHLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00175
KIR:KIR00175 KIR3DL3*0090101 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00481
KIR:KIR00481 KIR3DL3*0090102 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00484
KIR:KIR00484 KIR3DL3*0090103 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00223
KIR:KIR00223 KIR3DL3*00902 393 bases
 GPWPHVGGQD KPFLSAWPGT VVSEGQHVTL QCRSRLGFNE FSLSKEDGMP VPELYNRIFR
 NSFLMGPVTP AHAGTYRCCS SHPHSPTGWS APSNPVVIMV TGVHRKPSLL AHPGPLVKSG
 ETVILQCWSD VRFERFLLHR EGITEDPLRL IGQLHDAGSQ VNYSMGPMTP ALAGTYRCFG
 SVTHLPYELS APSDPLDIVV VGLYGKPSLS AQPGPTVQAG ENVTLSCSSR SLFDIYHLSR
 EAEAGELRLT AVLRVNGTFQ ANFPLGPVTH GGNYRCFGSF RALPHAWSDP SDPLPVSVTG
 NSRHLHVLIG TSVVIIPFAI LLFFLLHRWC ANKKNAVVMD QEPAGNRTVN REDSDEQDPQ
 EVTYAQLNHC VFTQRKITRP SQRPKTPPTD TSV*  
>P1;KIR:KIR00382
KIR:KIR00382 KIR3DL3*00903 386 bases
 GQDKPFLSAW PGTVVSEGQH VTLQCRSRLG FNEFSLSKED GMPVPELYNR IFRNSFLMGP
 VTPAHAGTYR CCSSHPHSPT GWSAPSNPVV IMVTGVHRKP SLLAHPGPLV KSGETVILQC
 WSDVRFERFL LHREGITEDP LRLIGQLHDA GSQVNYSMGP MTPALAGTYR CFGSVTHLPY
 ELSAPSDPLD IVVVGLYGKP SLSAQPGPTV QAGENVTLSC SSRSLFDIYH LSREAEAGEL
 RLTAVLRVNG TFQANFPLGP VTHGGNYRCF GSFRALPHAW SDPSDPLPVS VTGNSRHLHV
 LIGTSVVIIP FAILLFFLLH RWCANKKNAV VMDQEPAGNR TVNREDSDEQ DPQEVTYAQL
 NHCVFTQRKI TRPSQRPKTP PTDTSV*   
>P1;KIR:KIR00563
KIR:KIR00563 KIR3DL3*00904 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00612
KIR:KIR00612 KIR3DL3*00905 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00181
KIR:KIR00181 KIR3DL3*01001 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFWNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00533
KIR:KIR00533 KIR3DL3*01002 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFWNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00923
KIR:KIR00923 KIR3DL3*01003 411 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFWNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV X*
>P1;KIR:KIR00182
KIR:KIR00182 KIR3DL3*01101 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGT YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00188
KIR:KIR00188 KIR3DL3*01102 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGT YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00179
KIR:KIR00179 KIR3DL3*012 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFKEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGT YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00176
KIR:KIR00176 KIR3DL3*01301 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00183
KIR:KIR00183 KIR3DL3*01302 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00184
KIR:KIR00184 KIR3DL3*01303 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00185
KIR:KIR00185 KIR3DL3*01304 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00221
KIR:KIR00221 KIR3DL3*01305 393 bases
 GPWPHVGGQD KPFLSAWPGT VVSEGQHVTL QCRSRLGFNE FSLSKEDGMP VPELYNRIFR
 NSFLMGPVTP AHAGTYRCCS SHPHSPTGWS APSNPVVIMV TGVHRKPSLL AHPGPLVKSG
 ETVILQCWSD VRFERFLLHR EGITEDPLRL VGQLHDAGSQ VNYSMGPMTP ALAGTYRCFG
 SVTHLPYELS APSDPLDIVV VGLYGKPSLS AQPGPTVQAG ENVTLSCSSR SLFDIYHLSR
 EAEAGELRLT AVLRVNGTFQ ANFPLGPVTH GGNYRCFGSF RALPHAWSDP SDPLPVSVTG
 NSRNLHVLIG TSVVIIPFAI LLFFLLHRWC ANKKNAVVMD QEPAGNRTVN REDSDEQDPQ
 EVTYAQLNHC VFTQRKITRP SQRPKTPPTD TSV*  
>P1;KIR:KIR00231
KIR:KIR00231 KIR3DL3*01306 393 bases
 GPWPHVGGQD KPFLSAWPGT VVSEGQHVTL QCRSRLGFNE FSLSKEDGMP VPELYNRIFR
 NSFLMGPVTP AHAGTYRCCS SHPHSPTGWS APSNPVVIMV TGVHRKPSLL AHPGPLVKSG
 ETVILQCWSD VRFERFLLHR EGITEDPLRL VGQLHDAGSQ VNYSMGPMTP ALAGTYRCFG
 SVTHLPYELS APSDPLDIVV VGLYGKPSLS AQPGPTVQAG ENVTLSCSSR SLFDIYHLSR
 EAEAGELRLT AVLRVNGTFQ ANFPLGPVTH GGNYRCFGSF RALPHAWSDP SDPLPVSVTG
 NSRNLHVLIG TSVVIIPFAI LLFFLLHRWC ANKKNAVVMD QEPAGNRTVN REDSDEQDPQ
 EVTYAQLNHC VFTQRKITRP SQRPKTPPTD TSV*  
>P1;KIR:KIR00225
KIR:KIR00225 KIR3DL3*01307 393 bases
 GPWPHVGGQD KPFLSAWPGT VVSEGQHVTL QCRSRLGFNE FSLSKEDGMP VPELYNRIFR
 NSFLMGPVTP AHAGTYRCCS SHPHSPTGWS APSNPVVIMV TGVHRKPSLL AHPGPLVKSG
 ETVILQCWSD VRFERFLLHR EGITEDPLRL VGQLHDAGSQ VNYSMGPMTP ALAGTYRCFG
 SVTHLPYELS APSDPLDIVV VGLYGKPSLS AQPGPTVQAG ENVTLSCSSR SLFDIYHLSR
 EAEAGELRLT AVLRVNGTFQ ANFPLGPVTH GGNYRCFGSF RALPHAWSDP SDPLPVSVTG
 NSRNLHVLIG TSVVIIPFAI LLFFLLHRWC ANKKNAVVMD QEPAGNRTVN REDSDEQDPQ
 EVTYAQLNHC VFTQRKITRP SQRPKTPPTD TSV*  
>P1;KIR:KIR00556
KIR:KIR00556 KIR3DL3*01308 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00565
KIR:KIR00565 KIR3DL3*01309 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00177
KIR:KIR00177 KIR3DL3*01401 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00186
KIR:KIR00186 KIR3DL3*0140201 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00485
KIR:KIR00485 KIR3DL3*0140202 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00626
KIR:KIR00626 KIR3DL3*0140203 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00187
KIR:KIR00187 KIR3DL3*01403 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00228
KIR:KIR00228 KIR3DL3*01404 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00234
KIR:KIR00234 KIR3DL3*01405 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00381
KIR:KIR00381 KIR3DL3*01406 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00558
KIR:KIR00558 KIR3DL3*01407 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00613
KIR:KIR00613 KIR3DL3*01408 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00189
KIR:KIR00189 KIR3DL3*01501 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFKEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVSF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGT YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00384
KIR:KIR00384 KIR3DL3*01502 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFKEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVSF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGT YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00190
KIR:KIR00190 KIR3DL3*01601 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFKEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVSF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGT YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00386
KIR:KIR00386 KIR3DL3*01602 386 bases
 GQDKPFLSAW PGTVVSEGQH VTLQCRSRLG FKEFSLSKED GMPVPELYNR IFRNSFLMGP
 VTPAHAGTYR CCSSHPHSPT GWSAPSNPVV IMVTGVHRKP SLLAHPGPLV KSGETVILQC
 WSDVSFERFL LHREGITEDP LRLVGQLHDA GSQVNYSMGP MTPALAGTYR CFGSVTHLPY
 ELSAPSDPLD IVVVGLYGKP SLSAQPGPTV QAGENVTLSC SSRSLFDIYH LSREAEAGEL
 RLTAVLRVNG TFQANFPLGP VTHGGTYRCF GSFRALPHAW SDPSDPLPVS VTGNSRYLHA
 LIGTSVVIIP FAILLFFLLH RWCANKKNAV VMDQEPAGNR TVNREDSDEQ DPQEVTYAQL
 NHCVFTQRKI TRPSQRPKTP PTDTSV*   
>P1;KIR:KIR00192
KIR:KIR00192 KIR3DL3*017 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGT YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00193
KIR:KIR00193 KIR3DL3*01801 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVSF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGT YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00608
KIR:KIR00608 KIR3DL3*01802 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVSF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGT YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00194
KIR:KIR00194 KIR3DL3*019 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF EHFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00195
KIR:KIR00195 KIR3DL3*020 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGT YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00196
KIR:KIR00196 KIR3DL3*02101 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVSF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGT YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00215
KIR:KIR00215 KIR3DL3*02102 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVSF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGT YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00197
KIR:KIR00197 KIR3DL3*022 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFKEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGT YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00216
KIR:KIR00216 KIR3DL3*023 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFKEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00217
KIR:KIR00217 KIR3DL3*0250101 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFKEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVSF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGT YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCPNK KNAVVMDQEP
 AGNRTVNRED SDDQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00385
KIR:KIR00385 KIR3DL3*02502 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFKEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVSF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGT YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCPNK KNAVVMDQEP
 AGNRTVNRED SDDQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00219
KIR:KIR00219 KIR3DL3*02601 393 bases
 GPWPHVGGQD KPFLSAWPGT VVSEGQHVTL QCRSHLGFNE FSLSKEDGMP VPELYNRIFR
 NSFLMGPVTP AHAGTYRCCS SHPHSPTGWS APSNPVVIMV TGVHRKPSLL AHPGPLVKSG
 ETVILQCWSD VRFERFLLHR EGITEDPLRL VGQLHDAGSQ VNYSMGPMTP ALAGTYRCFG
 SVTHLPYELS APSDPLDIVV VGLYGKPSLS AQPGPTVQAG ENVTLSCSSR SLFDIYHLSR
 EAEAGELRLT AVLRVNGTFQ ANFPLGPVTH GGNYRCFGSF RALPHAWSDP SDPLPVSVTG
 NSRNLHVLIG TSVVIIPFAI LLFFLLHRWC ANKKNAVVMD QEPAGNRTVN REDSDEQDPQ
 EVTYAQLNHC VFTQRKITRP SQRPKTPPTD TSV*  
>P1;KIR:KIR00919
KIR:KIR00919 KIR3DL3*02602 411 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SHLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV X*
>P1;KIR:KIR00220
KIR:KIR00220 KIR3DL3*02701 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCPNK KNAVVMDQEP
 AGNRTVNRED SDDQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00513
KIR:KIR00513 KIR3DL3*02702 387 bases
 GGQDKPFLSA WPGTVVSEGQ HVTLQCRSRL GFNEFSLSKE DGMPVPELYN RIFRNSFLMG
 PVTPAHAGTY RCCSSHPHSP TGWSAPSNPV VIMVTGVHRK PSLLAHPGPL VKSGETVILQ
 CWSDVRFERF LLHREGITED PLRLVGQLHD AGSQVNYSMG PMTPALAGTY RCFGSVTHLP
 YELSAPSDPL DIVVVGLYGK PSLSAQPGPT VQAGENVTLS CSSRSLFDIY HLSREAEAGE
 LRLTAVLRVN GTFQANFPLG PVTHGGNYRC FGSFRALPHA WSDPSDPLPV SVTGNSRHLH
 VLIGTSVVII PFAILLFFLL HRWCPNKKNA VVMDQEPAGN RTVNREDSDD QDPQEVTYAQ
 LNHCVFTQRK ITRPSQRPKT PPTDTSV*   
>P1;KIR:KIR00553
KIR:KIR00553 KIR3DL3*02703 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCPNK KNAVVMDQEP
 AGNRTVNRED SDDQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00226
KIR:KIR00226 KIR3DL3*028 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFWNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00227
KIR:KIR00227 KIR3DL3*029 393 bases
 GPWPHVGGQD KPFLSAWPGT VVSEGQHVTL QCRSRLGFNE FSLSKEDGMP VPELYNRIFR
 NSFLMGPVTP AHAGTYRCCS SHPHSPTGWS APSNPVVIMV TGVHRKPSLL AHPGPLVKSG
 ETVILQCWSD VRFERFLLHR EGITEDPLRL VGQLHDAGSQ VNYSMGPMTP ALAGTYRCFG
 SVTHLPYELS APSDPLDIVV VGLYGKPSLS AQPGPTVQAG ENVTLSCSSR SLFDIYHLSR
 EAEAGELRLT AVLRVNGTFQ ANFPLGPVTH GGNYRCFGSF RALPHAWSDP SDPLPVSVTG
 NSRHLHDLIG TSVVIIPFAI LLFFLLHRWC PNKKNAVVMD QEPAGNRTVN REDSDDQDPQ
 EVTYAQLNHC VFTQRKITRP SQRPKTPPTD TSV*  
>P1;KIR:KIR00229
KIR:KIR00229 KIR3DL3*030 393 bases
 GPWPHVGGQD KPFLSAWPGT VVSEGQHVTL QCRSRLGFNE FSLSKEDGMP VPELYNRIFR
 NSFLMGPVTP AHAGTYRCCS SHPHSPTGWS APSNPVVIMV TGVHRKPSLL AHPGPLVKSG
 ETVILQCWSD VRFEHFLLHR EGITEDPLRL VGQLHDAGSQ VNYSMGPMTP ALAGTYRCFG
 SVTHLPYELS APSDPLDIVV VGLYGKPSLS AQPGPTVQAG ENVTLSCSSR SLFDIYHLSR
 EAEAGELRLT AVLRVNGTFQ ANFPLGPVTH GGNYRCFGSF RALPHAWSDP SDPLPVSVTG
 NSRHLHVLIG TSVVIIPFAI LLFFLLHRWC ANKKNAVVMD QEPAGNRTVN REDSDEQDPQ
 EVTYAQLNHC VFTQRKITRP SQRPKTPPTD TSV*  
>P1;KIR:KIR00235
KIR:KIR00235 KIR3DL3*031 393 bases
 GPWPHVGGQD KPFLSAWPGT VVSEGQHVTL QCRSRLGFNE FSLSKEDGMP VPELYNRIFR
 NSFLMGPVTP AHAGTYRCCS SHPHSPTGWS APSNPVVIMV TGVHRKPSLL AHPGPLVKSG
 ETVILQCWSD VRFEHFLLHR EGITEDPLRL VGQLHDAGSQ VNYSMGPMTP ALAGTYRCFG
 SVTHLPYELS APSDPLDIVV VGLYGKPSLS AQPGPTVQAG ENVTLSCSSR SLFDIYHLSR
 EAEAGELRLT AVLRVNGTFQ ANFPLGPVTH GGNYRCFGSF RALPHAWSDP SDPLPVSVTG
 NSRHLHVLIG TSVVIIPFAI LLFFLLHRWC PNKKNAVVMD QEPAGNRTVN REDSDDQDPQ
 EVTYAQLNHC VFTQRKITRP SQRPKTPPTD TSV*  
>P1;KIR:KIR00379
KIR:KIR00379 KIR3DL3*032 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GLLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00380
KIR:KIR00380 KIR3DL3*033 386 bases
 GQDKPFLSAW PGTVVSEGQH VTLQCRSHLG FNEFSLSKED GKPVPELYNR IFRNSFLMGP
 VTPAHAGTYR CCSSHPHSPT GWSAPSNPVV IMVTGVHRKP SLLAHPGPLV KSGETVILQC
 WSDVRFERFL LHREGITEDP LRLVGQLHDA GSQVNYSMGP MTPALAGTYR CFGSVTHLPY
 ELSAPSDPLD IVVVGLYGKP SLSAQPGPTV QAGENVTLSC SSRSLFDIYH LSREAEAGEL
 RLTAVLRVNG TFQANFPLGP VTHGGNYRCF GSFRALPHAW SDPSDPLPVS VTGNSRYLHA
 LIGTSVVIIP FAILLFFLLH RWCANKKNAV VMDQEPAGNR TVNREDSDEQ DPQEVTYAQL
 NHCVFTQRKI TRPSQRPKTP PTDTSV*   
>P1;KIR:KIR00387
KIR:KIR00387 KIR3DL3*034 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP DPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00388
KIR:KIR00388 KIR3DL3*035 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP DPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCPNK KNAVVMDQEP
 AGNRTVNRED SDDQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00483
KIR:KIR00483 KIR3DL3*036 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVSF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGT YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00514
KIR:KIR00514 KIR3DL3*037 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLCLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00515
KIR:KIR00515 KIR3DL3*038 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIAVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGT YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00516
KIR:KIR00516 KIR3DL3*039 387 bases
 GGQDKPFLSA WPGTVVSEGQ HVTLQCRSRL GFNEFSLSKE DGMPVPELYN RIFRNSFLMG
 PVTPAHAGTY RCCSSHPHSP TGWPAPSNPV VIMVTGVHRK PSLLAHPGPL VKSGETVILQ
 CWSDVRFERF LLHREGITED PLRLVGQLHD AGSQVNYSMG PMTPALAGTY RCFGSVTHLP
 YELSAPSDPL DIVVVGLYGK PSLSAQPGPT VQAGENVTLS CSSRSLFDIY HLSREAEAGE
 LRLTAVLRVN GTFQANFPLG PVTHGGNYRC FGSFRALPHA WSDPSDPLPV SVTGNSRYLH
 ALIGTSVVII PFAILLFFLL HRWCANKKNA VVMDQEPAGN RTVNREDSDE QDPQEVTYAQ
 LNHCVFTQRK ITRPSQRPKT PPTDTSV*   
>P1;KIR:KIR00517
KIR:KIR00517 KIR3DL3*040 387 bases
 GGQDKPFLSA WPGTVVSEGQ HVTLQCRSRL GFNEFSLSKE DGMPVPELYN RIFRNSFLMG
 PVTPAHAGTY RCCSSHPHSP TGWSAPSNPV VIMVTGVHRK PSLLAHPGPL VKSGETVILQ
 CWSDVRFERF LLHREGITED PLRLVGQLHD AGSQVNYSMG PMTPALAGTY RCFGSVTHLP
 YELSAPSDPL DIVVVGLYGK PSLSAQPGPT VQAGENVTLS CSSRSLFDIY HLSREAEAGE
 LRLTAVLRVN GTFQANFPLG PVTHGGNYRC FGSFRALPHA WSDPSDPLPI SVTGNSRHLH
 VLIGTSVVII PFAILLFFLL HRWCPNKKNA VVMDQEPAGN RTVNREDSDD QDPQEVTYAQ
 LNHCVFTQRK ITRPSQRPKT PPTDTSV*   
>P1;KIR:KIR00551
KIR:KIR00551 KIR3DL3*041 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCPNK KNAVVMDQEP
 AGNRTVNRED SDDQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00552
KIR:KIR00552 KIR3DL3*042 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP DPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00555
KIR:KIR00555 KIR3DL3*043 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHA HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00557
KIR:KIR00557 KIR3DL3*044 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVDL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00561
KIR:KIR00561 KIR3DL3*045 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPRDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00562
KIR:KIR00562 KIR3DL3*046 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLHLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00564
KIR:KIR00564 KIR3DL3*047 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTMVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00641
KIR:KIR00641 KIR3DL3*048 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFWNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00917
KIR:KIR00917 KIR3DL3*04802 411 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFWNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV X*
>P1;KIR:KIR00605
KIR:KIR00605 KIR3DL3*04901 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SHLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCPNK KNAVVMDQEP
 AGNRTVNRED SDDQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00791
KIR:KIR00791 KIR3DL3*04902 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SHLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCPNK KNAVVMDQEP
 AGNRTVNRED SDDQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00606
KIR:KIR00606 KIR3DL3*050 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPISVTGNSR YLHALIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00607
KIR:KIR00607 KIR3DL3*051 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFKEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00609
KIR:KIR00609 KIR3DL3*052 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWPAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00610
KIR:KIR00610 KIR3DL3*053 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPISVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00611
KIR:KIR00611 KIR3DL3*054 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLMKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00614
KIR:KIR00614 KIR3DL3*055 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFQNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP DPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00662
KIR:KIR00662 KIR3DL3*056 387 bases
 GGQDKPFLSA WPGTVVSEGQ HVTLQCRSRL GFNEFSLSKE DGMPVPELYN RIFRNSFLMG
 PVTPAHAGTY RCCSSHPHSP TGWSAPSNPV VIMVTGVHRK PSLLAHPGPL VKSGETVILQ
 CWSDVRFERF LLHREGITED PLRLVGQLHD AGSQVNYSMG PMTPALAGTY RCFGSVTHLP
 YELSAPSDPL DIVVVGLYGK PSLSAQPGPT VQAGENVTLS CSSRSLFDIY HLSREAEAGE
 LRLTAVLRVN GTFQANFPLG PVTHGGTYRC FGSFRALPHA WSDPSDPLPV SVTGNSRHLH
 VLIGTSVVII PFAILLFFLL HRWCPNKKNA VVMDQEPAGN RTVNREDSDD QDPQEVTYAQ
 LNHCVFTQRK ITRPSQRPKT PPTDTSV*   
>P1;KIR:KIR00669
KIR:KIR00669 KIR3DL3*057 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SHLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGT YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00792
KIR:KIR00792 KIR3DL3*058 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILRCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGT YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCPNK KNAVVMDQEP
 AGNRTVNRED SDDQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00833
KIR:KIR00833 KIR3DL3*059 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWPAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00835
KIR:KIR00835 KIR3DL3*060 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFWNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDDQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00837
KIR:KIR00837 KIR3DL3*061 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GLLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR HLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDDQDPQEVT YAQLNHCVFT QRKITRPSQR PKTPPTDTSV *
>P1;KIR:KIR00920
KIR:KIR00920 KIR3DL3*062 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SHLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKIIRPSQR PKTPPTDTSV *
>P1;KIR:KIR00918
KIR:KIR00918 KIR3DL3*063 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFWNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKIIRPSQR PKTPPTDTSV *
>P1;KIR:KIR00921
KIR:KIR00921 KIR3DL3*064 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFKEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVSF ERFLLHREGI TEDPLRLVGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGT YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKIIRPSQR PKTPPTDTSV *
>P1;KIR:KIR00922
KIR:KIR00922 KIR3DL3*065 410 bases
 MSLMVVSMAC VGFFLLEGPW PHVGGQDKPF LSAWPGTVVS EGQHVTLQCR SRLGFNEFSL
 SKEDGMPVPE LYNRIFRNSF LMGPVTPAHA GTYRCCSSHP HSPTGWSAPS NPVVIMVTGV
 HRKPSLLAHP GPLVKSGETV ILQCWSDVRF ERFLLHREGI TEDPLRLIGQ LHDAGSQVNY
 SMGPMTPALA GTYRCFGSVT HLPYELSAPS DPLDIVVVGL YGKPSLSAQP GPTVQAGENV
 TLSCSSRSLF DIYHLSREAE AGELRLTAVL RVNGTFQANF PLGPVTHGGN YRCFGSFRAL
 PHAWSDPSDP LPVSVTGNSR NLHVLIGTSV VIIPFAILLF FLLHRWCANK KNAVVMDQEP
 AGNRTVNRED SDEQDPQEVT YAQLNHCVFT QRKIIRPSQR PKTPPTDTSV *
