>P1;KIR:KIR00082
KIR:KIR00082 KIR3DS1*010 387 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKNA AVMDQEPAGN RSEQRGF*   
>P1;KIR:KIR00083
KIR:KIR00083 KIR3DS1*011 383 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSPQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00084
KIR:KIR00084 KIR3DS1*012 383 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSHLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00085
KIR:KIR00085 KIR3DS1*0130101 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00489
KIR:KIR00489 KIR3DS1*0130102 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00488
KIR:KIR00488 KIR3DS1*0130103 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00708
KIR:KIR00708 KIR3DS1*0130104 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00709
KIR:KIR00709 KIR3DS1*0130105 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00710
KIR:KIR00710 KIR3DS1*0130106 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00711
KIR:KIR00711 KIR3DS1*0130107 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00713
KIR:KIR00713 KIR3DS1*0130108 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00715
KIR:KIR00715 KIR3DS1*0130109 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00717
KIR:KIR00717 KIR3DS1*0130110 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00719
KIR:KIR00719 KIR3DS1*0130111 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00164
KIR:KIR00164 KIR3DS1*01302 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00667
KIR:KIR00667 KIR3DS1*01303 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00853
KIR:KIR00853 KIR3DS1*01304 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00887
KIR:KIR00887 KIR3DS1*01305 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00891
KIR:KIR00891 KIR3DS1*01306 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00896
KIR:KIR00896 KIR3DS1*01307 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00086
KIR:KIR00086 KIR3DS1*014 382 bases
 MLLMVVSMAC VGFFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QK*   
>P1;KIR:KIR00165
KIR:KIR00165 KIR3DS1*045 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP PLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00166
KIR:KIR00166 KIR3DS1*046 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKASF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00167
KIR:KIR00167 KIR3DS1*047 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SISSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00168
KIR:KIR00168 KIR3DS1*048 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFHHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00146
KIR:KIR00146 KIR3DS1*049N 185 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKTPHASLDR SMMGSPRPIS
 PSVPX*     
>P1;KIR:KIR00236
KIR:KIR00236 KIR3DS1*050 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YHHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00243
KIR:KIR00243 KIR3DS1*055 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHREWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00261
KIR:KIR00261 KIR3DS1*058 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDNPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00751
KIR:KIR00751 KIR3DS1*078 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSRERG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00749
KIR:KIR00749 KIR3DS1*082 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CRNGPRACRE QKX*   
>P1;KIR:KIR00750
KIR:KIR00750 KIR3DS1*083 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00752
KIR:KIR00752 KIR3DS1*084 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSLTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00753
KIR:KIR00753 KIR3DS1*085 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LFVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00852
KIR:KIR00852 KIR3DS1*104 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESM
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00856
KIR:KIR00856 KIR3DS1*105 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMRPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00858
KIR:KIR00858 KIR3DS1*106 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGEHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00871
KIR:KIR00871 KIR3DS1*107 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS FKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
>P1;KIR:KIR00874
KIR:KIR00874 KIR3DS1*108 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYRCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX*   
