>P1;KIR:KIR00082
KIR:KIR00082 KIR3DS1*010 387 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKNA AVMDQEPAGN RSEQRGF   
>P1;KIR:KIR00083
KIR:KIR00083 KIR3DS1*011 383 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSPQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00084
KIR:KIR00084 KIR3DS1*012 383 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSHLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00086
KIR:KIR00086 KIR3DS1*014 383 bases
 MLLMVVSMAC VGFFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00165
KIR:KIR00165 KIR3DS1*045 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP PLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00166
KIR:KIR00166 KIR3DS1*046 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKASF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00167
KIR:KIR00167 KIR3DS1*047 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SISSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00168
KIR:KIR00168 KIR3DS1*048 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFHHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00236
KIR:KIR00236 KIR3DS1*050 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YHHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00243
KIR:KIR00243 KIR3DS1*055 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHREWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00261
KIR:KIR00261 KIR3DS1*058 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDNPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00751
KIR:KIR00751 KIR3DS1*078 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSRERG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00749
KIR:KIR00749 KIR3DS1*082 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CRNGPRACRE QKX   
>P1;KIR:KIR00750
KIR:KIR00750 KIR3DS1*083 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00752
KIR:KIR00752 KIR3DS1*084 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSLTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00753
KIR:KIR00753 KIR3DS1*085 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LFVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00852
KIR:KIR00852 KIR3DS1*104 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESM
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00856
KIR:KIR00856 KIR3DS1*105 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMRPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00858
KIR:KIR00858 KIR3DS1*106 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGEHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00871
KIR:KIR00871 KIR3DS1*107 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS FKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00874
KIR:KIR00874 KIR3DS1*108 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYRCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01675
KIR:KIR01675 KIR3DS1*122 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLLKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01637
KIR:KIR01637 KIR3DS1*126 388 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QNSEQRGF   
>P1;KIR:KIR01632
KIR:KIR01632 KIR3DS1*129 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTIFLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01669
KIR:KIR01669 KIR3DS1*131 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVP KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01668
KIR:KIR01668 KIR3DS1*132 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSN DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01647
KIR:KIR01647 KIR3DS1*134 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DTYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01646
KIR:KIR01646 KIR3DS1*135 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKLQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01652
KIR:KIR01652 KIR3DS1*136 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLIGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00164
KIR:KIR00164 KIR3DS1*01302 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00667
KIR:KIR00667 KIR3DS1*01303 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00853
KIR:KIR00853 KIR3DS1*01304 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00887
KIR:KIR00887 KIR3DS1*01305 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00891
KIR:KIR00891 KIR3DS1*01306 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00896
KIR:KIR00896 KIR3DS1*01307 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01639
KIR:KIR01639 KIR3DS1*01308 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01666
KIR:KIR01666 KIR3DS1*01309 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01665
KIR:KIR01665 KIR3DS1*01310 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01649
KIR:KIR01649 KIR3DS1*01311 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01651
KIR:KIR01651 KIR3DS1*01312 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01658
KIR:KIR01658 KIR3DS1*01313 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01664
KIR:KIR01664 KIR3DS1*01314 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00146
KIR:KIR00146 KIR3DS1*04901N 185 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKTPHASLDR SMMGSPRPIS
 PSVPX     
>P1;KIR:KIR01630
KIR:KIR01630 KIR3DS1*04902N 185 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKTPHASLDR SMMGSPRPIS
 PSVPX     
>P1;KIR:KIR00085
KIR:KIR00085 KIR3DS1*0130101 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00489
KIR:KIR00489 KIR3DS1*0130102 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00488
KIR:KIR00488 KIR3DS1*0130103 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00708
KIR:KIR00708 KIR3DS1*0130104 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00709
KIR:KIR00709 KIR3DS1*0130105 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00710
KIR:KIR00710 KIR3DS1*0130106 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00711
KIR:KIR00711 KIR3DS1*0130107 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00713
KIR:KIR00713 KIR3DS1*0130108 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00715
KIR:KIR00715 KIR3DS1*0130109 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00717
KIR:KIR00717 KIR3DS1*0130110 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR00719
KIR:KIR00719 KIR3DS1*0130111 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01641
KIR:KIR01641 KIR3DS1*0130112 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01672
KIR:KIR01672 KIR3DS1*0130113 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01635
KIR:KIR01635 KIR3DS1*0130114 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01638
KIR:KIR01638 KIR3DS1*0130115 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01678
KIR:KIR01678 KIR3DS1*0130116 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01631
KIR:KIR01631 KIR3DS1*0130117 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01667
KIR:KIR01667 KIR3DS1*0130118 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01659
KIR:KIR01659 KIR3DS1*0130119 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01648
KIR:KIR01648 KIR3DS1*0130120 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01653
KIR:KIR01653 KIR3DS1*0130121 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01661
KIR:KIR01661 KIR3DS1*0130122 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01656
KIR:KIR01656 KIR3DS1*0130123 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01657
KIR:KIR01657 KIR3DS1*0130124 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01662
KIR:KIR01662 KIR3DS1*0130125 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01654
KIR:KIR01654 KIR3DS1*0130126 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01633
KIR:KIR01633 KIR3DS1*0130127 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01670
KIR:KIR01670 KIR3DS1*0130128 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01634
KIR:KIR01634 KIR3DS1*0130129 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01629
KIR:KIR01629 KIR3DS1*0130130 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01644
KIR:KIR01644 KIR3DS1*0130131 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01674
KIR:KIR01674 KIR3DS1*0130132 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01676
KIR:KIR01676 KIR3DS1*1230101 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01673
KIR:KIR01673 KIR3DS1*1230102 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01642
KIR:KIR01642 KIR3DS1*1230103 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01677
KIR:KIR01677 KIR3DS1*1240101 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERMLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01650
KIR:KIR01650 KIR3DS1*1240102 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERMLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01679
KIR:KIR01679 KIR3DS1*1250101 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFSSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01643
KIR:KIR01643 KIR3DS1*1250102 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFSSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01645
KIR:KIR01645 KIR3DS1*1270101 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHEHRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01671
KIR:KIR01671 KIR3DS1*1270102 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHEHRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01636
KIR:KIR01636 KIR3DS1*1280101 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKS CCNGPRACRE QKX   
>P1;KIR:KIR01655
KIR:KIR01655 KIR3DS1*1280102 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKS CCNGPRACRE QKX   
>P1;KIR:KIR01680
KIR:KIR01680 KIR3DS1*1300101 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KINRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01663
KIR:KIR01663 KIR3DS1*1300102 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KINRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01660
KIR:KIR01660 KIR3DS1*1330101 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVC KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
>P1;KIR:KIR01640
KIR:KIR01640 KIR3DS1*1330102 383 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVC KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNLRHLH ILIGTSVVKI PFTILLFFLL
 HRWCSNKKKC CCNGPRACRE QKX   
