>P1;KIR:KIR00054
KIR:KIR00054 KIR3DL1*0010101 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00434
KIR:KIR00434 KIR3DL1*0010102 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00761
KIR:KIR00761 KIR3DL1*0010103 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00055
KIR:KIR00055 KIR3DL1*00102 417 bases
 KPFLSAWPSA VVPRGGHVTL RCHYRHRFNN FMLYKEDRIH IPIFHGRIFQ ESFNMSPVTT
 AHAGNYTCRG SHPHSPTGWS APSNPVVIMV TGNHRKPSLL AHPGPLVKSG ERVILQCWSD
 IMFEHFFLHK EGISKDPSRL VGQIHDGVSK ANFSIGPMML ALAGTYRCYG SVTHTPYQLS
 APSDPLDIVV TGPYEKPSLS AQPGPKVQAG ESVTLSCSSR SSYDMYHLSR EGGAHERRLP
 AVRKVNRTFQ ADFPLGPATH GGTYRCFGSF RHSPYEWSDP SDPLLVSVTG NPSSSWPSPT
 EPSSKSGNPR HLHILIGTSV VIILFILLLF FLLHLWCSNK KNAAVMDQEP AGNRTANSED
 SDEQDPEEVT YAQLDHCVFT QRKITRPSQR PKTPPTDTIL YTELPNAKPR SKVVSCP*
>P1;KIR:KIR00809
KIR:KIR00809 KIR3DL1*00103 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00857
KIR:KIR00857 KIR3DL1*00104 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00877
KIR:KIR00877 KIR3DL1*00105 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00056
KIR:KIR00056 KIR3DL1*002 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSRERG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00058
KIR:KIR00058 KIR3DL1*0040101 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YHHRFNNFML
 YKEDGIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWLAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWYSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00758
KIR:KIR00758 KIR3DL1*0040102 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YHHRFNNFML
 YKEDGIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWLAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWYSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00762
KIR:KIR00762 KIR3DL1*0040103 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YHHRFNNFML
 YKEDGIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWLAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWYSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00059
KIR:KIR00059 KIR3DL1*00402 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YHHRFNNFML
 YKEDGIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWLAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWYSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00526
KIR:KIR00526 KIR3DL1*00403 434 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YHHRFNNFML
 YKEDGIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWLAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWYSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNA*    
>P1;KIR:KIR00854
KIR:KIR00854 KIR3DL1*00404 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YHHRFNNFML
 YKEDGIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWLAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWYSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00060
KIR:KIR00060 KIR3DL1*0050101 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00456
KIR:KIR00456 KIR3DL1*0050102 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00707
KIR:KIR00707 KIR3DL1*0050103 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00716
KIR:KIR00716 KIR3DL1*0050104 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00718
KIR:KIR00718 KIR3DL1*0050105 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00160
KIR:KIR00160 KIR3DL1*00502 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00673
KIR:KIR00673 KIR3DL1*00503 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00855
KIR:KIR00855 KIR3DL1*00504 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00873
KIR:KIR00873 KIR3DL1*00505 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00061
KIR:KIR00061 KIR3DL1*006 444 bases
 MLLMVVSMAC VGFFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFCHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00062
KIR:KIR00062 KIR3DL1*0070101 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00639
KIR:KIR00639 KIR3DL1*0070102 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00712
KIR:KIR00712 KIR3DL1*0070103 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00714
KIR:KIR00714 KIR3DL1*0070104 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00063
KIR:KIR00063 KIR3DL1*008 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YHHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00064
KIR:KIR00064 KIR3DL1*009 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00102
KIR:KIR00102 KIR3DL1*0150101 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00754
KIR:KIR00754 KIR3DL1*0150102 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00755
KIR:KIR00755 KIR3DL1*0150103 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00057
KIR:KIR00057 KIR3DL1*0150201 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00479
KIR:KIR00479 KIR3DL1*0150202 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00480
KIR:KIR00480 KIR3DL1*0150203 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00720
KIR:KIR00720 KIR3DL1*0150204 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00722
KIR:KIR00722 KIR3DL1*0150205 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00724
KIR:KIR00724 KIR3DL1*0150206 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00725
KIR:KIR00725 KIR3DL1*0150207 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00726
KIR:KIR00726 KIR3DL1*0150208 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00727
KIR:KIR00727 KIR3DL1*0150209 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00728
KIR:KIR00728 KIR3DL1*0150210 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00759
KIR:KIR00759 KIR3DL1*0150211 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00760
KIR:KIR00760 KIR3DL1*0150212 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00501
KIR:KIR00501 KIR3DL1*01503 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00676
KIR:KIR00676 KIR3DL1*01504 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00742
KIR:KIR00742 KIR3DL1*01505 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00872
KIR:KIR00872 KIR3DL1*01506 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00104
KIR:KIR00104 KIR3DL1*016 444 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00105
KIR:KIR00105 KIR3DL1*01701 444 bases
 MLLMVVSMAC VGFFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00233
KIR:KIR00233 KIR3DL1*01702 422 bases
 MLLMVVSMAC VGFFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PP*     
>P1;KIR:KIR00106
KIR:KIR00106 KIR3DL1*018 420 bases
 MSLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 *     
>P1;KIR:KIR00108
KIR:KIR00108 KIR3DL1*019 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH CHHRFNNFML
 YKEDGIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWLAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWYSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00133
KIR:KIR00133 KIR3DL1*0200101 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSSLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00723
KIR:KIR00723 KIR3DL1*0200102 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSSLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00144
KIR:KIR00144 KIR3DL1*021 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YHHRFNNFML
 YKEDGIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWLAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGDRV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWYSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00145
KIR:KIR00145 KIR3DL1*022 444 bases
 MLLMVVSMAC VGFFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFCHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00147
KIR:KIR00147 KIR3DL1*023 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGRDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSSLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00148
KIR:KIR00148 KIR3DL1*024N 185 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGR SMMGSPRPIS
 PSVPX*     
>P1;KIR:KIR00149
KIR:KIR00149 KIR3DL1*0250101 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00756
KIR:KIR00756 KIR3DL1*0250102 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00757
KIR:KIR00757 KIR3DL1*0250103 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00150
KIR:KIR00150 KIR3DL1*026 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEASDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00151
KIR:KIR00151 KIR3DL1*02701 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP QGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00745
KIR:KIR00745 KIR3DL1*02702 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP QGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00152
KIR:KIR00152 KIR3DL1*028 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCWGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSSLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00153
KIR:KIR00153 KIR3DL1*0290101 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFKADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00638
KIR:KIR00638 KIR3DL1*0290102 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFKADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00154
KIR:KIR00154 KIR3DL1*030 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHT HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00155
KIR:KIR00155 KIR3DL1*0310101 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAEPRSKV VSCP*   
>P1;KIR:KIR00763
KIR:KIR00763 KIR3DL1*0310102 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAEPRSKV VSCP*   
>P1;KIR:KIR00506
KIR:KIR00506 KIR3DL1*03102 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAEPRSKV VSCP*   
>P1;KIR:KIR00156
KIR:KIR00156 KIR3DL1*032 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLAGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00157
KIR:KIR00157 KIR3DL1*033 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SEDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00158
KIR:KIR00158 KIR3DL1*034 444 bases
 MLLMVVSMAC VGFFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFCHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAEPRSKV VSCP*   
>P1;KIR:KIR00159
KIR:KIR00159 KIR3DL1*035 444 bases
 MLLMVVSMAC VGFFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSRDGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFCHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00747
KIR:KIR00747 KIR3DL1*03502 444 bases
 MLLMVVSMAC VGFFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSRDGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFCHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00162
KIR:KIR00162 KIR3DL1*036 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YHRRFNNFML
 YKEDGIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWLAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWYSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00163
KIR:KIR00163 KIR3DL1*037 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YHHRFNNFML
 YKEDGIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWLAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKTSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWYSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00169
KIR:KIR00169 KIR3DL1*038 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGETV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFKADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00170
KIR:KIR00170 KIR3DL1*039 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YHHRFNNFML
 YKEDGIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSRP HSPTGWLAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWYSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00171
KIR:KIR00171 KIR3DL1*040 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YHHRFNNFML
 YKEDGIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGL YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00172
KIR:KIR00172 KIR3DL1*041 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00173
KIR:KIR00173 KIR3DL1*042 444 bases
 MLLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00174
KIR:KIR00174 KIR3DL1*043 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGETV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00161
KIR:KIR00161 KIR3DL1*044 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGDQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00238
KIR:KIR00238 KIR3DL1*051 444 bases
 MSLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00239
KIR:KIR00239 KIR3DL1*052 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSQSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00240
KIR:KIR00240 KIR3DL1*053 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVLP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00241
KIR:KIR00241 KIR3DL1*054 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEWI SKDPSRLVGQ IHDGVSKANF
 SIGSMMRALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSRERG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00250
KIR:KIR00250 KIR3DL1*056 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YHHRFNNFML
 YKEDGIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWLAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA ETYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWYSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00251
KIR:KIR00251 KIR3DL1*057 333 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRIFQEGF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPMVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSCLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKS*  
>P1;KIR:KIR00311
KIR:KIR00311 KIR3DL1*05901 456 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVFX*  
>P1;KIR:KIR00860
KIR:KIR00860 KIR3DL1*05902 456 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVFX*  
>P1;KIR:KIR00312
KIR:KIR00312 KIR3DL1*060 456 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPCQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVFX*  
>P1;KIR:KIR00310
KIR:KIR00310 KIR3DL1*061 456 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCIFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVFX*  
>P1;KIR:KIR00454
KIR:KIR00454 KIR3DL1*062 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSSLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00455
KIR:KIR00455 KIR3DL1*063 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YHHRFNNFML
 YKEDGIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWYSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00500
KIR:KIR00500 KIR3DL1*064 434 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ NHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNA*    
>P1;KIR:KIR00502
KIR:KIR00502 KIR3DL1*065 453 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEG*  
>P1;KIR:KIR00503
KIR:KIR00503 KIR3DL1*066 444 bases
 MLLMVVSMAC VGFFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMTPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00504
KIR:KIR00504 KIR3DL1*067 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA VVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00505
KIR:KIR00505 KIR3DL1*068 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYTQ LNHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00508
KIR:KIR00508 KIR3DL1*069 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YHHRFNNFML
 YKEDGIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWYSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00509
KIR:KIR00509 KIR3DL1*070 421 bases
 GGQDKPFLSA WPSAVVPRGG HVTLRCHYRH RFNNFMLYKE DRIHVPIFHG RLFQESFNMS
 PVTTAHAGNY TCRGSHPHSP TGWSAPSNPL VIMVTGNHRK PSLLAHPGPL VKSGERVILQ
 CWSDIMFEHF FLHKEGISKD PSRLVGQIHD GVSKANFSIG PMMLALAGTY RCYGSVTHTP
 YQLSAPSDPL DIVVTGPYEK PSLSAQPGPK VQAGESVTLS CSSRSSYDMY HLSREGGAHE
 RRLPAVRKVN RTFQADFPLG PATHGGTYRC FGSFRHSPYE WSDPSDPLLV SVTGNPSSSW
 PSPTEPSSKS GNPRHLHILI GTSVVIILFI LLLFFLLHLW CSNKKNAAVM DQEPAGNRTA
 NSEDSDEQDP EEVTYAQLDH CVFTQRKITR PSQRPKTPPT DTILYTELPN AKPRSKVVSC
 P*     
>P1;KIR:KIR00511
KIR:KIR00511 KIR3DL1*071 421 bases
 GGQDKPFLSA WPSAVVPRGG HVTLRCHYRH RFNNFMLYKE DRIHVPIFHG RLFQESFNMS
 PVTTAHAGNY TCRGSHPHSP TGWSAPSNPL VIMVTGNHRK PSLLAHPGPL VKSGERVILQ
 CWSDIMFEHF FLHKEGISKD PSRLVGQIHD GVSKANFSIG PMMLALAGTY RCYGSVTHTP
 YQLSAPSDPL DIVVTGPYEK PSLSAQPGPK VQAGESVTLS CSSRSSYDMY HLSRDGGAHE
 RRLPAVRKVN RTFQADFPLG PATHGGTYRC FGSFCHSPYE WSDPSDPLLV SVTGNPSSSW
 PSPTEPSSKS GNPRHLHILI GTSVVIILFI LLLFFLLHLW CSNKKNAAVM DQEPAGNRTA
 NSEDSDEQDP EEVTYAQLDH CVFTQRKITR PSQRPKTPPT DTILYTELPN AKPRSKVVSC
 P*     
>P1;KIR:KIR00527
KIR:KIR00527 KIR3DL1*072 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YHHRFNNFML
 YKEDGIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWLAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLIGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWYSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00528
KIR:KIR00528 KIR3DL1*073 434 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVLP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTTYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNA*    
>P1;KIR:KIR00681
KIR:KIR00681 KIR3DL1*074 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTGHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSSLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00679
KIR:KIR00679 KIR3DL1*075 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00701
KIR:KIR00701 KIR3DL1*076 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HRWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00730
KIR:KIR00730 KIR3DL1*077 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPTVLAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00743
KIR:KIR00743 KIR3DL1*079 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVIDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00744
KIR:KIR00744 KIR3DL1*080 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSPVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00746
KIR:KIR00746 KIR3DL1*081N 150 bases
 MLLMVVSMAC VGFFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWGTQQ PRGDHGHRKP
 QKTFPPGPPR SPGEIRRESH PAMLVRYHVX *  
>P1;KIR:KIR00767
KIR:KIR00767 KIR3DL1*086 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP QGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAAS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMFALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00766
KIR:KIR00766 KIR3DL1*087 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYVQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00810
KIR:KIR00810 KIR3DL1*088 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSSLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00811
KIR:KIR00811 KIR3DL1*089 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGRMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00812
KIR:KIR00812 KIR3DL1*090 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSARPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSSLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00813
KIR:KIR00813 KIR3DL1*091 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YHHRFNNFML
 YKEDGIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWLAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWYSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITCPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00814
KIR:KIR00814 KIR3DL1*092 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRDA
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00815
KIR:KIR00815 KIR3DL1*093 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSACPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00816
KIR:KIR00816 KIR3DL1*094N 40 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP * 
>P1;KIR:KIR00851
KIR:KIR00851 KIR3DL1*095 444 bases
 MSLMVVSMAC VGLFLVQRAG PHTGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00866
KIR:KIR00866 KIR3DL1*096 444 bases
 MLLMVVSMAC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLIGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00867
KIR:KIR00867 KIR3DL1*097 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSERPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00868
KIR:KIR00868 KIR3DL1*098 456 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF SLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVFX*  
>P1;KIR:KIR00869
KIR:KIR00869 KIR3DL1*099 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIVF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00859
KIR:KIR00859 KIR3DL1*100 444 bases
 MLLMVVSMAC VGFFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRSHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSRDGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFCHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00870
KIR:KIR00870 KIR3DL1*101 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGERV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00875
KIR:KIR00875 KIR3DL1*102 444 bases
 MLLMVVSMVC VGFFLVQRAG PHVGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHVPI FHGRLFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH VLIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPQEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00876
KIR:KIR00876 KIR3DL1*103 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKEPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTPYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYEWSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEPAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
>P1;KIR:KIR00890
KIR:KIR00890 KIR3DL1*109 444 bases
 MSLMVVSMAC VGLFLVQRAG PHMGGQDKPF LSAWPSAVVP RGGHVTLRCH YRHRFNNFML
 YKEDRIHIPI FHGRIFQESF NMSPVTTAHA GNYTCRGSHP HSPTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLVKSGERV ILQCWSDIMF EHFFLHKEGI SKDPSRLVGQ IHDGVSKANF
 SIGPMMLALA GTYRCYGSVT HTSYQLSAPS DPLDIVVTGP YEKPSLSAQP GPKVQAGESV
 TLSCSSRSSY DMYHLSREGG AHERRLPAVR KVNRTFQADF PLGPATHGGT YRCFGSFRHS
 PYELSDPSDP LLVSVTGNPS SSWPSPTEPS SKSGNPRHLH ILIGTSVVII LFILLLFFLL
 HLWCSNKKNA AVMDQEHAGN RTANSEDSDE QDPEEVTYAQ LDHCVFTQRK ITRPSQRPKT
 PPTDTILYTE LPNAKPRSKV VSCP*   
