>DL;IPD:KIR00087
KIR:KIR00087 KIR3DP1*001 949 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTC CTCTCTGCCT GGCCCAGCCC TGTGGTGTCT
 GAAGGAGAAC ATGTGGCTCT TCAGTGTCGC TCTCGTCTTG GGTTTAACGA ATTCAGTCTG
 TCCAAAGAAG ACGGGATGCC TGTCCCTGAG CTCTACAACA GAGTATTCCG AAACACCGTT
 TTCATAGGCC CTGTGACCCC AGCACATGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CACTTCCTCA CTGGGTGGTC AGCACCCAGC AACCCCCTGG TGATCATGGT CACAGGAGTC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGA AGAGACAGTC
 ATCCTGCAAT GTTGGTCAGA TGTCATGTTT GAGCACTTCC TTCTGCACAG AGAGGGGAAG
 TTTAATGACA CTTTGCGCCT CACTGGAGAG CTCCATGATG GGGTCTCCAA GGCCAACTTC
 TCCATCGGTC GCATGACGCA AGACCTTGCA GGGACCTACA GATGCTACGG TTCTGTTCCT
 CATTCCCCCT ATCAGTTGTC AGCTCCCAGT GACCCTCTGG ACATCGTGAT TACAGGTCTA
 TGTGGGAAAC CTTCTCTCTC AGCCCAGCCG CGCCCCATGG TTAAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GCAGCTCCCG GAGCTCCTAT GACATCTACC ATCTATCAAG GGAGGGGGAG
 GCTCATGAAC TTAGGTTCCC TGCAGTGCCC AAGGTCAATG GAACCTTCCA GGCCAACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTGACTCT
 CCCTACGAGT GGTCAGACCT TAGTGACCCA CTGCTTGTTT CTGTCACAG* 
>DL;IPD:KIR00093
KIR:KIR00093 KIR3DP1*002 949 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTC CTCTCTGCCT GGCCCAGCCC TGTGGTGTCT
 GAAGGAGAAC ATGTGGCTCT TCAGTGTCGC TCTCGTCTTG GGTTTAACGA ATTCAGTCTG
 TCCAAAGAAG ACGGGATGCC TGTCCCTGAG CTCTACAACA GAGTATTCCG AAACACCGTT
 TTCATAGGCC CTGTGACCCC AGCACATGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CACTTCCTCA CTGGGTGGTC AGCACCCAGC AACCCCCTGG TGATCATGGT CACAGGAGTC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGA AGAGACAGTC
 ATCCTGCAAT GTTGGTCAGA TGTCATGTTT GAGCACTTCC TTCTGCACAG AGAGGGGAAG
 TTTAATGACA CTTTGCGCCT CACTGGAGAG CTCCATGATG GGGTCTCCAA GGCCAACTTC
 TCCATCGGTC GCATGACGCA AGACCTTGCA GGGACCTACA GATGCTACGG TTCTGTTCCT
 CATTCCCCCT ATCAGTTGTC AGCTCCCAGT GACCCTCTGG ACATCGTGAT TACAGGTCTA
 TGTGGGAAAC CTTCTCTCTC AGCCCAGCCG CGCCCCATGG TTAAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GCAGCTCCCG GAGCTCCTAT GACATCTACC ATCTATCAAG GGACGGGGAG
 GCTCATGAAC TTAGGTTCCC TGCAGTGCCC AAGGTCAATG GAACCTTCCA GGCCAACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTGACTCT
 CCCTACGAGT GGTCAGACCT TAGTGACCCA CTGCTTGTTT CTGTCACAG* 
>DL;IPD:KIR00088
KIR:KIR00088 KIR3DP1*0030101 913 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGTGGTC AGGACAAGCC CTTCCTCTCT
 GCCTGGCCCA GCCCCGTGGT GTCTGAAGGA GAACATGTGG CTCTTCAGTG TCGCTCTCGT
 CTTGGGTTTA ACGAATTCAG TCTGTCCAAA GAAGACGGGA TGCCTGTCCC TGAGCTCTAC
 AACAGAGTAT TCCGAAACAC CGTTTTCATA GGCCCTGTGA CCCCAGCACA TGCAGGGACC
 TACAGATGTC GGGGTTCACA CCCACACTTC CTCACTGGGT GGTCAGCACC CAGCAACCCC
 CTGGTGATCA TGGTCACAGG AGTCCACAGA AAACCTTCCC TCCTGGCCCA CCCAGGTCCC
 CTGGTGAAAT CAGAAGAGAC AGTCATCCTG CAATGTTGGT CAGATGTCAT GTTTGAGCAC
 TTCCTTCTGC ACAGAGAGGG GAAGTTTAAT GACACTTTGC GCCTCACTGG AGAGCTCCAT
 GATGGGGTCT CCAAGGCCAA CTTCTCCATC GGTCGCATGA CGCAAGACCT TGCAGGGACC
 TACAGATGCT ACGGTTCTGT TCCTCATTCC CCCTATCAGT TGTCAGCTCC CAGTGACCCT
 CTGGACATCG TGATTACAGG TCTATGTGGG AAACCTTCTC TCTCAGCCCA GCCGCGCCCC
 ATGGTTAAGG CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATC
 TACCATCTAT CAAGGGAGGG GGAGGCTCAT GAACTTAGGT TCCCTGCAGT GCCCAAGGTC
 AATGGAACCT TCCAGGCCAA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG GACCTACAGA
 TGCTTCGGCT CTTTCCGTGA CTCTCCCTAC GAGTGGTCAG ACCTTAGTGA CCCACTGCTT
 GTTTCTGTCA CAG*    
>DL;IPD:KIR00467
KIR:KIR00467 KIR3DP1*0030102 913 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGTGGTC AGGACAAGCC CTTCCTCTCT
 GCCTGGCCCA GCCCCGTGGT GTCTGAAGGA GAACATGTGG CTCTTCAGTG TCGCTCTCGT
 CTTGGGTTTA ACGAATTCAG TCTGTCCAAA GAAGACGGGA TGCCTGTCCC TGAGCTCTAC
 AACAGAGTAT TCCGAAACAC CGTTTTCATA GGCCCTGTGA CCCCAGCACA TGCAGGGACC
 TACAGATGTC GGGGTTCACA CCCACACTTC CTCACTGGGT GGTCAGCACC CAGCAACCCC
 CTGGTGATCA TGGTCACAGG AGTCCACAGA AAACCTTCCC TCCTGGCCCA CCCAGGTCCC
 CTGGTGAAAT CAGAAGAGAC AGTCATCCTG CAATGTTGGT CAGATGTCAT GTTTGAGCAC
 TTCCTTCTGC ACAGAGAGGG GAAGTTTAAT GACACTTTGC GCCTCACTGG AGAGCTCCAT
 GATGGGGTCT CCAAGGCCAA CTTCTCCATC GGTCGCATGA CGCAAGACCT TGCAGGGACC
 TACAGATGCT ACGGTTCTGT TCCTCATTCC CCCTATCAGT TGTCAGCTCC CAGTGACCCT
 CTGGACATCG TGATTACAGG TCTATGTGGG AAACCTTCTC TCTCAGCCCA GCCGCGCCCC
 ATGGTTAAGG CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATC
 TACCATCTAT CAAGGGAGGG GGAGGCTCAT GAACTTAGGT TCCCTGCAGT GCCCAAGGTC
 AATGGAACCT TCCAGGCCAA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG GACCTACAGA
 TGCTTCGGCT CTTTCCGTGA CTCTCCCTAC GAGTGGTCAG ACCTTAGTGA CCCACTGCTT
 GTTTCTGTCA CAG*    
>DL;IPD:KIR00094
KIR:KIR00094 KIR3DP1*0030201 913 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGTGGTC AGGACAAGCC CTTCCTCTCT
 GCCTGGCCCA GCCCTGTGGT GTCTGAAGGA GAACATGTGG CTCTTCAGTG TCGCTCTCGT
 CTTGGGTTTA ACGAATTCAG TCTGTCCAAA GAAGACGGGA TGCCTGTCCC TGAGCTCTAC
 AACAGAGTAT TCCGAAACAC CGTTTTCATA GGCCCTGTGA CCCCAGCACA TGCAGGGACC
 TACAGATGTC GGGGTTCACA CCCACACTTC CTCACTGGGT GGTCAGCACC CAGCAACCCC
 CTGGTGATCA TGGTCACAGG AGTCCACAGA AAACCTTCCC TCCTGGCCCA CCCAGGTCCC
 CTGGTGAAAT CAGAAGAGAC AGTCATCCTG CAATGTTGGT CAGATGTCAT GTTTGAGCAC
 TTCCTTCTGC ACAGAGAGGG GAAGTTTAAT GACACTTTGC GCCTCACTGG AGAGCTCCAT
 GATGGGGTCT CCAAGGCCAA CTTCTCCATC GGTCGCATGA CGCAAGACCT TGCAGGGACC
 TACAGATGCT ACGGTTCTGT TCCTCATTCC CCCTATCAGT TGTCAGCTCC CAGTGACCCT
 CTGGACATCG TGATTACAGG TCTATGTGGG AAACCTTCTC TCTCAGCCCA GCCGCGCCCC
 ATGGTTAAGG CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATC
 TACCATCTAT CAAGGGAGGG GGAGGCTCAT GAACTTAGGT TCCCTGCAGT GCCCAAGGTC
 AATGGAACCT TCCAGGCCAA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG GACCTACAGA
 TGCTTCGGCT CTTTCCGTGA CTCTCCCTAC GAGTGGTCAG ACCTTAGTGA CCCACTGCTT
 GTTTCTGTCA CAG*    
>DL;IPD:KIR00466
KIR:KIR00466 KIR3DP1*0030202 913 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGTGGTC AGGACAAGCC CTTCCTCTCT
 GCCTGGCCCA GCCCTGTGGT GTCTGAAGGA GAACATGTGG CTCTTCAGTG TCGCTCTCGT
 CTTGGGTTTA ACGAATTCAG TCTGTCCAAA GAAGACGGGA TGCCTGTCCC TGAGCTCTAC
 AACAGAGTAT TCCGAAACAC CGTTTTCATA GGCCCTGTGA CCCCAGCACA TGCAGGGACC
 TACAGATGTC GGGGTTCACA CCCACACTTC CTCACTGGGT GGTCAGCACC CAGCAACCCC
 CTGGTGATCA TGGTCACAGG AGTCCACAGA AAACCTTCCC TCCTGGCCCA CCCAGGTCCC
 CTGGTGAAAT CAGAAGAGAC AGTCATCCTG CAATGTTGGT CAGATGTCAT GTTTGAGCAC
 TTCCTTCTGC ACAGAGAGGG GAAGTTTAAT GACACTTTGC GCCTCACTGG AGAGCTCCAT
 GATGGGGTCT CCAAGGCCAA CTTCTCCATC GGTCGCATGA CGCAAGACCT TGCAGGGACC
 TACAGATGCT ACGGTTCTGT TCCTCATTCC CCCTATCAGT TGTCAGCTCC CAGTGACCCT
 CTGGACATCG TGATTACAGG TCTATGTGGG AAACCTTCTC TCTCAGCCCA GCCGCGCCCC
 ATGGTTAAGG CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATC
 TACCATCTAT CAAGGGAGGG GGAGGCTCAT GAACTTAGGT TCCCTGCAGT GCCCAAGGTC
 AATGGAACCT TCCAGGCCAA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG GACCTACAGA
 TGCTTCGGCT CTTTCCGTGA CTCTCCCTAC GAGTGGTCAG ACCTTAGTGA CCCACTGCTT
 GTTTCTGTCA CAG*    
>DL;IPD:KIR00468
KIR:KIR00468 KIR3DP1*0030203 913 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGTGGTC AGGACAAGCC CTTCCTCTCT
 GCCTGGCCCA GCCCTGTGGT GTCTGAAGGA GAACATGTGG CTCTTCAGTG TCGCTCTCGT
 CTTGGGTTTA ACGAATTCAG TCTGTCCAAA GAAGACGGGA TGCCTGTCCC TGAGCTCTAC
 AACAGAGTAT TCCGAAACAC CGTTTTCATA GGCCCTGTGA CCCCAGCACA TGCAGGGACC
 TACAGATGTC GGGGTTCACA CCCACACTTC CTCACTGGGT GGTCAGCACC CAGCAACCCC
 CTGGTGATCA TGGTCACAGG AGTCCACAGA AAACCTTCCC TCCTGGCCCA CCCAGGTCCC
 CTGGTGAAAT CAGAAGAGAC AGTCATCCTG CAATGTTGGT CAGATGTCAT GTTTGAGCAC
 TTCCTTCTGC ACAGAGAGGG GAAGTTTAAT GACACTTTGC GCCTCACTGG AGAGCTCCAT
 GATGGGGTCT CCAAGGCCAA CTTCTCCATC GGTCGCATGA CGCAAGACCT TGCAGGGACC
 TACAGATGCT ACGGTTCTGT TCCTCATTCC CCCTATCAGT TGTCAGCTCC CAGTGACCCT
 CTGGACATCG TGATTACAGG TCTATGTGGG AAACCTTCTC TCTCAGCCCA GCCGCGCCCC
 ATGGTTAAGG CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATC
 TACCATCTAT CAAGGGAGGG GGAGGCTCAT GAACTTAGGT TCCCTGCAGT GCCCAAGGTC
 AATGGAACCT TCCAGGCCAA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG GACCTACAGA
 TGCTTCGGCT CTTTCCGTGA CTCTCCCTAC GAGTGGTCAG ACCTTAGTGA CCCACTGCTT
 GTTTCTGTCA CAG*    
>DL;IPD:KIR00469
KIR:KIR00469 KIR3DP1*0030204 913 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGTGGTC AGGACAAGCC CTTCCTCTCT
 GCCTGGCCCA GCCCTGTGGT GTCTGAAGGA GAACATGTGG CTCTTCAGTG TCGCTCTCGT
 CTTGGGTTTA ACGAATTCAG TCTGTCCAAA GAAGACGGGA TGCCTGTCCC TGAGCTCTAC
 AACAGAGTAT TCCGAAACAC CGTTTTCATA GGCCCTGTGA CCCCAGCACA TGCAGGGACC
 TACAGATGTC GGGGTTCACA CCCACACTTC CTCACTGGGT GGTCAGCACC CAGCAACCCC
 CTGGTGATCA TGGTCACAGG AGTCCACAGA AAACCTTCCC TCCTGGCCCA CCCAGGTCCC
 CTGGTGAAAT CAGAAGAGAC AGTCATCCTG CAATGTTGGT CAGATGTCAT GTTTGAGCAC
 TTCCTTCTGC ACAGAGAGGG GAAGTTTAAT GACACTTTGC GCCTCACTGG AGAGCTCCAT
 GATGGGGTCT CCAAGGCCAA CTTCTCCATC GGTCGCATGA CGCAAGACCT TGCAGGGACC
 TACAGATGCT ACGGTTCTGT TCCTCATTCC CCCTATCAGT TGTCAGCTCC CAGTGACCCT
 CTGGACATCG TGATTACAGG TCTATGTGGG AAACCTTCTC TCTCAGCCCA GCCGCGCCCC
 ATGGTTAAGG CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATC
 TACCATCTAT CAAGGGAGGG GGAGGCTCAT GAACTTAGGT TCCCTGCAGT GCCCAAGGTC
 AATGGAACCT TCCAGGCCAA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG GACCTACAGA
 TGCTTCGGCT CTTTCCGTGA CTCTCCCTAC GAGTGGTCAG ACCTTAGTGA CCCACTGCTT
 GTTTCTGTCA CAG*    
>DL;IPD:KIR00627
KIR:KIR00627 KIR3DP1*0030205 913 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGTGGTC AGGACAAGCC CTTCCTCTCT
 GCCTGGCCCA GCCCTGTGGT GTCTGAAGGA GAACATGTGG CTCTTCAGTG TCGCTCTCGT
 CTTGGGTTTA ACGAATTCAG TCTGTCCAAA GAAGACGGGA TGCCTGTCCC TGAGCTCTAC
 AACAGAGTAT TCCGAAACAC CGTTTTCATA GGCCCTGTGA CCCCAGCACA TGCAGGGACC
 TACAGATGTC GGGGTTCACA CCCACACTTC CTCACTGGGT GGTCAGCACC CAGCAACCCC
 CTGGTGATCA TGGTCACAGG AGTCCACAGA AAACCTTCCC TCCTGGCCCA CCCAGGTCCC
 CTGGTGAAAT CAGAAGAGAC AGTCATCCTG CAATGTTGGT CAGATGTCAT GTTTGAGCAC
 TTCCTTCTGC ACAGAGAGGG GAAGTTTAAT GACACTTTGC GCCTCACTGG AGAGCTCCAT
 GATGGGGTCT CCAAGGCCAA CTTCTCCATC GGTCGCATGA CGCAAGACCT TGCAGGGACC
 TACAGATGCT ACGGTTCTGT TCCTCATTCC CCCTATCAGT TGTCAGCTCC CAGTGACCCT
 CTGGACATCG TGATTACAGG TCTATGTGGG AAACCTTCTC TCTCAGCCCA GCCGCGCCCC
 ATGGTTAAGG CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATC
 TACCATCTAT CAAGGGAGGG GGAGGCTCAT GAACTTAGGT TCCCTGCAGT GCCCAAGGTC
 AATGGAACCT TCCAGGCCAA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG GACCTACAGA
 TGCTTCGGCT CTTTCCGTGA CTCTCCCTAC GAGTGGTCAG ACCTTAGTGA CCCACTGCTT
 GTTTCTGTCA CAG*    
>DL;IPD:KIR00643
KIR:KIR00643 KIR3DP1*0030206 913 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGTGGTC AGGACAAGCC CTTCCTCTCT
 GCCTGGCCCA GCCCTGTGGT GTCTGAAGGA GAACATGTGG CTCTTCAGTG TCGCTCTCGT
 CTTGGGTTTA ACGAATTCAG TCTGTCCAAA GAAGACGGGA TGCCTGTCCC TGAGCTCTAC
 AACAGAGTAT TCCGAAACAC CGTTTTCATA GGCCCTGTGA CCCCAGCACA TGCAGGGACC
 TACAGATGTC GGGGTTCACA CCCACACTTC CTCACTGGGT GGTCAGCACC CAGCAACCCC
 CTGGTGATCA TGGTCACAGG AGTCCACAGA AAACCTTCCC TCCTGGCCCA CCCAGGTCCC
 CTGGTGAAAT CAGAAGAGAC AGTCATCCTG CAATGTTGGT CAGATGTCAT GTTTGAGCAC
 TTCCTTCTGC ACAGAGAGGG GAAGTTTAAT GACACTTTGC GCCTCACTGG AGAGCTCCAT
 GATGGGGTCT CCAAGGCCAA CTTCTCCATC GGTCGCATGA CGCAAGACCT TGCAGGGACC
 TACAGATGCT ACGGTTCTGT TCCTCATTCC CCCTATCAGT TGTCAGCTCC CAGTGACCCT
 CTGGACATCG TGATTACAGG TCTATGTGGG AAACCTTCTC TCTCAGCCCA GCCGCGCCCC
 ATGGTTAAGG CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATC
 TACCATCTAT CAAGGGAGGG GGAGGCTCAT GAACTTAGGT TCCCTGCAGT GCCCAAGGTC
 AATGGAACCT TCCAGGCCAA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG GACCTACAGA
 TGCTTCGGCT CTTTCCGTGA CTCTCCCTAC GAGTGGTCAG ACCTTAGTGA CCCACTGCTT
 GTTTCTGTCA CAG*    
>DL;IPD:KIR00470
KIR:KIR00470 KIR3DP1*00303 913 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGTGGTC AGGACAAGCC CTTCCTCTCT
 GCCTGGCCCA GCCCTGTGGT GTCTGAAGGA GAACATGTGG CTCTTCAGTG TCGCTCTCGT
 CTTGGGTTTA ACGAATTCAG TCTGTCCAAA GAAGACGGGA TGCCTGTCCC TGAGCTCTAC
 AACAGAGTAT TCCGAAACAC CGTTTTCATA GGCCCTGTGA CCCCAGCACA TGCAGGGACC
 TACAGATGTC GGGGTTCACA CCCACACTTC CTCACTGGGT GGTCAGCACC CAGCAACCCC
 CTGGTGATCA TGGTCACAGG AGTCCACAGA AAACCTTCCC TCCTGGCCCA CCCAGGTCCC
 CTGGTGAAAT CAGAAGAGAC AGTCATCCTG CAATGTTGGT CAGATGTCAT GTTTGAGCAC
 TTCCTTCTGC ACAGAGAGGG GAAGTTTAAT GACACTTTGC GCCTCACTGG AGAGCTCCAT
 GATGGAGTCT CCAAGGCCAA CTTCTCCATC GGTCGCATGA CGCAAGACCT TGCAGGGACC
 TACAGATGCT ACGGTTCTGT TCCTCATTCC CCCTATCAGT TGTCAGCTCC CAGTGACCCT
 CTGGACATCG TGATTACAGG TCTATGTGGG AAACCTTCTC TCTCAGCCCA GCCGCGCCCC
 ATGGTTAAGG CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATC
 TACCATCTAT CAAGGGAGGG GGAGGCTCAT GAACTTAGGT TCCCTGCAGT GCCCAAGGTC
 AATGGAACCT TCCAGGCCAA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG GACCTACAGA
 TGCTTCGGCT CTTTCCGTGA CTCTCCCTAC GAGTGGTCAG ACCTTAGTGA CCCACTGCTT
 GTTTCTGTCA CAG*    
>DL;IPD:KIR00471
KIR:KIR00471 KIR3DP1*0030401 913 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGTGGTC AGGACAAGCC CTTCCTCTCT
 GCCTGGCCCA GCCCTGTGGT GTCTGAAGGA GAACATGTGG CTCTTCAGTG TCGCTCTCGT
 CTTGGGTTTA ACGAATTCAG TCTGTCCAAA GAAGACGGGA TGCCTGTCCC TGAGCTCTAC
 AACAGAGTAT TCCGAAACAC CGTTTTCATA GGCCCTGTGA CCCCAGCACA TGCAGGGACC
 TACAGATGTC GGGGTTCACA CCCACACTTC CTCACTGGGT GGTCAGCACC CAGCAACCCC
 CTGGTGATCA TGGTCACAGG AGTCCACAGA AAACCTTCCC TCCTGGCCCA CCCAGGTCCC
 CTGGTGAAAT CAGAAGAGAC AGTCATCCTG CAATGTTGGT CAGATGTCAT GTTTGAGCAC
 TTCCTTCTGC ACAGAGAGGG GAAGTTTAAT GACACTTTGC GCCTCACTGG AGAGCTCCAT
 GATGGGGTCT CCAAGGCCAA CTTCTCCATC GGTCGCATGA CGCAAGACCT TGCAGGGACC
 TACAGATGCT ACGGTTCTGT TCCTCATTCC CCCTATCAGT TGTCAGCTCC CAGTGACCCT
 CTGGACATCG TGATTACAGG TCTATGTGGG AAACCTTCTC TCTCAGCCCA GCCGCGCCCC
 ATGGTTAAGG CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATC
 TACCATCTAT CAAGGGAGGG GGAGGCTCAT GAACTTAGGT TCCCTGCAGT GCCCAAGGTC
 AATGGAACCT TCCAGGCCAA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG GACCTACAGA
 TGCTTCGGCT CTTTCCGTGA CTCTCCCTAC GAGTGGTCAG ACCTTAGTGA CCCACTGCTT
 GTGTCTGTCA CAG*    
>DL;IPD:KIR00629
KIR:KIR00629 KIR3DP1*0030402 913 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGTGGTC AGGACAAGCC CTTCCTCTCT
 GCCTGGCCCA GCCCTGTGGT GTCTGAAGGA GAACATGTGG CTCTTCAGTG TCGCTCTCGT
 CTTGGGTTTA ACGAATTCAG TCTGTCCAAA GAAGACGGGA TGCCTGTCCC TGAGCTCTAC
 AACAGAGTAT TCCGAAACAC CGTTTTCATA GGCCCTGTGA CCCCAGCACA TGCAGGGACC
 TACAGATGTC GGGGTTCACA CCCACACTTC CTCACTGGGT GGTCAGCACC CAGCAACCCC
 CTGGTGATCA TGGTCACAGG AGTCCACAGA AAACCTTCCC TCCTGGCCCA CCCAGGTCCC
 CTGGTGAAAT CAGAAGAGAC AGTCATCCTG CAATGTTGGT CAGATGTCAT GTTTGAGCAC
 TTCCTTCTGC ACAGAGAGGG GAAGTTTAAT GACACTTTGC GCCTCACTGG AGAGCTCCAT
 GATGGGGTCT CCAAGGCCAA CTTCTCCATC GGTCGCATGA CGCAAGACCT TGCAGGGACC
 TACAGATGCT ACGGTTCTGT TCCTCATTCC CCCTATCAGT TGTCAGCTCC CAGTGACCCT
 CTGGACATCG TGATTACAGG TCTATGTGGG AAACCTTCTC TCTCAGCCCA GCCGCGCCCC
 ATGGTTAAGG CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATC
 TACCATCTAT CAAGGGAGGG GGAGGCTCAT GAACTTAGGT TCCCTGCAGT GCCCAAGGTC
 AATGGAACCT TCCAGGCCAA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG GACCTACAGA
 TGCTTCGGCT CTTTCCGTGA CTCTCCCTAC GAGTGGTCAG ACCTTAGTGA CCCACTGCTT
 GTGTCTGTCA CAG*    
>DL;IPD:KIR00091
KIR:KIR00091 KIR3DP1*004 949 bases
 ATGTCGCTCA TGGTCATCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTC CTCTCTGCCT GGCCCAGCCC TGTGGTGTCT
 GAAGGAGAAC ATGTGGCTCT TCAGTGTCGC TCTCGTCTTG GGTTTAACGA ATTCAGTCTG
 TCCAAAGAAG ACGGGATGCC TGTCCCTGAG CTCTACAACA GAGTATTCCG AAACACCGTT
 TTCATAGGCC CTGTGACCCC AGCACATGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CACTTCCTCA CTGGGTGGTC AGCACCCAGC AACCCCCTGG TGATCATGGT CACAGGAGTC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGA AGAGACAGTC
 ATCCTGCAAT GTTGGTCAGA TGTCATGTTT GAGCACTTCC TTCTGCACAG AGAGGGGAAG
 TTTAATGACA CTTTGCGCCT CACTGGAGAG CTCCATGATG GGGTCTCCAA GGCCAACTTC
 TCCATCGGTC GCATGACGCA AGACCTTGCA GGGACCTACA GATGCTACGG TTCTGTTCCT
 CATTCCCCCT ATCAGTTGTC AGCTCCCAGT GACCCTCTGG ACATCGTGAT TACAGGTCTA
 TGTGGGAAAC CTTCTCTCTC AGCCCAGCCG CGCCCCATGG TTAAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GCAGCTCCCG GAGCTCCTAT GACATCTACC ATCTATCAAG GGAGGGGGAG
 GCTCATGAAC TTAGGTTCCC TGCAGTGCCC AAGGTCAATG GAACCTTCCA GGCCAACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTGACTCT
 CCCTACGAGT GGTCAGACCT TAGTGACCCA CTGCTTGTTT CTGTCACAG* 
>DL;IPD:KIR00268
KIR:KIR00268 KIR3DP1*005 913 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGTGGTC AGGACAAGCC CTTCCTCTCT
 GCCTGGCCCA GCCCTGTGGT GTCTGAAGGA GAACATGTGG CTCTTCAGTG TCGCTCTCGT
 CTTGGGTTTA ACGAATTCAG TCTGTCCAAA GAAGACGGGA TGCCTGTCCC TGAGCTCTAC
 AACAGAGTAT TCCGAAACAC CGTTTTCATA GGCCCTGTGA CCCCAGCACA TGCAGGGACC
 TACAGATGTC GGGGTTCACA CCCACACTTC CTCACTGGGT GGTCAGCACC CAGCAACCCC
 CTGGTGATCA TGGTCACAGG AGTCCACAGA AAACCTTCCC TCCTGGCCCA CCCAGGTCCC
 CTGGTGAAAT CAGAAGAGAC AGTCATCCTG CAATGTTGGT CAGATGTCAT GTTTGAGCAC
 TTCCTTCTGC ACAGAGAGGG GACGTTTAAT GACACTTTGC GCCTCACTGG AGAGCTCCAT
 GATGGGGTCT CCAAGGCCAA CTTCTCCATC GGTCGCATGA CGCAAGACCT TGCAGGGACC
 TACAGATGCT ACGGTTCTGT TCCTCATTCC CCCTATCAGT TGTCAGCTCC CAGTGACCCT
 CTGGACATCG TGATTACAGG TCTATGTGGG AAACCTTCTC TCTCAGCCCA GCCGTGCCCC
 ATGGTTAAGG CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATC
 TACCATCTAT CAAGGGACGG GGAGGCTCAT GAACTTAGGC TCCCTGCAGT GCCCAAGGTC
 AATGGAACCT TCCAGGCCAA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG GACCTACAGA
 TGCTTCGGCT CTTTCCGTGA CTCTCCCTAC GAGTGGTCAG ACCTTAGTGA CCCACTGCTT
 GTTTCTGTCA CAG*    
>DL;IPD:KIR00269
KIR:KIR00269 KIR3DP1*006 913 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGTGGTC AGGACAAGCC CTTCCTCTCT
 GCCTGGCCCA GCCCTGTGGT GTCTGAAGGA GAACATGTGG CTCTTCAGTG TCGCTCTCGT
 CTTGGGTTTA ACGAATTCAG TCTGTCCAAA GAAGACGGGA TGCCTGTCCC TGAGCTCTAC
 AACAGAGTAT TCCGAAACAC CGTTTTCATA GGCCCTGTGA CCCCAGCACA TGCAGGGACC
 TACAGATGTC GGGGTTCACA CCCACACTTC CTCACTGGGT GGTCAGCACC CAGCAACCCC
 CTGGTGATCA TGGTCACAGG AGTCCACAGA AAACCTTCCC TCCTGGCCCA CCCAGGTCCC
 CTGGTGAAAT CAGAAGAGAC AGTCATCCTG CAATGTTGGT CAGATGTCAT GTTTGAGCAC
 TTCCTTCTGC ACAGAGAGGG GACGTTTAAT GACACTTTGC GCCTCACTGG AGAGCTCCAT
 GATGGGGTCT CCAAGGCCAA CTTCTCCATC GGTCGCATGA CGCAAGACCT TGCAGGGACC
 TACAGATGCT ACGGTTCTGT TCCTCATTCC CCCTATCAGT TGTCAGCTCC CAGTGACCCT
 CTGGACATCG TGATTACAGG TCTATGTGGG AAACCTTCTC TCTCAGCCCA GCCGCGCCCC
 ATGGTTAAGG CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATC
 TACCATCTAT CAAGGGACGG GGAGGCTCAT GAACTTAGGC TCCCTGCAGT GCCCAAGGTC
 AATGGAACCT TCCAGGCCAA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG GACCTACAGA
 TGCTTCGGCT CTTTCCGTGA CTCTCCCTAC GAGTGGTCAG ACCTTAGTGA CCCACTGCTT
 GTTTCTGTCA CAG*    
>DL;IPD:KIR00309
KIR:KIR00309 KIR3DP1*007 949 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTC CTCTCTGCCT GGCCCAGCCC TGTGGTGTCT
 GAAGGAGAAC ATGTGGCTCT TCAGTGTCGC TCTCGTCTTG GGTTTAACGA ATTCAGTCTG
 TCCAAAGAAG ACGGGGTGCC TGTCCCTGAG CTCTACAACA GAGTATTCCG AAACACCGTT
 TTCATAGGCC CTGTGACCCC AGCACATGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CACTTCCTCA CTGGGTGGTC AGCACCCAGC AACCCCCTGG TGATCATGGT CACAGGAGTC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGA AGAGACAGTC
 ATCCTGCAAT GTTGGTCAGA TGTCATGTTT GAGCACTTCC TTCTGCACAG AGAGGGGAAG
 TTTAATGACA CTTTGCGCCT CACTGGAGAG CTCCATGATG GGGTCTCCAA GGCCAACTTC
 TCCATCGGTC GCATGACGCA AGACCTTGCA GGGACCTACA GATGCTACGG TTCTGTTCCT
 CATTCCCCCT ATCAGTTGTC AGCTCCCAGT GACCCTCTGG ACATCGTGAT TACAGGTCTA
 TGTGGGAAAC CTTCTCTCTC AGCCCAGCCG CGCCCCATGG TTAAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GCAGCTCCCG GAGCTCCTAT GACATCTACC ATCTATCAAG GGAGGGGGAG
 GCTCATGAAC TTAGGTTCCC TGCAGTGCCC AAGGTCAATG GAACCTTCCA GGCCAACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTGACTCT
 CCCTACGAGT GGTCAGACCT TAGTGACCCA CTGCTTGTTT CTGTCACAG* 
>DL;IPD:KIR00472
KIR:KIR00472 KIR3DP1*008 913 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGTGGTC AGGACAAGCC CTTCCTCTCT
 GCCTGGCCCA GCCCTGTGGT GTCTGAAGGA GAACATGTGG CTCTTCAGTG TCGCTCTCGT
 CTTGGGTTTA ACGAATTCAG TCTGTCCAAA GAAGACGGGA TGCCTGTCCC TGAGCTCTAC
 AACAGAGTAT TCCGAAACAC CGTTTTCATA GGCCCTGTGA CCCCAGCACA TGCAGGGACC
 TACAGATGTC GGGGTTCACA CCCACACTTC CTCACTGGGT GGTCAGCACC CAGCAACCCC
 CTGGTGATCA TGGTCACAGG AGTCCACAGA AAACCTTCCC TCCTGGCCCA CCCAGGTCCC
 CTGGTGAAAT CAGAAGAGAC AGTCATCCTG CAATGTTGGT CAGATGTCAT GTTTGAGCAC
 TTCCTTCTGC ACAGAGAGGG GAAGTTTAAT GACACTTTGC GCCTCACTGG AGAGCTCCAT
 GATGGGCTCT CCAAGGCCAA CTTCTCCATC GGTCGCATGA CGCAAGACCT TGCAGGGACC
 TACAGATGCT ACGGTTCTGT TCCTCATTCC CCCTATCAGT TGTCAGCTCC CAGTGACCCT
 CTGGACATCG TGATTACAGG TCTATGTGGG AAACCTTCTC TCTCAGCCCA GCCGCGCCCC
 ATGGTTAAGG CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATC
 TACCATCTAT CAAGGGAGGG GGAGGCTCAT GAACTTAGGT TCCCTGCAGT GCCCAAGGTC
 AATGGAACCT TCCAGGCCAA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG GACCTACAGA
 TGCTTCGGCT CTTTCCGTGA CTCTCCCTAC GAGTGGTCAG ACCTTAGTGA CCCACTGCTT
 GTTTCTGTCA CAG*    
>DL;IPD:KIR00492
KIR:KIR00492 KIR3DP1*0090101 949 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTC CTCTCTGCCT GGCCCAGCCC TGTGGTGTCT
 GAAGGAGAAC ATGTGGCTCT TCAGTGTCGC TCTCGTCTTG GGTTTAACGA ATTCAGTCTG
 TCCAAAGAAG ACGGGATGCC TGTCCCTGAG CTCTACAACA GAGTATTCCG AAACACCGTT
 TTCATAGGCC CTGTGACCCC AGCACATGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CACTTCCTCA CTGGGTGGTC AGCACCCAGC AACCCCCTGG TGATCATGGT CACAGGAGTC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGA AGAGACAGTC
 ATCCTGCAAT GTTGGTCAGA TGTCATGTTT GAGCACTTCC TTCTGCACAG AGAGGGGAAG
 TTTAATGACA CTTTGCGCCT CACTGGAGAG CTCCATGATG GGGTCTCCAA GGCCAACTTC
 TCCATCGGTC GCATGACGCA AGACCTTGCA GGGACCTACA GATGCTACGG TTCTGTTCCT
 CATTCCCCCT ATCAGTTGTC AGCTCCCAGT GACCCTCTGG ACATCGTGAT TACAGGTCTA
 TGTGGGAAAC CTTCTCTCTC AGCCCAGCCG CGCCCCATGG TTAAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GCAGCTCCCG GAGCTCCTAT GACATCTACC ATCTATCAAG GGAGGGGGAG
 GCTCATGAAC TTAGGTTCCC TGCAGTGCCC AAGGTCAATG GAACCTTCCA GGCCAACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTGACTCT
 CCCTACGAGT GGTCAGACCT TAGTGACCCA CTGCTTGTTT CTGTCACAG* 
>DL;IPD:KIR00494
KIR:KIR00494 KIR3DP1*0090102 949 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTC CTCTCTGCCT GGCCCAGCCC TGTGGTGTCT
 GAAGGAGAAC ATGTGGCTCT TCAGTGTCGC TCTCGTCTTG GGTTTAACGA ATTCAGTCTG
 TCCAAAGAAG ACGGGATGCC TGTCCCTGAG CTCTACAACA GAGTATTCCG AAACACCGTT
 TTCATAGGCC CTGTGACCCC AGCACATGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CACTTCCTCA CTGGGTGGTC AGCACCCAGC AACCCCCTGG TGATCATGGT CACAGGAGTC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGA AGAGACAGTC
 ATCCTGCAAT GTTGGTCAGA TGTCATGTTT GAGCACTTCC TTCTGCACAG AGAGGGGAAG
 TTTAATGACA CTTTGCGCCT CACTGGAGAG CTCCATGATG GGGTCTCCAA GGCCAACTTC
 TCCATCGGTC GCATGACGCA AGACCTTGCA GGGACCTACA GATGCTACGG TTCTGTTCCT
 CATTCCCCCT ATCAGTTGTC AGCTCCCAGT GACCCTCTGG ACATCGTGAT TACAGGTCTA
 TGTGGGAAAC CTTCTCTCTC AGCCCAGCCG CGCCCCATGG TTAAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GCAGCTCCCG GAGCTCCTAT GACATCTACC ATCTATCAAG GGAGGGGGAG
 GCTCATGAAC TTAGGTTCCC TGCAGTGCCC AAGGTCAATG GAACCTTCCA GGCCAACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTGACTCT
 CCCTACGAGT GGTCAGACCT TAGTGACCCA CTGCTTGTTT CTGTCACAG* 
>DL;IPD:KIR00495
KIR:KIR00495 KIR3DP1*0090103 949 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTC CTCTCTGCCT GGCCCAGCCC TGTGGTGTCT
 GAAGGAGAAC ATGTGGCTCT TCAGTGTCGC TCTCGTCTTG GGTTTAACGA ATTCAGTCTG
 TCCAAAGAAG ACGGGATGCC TGTCCCTGAG CTCTACAACA GAGTATTCCG AAACACCGTT
 TTCATAGGCC CTGTGACCCC AGCACATGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CACTTCCTCA CTGGGTGGTC AGCACCCAGC AACCCCCTGG TGATCATGGT CACAGGAGTC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGA AGAGACAGTC
 ATCCTGCAAT GTTGGTCAGA TGTCATGTTT GAGCACTTCC TTCTGCACAG AGAGGGGAAG
 TTTAATGACA CTTTGCGCCT CACTGGAGAG CTCCATGATG GGGTCTCCAA GGCCAACTTC
 TCCATCGGTC GCATGACGCA AGACCTTGCA GGGACCTACA GATGCTACGG TTCTGTTCCT
 CATTCCCCCT ATCAGTTGTC AGCTCCCAGT GACCCTCTGG ACATCGTGAT TACAGGTCTA
 TGTGGGAAAC CTTCTCTCTC AGCCCAGCCG CGCCCCATGG TTAAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GCAGCTCCCG GAGCTCCTAT GACATCTACC ATCTATCAAG GGAGGGGGAG
 GCTCATGAAC TTAGGTTCCC TGCAGTGCCC AAGGTCAATG GAACCTTCCA GGCCAACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTGACTCT
 CCCTACGAGT GGTCAGACCT TAGTGACCCA CTGCTTGTTT CTGTCACAG* 
>DL;IPD:KIR00493
KIR:KIR00493 KIR3DP1*00902 949 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 CCACATGAGG GTGGTCAGGA CAAGCCCTTC CTCTCTGCCT GGCCCAGCCC TGTGGTGTCT
 GAAGGAGAAC ATGTGGCTCT TCAGTGTCGC TCTCGTCTTG GGTTTAACGA ATTCAGTCTG
 TCCAAAGAAG ACGGGATGCC TGTCCCTGAG CTCTACAACA GAGTATTCCG AAACACCGTT
 TTCATAGGCC CTGTGACCCC AGCACATGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CACTTCCTCA CTGGGTGGTC AGCACCCAGC AACCCCCTGG TGATCATGGT CACAGGAGTC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGA GGAGACAGTC
 ATCCTGCAAT GTTGGTCAGA TGTCATGTTT GAGCACTTCC TTCTGCACAG AGAGGGGAAG
 TTTAATGACA CTTTGCGCCT CACTGGAGAG CTCCATGATG GGGTCTCCAA GGCCAACTTC
 TCCATCGGTC GCATGACGCA AGACCTTGCA GGGACCTACA GATGCTACGG TTCTGTTCCT
 CATTCCCCCT ATCAGTTGTC AGCTCCCAGT GACCCTCTGG ACATCGTGAT TACAGGTCTA
 TGTGGGAAAC CTTCTCTCTC AGCCCAGCCG CGCCCCATGG TTAAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GCAGCTCCCG GAGCTCCTAT GACATCTACC ATCTATCAAG GGAGGGGGAG
 GCTCATGAAC TTAGGTTCCC TGCAGTGCCC AAGGTCAATG GAACCTTCCA GGCCAACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTGACTCT
 CCCTACGAGT GGTCAGACCT TAGTGACCCA CTGCTTGTTT CTGTCACAG* 
>DL;IPD:KIR00628
KIR:KIR00628 KIR3DP1*01001 913 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGTGGTC AGGACAAGCC CTTCCTCTCT
 GCCTGGCCCA GCCCTGTGGT GTCTGAAGGA GAACATGTGG CTCTTCAGTG TCGCTCTCGT
 CTTGGGTTTA ACGAATTCAG TCTGTCCAAA GAAGACGGGA TGCCTGTCCC TGAGCTCTAC
 AACAGAGTAT TCCGAAACAC CGTTTTCATA GGCCCTGTGA CCCCAGCACA TGCAGGGACC
 TACAGATGTC GGGGTTCACA CCCACACTTC CTCACTGGGT GGTCAGCACC CAGCAACCCC
 CTGGTGATCA TGGTCACAGG AGTCCACAGA AAACCTTCCC TCCTGGCCCA CCCAGGTCCC
 CTGGTGAAAT CAGAAGAGAC AGTCATCCTG CAATGTTGGT CAGATGTCAT GTTTGAGCAC
 TTCCTTCTGC ACAGAGAGGG GAAGTTTAAT GACACTTTGC GCCTCACTGG AGAGCTCCAT
 GATGGGGTCT CCAAGGCCAA CTTCTCCATC GGTCGCATGA CGCAAGACCT TGCAGGGACC
 TACAGATGCT ACGGTTCTGT TCCTCATTCC CCCTATCAGT TGTCAGCTCC CAGTGACCCT
 CTGGACATCG TGATTACAGG TCTATGTGGG AAACCTTCTC TCTCAGCCCA GCCGCGCCCC
 ATGGTTAAGG CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATC
 TACCATCTAT CAAGGGACGG GGAGGCTCAT GAACTTAGGC TCCCTGCAGT GCCCAAGGTC
 AATGGAACCT TCCAGGCCAA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG GACCTACAGA
 TGCTTCGGCT CTTTCCGTGA CTCTCCCTAC GAGTGGTCAG ACCTTAGTGA CCCACTGCTT
 GTTTCTGTCA CAG*    
>DL;IPD:KIR00864
KIR:KIR00864 KIR3DP1*01002 913 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGTGGTC AGGACAAGCC CTTCCTCTCT
 GCCTGGCCCA GCCCTGTGGT GTCTGAAGGA GAACATGTGG CTCTTCAGTG TCGCTCTCGT
 CTTGGGTTTA ACGAATTCAG TCTGTCCAAA GAAGACGGGA TGCCTGTCCC TGAGCTCTAC
 AACAGAGTAT TCCGAAACAC CGTTTTCATA GGCCCTGTGA CCCCAGCACA TGCAGGGACC
 TACAGATGTC GGGGTTCACA CCCACACTTC CTCACTGGGT GGTCAGCCCC CAGCAACCCC
 CTGGTGATCA TGGTCACAGG AGTCCACAGA AAACCTTCCC TCCTGGCCCA CCCAGGTCCC
 CTGGTGAAAT CAGAAGAGAC AGTCATCCTG CAATGTTGGT CAGATGTCAT GTTTGAGCAC
 TTCCTTCTGC ACAGAGAGGG GAAGTTTAAT GACACTTTGC GCCTCACTGG AGAGCTCCAT
 GATGGGGTCT CCAAGGCCAA CTTCTCCATC GGTCGCATGA CGCAAGACCT TGCAGGGACC
 TACAGATGCT ACGGTTCTGT TCCTCATTCC CCCTATCAGT TGTCAGCTCC CAGTGACCCT
 CTGGACATCG TGATTACAGG TCTATGTGGG AAACCTTCTC TCTCAGCCCA GCCGCGCCCC
 ATGGTTAAGG CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATC
 TACCATCTAT CAAGGGACGG GGAGGCTCAT GAACTTAGGC TCCCTGCAGT GCCCAAGGTC
 AATGGAACCT TCCAGGCCAA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG GACCTACAGA
 TGCTTCGGCT CTTTCCGTGA CTCTCCCTAC GAGTGGTCAG ACCTTAGTGA CCCACTGCTT
 GTTTCTGTCA CAG*    
>DL;IPD:KIR00696
KIR:KIR00696 KIR3DP1*011 949 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTC CTCTCTGCCT GGCCCAGCCC TGTGGTGTCT
 GAAGGAGAAC ATGTGGCTCT TCAGTGTCGC TCTCGTCTTG GGTTTAACGA ATTCAGTCTG
 TCCAAAGAAG ACGGGATGCC TGTCCCTGAG CTCTACAACA GAGTATTCCG AAACACCGTT
 TTCATAGGCC CTGTGACCCC AGCACATGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CACTTCCTCA CTGGGTGGTC AGCACCCAGC AACCCCCTGG TGATCATGGT CACAGGAGTC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGA AGAGACAGTC
 ATCCTGCAAT GTTGGTCAGA TGTCATGTTT GAGCACTTCC TTCTGCACAG AGAGGGGAAG
 TTTAATGACA CTTTGCGCCT CACTGGAGAG CTCCATGATG GGGTCTCCAA GGCCAACTTC
 TCCATCGGTC GCATGACGCA AGACCTTGCA GGGACCTACA GATGCTACGG TTCTGTTCCT
 CATTCCCCCT ATCAGTTGTC AGCTCCCAGT GACCCTCTGG ACATCGTGAT TACAGGTCTA
 TGTGGGAAAC CTTCTCTCTC AGCCCAGCCG CGCCCCATGG TTAAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GCAGCTCCCG GAGCTCCTAT GACATCTACC ATCTATCAAG GGACGGGGAG
 GCTCATGAAC TTAGGCTCCC TGCAGTGCCC AAGGTCAATG GAACCTTCCA GGCCAACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTGACTCT
 CCCTACGAGT GGTCAGACCT TAGTGACCCA CTGCTTGTTT CTGTCACAG* 
>DL;IPD:KIR00700
KIR:KIR00700 KIR3DP1*012 949 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGCTGCA GGGGGCCTGG
 ACACATGAGG GTGGTCAGGA CAAGCCCTTC CTCTCTGCCT GGCCCAGCCC TGTGGTGTCT
 GAAGGAGAAC ATGTGGCTCT TCAGTGTCGC TCTCGTCTTG GGTTTAACGA ATTCAGTCTG
 TCCAAAGAAG ACGGGATGCC TGTCCCTGAG CTCTACAACA GAGTATTCCG AAACACCGTT
 TTCATAGGCC CTGTGACCCC AGCACATGCA GGGACCTACA GATGTCGGGG TTCACACCCA
 CACTTCCTCA CTGGGTGGTC AGCACCCAGC AACCCCCTGG TGATCATGGT CACAGGAGTC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGA AGAGACAGTC
 ATCCTGCAAT GTTGGTCAGA TGTCATGTTT GAACACTTCC TTCTGCACAG AGAGGGGAAG
 TTTAATGACA CTTTGCGCCT CACTGGAGAG CTCCATGATG GGGTCTCCAA GGCCAACTTC
 TCCATCGGTC GCATGACGCA AGACCTTGCA GGGACCTACA GATGCTACGG TTCTGTTCCT
 CATTCCCCCT ATCAGTTGTC AGCTCCCAGT GACCCTCTGG ACATCGTGAT TACAGGTCTA
 TGTGGGAAAC CTTCTCTCTC AGCCCAGCCG TGCCCCATGG TTAAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GCAGCTCCCG GAGCTCCTAT GACATCTACC ATCTATCAAG GGAGGGGGAG
 GCTCATGAAC TTAGGTTCCC TGCAGTGCCC AAGGTCAATG GAACCTTCCA GGCCAACTTT
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTGACTCT
 CCCTACGAGT GGTCAGACCT TAGTGACCCA CTGCTTGTTT CTGTCACAG* 
>DL;IPD:KIR00698
KIR:KIR00698 KIR3DP1*013 913 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGTGGTC AGGACAAGCC CTTCCTCTCT
 GCCTGGCCCA GCCCTGTGGT GTCTGAAGGA GAACATGTGG CTCTTCAGTG TCGCTCTCGT
 CTTGGGTTTA ACGAATTCAG TCTGTCCAAA GAAGACGGGA TGCCTGTCCC TGAGCTCTAC
 AACAGAGTAT TCCGAAACAC CGTTTTCATA GGCCCTGTGA CCCCAGCACA TGCAGGGACC
 TACAGATGTC GGGGTTCACA CCCACACTTC CTCACTGGGT GGTCAGCACC CAGCAACCCC
 CTGGTGATCA TGGTCACAGG AGTCCACAGA AAACCTTCCC TCCTGGCCCA CCCAGGTCCC
 CTGGTGAAAT CAGAAGAGAC AGTCATCCTG CAATGTTGGT CAGATGTCAT GTTTGAGCAC
 TTCCTTCTGC ACAGAGAGGG GAAGTTTAAT GACACTTTGC GCCTCACTGG AGAGCTCCAT
 GATGGGGTCT CCAAGGCCAA CTTCTCCATC GGTCGCATGA CGCAAGACCT TGCAGGGACC
 TACAGATGCT ACGGTTCTGT TCCTCATTCC CCCTATCAGT TGTCAGCTCC CAGTGACCCT
 CTGGACATCG TGATTACAGG TCTATGTGGG AAACCTTCTC TCTCAGCCCA GCCGCGCCCC
 ATGGTTAAGG CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATC
 TACCATCTAT CAAGGGAGGG GGAGGCTCAT GAACTTAGGC TCCCTGCAGT GCCCAAGGTC
 AATGGAACCT TCCAGGCCAA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG GACCTACAGA
 TGCTTCGGCT CTTTCCGTGA CTCTCCCTAC GAGTGGTCAG ACCTTAGTGA CCCACTGCTT
 GTTTCTGTCA CAG*    
>DL;IPD:KIR00705
KIR:KIR00705 KIR3DP1*014 913 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGTGGTC AGGACAAGCC CTTCGTCTCT
 GCCTGGCCCA GCCCTGTGGT GTCTGAAGGA GAACATGTGG CTCTTCAGTG TCGCTCTCGT
 CTTGGGTTTA ACGAATTCAG TCTGTCCAAA GAAGACGGGA TGCCTGTCCC TGAGCTCTAC
 AACAGAGTAT TCCGAAACAC CGTTTTCATA GGCCCTGTGA CCCCAGCACA TGCAGGGACC
 TACAGATGTC GGGGTTCACA CCCACACTTC CTCACTGGGT GGTCAGCACC CAGCAACCCC
 CTGGTGATCA TGGTCACAGG AGTCCACAGA AAACCTTCCC TCCTGGCCCA CCCAGGTCCC
 CTGGTGAAAT CAGAAGAGAC AGTCATCCTG CAATGTTGGT CAGATGTCAT GTTTGAGCAC
 TTCCTTCTGC ACAGAGAGGG GAAGTTTAAT GACACTTTGC GCCTCACTGG AGAGCTCCAT
 GATGGGGTCT CCAAGGCCAA CTTCTCCATC GGTCGCATGA CGCAAGACCT TGCAGGGACC
 TACAGATGCT ACGGTTCTGT TCCTCATTCC CCCTATCAGT TGTCAGCTCC CAGTGACCCT
 CTGGACATCG TGATTACAGG TCTATGTGGG AAACCTTCTC TCTCAGCCCA GCCGCGCCCC
 ATGGTTAAGG CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATC
 TACCATCTAT CAAGGGAGGG GGAGGCTCAT GAACTTAGGT TCCCTGCAGT GCCCAAGGTC
 AATGGAACCT TCCAGGCCAA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG GACCTACAGA
 TGCTTCGGCT CTTTCCGTGA CTCTCCCTAC GAGTGGTCAG ACCTTAGTGA CCCACTGCTT
 GTTTCTGTCA CAG*    
>DL;IPD:KIR00863
KIR:KIR00863 KIR3DP1*015 913 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGTGGTC AGGACAAGCC CTTCCTCTCT
 GCCTGGCCCA GCCCTGTGGT GTCTGAAGGA GAACATGTGG CTCTTCAGTG TCGCTCTCGT
 CTTGGGTTTA ACGAATTCAG TCTGTCCAAA GAAGACGGGA TGCCTGTCCC TGAGCTCTAC
 AACAGAGTAT TCCGAAACAC CGTTTTCATA GGCCCTGTGA CCCCAGCACA TGCAGGGACC
 TACAGATGTC GGGGTTCACA CCCACACTTC CTCACTGGGT GGTCAGCACC CAGCAACCCC
 CTGGTGATCA TGGTCACAGG AGTCCACAGA AAACCTTCCC TCCTGGCCCA CCCAGGTCCC
 CTGGTGAAAT CAGAAGAGAC AGTCATCCTG CAATGTTGGT CAGATGTCAT GTTTGAGCAC
 TTCCTTCTGC ACAGAGAGGG GACGTTTAAT GACACTTTGC GCCTCACTGG AGAGCTCCAT
 GATGGGGTCT CCAAGGCCAA CTTCTCCATC GGTCGCATGA CGCAAGACCT TGCAGGGACC
 TACAGATGCT ACGGTTCTGT TCCTCATTCC CCCTATCAGT TGTCAGCTCC CAGTGACCCT
 CTGGACATCG TGATTACAGG TCTATGTGGG AAACCTTCTC TCTCAGCCCA GCCGCGCCCC
 ATGGTTAAGG CAGGAGAGAG CGTGACCTTG TCCTGCAGCT CCCGGAGCTC CTATGACATC
 TACCATCTAT CAAGGGAGGG GGAGGCTCAT GAACTTAGGT TCCCTGCAGT GCCCAAGGTC
 AATGGAACCT TCCAGGCCAA CTTTCCTCTG GGCCCTGCCA CCCACGGAGG GACCTACAGA
 TGCTTCGGCT CTTTCCGTGA CTCTCCCTAC GAGTGGTCAG ACCTTAGTGA CCCACTGCTT
 GTTTCTGTCA CAG*    
