>P1;KIR:KIR00065
KIR:KIR00065 KIR3DL2*0010101 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00459
KIR:KIR00459 KIR3DL2*0010102 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00280
KIR:KIR00280 KIR3DL2*00102 431 bases
 GQDKPFLSAR PSTVVPRGGH VALQCHYRRG FNNFMLYKED RSHVPIFHGR IFQESFIMGP
 VTPAHAGTYR CRGSRPHSLT GWSAPSNPLV IMVTGNHRKP SLLAHPGPLL KSGETVILQC
 WSDVMFEHFF LHREGISEDP SRLVGQIHDG VSKANFSIGP LMPVLAGTYR CYGSVPHSPY
 QLSAPSDPLD IVITGLYEKP SLSAQPGPTV QAGENVTLSC SSWSSYDIYH LSREGEAHER
 RLRAVPKVNR TFQADFPLGP ATHGGTYRCF GSFRALPCVW SNSSDPLLVS VTGNPSSSWP
 SPTEPSSKSG ICRHLHVLIG TSVVIFLFIL LLFFLLYRWC SNKKNAAVMD QEPAGDRTVN
 RQDSDEQDPQ EVTYAQLDHC VFIQRKISRP SQRPKTPLTD TSVYTELPNA EPRSKVVSCP
 RAPQSGLEGV F*    
>P1;KIR:KIR00317
KIR:KIR00317 KIR3DL2*0010301 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00462
KIR:KIR00462 KIR3DL2*0010302 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00541
KIR:KIR00541 KIR3DL2*00104 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00066
KIR:KIR00066 KIR3DL2*0020101 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00461
KIR:KIR00461 KIR3DL2*0020102 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00463
KIR:KIR00463 KIR3DL2*0020103 397 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVT*  
>P1;KIR:KIR00464
KIR:KIR00464 KIR3DL2*0020104 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00465
KIR:KIR00465 KIR3DL2*0020105 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00640
KIR:KIR00640 KIR3DL2*0020106 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00460
KIR:KIR00460 KIR3DL2*00202 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00067
KIR:KIR00067 KIR3DL2*00301 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00287
KIR:KIR00287 KIR3DL2*00302 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00068
KIR:KIR00068 KIR3DL2*004 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVA RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSHLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSPQP GPTVQAGENV
 TLSCSSWSSY DTYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00069
KIR:KIR00069 KIR3DL2*00501 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSHLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00600
KIR:KIR00600 KIR3DL2*00502 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSHLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00070
KIR:KIR00070 KIR3DL2*006 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00071
KIR:KIR00071 KIR3DL2*0070101 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00295
KIR:KIR00295 KIR3DL2*0070102 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00458
KIR:KIR00458 KIR3DL2*0070103 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00543
KIR:KIR00543 KIR3DL2*00702 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00072
KIR:KIR00072 KIR3DL2*008 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP QGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GTLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PPTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00073
KIR:KIR00073 KIR3DL2*00901 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFHAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00134
KIR:KIR00134 KIR3DL2*00902 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFHAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00457
KIR:KIR00457 KIR3DL2*00903 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFHAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00615
KIR:KIR00615 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFHAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00074
KIR:KIR00074 KIR3DL2*01001 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00075
KIR:KIR00075 KIR3DL2*01101 432 bases
 GGQDKPFLSA RPSTVVPRGG HVALQCHYRR GFNNFMLYKE DRSHVPIFHG RIFQESFIMG
 PVTPAHAGTY RCRGSRPHSL TGWSAPSNPV VIMVTGNHRK PSLLAHPGPL LKSGETVILQ
 CWSDVMFEHF FLHREGISED PSRLVGQIHD GVSKANFSIG PLMPVLAGTY RCYGSVPHSP
 YQLSAPSDPL DIVITGLYEK PSLSAQPGPT VQAGENVTLS CSSWSSYDIY HLSREGEAHE
 RRLRAVPKVN RTFQADFPLG PATHGGTYRC FGSFRALPCV WSNSSDPLLV SVTGNPSSSW
 PSPTEPSSKS GICRHLHVLI GTSVVIFLFI LLLFFLLYRW CSNKKNAAVM DQEPAGDRTV
 NRQDSDEQDP QEVMYAQLDH CVFIQRKISR PSQRPKTPLT DTSVYTELPN AEPRSKVVSC
 PRAPQSGLEG VF*    
>P1;KIR:KIR00544
KIR:KIR00544 KIR3DL2*01102 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00549
KIR:KIR00549 KIR3DL2*01103 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00076
KIR:KIR00076 KIR3DL2*012 432 bases
 GGQDKPFLSA RPSTVVPQGG HVALQCHYRR GFNNFMLYKE DRSHVPIFHG RIFQESFIMG
 PVTPAHAGTY RCRGSRPHSL TGWSAPSNPL VIMVTGNHRK PSLLAHPGPL LKSGETVILQ
 CWSDVMFEHF FLHREGISED PSHLVGQIHD GVSKANFSIG PLMPVLAGTY RCYGSVPHSP
 YQLSAPSDPL DIVITGLYEK PSLSAQPGPT VQAGENVTLS CSSWSSYDIY HLSREGEAHE
 RRLRAVPKVN RTFQADFPLG PATHGGTYRC FGSFRALPCV WSNSSDPLLV SVTGNPSSSW
 PSPTEPSSKS GICRHLHVLI GTSVVIFLFI LLLFFLLYRW CSNKKNAAVM DQEPAGDRTV
 NRQDSDEQDP QEVTYAQLDH CVFIQRKISR PSQRPKTPLT DTSVYTELPN AEPRSKVVSC
 PRAPQSGLEG VF*    
>P1;KIR:KIR00107
KIR:KIR00107 KIR3DL2*01301 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSAWPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00597
KIR:KIR00597 KIR3DL2*01302 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSAWPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00598
KIR:KIR00598 KIR3DL2*01303 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSAWPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00135
KIR:KIR00135 KIR3DL2*014 445 bases
 VGFFLLQGAW PLMGGQDKPF LSAWPSTVVP RGGHVALQCH YRRGFNNFML YKEDRSHVPI
 FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN HRKPSLLAHP
 GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF SIGPLMPVLA
 GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV TLSCSSWSSY
 DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFHAL PCVWSNSSDP
 LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL YRWCSNKKNA
 AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT PLTDTSVYTE
 LPNAEPRSKV VSCPRAPQSG LEGVF*   
>P1;KIR:KIR00136
KIR:KIR00136 KIR3DL2*015 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00137
KIR:KIR00137 KIR3DL2*016 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP QGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00204
KIR:KIR00204 KIR3DL2*017 442 bases
 FFLLQGAWPL MGGQDKPFLS ARPSTVVPRG GHVALQCHYR RGFNNFMLYK EDRSHVPIFH
 GRIFQESFIM GPVTPAHAGT YRCRGSRPHS LTGWSTPSNP LVIMVTGNHR KPSLLAHPGP
 LLKSGETVIL QCWSDVMFEH FFLHREGISE DPSRLVGQIH DGVSKANFSI GPLMPVLAGT
 YRCYGSVPHS PYQLSAPSDP LDIVITGLYE KPSLSAQPGP TVQAGENVTL SCSSWSSYDI
 YHLSREGEAH ERRLRAVPKV NRTFQADFPL GPATHGGTYR CFGSFCALPC VWSNSSDPLL
 VSVTGNPSSS WPSPTEPSSK SGICRHLHVL IGTSVVIFLF ILLLFFLLYR WCSNKKNAAV
 MDQEPAGDRT VNRQDSDEQD PQEVMYAQLD HCVFIQRKIS RPSQRPKTPL TDTSVYTELP
 NAEPRSKVVS CPRAPQSGLE GV*   
>P1;KIR:KIR00205
KIR:KIR00205 KIR3DL2*018 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRDL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00206
KIR:KIR00206 KIR3DL2*019 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFHAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00207
KIR:KIR00207 KIR3DL2*020 442 bases
 FFLLQGAWPL MGGQDKPFLS ARPSTVVPRG GHVALQCHYR RGFNNFMLYK EDRSHVPIFH
 SRIFQESFIM GPVTPAHAGT YRCRGSRPHS LTGWSAPSNP VVIMVTGNHR KPSLLAHPGP
 LLKSGETVIL QCWSDVMFEH FFLHREGISE DPSHLVGQIH DGVSKANFSI GPLMPVLAGT
 YRCYGSVPHS PYQLSAPSDP LDIVITGLYE KPSLSAQPGP TVQAGENVTL SCSSWSSYDI
 YHLSREGEAH ERRLRAVPKV NRTFQADFPL GPATHGGTYR CFGSFRALPC VWSNSSDPLL
 VSVTGNPSSS WPSPTEPSSK SGICRHLHVL IGTSVVIFLF ILLLFFLLYR WCSNKKNAAV
 MDQEPAGDRT VNRQDSDEQD PQEVTYAQLD HCVFIQRKIS RPSQRPKTPL TDTSVYTELP
 NAEPRSKVVS CPRAPQSGLE GV*   
>P1;KIR:KIR00210
KIR:KIR00210 KIR3DL2*021 442 bases
 FFLLQGAWPL MGGQDKPFLS ARPSTVVPRG GHVALQCHYR RGFNNFMLYK EDRSHVPIFH
 GRIFQESFIM GPVTPAHAGT YRCRGSRPHS LTGWSAPSNP LVIMVTGNHR KPSLLAHPGT
 LLKSGETVIL QCWSDVMFEH FFLHREGISE DPSRLVGQIH DGVSKANFSI GPLMPVLAGT
 YRCYGSVPHS PYQLSAPSDP LDIVITGLYE KPSLSAQPGP TVQAGENVTL SCSSWSSYDI
 YHLSREGEAH ERRLRAVPKV NRTFQADFPL GPATHGGTYR CFGSFRALPC VWSNSSDPLL
 VSVTGNPSSS WPSPTEPSSK SGICRHLHVL IGTSVVIFLF ILLLFFLLYR WCSNKKNAAV
 MDQEPAGDRT VNRQDSDEQD PQEVTYAQLD HCVFIQRKIS RPSQRPKTPP TDTSVYTELP
 NAEPRSKVVS CPRAPQSGLE GV*   
>P1;KIR:KIR00237
KIR:KIR00237 KIR3DL2*022 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSSVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00279
KIR:KIR00279 KIR3DL2*023 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSHLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00281
KIR:KIR00281 KIR3DL2*024 431 bases
 GQDKPFLSAW PSTVVPRGGH VALQCHYRRG FNNFMLYKED RSHVPIFHGR IFQESFIMGP
 VTPAHAGTYR CRGSRPHSLT GWSAPSNPLV IMVTGNHRKP SLLAHPGPLL KSGETVILQC
 WSDVMFEHFF LHREGISEDP SRLVGQIHDG VSKANFSIGP LMPVLAGTYR CYGSVPHSPY
 QLSAPSDPLD IVITGLYEKP SLSAQPGPTV QAGENVTLSC SSWSSYDIYH LSREGEAHER
 RLRAVPKVNR TFQADFPLGP ATHGGTYRCF GSFRALPCVW SNSSDPLLVS VTGNPSSSWP
 SPTEPSSKSG ICRHLHVLIG TSVVIFLFIL LLFFLLYRWC SNKKNAAVMD QEPAGDRTVN
 RQDSDEQDPQ EVMYAQLDHC VFIQRKISRP SQRPKTPLTD TSVYTELPNA EPRSKVVSCP
 RAPQSGLEGV F*    
>P1;KIR:KIR00282
KIR:KIR00282 KIR3DL2*025 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSAWPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSHLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00283
KIR:KIR00283 KIR3DL2*026 431 bases
 GQDKPFLSAR PSTVVPRGGH VALQCHYRRG FNNFMLYKED RSHVPIFHGR IFQESFIMGP
 VTPAHAGTYR CRGSRPHSLT GWSAPSNPVV IMVTGNHRKP SLLAHPGPLL KSGETVILQC
 WSDVMFEHFF LHRDGISEDP SRLVGQIHDG VSKANFSIGP LMPVLAGTYR CYGSVPHSPY
 QLSAPSDPLD IVITGLYEKP SLSAQPGPTV QAGENVTLSC SSWSSYDIYH LSREGEAHER
 RLRAVPKVNR TFQADFPLGP ATHGGTYRCF GSFRALPCVW SNSSDPLLVS VTGNPSSSWP
 SPTEPSSKSG ICRHLHVLIG TSVVIFLFIL LLFFLLYRWC SNKKNAAVMD QEPAGDRTVN
 RQDSDEQDPQ EVTYAQLDHC VFIQRKISRP SQRPKTPLTD TSVYTELPNA EPRSKVVSCP
 RAPQSGLEGV F*    
>P1;KIR:KIR00284
KIR:KIR00284 KIR3DL2*027 431 bases
 GQDKPFLSAR PSTVVPRGGH VALQCHYRRG FNNFMLYKED RSHVPIFHGR IFQESFIMGP
 VTPAHAGTYR CRGSRPHSLT GWSTPSNPLV IMVTGNHRKP SLLAHPGTLL KSGETVILQC
 WSDVMFEHFF LHREGISEDP SRLVGQIHDG VSKANFSIGP LMPVLAGTYR CYGSVPHSPY
 QLSAPSDPLD IVITGLYEKP SLSAQPGPTV QAGENVTLSC SSWSSYDIYH LSREGEAHER
 RLRAVPKVNR TFQADFPLGP ATHGGTYRCF GSFRALPCVW SNSSDPLLVS VTGNPSSSWP
 SPTEPSSKSG ICRHLHVLIG TSVVIFLFIL LLFFLLYRWC SNKKNAAVMD QEPAGDRTVN
 RQDSDEQDPQ EVTYAQLDHC VFIQRKISRP SQRPKTPPTD TSVYTELPNA EPRSKVVSCP
 RAPQSGLEGV F*    
>P1;KIR:KIR00285
KIR:KIR00285 KIR3DL2*028 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPF FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00286
KIR:KIR00286 KIR3DL2*029 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCPGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00288
KIR:KIR00288 KIR3DL2*030 431 bases
 GQDKPFLSAR PSTVVPRGGH VALQCHYRRG FNNFMLYKED RSHVPIFHGR IFQESFIMGP
 VTPAHAGTYR CRGSRPHSLT GWSAPSNPVV IMVTGNHRKP SLLAHPGPLL KSGETVIQQC
 WSDVMFEHFF LHREGISEDP SRLVGQIHDG VSKANFSIGP LMPVLAGTYR CYGSVPHSPY
 QLSAPSDPLD IVITGLYEKP SLSAQPGPTV QAGENVTLSC SSWSSYDIYH LSREGEAHER
 RLRAVPKVNR TFQADFPLGP ATHGGTYRCF GSFRALPCVW SNSSDPLLVS VTGNPSSSWP
 SPTEPSSKSG ICRHLHVLIG TSVVIFLFIL LLFFLLYRWC SNKKNAAVMD QEPAGDRTVN
 RQDSDEQDPQ EVTYAQLDHC VFIQRKISRP SQRPKTPLTD TSVYTELPNA EPRSKVVSCP
 RAPQSGLEGV F*    
>P1;KIR:KIR00289
KIR:KIR00289 KIR3DL2*031 431 bases
 GQDKPFLSAR PSTVVPRGGH VALQCHYRRG FNNFMLYKED RSHVPIFHGR IFQESFIMGP
 VTPAHAGTYR CRGSRPHSLT GWSAPSNPLV IMVTGNHRKP SLLAHPGPLL KSGETVILQC
 WSDVMFEHFF LHREGISEDP SRLVGQIHDG VSKANFSIGP LMPVLAGTCR CYGSVPHSPY
 QLSAPSDPLD IVITGLYEKP SLSAQPGPTV QAGENVTLSC SSWSSYDIYH LSREGEAHER
 RLRAVPKVNR TFQADFPLGP ATHGGTYRCF GSFRALPCVW SNSSDPLLVS VTGNPSSSWP
 SPTEPSSKSG ICRHLHVLIG TSVVIFLFIL LLFFLLYRWC SNKKNAAVMD QEPAGDRTVN
 RQDSDEQDPQ EVTYAQLDHC VFIQRKISRP SQRPKTPLTD TSVYTELPNA EPRSKVVSCP
 RAPQSGLEGV F*    
>P1;KIR:KIR00290
KIR:KIR00290 KIR3DL2*032 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSRSSY DMYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00291
KIR:KIR00291 KIR3DL2*033 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENM
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00292
KIR:KIR00292 KIR3DL2*034 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSRGGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00343
KIR:KIR00343 KIR3DL2*035 431 bases
 GQDKPFLSAR PSTVVPRGGH VALQCHYRRG FNNFMLYKED RSHVPIFHGR IFQESFIMGP
 VTPAHAGTYR CRGSRPHSLT GWSAPSNPLV IMVTGNHRKP SLLAHPGPLL KSGETVILQC
 WSDVMFEHFF LHREGISEDP SRLVGQIHDG VSKANFSIGP LMPVLAGTYR CYGSVPHSPY
 QLSAPSDPLD IVITGLYEKP SLSAQPGPTV QAGENVTLSC SSRSSYDIYH LSREGEAHER
 RLRAVPKVNR TFQADFPLGP ATHGGTYRCF GSFRALPCVW SNSSDPLLVS VTGNPSSSWP
 SPTEPSSKSG ICRHLHVLIG TSVVIFLFIL LLFFLLYRWC SNKKNAAVMD QEPAGDRTVN
 RQDSDEQDPQ EVTYAQLDHC VFIQRKISRP SQRPKTPLTD TSVYTELPNA EPRSKVVSCP
 RAPQSGLEGV F*    
>P1;KIR:KIR00344
KIR:KIR00344 KIR3DL2*036 431 bases
 GQDKPFLSAR PSTVVPQGGH VALQCHYRRG FNNFMLYKED RSHVPIFHGR IFQESFIMGP
 VTPAHAGTYR CRGSRPHSLT GWSAPSNPLV IMVTGNHRKP SLLAHPGPLL KSGETVILQC
 WSDVMFEHFF LHREGISEDP SRLVGQIHDG VSKANFSIGP LMPVLAGTYR CYGSVPHSPY
 QLSAPSDPLD IVITGLYEKP SLSAQPGPTV QAGENVTLSC SSWSSYDIYH LSREGEAHER
 RLRAVPKVNR TFQADFPLGP ATHGGTYRCF GSFHALPCVW SNSSDPLLVS VTGNPSSSWP
 SPTEPSSKSG ICRHLHVLIG TSVVIFLFIL LLFFLLYRWC SNKKNAAVMD QEPAGDRTVN
 RQDSDEQDPQ EVTYAQLDHC VFIQRKISRP SQRPKTPLTD TSVYTELPNA EPRSKVVSCP
 RAPQSGLEGV F*    
>P1;KIR:KIR00345
KIR:KIR00345 KIR3DL2*037 431 bases
 GQDKPFLSAW PSTVVPRGGH VALQCHYRRG FNNFMLYKED RSHVPIFHGR IFQESFIMGP
 VTPAHAGTYR CRGSRPHSLT GWSAPSNPLV IMVTGNHRKP SLLAHPGPLL KSGETVILQC
 WSDVMFEHFF LHREGISEDP SRLVGQIHDG VSKANFSIGP LMPVLAGTYR CYGSVPHSPY
 QLSAPSDPLD IVITGLYEKP SLSAQPGPTV QAGENVTLSC SSWSSYDIYH LSREGEAHER
 RLRAVPKVNR TFQADFPLGP ATHGGTYRCF GSFHALPCVW SNSSDPLLVS VTGNPSSSWP
 SPTEPSSKSG ICRHLHVLIG TSVVIFLFIL LLFFLLYRWC SNKKNAAVMD QEPAGDRTVN
 RQDSDEQDPQ EVTYAQLDHC VFIQRKISRP SQRPKTPLTD TSVYTELPNA EPRSKVVSCP
 RAPQSGLEGV F*    
>P1;KIR:KIR00346
KIR:KIR00346 KIR3DL2*038 431 bases
 GQDKPFLSAR PSTVVPQGGH VALQCHYRRG FNNFMLYKED RSHVPIFHGR IFQESFIMGP
 VTPAHAGTYR CRGSRPHSLT GWSAPSNPLV IMVTGNHRKP SLLAHPGTLL KSGETVILQC
 WSDVMFEHFF LHREGISEDP SRLVGQIHDG VSKANFSIGP LMPVLAGTYR CYGSVPHSPY
 QLSAPSDPLD IVITGLYEKP SLSAQPGPTV QAGENVTLSC SSWSSYDIYH LSREGEAHER
 RLRAVPKVNR TFQADFPLGP ATHGGTYRCF GSFRALPCVW SNSSDPLLVS VTGNPSSSWP
 SPTEPSSKSG ICRHLHVLIG TSVVIFLFIL LLFFLLYRWC SNKKNAAVMD QEPAGDRTVN
 RQDSDEQDPQ EVTYAQLDHC VFIQRKISRP SQRPKTPLTD TSVYTELPNA EPRSKVVSCP
 RAPQSGLEGV F*    
>P1;KIR:KIR00347
KIR:KIR00347 KIR3DL2*039 431 bases
 GQDKPFLSAR PSTVVPRGGH VALQCHYRRG FNNFMLYKED RSHVPIFHGR IFQESFIMGP
 VTPAHAGTYR CRGSRPHSLT GWSAPSNPLV IMVTGNHRKP SLLAHPGPLL KSGETVILQC
 WSDVMFEHFF LHRDGISEDP SRLVGQIHDG VSKANFSIGP LMPVLAGTYR CYGSVPHSPY
 QLSAPSDPLD IVITGLYEKP SLSAQPGPTV QAGENVTLSC SSWSSYDMYH LSREGEAHER
 RLRAVPKVNR TFQADFPLGP ATHGGTYRCF GSFRALPCVW SNSSDPLLVS VTGNPSSSWP
 SPTEPSSKSG ICRHLHVLIG TSVVIFLFIL LLFFLLYRWC SNKKNAAVMD QEPAGDRTVN
 RQDSDEQDPQ EVTYAQLDHC VFIQRKISRP SQRPKTPLTD TSVYTELPNA EPRSKVVSCP
 RAPQSGLEGV F*    
>P1;KIR:KIR00348
KIR:KIR00348 KIR3DL2*040 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSAWPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00507
KIR:KIR00507 KIR3DL2*041 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSRSSY DMYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGFF*  
>P1;KIR:KIR00539
KIR:KIR00539 KIR3DL2*042N 437 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFHAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPX*    
>P1;KIR:KIR00540
KIR:KIR00540 KIR3DL2*043 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSHLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00542
KIR:KIR00542 KIR3DL2*044 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS NPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00545
KIR:KIR00545 KIR3DL2*045 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFCAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00546
KIR:KIR00546 KIR3DL2*046 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSAWPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSHLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00547
KIR:KIR00547 KIR3DL2*047 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYTCRGSHP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00548
KIR:KIR00548 KIR3DL2*048 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSHLVGQ IHDGVSKANF
 SIGPLMPVLS GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00572
KIR:KIR00572 KIR3DL2*049 432 bases
 GGQDKPFLSA RPSTVVPRGG HVALQCHYRR GFNNFMLYKE DRSHVPIFHG RIFQESFIMG
 PVTPAHAGTY RCRGSRPHSL TGWSAPSNPL VIMVTGNHRK PSLLAHPGPL LKSGETVILQ
 CWSDVMFEHF FLHREGISED PSRLVGQIHD GVSKANFSIG PLMPVLAGTY RCYGSVPHSP
 YQLSAPSDPL DIMITGLYEK PSLSAQPGPT VQAGENVTLS CSSWSSYDIY HLSREGEAHE
 RRLRAVPKVN RTFQADFPLG PATHGGTYRC FGSFRALPCV WSNSSDPLLV SVTGNPSSSW
 PSPTEPSSKS GICRHLHVLI GTSVVIFLFI LLLFFLLYRW CSNKKNAAVM DQEPAGDRTV
 NRQDSDEQDP QEVTYAQLDH CVFIQRKISR PSQRPKTPLT DTSVYTELPN AEPRSKVVSC
 PRAPQSGLEG VF*    
>P1;KIR:KIR00578
KIR:KIR00578 KIR3DL2*050 432 bases
 GGQDKPFLSA RPSTVVPRGG HVALQCHYRR GFNNFMLYKE DRSHVPIFHG RIFQESFIMG
 PVTPAHAGTY RCRGSRPHSL TGWSAPSNPL VIMVTGNHRK PSLLAHPGPL LKSGETVILQ
 CWSDVMFEHF FLHREGISED PSRLVGQIHD GVSKANFSIG PLMPVLAGTY RCYGSVPHSP
 YQLSAPSDPL DIVITGLYEK PSLSAQPGPT VQAGENVTLS CSSWSSYDIY HLSREGEAHE
 RRLRAVPKVN RTFQADFPLG PATHGGTYRC FGSFHALPCV WSNSSDPLLV SVTGNPSSSW
 PSPTEPSSKS GICRHLHVLI GTSVVIFLFI LLLFFLLYRW CSNKKNAAVM DQEPAGDRTV
 NRQDSDEQDP QEVTYAQLDH CVFIQRKISR PSQRPKTPPT DTSVYTELPN AEPRSKVVSC
 PRAPQSGLEG VF*    
>P1;KIR:KIR00580
KIR:KIR00580 KIR3DL2*051 432 bases
 GGQDKPFLSA RPSTVVPRGG HVALQCHYRR GFNNFMLYKE DRSHVPIFHG RIFQESFIMG
 PVTPAHAGTY RCRGSRPHSL TGWSAPSNPL VIMVTGNHRK PSLLAHPGPL LKSGETVIQQ
 CWSDVMFEHF FLHREGISED PSRLVGQIHD GVSKANFSIG PLMPVLAGTY RCYGSVPHSP
 YQLSAPSDPL DIVITGLYEK PSLSAQPGPT VQAGENVTLS CSSWSSYDIY HLSREGEAHE
 RRLRAVPKVN RTFQADFPLG PATHGGTYRC FGSFRALPCV WSNSSDPLLV SVTGNPSSSW
 PSPTEPSSKS GICRHLHVLI GTSVVIFLFI LLLFFLLYRW CSNKKNAAVM DQEPAGDRTV
 NRQDSDEQDP QEVMYAQLDH CVFIQRKISR PSQRPKTPLT DTSVYTELPN AEPRSKVVSC
 PRAPQSGLEG VF*    
>P1;KIR:KIR00581
KIR:KIR00581 KIR3DL2*052 432 bases
 GGQDKPFLSA WPSTVVPRGG HVAFQCHYRR GFNNFMLYKE DRSHVPIFHG RIFQESFIMG
 PVTPAHAGTY RCRGSRPHSL TGWSTPSNPL VIMVTGNHRK PSLLAHPGPL LKSGETVILQ
 CWSDVMFEHF FLHREGISED PSRLVGQIHD GVSKANFSIG PLMPVLAGTY RCYGSVPHSP
 YQLSAPSDPL DIVITGLYEK PSLSAQPGPT VQAGENVTLS CSSWSSYDIY HLSREGEAHE
 RRLRAVPKVN RTFQADFPLG PATHGGTYRC FGSFRALPCV WSNSSDPLLV SVTGNPSSSW
 PSPTEPSSKS GICRHLHVLI GTSVVIFLFI LLLFFLLYRW CSNKKNAAVM DQEPAGDRTV
 NRQDSDEQDP QEVTYAQLDH CVFIQRKISR PSQRPKTPLT DTSVYTELPN AEPRSKVVSC
 PRAPQSGLEG VF*    
>P1;KIR:KIR00582
KIR:KIR00582 KIR3DL2*053 432 bases
 GGQDKPFLSA RPSTVVPRGG HVALQCHYRR GFNNFMLYKE DRSHVPIFHG RIFQESFIMG
 PVTPAHAGTY RCRGSRPHSL TGWSAPSNPL VIMVTGNHRK PSLLAHPGPL LKSGETVILQ
 CWSDVMFEHF FLHRDGISED PSRLVGQIHD GVSKANFSIG PLMPVLAGTY RCYGSVPHSP
 YQLSAPSDPL DIVITGLYEK PSLSAQPGPT VQAGENVTLS CSSWSSYDIY HLSREGEAHE
 HRLRAVPKVN RTFQADFPLG PATHGGTYRC FGSFRALPCV WSNSSDPLLV SVTGNPSSSW
 PSPTEPSSKS GICRHLHVLI GTSVVIFLFI LLLFFLLYRW CSNKKNAAVM DQEPAGDRTV
 NRQDSDEQDP QEVTYAQLDH CVFIQRKISR PSQRPKTPPT DTSVYTELPN AEPRSKVVSC
 PRAPQSGLEG VF*    
>P1;KIR:KIR00583
KIR:KIR00583 KIR3DL2*054 432 bases
 GGQDKPFLSA WPSAVVPRGG HVTLRCHYHH RFNNFMLYKE DGIHIPIFHG RIFQESFNMS
 PVTTAHAGNY TCRGSRPHSL TGWSAPSNPL VIMVTGNHRK PSLLAHPGPL LKSGETVILQ
 CWSDVMFEHF FLHREGISED PSRLVGQIHD GVSKANFSIG PLMPVLAGTY RCYGSVPHSP
 YQLSAPSDPL DIVITGLYEK PSLSAQPGPT VQAGENVTLS CSSWSSYDIY HLSREGEAHE
 RRLRAVPKVN RTFQADFPLG PATHGGTYRC FGSFRALPCV WSNSSDPLLV SVTGNPSSSW
 PSPTEPSSKS GICRHLHVLI GTSVVIFLFI LLLFFLLYRW CSNKKNAAVM DQEPAGDRTV
 NRQDSDEQDP QEVTYAQLDH CVFIQRKISR PSQRPKTPLT DTSVYTELPN AEPRSKVVSC
 PRAPQSGLEG VF*    
>P1;KIR:KIR00579
KIR:KIR00579 KIR3DL2*055 432 bases
 GGQDKPFLSA RPSTVVPRGG HVALQCHYRR GFNNFMLYKE DRSHVPIFHG RIFQESFIMG
 PVTPAHAGTY RCRGSRPHSL TGWSAPSNPL VIMVTGNHRK PSLLAHPGPL LKSGETVILQ
 CWSDVMFEHF FLHRDGISED PSRLVGQIHD GVSKANFSIG PLMPVLAGTY RCYGSVPHSP
 YQLSAPSDPL DIVITGLYEK PSLSAQPGPT VQAGENVTLS CSSWSSYDIY HLSREGEAHE
 RRLRAVPKVN RTFQADFPLG PATHGGTYRC FGSFRALPCV WSNSSDPLLV SVTGNPSSSW
 PSPTEPSSKS GICRHLHVLI GTSVVIFLFI LLLFFLLYRW CSNKKNAAVM DQEPAGDRTV
 NRQDSDEQDP QEVTYAQLDH CVFIQRKISR PSQRPKTPPT DTSVYTELPN AEPRSKVVSC
 PRAPQSGLEG VF*    
>P1;KIR:KIR00624
KIR:KIR00624 KIR3DL2*056 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDIMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00599
KIR:KIR00599 KIR3DL2*057 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSHLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00601
KIR:KIR00601 KIR3DL2*058 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHIPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00602
KIR:KIR00602 KIR3DL2*059 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCPGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSHLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00603
KIR:KIR00603 KIR3DL2*060 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SISPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00604
KIR:KIR00604 KIR3DL2*061 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIMITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSRSSY DMYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00666
KIR:KIR00666 KIR3DL2*06202 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFHAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF*  
>P1;KIR:KIR00702
KIR:KIR00702 KIR3DL2*063 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE FPNAEPRSKV VSCPRAPQSG LEGVF*  
