>P1;KIR:KIR00065
KIR:KIR00065 KIR3DL2*0010101 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00459
KIR:KIR00459 KIR3DL2*0010102 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00280
KIR:KIR00280 KIR3DL2*00102 431 bases
 GQDKPFLSAR PSTVVPRGGH VALQCHYRRG FNNFMLYKED RSHVPIFHGR IFQESFIMGP
 VTPAHAGTYR CRGSRPHSLT GWSAPSNPLV IMVTGNHRKP SLLAHPGPLL KSGETVILQC
 WSDVMFEHFF LHREGISEDP SRLVGQIHDG VSKANFSIGP LMPVLAGTYR CYGSVPHSPY
 QLSAPSDPLD IVITGLYEKP SLSAQPGPTV QAGENVTLSC SSWSSYDIYH LSREGEAHER
 RLRAVPKVNR TFQADFPLGP ATHGGTYRCF GSFRALPCVW SNSSDPLLVS VTGNPSSSWP
 SPTEPSSKSG ICRHLHVLIG TSVVIFLFIL LLFFLLYRWC SNKKNAAVMD QEPAGDRTVN
 RQDSDEQDPQ EVTYAQLDHC VFIQRKISRP SQRPKTPLTD TSVYTELPNA EPRSKVVSCP
 RAPQSGLEGV F    
>P1;KIR:KIR00317
KIR:KIR00317 KIR3DL2*0010301 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00462
KIR:KIR00462 KIR3DL2*0010302 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00541
KIR:KIR00541 KIR3DL2*00104 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00796
KIR:KIR00796 KIR3DL2*00105 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00789
KIR:KIR00789 KIR3DL2*00106 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00832
KIR:KIR00832 KIR3DL2*00107 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00937
KIR:KIR00937 KIR3DL2*00109 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00066
KIR:KIR00066 KIR3DL2*0020101 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00461
KIR:KIR00461 KIR3DL2*0020102 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00463
KIR:KIR00463 KIR3DL2*0020103 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00464
KIR:KIR00464 KIR3DL2*0020104 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00465
KIR:KIR00465 KIR3DL2*0020105 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00640
KIR:KIR00640 KIR3DL2*0020106 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00460
KIR:KIR00460 KIR3DL2*00202 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00770
KIR:KIR00770 KIR3DL2*00203 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00847
KIR:KIR00847 KIR3DL2*00204 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00067
KIR:KIR00067 KIR3DL2*00301 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00287
KIR:KIR00287 KIR3DL2*00302 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00774
KIR:KIR00774 KIR3DL2*00303 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00783
KIR:KIR00783 KIR3DL2*00304 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00068
KIR:KIR00068 KIR3DL2*004 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVA RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSHLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSPQP GPTVQAGENV
 TLSCSSWSSY DTYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00069
KIR:KIR00069 KIR3DL2*00501 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSHLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00600
KIR:KIR00600 KIR3DL2*00502 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSHLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00070
KIR:KIR00070 KIR3DL2*00601 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00930
KIR:KIR00930 KIR3DL2*00602 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00071
KIR:KIR00071 KIR3DL2*0070101 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00295
KIR:KIR00295 KIR3DL2*0070102 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00458
KIR:KIR00458 KIR3DL2*0070103 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00543
KIR:KIR00543 KIR3DL2*00702 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00778
KIR:KIR00778 KIR3DL2*00703 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00808
KIR:KIR00808 KIR3DL2*00704 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00823
KIR:KIR00823 KIR3DL2*00705 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00841
KIR:KIR00841 KIR3DL2*00706 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00844
KIR:KIR00844 KIR3DL2*00707 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00915
KIR:KIR00915 KIR3DL2*00708 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00927
KIR:KIR00927 KIR3DL2*00709 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00997
KIR:KIR00997 KIR3DL2*00710 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR01608
KIR:KIR01608 KIR3DL2*00711 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00072
KIR:KIR00072 KIR3DL2*008 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP QGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GTLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PPTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00073
KIR:KIR00073 KIR3DL2*00901 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFHAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00134
KIR:KIR00134 KIR3DL2*00902 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFHAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00457
KIR:KIR00457 KIR3DL2*00903 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFHAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00074
KIR:KIR00074 KIR3DL2*01001 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00784
KIR:KIR00784 KIR3DL2*01002 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00840
KIR:KIR00840 KIR3DL2*01003 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00883
KIR:KIR00883 KIR3DL2*01004 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00075
KIR:KIR00075 KIR3DL2*01101 432 bases
 GGQDKPFLSA RPSTVVPRGG HVALQCHYRR GFNNFMLYKE DRSHVPIFHG RIFQESFIMG
 PVTPAHAGTY RCRGSRPHSL TGWSAPSNPV VIMVTGNHRK PSLLAHPGPL LKSGETVILQ
 CWSDVMFEHF FLHREGISED PSRLVGQIHD GVSKANFSIG PLMPVLAGTY RCYGSVPHSP
 YQLSAPSDPL DIVITGLYEK PSLSAQPGPT VQAGENVTLS CSSWSSYDIY HLSREGEAHE
 RRLRAVPKVN RTFQADFPLG PATHGGTYRC FGSFRALPCV WSNSSDPLLV SVTGNPSSSW
 PSPTEPSSKS GICRHLHVLI GTSVVIFLFI LLLFFLLYRW CSNKKNAAVM DQEPAGDRTV
 NRQDSDEQDP QEVMYAQLDH CVFIQRKISR PSQRPKTPLT DTSVYTELPN AEPRSKVVSC
 PRAPQSGLEG VF    
>P1;KIR:KIR00544
KIR:KIR00544 KIR3DL2*01102 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00549
KIR:KIR00549 KIR3DL2*01103 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00076
KIR:KIR00076 KIR3DL2*012 432 bases
 GGQDKPFLSA RPSTVVPQGG HVALQCHYRR GFNNFMLYKE DRSHVPIFHG RIFQESFIMG
 PVTPAHAGTY RCRGSRPHSL TGWSAPSNPL VIMVTGNHRK PSLLAHPGPL LKSGETVILQ
 CWSDVMFEHF FLHREGISED PSHLVGQIHD GVSKANFSIG PLMPVLAGTY RCYGSVPHSP
 YQLSAPSDPL DIVITGLYEK PSLSAQPGPT VQAGENVTLS CSSWSSYDIY HLSREGEAHE
 RRLRAVPKVN RTFQADFPLG PATHGGTYRC FGSFRALPCV WSNSSDPLLV SVTGNPSSSW
 PSPTEPSSKS GICRHLHVLI GTSVVIFLFI LLLFFLLYRW CSNKKNAAVM DQEPAGDRTV
 NRQDSDEQDP QEVTYAQLDH CVFIQRKISR PSQRPKTPLT DTSVYTELPN AEPRSKVVSC
 PRAPQSGLEG VF    
>P1;KIR:KIR00107
KIR:KIR00107 KIR3DL2*01301 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSAWPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00597
KIR:KIR00597 KIR3DL2*01302 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSAWPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00598
KIR:KIR00598 KIR3DL2*01303 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSAWPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00135
KIR:KIR00135 KIR3DL2*014 445 bases
 VGFFLLQGAW PLMGGQDKPF LSAWPSTVVP RGGHVALQCH YRRGFNNFML YKEDRSHVPI
 FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN HRKPSLLAHP
 GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF SIGPLMPVLA
 GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV TLSCSSWSSY
 DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFHAL PCVWSNSSDP
 LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL YRWCSNKKNA
 AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT PLTDTSVYTE
 LPNAEPRSKV VSCPRAPQSG LEGVF   
>P1;KIR:KIR00136
KIR:KIR00136 KIR3DL2*015 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00137
KIR:KIR00137 KIR3DL2*016 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP QGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00204
KIR:KIR00204 KIR3DL2*017 442 bases
 FFLLQGAWPL MGGQDKPFLS ARPSTVVPRG GHVALQCHYR RGFNNFMLYK EDRSHVPIFH
 GRIFQESFIM GPVTPAHAGT YRCRGSRPHS LTGWSTPSNP LVIMVTGNHR KPSLLAHPGP
 LLKSGETVIL QCWSDVMFEH FFLHREGISE DPSRLVGQIH DGVSKANFSI GPLMPVLAGT
 YRCYGSVPHS PYQLSAPSDP LDIVITGLYE KPSLSAQPGP TVQAGENVTL SCSSWSSYDI
 YHLSREGEAH ERRLRAVPKV NRTFQADFPL GPATHGGTYR CFGSFCALPC VWSNSSDPLL
 VSVTGNPSSS WPSPTEPSSK SGICRHLHVL IGTSVVIFLF ILLLFFLLYR WCSNKKNAAV
 MDQEPAGDRT VNRQDSDEQD PQEVMYAQLD HCVFIQRKIS RPSQRPKTPL TDTSVYTELP
 NAEPRSKVVS CPRAPQSGLE GV   
>P1;KIR:KIR00205
KIR:KIR00205 KIR3DL2*018 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRDL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00206
KIR:KIR00206 KIR3DL2*01901 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFHAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00931
KIR:KIR00931 KIR3DL2*01902 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFHAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00207
KIR:KIR00207 KIR3DL2*020 442 bases
 FFLLQGAWPL MGGQDKPFLS ARPSTVVPRG GHVALQCHYR RGFNNFMLYK EDRSHVPIFH
 SRIFQESFIM GPVTPAHAGT YRCRGSRPHS LTGWSAPSNP VVIMVTGNHR KPSLLAHPGP
 LLKSGETVIL QCWSDVMFEH FFLHREGISE DPSHLVGQIH DGVSKANFSI GPLMPVLAGT
 YRCYGSVPHS PYQLSAPSDP LDIVITGLYE KPSLSAQPGP TVQAGENVTL SCSSWSSYDI
 YHLSREGEAH ERRLRAVPKV NRTFQADFPL GPATHGGTYR CFGSFRALPC VWSNSSDPLL
 VSVTGNPSSS WPSPTEPSSK SGICRHLHVL IGTSVVIFLF ILLLFFLLYR WCSNKKNAAV
 MDQEPAGDRT VNRQDSDEQD PQEVTYAQLD HCVFIQRKIS RPSQRPKTPL TDTSVYTELP
 NAEPRSKVVS CPRAPQSGLE GV   
>P1;KIR:KIR00210
KIR:KIR00210 KIR3DL2*021 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GTLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PPTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00237
KIR:KIR00237 KIR3DL2*022 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSSVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00279
KIR:KIR00279 KIR3DL2*023 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSHLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00281
KIR:KIR00281 KIR3DL2*024 431 bases
 GQDKPFLSAW PSTVVPRGGH VALQCHYRRG FNNFMLYKED RSHVPIFHGR IFQESFIMGP
 VTPAHAGTYR CRGSRPHSLT GWSAPSNPLV IMVTGNHRKP SLLAHPGPLL KSGETVILQC
 WSDVMFEHFF LHREGISEDP SRLVGQIHDG VSKANFSIGP LMPVLAGTYR CYGSVPHSPY
 QLSAPSDPLD IVITGLYEKP SLSAQPGPTV QAGENVTLSC SSWSSYDIYH LSREGEAHER
 RLRAVPKVNR TFQADFPLGP ATHGGTYRCF GSFRALPCVW SNSSDPLLVS VTGNPSSSWP
 SPTEPSSKSG ICRHLHVLIG TSVVIFLFIL LLFFLLYRWC SNKKNAAVMD QEPAGDRTVN
 RQDSDEQDPQ EVMYAQLDHC VFIQRKISRP SQRPKTPLTD TSVYTELPNA EPRSKVVSCP
 RAPQSGLEGV F    
>P1;KIR:KIR00282
KIR:KIR00282 KIR3DL2*025 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSAWPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSHLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00283
KIR:KIR00283 KIR3DL2*026 431 bases
 GQDKPFLSAR PSTVVPRGGH VALQCHYRRG FNNFMLYKED RSHVPIFHGR IFQESFIMGP
 VTPAHAGTYR CRGSRPHSLT GWSAPSNPVV IMVTGNHRKP SLLAHPGPLL KSGETVILQC
 WSDVMFEHFF LHRDGISEDP SRLVGQIHDG VSKANFSIGP LMPVLAGTYR CYGSVPHSPY
 QLSAPSDPLD IVITGLYEKP SLSAQPGPTV QAGENVTLSC SSWSSYDIYH LSREGEAHER
 RLRAVPKVNR TFQADFPLGP ATHGGTYRCF GSFRALPCVW SNSSDPLLVS VTGNPSSSWP
 SPTEPSSKSG ICRHLHVLIG TSVVIFLFIL LLFFLLYRWC SNKKNAAVMD QEPAGDRTVN
 RQDSDEQDPQ EVTYAQLDHC VFIQRKISRP SQRPKTPLTD TSVYTELPNA EPRSKVVSCP
 RAPQSGLEGV F    
>P1;KIR:KIR00284
KIR:KIR00284 KIR3DL2*027 431 bases
 GQDKPFLSAR PSTVVPRGGH VALQCHYRRG FNNFMLYKED RSHVPIFHGR IFQESFIMGP
 VTPAHAGTYR CRGSRPHSLT GWSTPSNPLV IMVTGNHRKP SLLAHPGTLL KSGETVILQC
 WSDVMFEHFF LHREGISEDP SRLVGQIHDG VSKANFSIGP LMPVLAGTYR CYGSVPHSPY
 QLSAPSDPLD IVITGLYEKP SLSAQPGPTV QAGENVTLSC SSWSSYDIYH LSREGEAHER
 RLRAVPKVNR TFQADFPLGP ATHGGTYRCF GSFRALPCVW SNSSDPLLVS VTGNPSSSWP
 SPTEPSSKSG ICRHLHVLIG TSVVIFLFIL LLFFLLYRWC SNKKNAAVMD QEPAGDRTVN
 RQDSDEQDPQ EVTYAQLDHC VFIQRKISRP SQRPKTPPTD TSVYTELPNA EPRSKVVSCP
 RAPQSGLEGV F    
>P1;KIR:KIR00285
KIR:KIR00285 KIR3DL2*028 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPF FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00286
KIR:KIR00286 KIR3DL2*029 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCPGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00288
KIR:KIR00288 KIR3DL2*030 431 bases
 GQDKPFLSAR PSTVVPRGGH VALQCHYRRG FNNFMLYKED RSHVPIFHGR IFQESFIMGP
 VTPAHAGTYR CRGSRPHSLT GWSAPSNPVV IMVTGNHRKP SLLAHPGPLL KSGETVIQQC
 WSDVMFEHFF LHREGISEDP SRLVGQIHDG VSKANFSIGP LMPVLAGTYR CYGSVPHSPY
 QLSAPSDPLD IVITGLYEKP SLSAQPGPTV QAGENVTLSC SSWSSYDIYH LSREGEAHER
 RLRAVPKVNR TFQADFPLGP ATHGGTYRCF GSFRALPCVW SNSSDPLLVS VTGNPSSSWP
 SPTEPSSKSG ICRHLHVLIG TSVVIFLFIL LLFFLLYRWC SNKKNAAVMD QEPAGDRTVN
 RQDSDEQDPQ EVTYAQLDHC VFIQRKISRP SQRPKTPLTD TSVYTELPNA EPRSKVVSCP
 RAPQSGLEGV F    
>P1;KIR:KIR00289
KIR:KIR00289 KIR3DL2*031 431 bases
 GQDKPFLSAR PSTVVPRGGH VALQCHYRRG FNNFMLYKED RSHVPIFHGR IFQESFIMGP
 VTPAHAGTYR CRGSRPHSLT GWSAPSNPLV IMVTGNHRKP SLLAHPGPLL KSGETVILQC
 WSDVMFEHFF LHREGISEDP SRLVGQIHDG VSKANFSIGP LMPVLAGTCR CYGSVPHSPY
 QLSAPSDPLD IVITGLYEKP SLSAQPGPTV QAGENVTLSC SSWSSYDIYH LSREGEAHER
 RLRAVPKVNR TFQADFPLGP ATHGGTYRCF GSFRALPCVW SNSSDPLLVS VTGNPSSSWP
 SPTEPSSKSG ICRHLHVLIG TSVVIFLFIL LLFFLLYRWC SNKKNAAVMD QEPAGDRTVN
 RQDSDEQDPQ EVTYAQLDHC VFIQRKISRP SQRPKTPLTD TSVYTELPNA EPRSKVVSCP
 RAPQSGLEGV F    
>P1;KIR:KIR00290
KIR:KIR00290 KIR3DL2*032 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSRSSY DMYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00291
KIR:KIR00291 KIR3DL2*033 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENM
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00292
KIR:KIR00292 KIR3DL2*034 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSRGGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00343
KIR:KIR00343 KIR3DL2*035 431 bases
 GQDKPFLSAR PSTVVPRGGH VALQCHYRRG FNNFMLYKED RSHVPIFHGR IFQESFIMGP
 VTPAHAGTYR CRGSRPHSLT GWSAPSNPLV IMVTGNHRKP SLLAHPGPLL KSGETVILQC
 WSDVMFEHFF LHREGISEDP SRLVGQIHDG VSKANFSIGP LMPVLAGTYR CYGSVPHSPY
 QLSAPSDPLD IVITGLYEKP SLSAQPGPTV QAGENVTLSC SSRSSYDIYH LSREGEAHER
 RLRAVPKVNR TFQADFPLGP ATHGGTYRCF GSFRALPCVW SNSSDPLLVS VTGNPSSSWP
 SPTEPSSKSG ICRHLHVLIG TSVVIFLFIL LLFFLLYRWC SNKKNAAVMD QEPAGDRTVN
 RQDSDEQDPQ EVTYAQLDHC VFIQRKISRP SQRPKTPLTD TSVYTELPNA EPRSKVVSCP
 RAPQSGLEGV F    
>P1;KIR:KIR00344
KIR:KIR00344 KIR3DL2*036 431 bases
 GQDKPFLSAR PSTVVPQGGH VALQCHYRRG FNNFMLYKED RSHVPIFHGR IFQESFIMGP
 VTPAHAGTYR CRGSRPHSLT GWSAPSNPLV IMVTGNHRKP SLLAHPGPLL KSGETVILQC
 WSDVMFEHFF LHREGISEDP SRLVGQIHDG VSKANFSIGP LMPVLAGTYR CYGSVPHSPY
 QLSAPSDPLD IVITGLYEKP SLSAQPGPTV QAGENVTLSC SSWSSYDIYH LSREGEAHER
 RLRAVPKVNR TFQADFPLGP ATHGGTYRCF GSFHALPCVW SNSSDPLLVS VTGNPSSSWP
 SPTEPSSKSG ICRHLHVLIG TSVVIFLFIL LLFFLLYRWC SNKKNAAVMD QEPAGDRTVN
 RQDSDEQDPQ EVTYAQLDHC VFIQRKISRP SQRPKTPLTD TSVYTELPNA EPRSKVVSCP
 RAPQSGLEGV F    
>P1;KIR:KIR00345
KIR:KIR00345 KIR3DL2*037 431 bases
 GQDKPFLSAW PSTVVPRGGH VALQCHYRRG FNNFMLYKED RSHVPIFHGR IFQESFIMGP
 VTPAHAGTYR CRGSRPHSLT GWSAPSNPLV IMVTGNHRKP SLLAHPGPLL KSGETVILQC
 WSDVMFEHFF LHREGISEDP SRLVGQIHDG VSKANFSIGP LMPVLAGTYR CYGSVPHSPY
 QLSAPSDPLD IVITGLYEKP SLSAQPGPTV QAGENVTLSC SSWSSYDIYH LSREGEAHER
 RLRAVPKVNR TFQADFPLGP ATHGGTYRCF GSFHALPCVW SNSSDPLLVS VTGNPSSSWP
 SPTEPSSKSG ICRHLHVLIG TSVVIFLFIL LLFFLLYRWC SNKKNAAVMD QEPAGDRTVN
 RQDSDEQDPQ EVTYAQLDHC VFIQRKISRP SQRPKTPLTD TSVYTELPNA EPRSKVVSCP
 RAPQSGLEGV F    
>P1;KIR:KIR00346
KIR:KIR00346 KIR3DL2*038 431 bases
 GQDKPFLSAR PSTVVPQGGH VALQCHYRRG FNNFMLYKED RSHVPIFHGR IFQESFIMGP
 VTPAHAGTYR CRGSRPHSLT GWSAPSNPLV IMVTGNHRKP SLLAHPGTLL KSGETVILQC
 WSDVMFEHFF LHREGISEDP SRLVGQIHDG VSKANFSIGP LMPVLAGTYR CYGSVPHSPY
 QLSAPSDPLD IVITGLYEKP SLSAQPGPTV QAGENVTLSC SSWSSYDIYH LSREGEAHER
 RLRAVPKVNR TFQADFPLGP ATHGGTYRCF GSFRALPCVW SNSSDPLLVS VTGNPSSSWP
 SPTEPSSKSG ICRHLHVLIG TSVVIFLFIL LLFFLLYRWC SNKKNAAVMD QEPAGDRTVN
 RQDSDEQDPQ EVTYAQLDHC VFIQRKISRP SQRPKTPLTD TSVYTELPNA EPRSKVVSCP
 RAPQSGLEGV F    
>P1;KIR:KIR00347
KIR:KIR00347 KIR3DL2*039 431 bases
 GQDKPFLSAR PSTVVPRGGH VALQCHYRRG FNNFMLYKED RSHVPIFHGR IFQESFIMGP
 VTPAHAGTYR CRGSRPHSLT GWSAPSNPLV IMVTGNHRKP SLLAHPGPLL KSGETVILQC
 WSDVMFEHFF LHRDGISEDP SRLVGQIHDG VSKANFSIGP LMPVLAGTYR CYGSVPHSPY
 QLSAPSDPLD IVITGLYEKP SLSAQPGPTV QAGENVTLSC SSWSSYDMYH LSREGEAHER
 RLRAVPKVNR TFQADFPLGP ATHGGTYRCF GSFRALPCVW SNSSDPLLVS VTGNPSSSWP
 SPTEPSSKSG ICRHLHVLIG TSVVIFLFIL LLFFLLYRWC SNKKNAAVMD QEPAGDRTVN
 RQDSDEQDPQ EVTYAQLDHC VFIQRKISRP SQRPKTPLTD TSVYTELPNA EPRSKVVSCP
 RAPQSGLEGV F    
>P1;KIR:KIR00348
KIR:KIR00348 KIR3DL2*040 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSAWPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00507
KIR:KIR00507 KIR3DL2*041 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSRSSY DMYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGFF  
>P1;KIR:KIR00539
KIR:KIR00539 KIR3DL2*042N 437 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFHAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPX    
>P1;KIR:KIR00540
KIR:KIR00540 KIR3DL2*04301 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSHLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00936
KIR:KIR00936 KIR3DL2*04302 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSHLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00542
KIR:KIR00542 KIR3DL2*044 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS NPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00545
KIR:KIR00545 KIR3DL2*045 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFCAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00546
KIR:KIR00546 KIR3DL2*046 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSAWPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSHLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00547
KIR:KIR00547 KIR3DL2*047 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYTCRGSHP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00548
KIR:KIR00548 KIR3DL2*048 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSHLVGQ IHDGVSKANF
 SIGPLMPVLS GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00572
KIR:KIR00572 KIR3DL2*049 432 bases
 GGQDKPFLSA RPSTVVPRGG HVALQCHYRR GFNNFMLYKE DRSHVPIFHG RIFQESFIMG
 PVTPAHAGTY RCRGSRPHSL TGWSAPSNPL VIMVTGNHRK PSLLAHPGPL LKSGETVILQ
 CWSDVMFEHF FLHREGISED PSRLVGQIHD GVSKANFSIG PLMPVLAGTY RCYGSVPHSP
 YQLSAPSDPL DIMITGLYEK PSLSAQPGPT VQAGENVTLS CSSWSSYDIY HLSREGEAHE
 RRLRAVPKVN RTFQADFPLG PATHGGTYRC FGSFRALPCV WSNSSDPLLV SVTGNPSSSW
 PSPTEPSSKS GICRHLHVLI GTSVVIFLFI LLLFFLLYRW CSNKKNAAVM DQEPAGDRTV
 NRQDSDEQDP QEVTYAQLDH CVFIQRKISR PSQRPKTPLT DTSVYTELPN AEPRSKVVSC
 PRAPQSGLEG VF    
>P1;KIR:KIR00578
KIR:KIR00578 KIR3DL2*050 432 bases
 GGQDKPFLSA RPSTVVPRGG HVALQCHYRR GFNNFMLYKE DRSHVPIFHG RIFQESFIMG
 PVTPAHAGTY RCRGSRPHSL TGWSAPSNPL VIMVTGNHRK PSLLAHPGPL LKSGETVILQ
 CWSDVMFEHF FLHREGISED PSRLVGQIHD GVSKANFSIG PLMPVLAGTY RCYGSVPHSP
 YQLSAPSDPL DIVITGLYEK PSLSAQPGPT VQAGENVTLS CSSWSSYDIY HLSREGEAHE
 RRLRAVPKVN RTFQADFPLG PATHGGTYRC FGSFHALPCV WSNSSDPLLV SVTGNPSSSW
 PSPTEPSSKS GICRHLHVLI GTSVVIFLFI LLLFFLLYRW CSNKKNAAVM DQEPAGDRTV
 NRQDSDEQDP QEVTYAQLDH CVFIQRKISR PSQRPKTPPT DTSVYTELPN AEPRSKVVSC
 PRAPQSGLEG VF    
>P1;KIR:KIR00580
KIR:KIR00580 KIR3DL2*051 432 bases
 GGQDKPFLSA RPSTVVPRGG HVALQCHYRR GFNNFMLYKE DRSHVPIFHG RIFQESFIMG
 PVTPAHAGTY RCRGSRPHSL TGWSAPSNPL VIMVTGNHRK PSLLAHPGPL LKSGETVIQQ
 CWSDVMFEHF FLHREGISED PSRLVGQIHD GVSKANFSIG PLMPVLAGTY RCYGSVPHSP
 YQLSAPSDPL DIVITGLYEK PSLSAQPGPT VQAGENVTLS CSSWSSYDIY HLSREGEAHE
 RRLRAVPKVN RTFQADFPLG PATHGGTYRC FGSFRALPCV WSNSSDPLLV SVTGNPSSSW
 PSPTEPSSKS GICRHLHVLI GTSVVIFLFI LLLFFLLYRW CSNKKNAAVM DQEPAGDRTV
 NRQDSDEQDP QEVMYAQLDH CVFIQRKISR PSQRPKTPLT DTSVYTELPN AEPRSKVVSC
 PRAPQSGLEG VF    
>P1;KIR:KIR00581
KIR:KIR00581 KIR3DL2*052 432 bases
 GGQDKPFLSA WPSTVVPRGG HVAFQCHYRR GFNNFMLYKE DRSHVPIFHG RIFQESFIMG
 PVTPAHAGTY RCRGSRPHSL TGWSTPSNPL VIMVTGNHRK PSLLAHPGPL LKSGETVILQ
 CWSDVMFEHF FLHREGISED PSRLVGQIHD GVSKANFSIG PLMPVLAGTY RCYGSVPHSP
 YQLSAPSDPL DIVITGLYEK PSLSAQPGPT VQAGENVTLS CSSWSSYDIY HLSREGEAHE
 RRLRAVPKVN RTFQADFPLG PATHGGTYRC FGSFRALPCV WSNSSDPLLV SVTGNPSSSW
 PSPTEPSSKS GICRHLHVLI GTSVVIFLFI LLLFFLLYRW CSNKKNAAVM DQEPAGDRTV
 NRQDSDEQDP QEVTYAQLDH CVFIQRKISR PSQRPKTPLT DTSVYTELPN AEPRSKVVSC
 PRAPQSGLEG VF    
>P1;KIR:KIR00582
KIR:KIR00582 KIR3DL2*053 432 bases
 GGQDKPFLSA RPSTVVPRGG HVALQCHYRR GFNNFMLYKE DRSHVPIFHG RIFQESFIMG
 PVTPAHAGTY RCRGSRPHSL TGWSAPSNPL VIMVTGNHRK PSLLAHPGPL LKSGETVILQ
 CWSDVMFEHF FLHRDGISED PSRLVGQIHD GVSKANFSIG PLMPVLAGTY RCYGSVPHSP
 YQLSAPSDPL DIVITGLYEK PSLSAQPGPT VQAGENVTLS CSSWSSYDIY HLSREGEAHE
 HRLRAVPKVN RTFQADFPLG PATHGGTYRC FGSFRALPCV WSNSSDPLLV SVTGNPSSSW
 PSPTEPSSKS GICRHLHVLI GTSVVIFLFI LLLFFLLYRW CSNKKNAAVM DQEPAGDRTV
 NRQDSDEQDP QEVTYAQLDH CVFIQRKISR PSQRPKTPPT DTSVYTELPN AEPRSKVVSC
 PRAPQSGLEG VF    
>P1;KIR:KIR00583
KIR:KIR00583 KIR3DL2*054 432 bases
 GGQDKPFLSA WPSAVVPRGG HVTLRCHYHH RFNNFMLYKE DGIHIPIFHG RIFQESFNMS
 PVTTAHAGNY TCRGSRPHSL TGWSAPSNPL VIMVTGNHRK PSLLAHPGPL LKSGETVILQ
 CWSDVMFEHF FLHREGISED PSRLVGQIHD GVSKANFSIG PLMPVLAGTY RCYGSVPHSP
 YQLSAPSDPL DIVITGLYEK PSLSAQPGPT VQAGENVTLS CSSWSSYDIY HLSREGEAHE
 RRLRAVPKVN RTFQADFPLG PATHGGTYRC FGSFRALPCV WSNSSDPLLV SVTGNPSSSW
 PSPTEPSSKS GICRHLHVLI GTSVVIFLFI LLLFFLLYRW CSNKKNAAVM DQEPAGDRTV
 NRQDSDEQDP QEVTYAQLDH CVFIQRKISR PSQRPKTPLT DTSVYTELPN AEPRSKVVSC
 PRAPQSGLEG VF    
>P1;KIR:KIR00579
KIR:KIR00579 KIR3DL2*055 432 bases
 GGQDKPFLSA RPSTVVPRGG HVALQCHYRR GFNNFMLYKE DRSHVPIFHG RIFQESFIMG
 PVTPAHAGTY RCRGSRPHSL TGWSAPSNPL VIMVTGNHRK PSLLAHPGPL LKSGETVILQ
 CWSDVMFEHF FLHRDGISED PSRLVGQIHD GVSKANFSIG PLMPVLAGTY RCYGSVPHSP
 YQLSAPSDPL DIVITGLYEK PSLSAQPGPT VQAGENVTLS CSSWSSYDIY HLSREGEAHE
 RRLRAVPKVN RTFQADFPLG PATHGGTYRC FGSFRALPCV WSNSSDPLLV SVTGNPSSSW
 PSPTEPSSKS GICRHLHVLI GTSVVIFLFI LLLFFLLYRW CSNKKNAAVM DQEPAGDRTV
 NRQDSDEQDP QEVTYAQLDH CVFIQRKISR PSQRPKTPPT DTSVYTELPN AEPRSKVVSC
 PRAPQSGLEG VF    
>P1;KIR:KIR00624
KIR:KIR00624 KIR3DL2*056 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDIMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00599
KIR:KIR00599 KIR3DL2*057 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSHLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00601
KIR:KIR00601 KIR3DL2*058 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHIPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00602
KIR:KIR00602 KIR3DL2*059 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCPGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSHLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00603
KIR:KIR00603 KIR3DL2*06001 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SISPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00934
KIR:KIR00934 KIR3DL2*06002 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SISPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00604
KIR:KIR00604 KIR3DL2*061 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIMITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSRSSY DMYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00615
KIR:KIR00615 KIR3DL2*06201 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFHAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00666
KIR:KIR00666 KIR3DL2*06202 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFHAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00702
KIR:KIR00702 KIR3DL2*063 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE FPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00793
KIR:KIR00793 KIR3DL2*064 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHCRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00794
KIR:KIR00794 KIR3DL2*065 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GNYTCRGSHP HSPTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00795
KIR:KIR00795 KIR3DL2*066 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGRT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00768
KIR:KIR00768 KIR3DL2*067 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSAWPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMDPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00769
KIR:KIR00769 KIR3DL2*068 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHECRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00771
KIR:KIR00771 KIR3DL2*069 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGERV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00772
KIR:KIR00772 KIR3DL2*070 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLDGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PPTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00773
KIR:KIR00773 KIR3DL2*071 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YHRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00775
KIR:KIR00775 KIR3DL2*072 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGE IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00776
KIR:KIR00776 KIR3DL2*073 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YCRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00777
KIR:KIR00777 KIR3DL2*074 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSRVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFHAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00779
KIR:KIR00779 KIR3DL2*075 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD STVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00780
KIR:KIR00780 KIR3DL2*076 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSHLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSS LEGVF  
>P1;KIR:KIR00781
KIR:KIR00781 KIR3DL2*077 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGRT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00782
KIR:KIR00782 KIR3DL2*078 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSAWPSAVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFHAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00785
KIR:KIR00785 KIR3DL2*07901 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV IQQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00929
KIR:KIR00929 KIR3DL2*07902 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV IQQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00786
KIR:KIR00786 KIR3DL2*080 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRIHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00787
KIR:KIR00787 KIR3DL2*081 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSAWPSTVVP RGGHVTLQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00788
KIR:KIR00788 KIR3DL2*082 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPCQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00807
KIR:KIR00807 KIR3DL2*083 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP QGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGTRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GTLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PPTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00825
KIR:KIR00825 KIR3DL2*084 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLIGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFHAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00827
KIR:KIR00827 KIR3DL2*085 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTCAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00829
KIR:KIR00829 KIR3DL2*086 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHRVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00831
KIR:KIR00831 KIR3DL2*087 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGPVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00834
KIR:KIR00834 KIR3DL2*088 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHYVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00836
KIR:KIR00836 KIR3DL2*089 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NHLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00838
KIR:KIR00838 KIR3DL2*090 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQKK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00839
KIR:KIR00839 KIR3DL2*091 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSQV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00842
KIR:KIR00842 KIR3DL2*092 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LAGVF  
>P1;KIR:KIR00843
KIR:KIR00843 KIR3DL2*093 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKTNF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00845
KIR:KIR00845 KIR3DL2*094 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVIDQEPPGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00846
KIR:KIR00846 KIR3DL2*095 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSAWPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPKVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00848
KIR:KIR00848 KIR3DL2*096 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPQAPQSG LEGVF  
>P1;KIR:KIR00862
KIR:KIR00862 KIR3DL2*097 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP QGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GTLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSKKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PPTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00888
KIR:KIR00888 KIR3DL2*098 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISCPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00908
KIR:KIR00908 KIR3DL2*099 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSHP HSPTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFHAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00910
KIR:KIR00910 KIR3DL2*10001 455 bases
 MSLTVVSMVC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00938
KIR:KIR00938 KIR3DL2*10002 455 bases
 MSLTVVSMVC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00911
KIR:KIR00911 KIR3DL2*101 455 bases
 MLLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00916
KIR:KIR00916 KIR3DL2*102 455 bases
 MSLTVVSMAC VGFFLLQVAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00924
KIR:KIR00924 KIR3DL2*103 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSAWPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00925
KIR:KIR00925 KIR3DL2*104 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVAFQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00926
KIR:KIR00926 KIR3DL2*105 455 bases
 MSLTVVSMVC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPVVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00932
KIR:KIR00932 KIR3DL2*10601 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHSRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00933
KIR:KIR00933 KIR3DL2*10701 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00935
KIR:KIR00935 KIR3DL2*10801 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PPTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00939
KIR:KIR00939 KIR3DL2*109 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP QGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00962
KIR:KIR00962 KIR3DL2*11001 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHEHRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00963
KIR:KIR00963 KIR3DL2*11002 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHEHRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00998
KIR:KIR00998 KIR3DL2*111 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLDGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PPTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR00999
KIR:KIR00999 KIR3DL2*112 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSTPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFHAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR01036
KIR:KIR01036 KIR3DL2*113 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHRDGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSKKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR01037
KIR:KIR01037 KIR3DL2*114 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP QGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPN NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR01040
KIR:KIR01040 KIR3DL2*115 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYRLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWPSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVMYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
>P1;KIR:KIR01598
KIR:KIR01598 KIR3DL2*116 455 bases
 MSLTVVSMAC VGFFLLQGAW PLMGGQDKPF LSARPSTVVP RGGHVALQCH YRRGFNNFML
 YKEDRSHVPI FHGRIFQESF IMGPVTPAHA GTYRCRGSRP HSLTGWSAPS NPLVIMVTGN
 HRKPSLLAHP GPLLKSGETV ILQCWSDVMF EHFFLHREGI SEDPSRLVGQ IHDGVSKANF
 SIGPLMPVLA GTYRCYGSVP HSPYQLSAPS DPLDIVITGL YEKPSLSAQP GPTVQAGENV
 TLSCSSWSSY DIYHLSREGE AHERRLRAVP KVNRTFQADF PLGPATHGGT YRCFGSFRAL
 PCVWSNSSDP LLVSVTGNPS SSWLSPTEPS SKSGICRHLH VLIGTSVVIF LFILLLFFLL
 YRWCSNKKNA AVMDQEPAGD RTVNRQDSDE QDPQEVTYAQ LDHCVFIQRK ISRPSQRPKT
 PLTDTSVYTE LPNAEPRSKV VSCPRAPQSG LEGVF  
