>P1;IPD:KIR00087
IPD:KIR00087 KIR3DP1*001, 297 bases, D5EF4F3B checksum.
 MSLMVVSMAC VGFFLLQGAW THEGGQDKPF LSAWPSPVVS EGEHVALQCR
 SRLGFNEFSL SKEDGMPVPE LYNRVFRNTV FIGPVTPAHA GTYRCRGSHP
 HFLTGWSAPS NPLVIMVTGV HRKPSLLAHP GPLVKSEETV ILQCWSDVMF
 EHFLLHREGK FNDTLRLTGE LHDGVSKANF SIGRMTQDLA GTYRCYGSVP
 HSPYQLSAPS DPLDIVITGL CGKPSLSAQP RPMVKAGESV TLSCSSRSSY
 DIYHLSREGE AHELRFPAVP KVNGTFQANF PLGPATHGGT YRCFGSF*

>P1;IPD:KIR00093
IPD:KIR00093 KIR3DP1*002, 316 bases, 4005E5F4 checksum.
 MSLMVVSMAC VGFFLLQGAW PHEGGQDKPF LSAWPSPVVS EGEHVALQCR
 SRLGFNEFSL SKEDGMPVPE LYNRVFRNTV FIGPVTPAHA GTYRCRGSHP
 HFLTGWSAPS NPLVIMVTGV HRKPSLLAHP GPLVKSEETV ILQCWSDVMF
 EHFLLHREGK FNDTLRLTGE LHDGVSKANF SIGRMTQDLA GTYRCYGSVP
 HSPYQLSAPS DPLDIVITGL CGKPSLSAQP RPMVKAGESV TLSCSSRSSY
 DIYHLSRDGE AHELRFPAVP KVNGTFQANF PLGPATHGGT YRCFGSFRDS
 PYEWSDLSDP LLVSVT*

>P1;IPD:KIR00088
IPD:KIR00088 KIR3DP1*00301, 304 bases, 6937DE54 checksum.
 MSLMVVSMAC VGGQDKPFLS AWPSPVVSEG EHVALQCRSR LGFNEFSLSK
 EDGMPVPELY NRVFRNTVFI GPVTPAHAGT YRCRGSHPHF LTGWSAPSNP
 LVIMVTGVHR KPSLLAHPGP LVKSEETVIL QCWSDVMFEH FLLHREGKFN
 DTLRLTGELH DGVSKANFSI GRMTQDLAGT YRCYGSVPHS PYQLSAPSDP
 LDIVITGLCG KPSLSAQPRP MVKAGESVTL SCSSRSSYDI YHLSREGEAH
 ELRFPAVPKV NGTFQANFPL GPATHGGTYR CFGSFRDSPY EWSDLSDPLL
 VSVT*

>P1;IPD:KIR00094
IPD:KIR00094 KIR3DP1*00302, 304 bases, 6937DE54 checksum.
 MSLMVVSMAC VGGQDKPFLS AWPSPVVSEG EHVALQCRSR LGFNEFSLSK
 EDGMPVPELY NRVFRNTVFI GPVTPAHAGT YRCRGSHPHF LTGWSAPSNP
 LVIMVTGVHR KPSLLAHPGP LVKSEETVIL QCWSDVMFEH FLLHREGKFN
 DTLRLTGELH DGVSKANFSI GRMTQDLAGT YRCYGSVPHS PYQLSAPSDP
 LDIVITGLCG KPSLSAQPRP MVKAGESVTL SCSSRSSYDI YHLSREGEAH
 ELRFPAVPKV NGTFQANFPL GPATHGGTYR CFGSFRDSPY EWSDLSDPLL
 VSVT*

>P1;IPD:KIR00091
IPD:KIR00091 KIR3DP1*004, 316 bases, 427316C9 checksum.
 MSLMVISMAC VGFFLLQGAW THEGGQDKPF LSAWPSPVVS EGEHVALQCR
 SRLGFNEFSL SKEDGMPVPE LYNRVFRNTV FIGPVTPAHA GTYRCRGSHP
 HFLTGWSAPS NPLVIMVTGV HRKPSLLAHP GPLVKSEETV ILQCWSDVMF
 EHFLLHREGK FNDTLRLTGE LHDGVSKANF SIGRMTQDLA GTYRCYGSVP
 HSPYQLSAPS DPLDIVITGL CGKPSLSAQP RPMVKAGESV TLSCSSRSSY
 DIYHLSREGE AHELRFPAVP KVNGTFQANF PLGPATHGGT YRCFGSFRDS
 PYEWSDLSDP LLVSVT*

>P1;IPD:KIR00268
IPD:KIR00268 KIR3DP1*005, 304 bases, EC34DA83 checksum.
 MSLMVVSMAC VGGQDKPFLS AWPSPVVSEG EHVALQCRSR LGFNEFSLSK
 EDGMPVPELY NRVFRNTVFI GPVTPAHAGT YRCRGSHPHF LTGWSAPSNP
 LVIMVTGVHR KPSLLAHPGP LVKSEETVIL QCWSDVMFEH FLLHREGTFN
 DTLRLTGELH DGVSKANFSI GRMTQDLAGT YRCYGSVPHS PYQLSAPSDP
 LDIVITGLCG KPSLSAQPCP MVKAGESVTL SCSSRSSYDI YHLSRDGEAH
 ELRLPAVPKV NGTFQANFPL GPATHGGTYR CFGSFRDSPY EWSDLSDPLL
 VSVT*

>P1;IPD:KIR00269
IPD:KIR00269 KIR3DP1*006, 304 bases, 6B8FE545 checksum.
 MSLMVVSMAC VGGQDKPFLS AWPSPVVSEG EHVALQCRSR LGFNEFSLSK
 EDGMPVPELY NRVFRNTVFI GPVTPAHAGT YRCRGSHPHF LTGWSAPSNP
 LVIMVTGVHR KPSLLAHPGP LVKSEETVIL QCWSDVMFEH FLLHREGTFN
 DTLRLTGELH DGVSKANFSI GRMTQDLAGT YRCYGSVPHS PYQLSAPSDP
 LDIVITGLCG KPSLSAQPRP MVKAGESVTL SCSSRSSYDI YHLSRDGEAH
 ELRLPAVPKV NGTFQANFPL GPATHGGTYR CFGSFRDSPY EWSDLSDPLL
 VSVT*

