>DL;KIR:KIR00082
KIR:KIR00082 KIR3DS1*010 1164 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAATGCT GCTGTAATGG ACCAAGAGCC TGCAGGGAAC
 AGAAGTGAAC AGCGAGGATT CTGA*   
>DL;KIR:KIR00083
KIR:KIR00083 KIR3DS1*011 1149 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC ACCGCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGA*     
>DL;KIR:KIR00084
KIR:KIR00084 KIR3DS1*012 1149 bases
 ATGTCGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACACCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGA*     
>DL;KIR:KIR00085
KIR:KIR00085 KIR3DS1*0130101 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00489
KIR:KIR00489 KIR3DS1*0130102 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00488
KIR:KIR00488 KIR3DS1*0130103 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00708
KIR:KIR00708 KIR3DS1*0130104 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00709
KIR:KIR00709 KIR3DS1*0130105 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00710
KIR:KIR00710 KIR3DS1*0130106 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00711
KIR:KIR00711 KIR3DS1*0130107 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00713
KIR:KIR00713 KIR3DS1*0130108 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00715
KIR:KIR00715 KIR3DS1*0130109 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00717
KIR:KIR00717 KIR3DS1*0130110 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00719
KIR:KIR00719 KIR3DS1*0130111 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00164
KIR:KIR00164 KIR3DS1*01302 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAAT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00667
KIR:KIR00667 KIR3DS1*01303 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCTCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00853
KIR:KIR00853 KIR3DS1*01304 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCT
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00887
KIR:KIR00887 KIR3DS1*01305 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCTATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00891
KIR:KIR00891 KIR3DS1*01306 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA TGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00896
KIR:KIR00896 KIR3DS1*01307 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTTCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00086
KIR:KIR00086 KIR3DS1*014 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTCT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGAGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGGGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00165
KIR:KIR00165 KIR3DS1*045 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CCGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00166
KIR:KIR00166 KIR3DS1*046 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAGTTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00167
KIR:KIR00167 KIR3DS1*047 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCAGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00168
KIR:KIR00168 KIR3DS1*048 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCATCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00146
KIR:KIR00146 KIR3DS1*049N 1164 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAAACCC CTCACGCCTC GTTGGACAGA TCCATGATGG GGTCTCCAAG GCCAATTTCT
 CCATCGGTTC CATGATGCGT GCCCTTGCAG GGACCTACAG ATGCTACGGT TCTGTTACTC
 ACACCCCCTA TCAGTTGTCA GCTCCCAGTG ATCCCCTGGA CATCGTGGTC ACAGGTCTAT
 ATGAGAAACC TTCTCTCTCA GCCCAGCCGG GCCCCAAGGT TCAGGCAGGA GAGAGCGTGA
 CCTTGTCCTG TAGCTCCCGG AGCTCCTATG ACATGTACCA TCTATCCAGG GAGGGGGGAG
 CCCATGAACG TAGGCTCCCT GCAGTGCGCA AGGTCAACAG AACATTCCAG GCAGATTTCC
 CTCTGGGCCC TGCCACCCAC GGAGGGACCT ACAGATGCTT CGGCTCTTTC CGTCACTCTC
 CCTACGAGTG GTCAGACCCG AGTGACCCAC TGCTTGTTTC TGTCACAGGA AACCCTTCAA
 GTAGTTGGCC TTCACCCACA GAACCAAGCT CCAAATCTGG TAACCTCAGA CACCTGCACA
 TTCTGATTGG GACCTCAGTG GTCAAAATCC CTTTCACCAT CCTCCTCTTC TTTCTCCTTC
 ATCGCTGGTG CTCCAACAAA AAAAAATGCT GCTGTAATGG ACCAAGAGCC TGCAGGGAAC
 AGAAGTGAAC AGCGAGGATT CTGA*   
>DL;KIR:KIR00236
KIR:KIR00236 KIR3DS1*050 1149 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCATCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGA*     
>DL;KIR:KIR00243
KIR:KIR00243 KIR3DS1*055 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAG AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00261
KIR:KIR00261 KIR3DS1*058 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAATCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00751
KIR:KIR00751 KIR3DS1*078 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGCGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00749
KIR:KIR00749 KIR3DS1*082 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCCGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00750
KIR:KIR00750 KIR3DS1*083 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGGCCCCTGC TGAAATCAGG AGAGACAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00752
KIR:KIR00752 KIR3DS1*084 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCTCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00753
KIR:KIR00753 KIR3DS1*085 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGTTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00852
KIR:KIR00852 KIR3DS1*104 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCATG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00856
KIR:KIR00856 KIR3DS1*105 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGGC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00858
KIR:KIR00858 KIR3DS1*106 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGAAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00871
KIR:KIR00871 KIR3DS1*107 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA CATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TTCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
>DL;KIR:KIR00874
KIR:KIR00874 KIR3DS1*108 1165 bases
 ATGTTGCTCA TGGTCGTCAG CATGGCGTGT GTTGGGTTGT TCTTGGTCCA GAGGGCCGGT
 CCACACATGG GTGGTCAGGA CAAGCCCTTC CTGTCTGCCT GGCCCAGCGC TGTGGTGCCT
 CGCGGAGGAC ACGTGACTCT TCGGTGTCAC TATCGTCATA GGTTTAACAA TTTCATGCTA
 TACAAAGAAG ACAGAATCCA CGTTCCCATC TTCCATGGCA GAATATTCCA GGAGGGCTTC
 AACATGAGCC CTGTGACCAC AGCACATGCA GGGAACTACA GATGTCGGGG TTCACACCCA
 CACTCCCCCA CTGGGTGGTC GGCACCCAGC AACCCCATGG TGATCATGGT CACAGGAAAC
 CACAGAAAAC CTTCCCTCCT GGCCCACCCA GGTCCCCTGG TGAAATCAGG AGAGAGAGTC
 ATCCTGCAAT GTTGGTCAGA TATCATGTTT GAGCACTTCT TTCTGCACAA AGAGTGGATC
 TCTAAGGACC CCTCACGCCT CGTTGGACAG ATCCATGATG GGGTCTCCAA GGCCAATTTC
 TCCATCGGTT CCATGATGCG TGCCCTTGCA GGGACCTACA GATGCTACGG TTCTGTTACT
 CACACCCCCT ATCAGTTGTC AGCTCCCAGT GATCCCCTGG ACATCGTGGT CACAGGTCTA
 TATGAGAAAC CTTCTCTCTC AGCCCAGCCG GGCCCCAAGG TTCAGGCAGG AGAGAGCGTG
 ACCTTGTCCT GTAGCTCCCG GAGCTCCTAT GACATGTACC ATCTATCCAG GGAGGGGGGA
 GCCCATGAAC GTAGGCTCCC TGCAGTGCGC AAGGTCAACA GAACATTCCA GGCAGATTTC
 CCTCTGGGCC CTGCCACCCA CGGAGGGACC TACAGATGCT TCGGCTCTTT CCGTCACTCT
 CCCTACGAGT GGTCAGACCC GAGTGACCCA CTGCTTGTTT CTGTCACAGG AAACCCTTCA
 AGTAGTTGGC CTTCACCCAC AGAACCAAGC TCCAAATCTG GTAACCTCAG ACACCTGCAC
 ATTCTGATTG GGACCTCAGT GGTCAAAATC CCTTTCACCA TCCTCCTCTT CTTTCTCCTT
 CATCGCTGGT GCTCCAACAA AAAAAAATGC TGCTGTAATG GACCAAGAGC CTGCAGGGAA
 CAGAAGTGAA CAGCGAGGAT TCTGA*   
